### ISSUE TITLE
[chan.sankanku.com] Wrong file extension in image links resulting in "File Not Found" errors

### ISSUE THREAD

**Issue by flowxxx** [RipMeApp/ripme#10]
* Ripme version: v1.5.1
* Java version (output of `java -version`): 1.8.0_131
* Operating system: Windows 10
* Exact URL you were trying to rip when the problem occurred: https://chan.sankakucomplex.com/?tags=kunaboto
* Please include any additional information about how to reproduce the problem: The problem occurs with any chan.sankanku.com link. 

## Expected Behavior
Get the images links with correct file extensions and download them.

## Actual Behavior
All the image links are parsed having ".jpg" extension but some of the images are ".png" or other extensions on the site server, resulting in 404 errors when trying to download them.

Example:
When trying to download the images from the link: https://chan.sankakucomplex.com/?tags=kunaboto
RipMe gets the link: 
https://cs.sankakucomplex.com/data/23/90/2390750eb665e15d0393733a31bd0632.jpg?6170028
When it should be:
https://cs.sankakucomplex.com/data/23/90/2390750eb665e15d0393733a31bd0632.png?6170028
Then RipMe cant download the image because the file extension on the link is wrong.
The same happens for all ".png" images.

**Comment by metaprime** [comment]
There doesn't seem to be any way of knowing whether a picture is jpg or png or something else without navigating to each image's page, which we can do, although it will add up to more requests (which means marginally slower ripping and a higher chance of being rate-limited or banned). Still, I think it's better to improve correctness, and worry about those problems later, if they become a problem.

**Comment by metaprime** [comment]
Yeah, had to add a delay, but this seems to be working.

Also testing with [NSFW] https://idol.sankakucomplex.com/?tags=kiriyama_rui

**Comment by metaprime** [comment]
getting some weird errors. i'll pick this up later. work in progress here: https://github.com/metaprime/ripme/tree/sankaku

**Comment by cyian-1756** [comment]
This is fixed in ripme 1.5.14
