### ISSUE TITLE
d

### ISSUE THREAD

**Issue by RedDevileon** [RipMeApp/ripme#1003]
* Ripme version:
* Java version: 
* Operating system: 

* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Detail the expected behavior here.

## Actual Behavior

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Comment by kevin51jiang** [comment]
Please fill it out with appropriate information, or else we will have to close this issue.
