### ISSUE TITLE
problem with imgur via reddit ripper

### ISSUE THREAD

**Issue by cppsse** [RipMeApp/ripme#1023]
* Ripme version: 1.7.68
* Java version: openjdk version "1.8.0_171"
* Operating system: Debian Jessie 8.11
* Exact URL you were trying to rip when the problem occurred: https://www.reddit.com/user/StopFightingIt
* Please include any additional information about how to reproduce the problem:

Imgur must have changed their API today or yesterday.  When ripping a reddit user, the image (https://imgur.com/9krCX1U) should be returned but instead a 4031 byte file with the name "9rlygpMy_first_post_here..." is downloaded which contains HTML.  I have renamed the file to .txt and have attached it here.  I tried reverted back to ripme 1.7.67 to see if this had something to do with the change for limiting filenames to < 255 but had the same behavior.

[97YS8C~Z.txt](https://github.com/RipMeApp/ripme/files/2522339/97YS8C.Z.txt)

Initialized ripme v1.7.68
Setting locale to default
    Downloading file: https://i.imgur.com/ Retry #1
[+] Saved https://i.imgur.com/ as ./9rlygpMy_first_post_here...

**Comment by cyian-1756** [comment]
@cppsse 

Retesting this with 1.7.69 it works fine, looks like this was fixed on accident

**Comment by cppsse** [comment]
I will upgrade to 1.7.69 and test a dozen or so of the users that are having this problem.  Will report back.

**Comment by cppsse** [comment]
Tested against 10 users where this problem existed and cannot reproduce the issue with 1.7.69 so let's go ahead and close this one out.
