### ISSUE TITLE
Please Fix The Update Dialog!

### ISSUE THREAD

**Issue by goodboi69** [RipMeApp/ripme#1026]
This is ridiculous. Please fix the new update dialog window.
![untitled-1](https://user-images.githubusercontent.com/43517545/47620060-27b9e080-dabc-11e8-98ac-25c81c55037f.jpg)

**Comment by goodboi69** [comment]
@mkoryak There's no reason to be a prick.
@cyian-1756

**Comment by mkoryak** [comment]
Agreed, being a prick is ridiculous!

**Comment by rautamiekka** [comment]
> Agreed, being a prick is ridiculous!

So by your logic: no one is allowed to bring up a problem, and **must** fix it **themselves**.

**Comment by mkoryak** [comment]
No, it's all in the tone.

**Comment by Hrxn** [comment]
Yeah. For example, start with giving your issue a proper title.

**Comment by cyian-1756** [comment]
@Tush-r Testing out your changes they work fine, make a PR and I'll merge it in
