### ISSUE TITLE
Flickr

### ISSUE THREAD

**Issue by InsiderAdam** [RipMeApp/ripme#1046]
* Ripme version: 1.7.69

## Expected Behavior

Ripping entire album or photostream from a user

## Actual Behavior

Error: "No images found at.."

Is there any progress on updating RipMe to work with Flickr?

**Comment by cyian-1756** [comment]
> Is there any progress on updating RipMe to work with Flickr?

There's not been any work done on that in months

**Comment by InsiderAdam** [comment]
Flickr has announced it will start deleting photos from accounts that have more than 1,000 photos. Would it be possible to expedite this issue so people can download their albums before the purge?

**Comment by chemistx** [comment]
> Flickr has announced it will start deleting photos from accounts that have more than 1,000 photos. Would it be possible to expedite this issue so people can download their albums before the purge?

saleen software  makes a flickr downloader, has no limits and downloads the highest res available

**Comment by cyian-1756** [comment]
> Would it be possible to expedite this issue so people can download their albums before the purge?

It might be but I'd still recommend exporting your photos from flickr using flickrs webtools or one of the tools that can be found [here](https://github.com/search?q=flickr+download) as I can't guarantee that the ripper will be working before flickr starts deleting photos

**Comment by cyian-1756** [comment]
I have gotten the flickr ripper semi-working (It can download images, but they might not always be the largest and it only works for public albums) I'll merge the PR for the next ripme release
