### ISSUE TITLE
Command line usage on a headless server triggers error

### ISSUE THREAD

**Issue by MrTimscampi** [RipMeApp/ripme#105]
* Ripme version: 1.5.14.r0.g8064772
* Java version: OpenJDK9
* Operating system: Linux 4.13.4
* Exact URL you were trying to rip when the problem occurred: none
* Please include any additional information about how to reproduce the problem: Launch ripme in a terminal on a machine without a graphical server.

## Expected Behavior

The app should simply return an help page if no argument is passed, otherwise it should run the operation as intended.

## Actual Behavior

The app refuses to do anything and outputs the following error:

> Exception in thread "main" java.awt.HeadlessException:
> No X11 DISPLAY variable was set, but this program performed an operation which requires it.
>         at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:202)
>         at java.desktop/java.awt.Window.<init>(Window.java:534)
>         at java.desktop/java.awt.Frame.<init>(Frame.java:423)
>         at java.desktop/javax.swing.JFrame.<init>(JFrame.java:224)
>         at com.rarchives.ripme.ui.MainWindow.<init>(MainWindow.java:162)
>         at com.rarchives.ripme.App.main(App.java:60)

**Comment by cyian-1756** [comment]
> The app should simply return an help page if no argument is passed

The issue here is that ripme considers no args being passed as GUI mode

**Comment by metaprime** [comment]
The only interactive mode ripme has is the GUI, so why would you want to run it from a console with no args?

**Comment by MrTimscampi** [comment]
It's be nice to get instructions on how to use it if you're on headless.

I might tackle this this weekend.  
I've found out about the following piece of code, which could achieve what I want:

```java
if (GraphicsEnvironment.isHeadless()) {
     // redirect to the command line options, if no option is supplied, show an help page
} else {
     // start the gui
}```

I'm mostly running it headless through a Systemd Timer for automated ripping of a list of URLs, but still, it's a "nice to have" for cleanliness on the end-user part :)
