### ISSUE TITLE
Possible to rip User posts on reddit?

### ISSUE THREAD

**Issue by Zatoo1234** [RipMeApp/ripme#1055]
* Ripme version: v.1.7.69
* Java version: Build 1.8.0_191-b12
* Operating system: Win 7
* https://www.reddit.com/user/neshamira/posts/
* Please include any additional information about how to reproduce the problem: It's not possible to rip all posts of a user on reddit, I always get the error: Failed to load https://www.reddit.com/user/neshamira/posts/.json after 1 attempts. This does not happen when I rip from the user-overview for example: https://www.reddit.com/user/neshamira Is this supposed to happen?

## Actual Behavior

Always get this error when trying to rip all posts from a user Failed to load https://www.reddit.com/user/neshamira/posts/.json after 1 attempts

**Comment by GenuineSounds** [comment]
There is no need to complicate things

Just use https://www.reddit.com/user/neshamira/ as the link.

**Comment by cyian-1756** [comment]
@GenuineSounds is right, just remove posts from the url and it will work

**Comment by Zatoo1234** [comment]
> 
> 
> @GenuineSounds is right, just remove posts from the url and it will work

Okay thanks for your work :)
