### ISSUE TITLE
Update minimum supported Java version to Java 8

### ISSUE THREAD

**Issue by MrTimscampi** [RipMeApp/ripme#106]
The targeted Java version is currently (according to the readme) Java 1.6.

It has been out of support for a long while now, and so has Java 7.

I propose that we update the minimum required Java version to Java 8, to enable developers to use new functions of the language.

I would be interested in doing a PR for this, as well as run a preliminary code analysis to find outdated patterns we can replace with the version change.

**Comment by rautamiekka** [comment]
It might even prevent a whole lot of problems arising in the future ...

**Comment by cyian-1756** [comment]
I agree with setting the min version to 1.8

**Comment by MrTimscampi** [comment]
I am preparing a PR that sets the Maven target to 1.8 as well as fixes most of the errors/warnings/code smells found by Jetbrains code analysis tools.

Further refactoring will likely be needed, but I feel like that's a good start. The PR will obviously be big and thus require a decent review before merging, though.

**Comment by cyian-1756** [comment]
The update went thru, so I'm going to close this
