### ISSUE TITLE
History not appearing

### ISSUE THREAD

**Issue by samt108** [RipMeApp/ripme#109]
* Ripme version: 1.5.14
* Java version: 1.8.0_131
* Operating system: Windows 10.0.15063
* Exact URL you were trying to rip when the problem occurred: N/A
* Please include any additional information about how to reproduce the problem:

This is more of a meta problem than an expected behavior problem:

After updating today, my history almost completely disappeared. It's still in the json file, but only imgur is showing up in the ripme app. Pictures attached.
![ripme](https://user-images.githubusercontent.com/31720841/31709164-25efc6e0-b3bf-11e7-806b-6d7bd5fd0f5f.png)
![history](https://user-images.githubusercontent.com/31720841/31709165-26053b24-b3bf-11e7-901b-5adae070dd0a.png)

**Comment by Nono54Fr** [comment]
The history file and the properties file were moved from the **RipMe** folder to the **AppData\Local\RipMe** folder. The RipMe.log is more explicit about the exact path.

**Comment by samt108** [comment]
Wish it had moved it automatically, but moving it manually fixed the issue.
