### ISSUE TITLE
imagefap not saving titles

### ISSUE THREAD

**Issue by oilydrinkwater** [RipMeApp/ripme#1093]
* Ripme version: v1.7.72
* Java version:  openjdk version 1.8.0_181
* Operating system:  Debian 9 Linux

* Exact URL you were trying to rip when the problem occurred: https://www.imagefap.com/gallery.php?gid=7789753
* Please include any additional information about how to reproduce the problem: Not saving the album title. Save album titles box is checked.

## Expected Behavior imagefap_Red.Heels.Lover.In.Love_7789753

Detail the expected behavior here.

## Actual Behavior imagefap_7789753

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Comment by basemann** [comment]
After digging into this more and comparing this ripper with other sites' rippers, I was able to fix it by changing things up with the below patch:

```diff
diff --git a/src/main/java/com/rarchives/ripme/ripper/rippers/ImagefapRipper.java b/src/main/java/com/rarchives/ripme/ripper/rippers/ImagefapRipper.java
index 07a6e529..ae02b5ca 100644
--- a/src/main/java/com/rarchives/ripme/ripper/rippers/ImagefapRipper.java
+++ b/src/main/java/com/rarchives/ripme/ripper/rippers/ImagefapRipper.java
@@ -145,11 +145,9 @@ public class ImagefapRipper extends AbstractHTMLRipper {
         try {
             // Attempt to use album title as GID
             String title = getFirstPage().title();
-            Pattern p = Pattern.compile("^Porn pics of (.*) \\(Page 1\\)$");
-            Matcher m = p.matcher(title);
-            if (m.matches()) {
-                return getHost() + "_" + m.group(1) + "_" + getGID(url);
-            }
+            title = title.replace("Porn Pics & Porn GIFs", "");
+            title = title.replace(" ", "_");
+            return getHost() + "_" + title + "_" + getGID(url);
         } catch (IOException e) {
             // Fall back to default album naming convention
         }
```

**Comment by fernandezh1983** [comment]
Facing this issue as well. Has it been fixed?

**Comment by cyian-1756** [comment]
@fernandezh1983 The PR has been merged and the fix will be in the next update
