### ISSUE TITLE
PornHub website change

### ISSUE THREAD

**Issue by rautamiekka** [RipMeApp/ripme#1095]
* Ripme version: 1.7.72 (also tested 1.7.70)
* Java version: 
```
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
```
* Operating system:  `ver`=`Microsoft Windows [Version 10.0.17134.345]` x64

* Exact URL you were trying to rip when the problem occurred: https://www.pornhub.com/view_video.php?viewkey=ph5bcaa78082fb5 (NSFW)
* Please include any additional information about how to reproduce the problem:
`youtube-dl` 2018.12.03 (and 2018.06.04), made in Python 2.6.x-2.7.x and 3.2+, has no problems with the link.

## Expected Behavior

Rips like normal.

## Actual Behavior
```
Rip complete, saved to D:\_DOWNLOADS_\RipMe\rips\videos
java.io.IOException: Unable to find encrypted video URL at https://www.pornhub.com/view_video.php?viewkey=ph5bcaa78082fb5
```

**Comment by cyian-1756** [comment]
This was fixed in #1176
