### ISSUE TITLE
Tumblr rips and API key

### ISSUE THREAD

**Issue by john-mb** [RipMeApp/ripme#11]
The issue I'm experiencing seems to be a common one--when I try to rip from Tumblr, I get a message saying "null." There are multiple threads about this issue but I can't seem to resolve the problem even with a new API key. I think some explicit and detailed instructions would benefit me and others in the future who have no idea what the hell we're doing. Steps that may seem obvious to some may not be obvious to everyone. 

Anyway, here's what I've tried so far:
1. Downloaded the latest version (v1.5.1), tried to rip a Tumblr page, and it returned "null"
2. Registered a new application on Tumblr and got a key. It gave me two keys, an OAuth Consumer Key and a Secret Key. I tried the following steps with both keys. 
3. I updated tumblr.auth in rip.properties and DEFAULT_API_KEY in TumblrRipper.java. I opened and edited the files with Notepad++, saved the changes, and exited. 
4. Re-opened RipMe and tried it again, but it still returned "null"
5. Ran build.bat, re-opened RipMe and tried it again, still "null." I did not see a new JAR file after I ran build.bat. 

I'm sure there's some obvious thing I'm missing, but like I said, I don't really know what I'm doing. Any help is appreciated.

**Comment by cyian-1756** [comment]
> I did not see a new JAR file after I ran build.bat.

What was the out put of build.bat?

**Comment by john-mb** [comment]
The command prompt flashes and then goes away, but I was able to catch what it said: 
"[File path]\ripme-master>mvn clean compile assembly:single 'mvn' is not recognized as an internal or external command, operable program or hatch file."

**Comment by cyian-1756** [comment]
You don't have maven installed. But setting the api key in rip.properties should work. Are you running ripme from the same dir as your edited rip.properties?

**Comment by john-mb** [comment]
I think so??? I'm running RipMe from the ripme-master folder and I edited rip.properties in ripme-master>src>main>resources. Not sure if that answers the question. 

Something I just noticed: RipMe returns "null" but there are also a few other lines of output that I didn't pay much attention to. Upon closer inspection it seems that API key it's trying to use is not the new one I entered.

**Comment by cyian-1756** [comment]
> edited rip.properties in ripme-master>src>main>resources

You want to edit rip.properties in the same folder as ripme.jar. Try copy the edited rip.properties to the same folder as ripme

**Comment by john-mb** [comment]
It worked! Thanks for all your help.
