### ISSUE TITLE
updating to version 1.7.73 crashes and does not update. 

### ISSUE THREAD

**Issue by bossman762x39** [RipMeApp/ripme#1106]
* Ripme version:1.7.72
* Java version: no clue. 
* Operating system: macOS high sierra

* Exact URL you were trying to rip when the problem occurred: no URL just trying to update from 1.7.72 to 1.7.73
* Please include any additional information about how to reproduce the problem: have not been able to update version for the last couple updates. i end up having to redownload the .jar file and deleting the old one because it crashes and when i open the program again it has not updated. 

## Expected Behavior
update as normal 
Detail the expected behavior here.
update to the new version 
## Actual Behavior
i hit yes to update and the program crashes and does not update. 
i have to download the new .jar file from here to get new version and delete old .jar file

**Comment by cyian-1756** [comment]
Can you run ripme from the terminal (with `java -jar ripme.jar`) and post the output generated whemn you try to update

**Comment by bossman762x39** [comment]
i have not used ripme with terminal before but tried it and i got this Error: Unable to access jarfile ripme.jar .  i use the guide from https://github.com/ripmeapp/ripme/wiki/How-To-Run-RipMe

**Comment by bossman762x39** [comment]
thank you cyian-1756, you have been so awesome. very quick with your replies and always so helpful. opening it in terminal updated it with no issue.

**Comment by cyian-1756** [comment]
> opening it in terminal updated it with no issue.

Weird. I have no idea why that worked but updating normally didn't.
