### ISSUE TITLE
Tumblr's different rate limit between download image server and video server

### ISSUE THREAD

**Issue by HdbKing** [RipMeApp/ripme#1108]
* Ripme version: 1.7.7
* Java version: newest java8
* Operating system: winver
* Exact URL you were trying to rip when the problem occurred: all
* Please include any additional information about how to reproduce the problem:

Tumblr have different download rate limit with his image and video server.
I hope have different download threads option with  image and video.

**Comment by cyian-1756** [comment]
Can you explain in more detail? Are you getting rate limited?

**Comment by rautamiekka** [comment]
RipMe 1.7.7 is very old, 'java8' is an invalid Java version string, not to mention 'winver' ain't a version string either, and 'all' for the 'exact URL' is as helpful as a placebo pill.
