### ISSUE TITLE
Ripme update downloads to $HOME directory even when currently running one is in different directory

### ISSUE THREAD

**Issue by BurhanDanger** [RipMeApp/ripme#1111]
* Ripme version: `1.7.74`
* Java version:   `openjdk version "1.8.0_192"`
* Operating system:  `archlinux`

## Actual Behavior

ripme.jar is located in `~/Documents/RIPME` but whenever it updates , new updated one goes to $HOME directory. 

## Expected Behavior

Updated one should be in the same directory as the currently running one and replace that .jar file

**Comment by cyian-1756** [comment]
Oh wow can't believe I never noticed that before

**Comment by cyian-1756** [comment]
This should be fixed in the latest version of ripme

**Comment by BurhanDanger** [comment]
```
$ pwd
/home/n00b

$ java -jar ~/Documents/RIPME/ripme.jar
Loaded /home/n00b/.config/ripme/rip.properties
Loaded log4j.properties
Initialized ripme v1.7.81
Setting locale to en_US
Loading history from /home/n00b/.config/ripme/history.json
Retrieving https://raw.githubusercontent.com/ripmeapp/ripme/master/ripme.json
oldVersion 1.7.81 < latestVersion1.7.82
Found newer version: 1.7.82
Saved configuration to /home/n00b/.config/ripme/rip.properties
```

@cyian-1756 can you please try this and check how that works ?

**Comment by cyian-1756** [comment]
Looks like this is still an issue.
