### ISSUE TITLE
Rip Me Language doesn't stay changed

### ISSUE THREAD

**Issue by goodboi69** [RipMeApp/ripme#1112]
Rip Me v1.7. 74
Windows 10 64bit

Every time I open Rip Me the language defaults to de_DE. When I change it to en_US, close it, and re-open it, it is still de_DE.

**Comment by rautamiekka** [comment]
Got the same problem with 1.7.70 and 1.7.72 but not 1.7.64.

**Comment by BurhanDanger** [comment]
It show de_DE but interface is actually English.

**Comment by cyian-1756** [comment]
> Much better solution is to add a feature to load locale from config file.

AFAIK that feature already exists, it's just not working

**Comment by Tush-r** [comment]
> 
> 
> > Much better solution is to add a feature to load locale from config file.
> 
> AFAIK that feature already exists, it's just not working

Looked into it. The `lang` config option is used to store the language in the config.
RipMeApp was not saving the chosen language on exit and also not loading the saved language at startup.
Fixed it here: https://github.com/Tush-r/ripme/commit/911fef6e557d46d30bf80703f1c7a38e68380b7c
Pulling a request for this is also merging my previous pull request( https://github.com/RipMeApp/ripme/pull/1115). Therefore, I've not done it.

Do let me know if there are any errors or a better way to do it.

**Comment by Tush-r** [comment]
@cyian-1756 
This issue has been fixed with version 1.7.75
https://github.com/RipMeApp/ripme/commit/90b7f1e45a7aa91145402d4577133cd451fe4560
This can be closed.
