### ISSUE TITLE
Luscious.net 

### ISSUE THREAD

**Issue by mxlvr** [RipMeApp/ripme#1119]
* Ripme version:
1.7.74
* Exact URL you were trying to rip when the problem occurred:
https://luscious.net/albums/women-of-color_58/
* Please include any additional information about how to reproduce the problem:

## Expected Behavior
Download of the full gallery
Detail the expected behavior here.

## Actual Behavior
After 320 Pictures error "no protocol: //cdni.luscious.net/757/lusciousnet_curly_haired_beauty_1474259667.jpg" shows up, stops ripping the gallery

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Comment by cyian-1756** [comment]
Looks like a minor issue with the ripper not checking if the url has https in it
