### ISSUE TITLE
[Request] support for www.gfycat.com

### ISSUE THREAD

**Issue by evetaku** [RipMeApp/ripme#1124]
* Ripme version: 17.74
* Java version: 1.8.0_1.9.1 Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
* Operating system: 
Windows 10 Enterprise N edition version 1809 OS Build 17763.195
* Exact URL you were trying to rip when the problem occurred: https://gfycat.com
* Please include any additional information about how to reproduce the problem:
1. aditional download in bulk downloader in whole profile, example link 
https://gfycat.com/@golbanstorage
2. aditional configuration save without folder file

**Comment by cyian-1756** [comment]
Please make all site requests in #38
