### ISSUE TITLE
save urls doesn't windows newlines

### ISSUE THREAD

**Issue by cyian-1756** [RipMeApp/ripme#1129]
* Ripme version: 1.7.74
* Java version: 
* Operating system:  Windows 10

* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

This bug was first reported on [here on reddit](https://www.reddit.com/r/ripme/comments/a9x7c9/possible_to_setup_ripme_to_generate_urls_on/)

each url goes on it's own line

## Actual Behavior

ripme uses a unix newline (\n) rather than a windows newline (\r\n). This can be fixed by using System.lineSeparator() instead of hardcoding \n

**Comment by rautamiekka** [comment]
Doesn't this break the file when moving between line endings (platforms) ?

**Comment by cyian-1756** [comment]
> Doesn't this break the file when moving between line endings (platforms) ?

Yea but if you're moving platforms you can always just use dos2unix or some similar program to change the line endings
