### ISSUE TITLE
Hentai foundry pdf test faulty

### ISSUE THREAD

**Issue by cyian-1756** [RipMeApp/ripme#1144]
* Ripme version: 1.7.76
* Java version:  1.8.0_191
* Operating system:  Ubunti 16.04

* Exact URL you were trying to rip when the problem occurred: https://www.hentai-foundry.com/stories/user/Rakked
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

The test to pass

## Actual Behavior

Despite being able to rip pdfs from https://www.hentai-foundry.com/stories/user/Rakked without issue the test always fails with "junit.framework.AssertionFailedError: Failed to download a single file from https://www.hentai-foundry.com/stories/user/Rakked"

**Comment by Tush-r** [comment]
Tests run fine on Windows 7 machine with same JRE version.

**Comment by cyian-1756** [comment]
I found the issue! I forgot an else in HentaifoundryRipper.java 

the function was 

```java
@Override
    public void downloadURL(URL url, int index) {
        // When downloading pdfs you *NEED* to end the cookies with the request or you just get the consent page
        if (url.toExternalForm().endsWith(".pdf")) {
            addURLToDownload(url, getPrefix(index), "", this.url.toExternalForm(), cookies);
        }
        addURLToDownload(url, getPrefix(index));
    }
```

If the url being added was a pdf it would be added twice, once in the if and then after. I assume this triggered a bug with the download queue that caused the file not to be downloaded

changing it to 

```java
@Override
    public void downloadURL(URL url, int index) {
        // When downloading pdfs you *NEED* to end the cookies with the request or you just get the consent page
        if (url.toExternalForm().endsWith(".pdf")) {
            addURLToDownload(url, getPrefix(index), "", this.url.toExternalForm(), cookies);
        } else {
            addURLToDownload(url, getPrefix(index));
        }
    }
```

caused the test to pass as expected
