### ISSUE TITLE
Updater should be pure java

### ISSUE THREAD

**Issue by cyian-1756** [RipMeApp/ripme#1153]
* Ripme version: 1.7.76
* Java version: 
* Operating system: 

* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

For portability and maintainability reasons the updater should be written entirely in java

## Actual Behavior

Right now much of the actual updating process is handle by a shell script

**Comment by cyian-1756** [comment]
> This would be rather hard with windows: you'd need an external jar to modify the main one

Why? I've never really done any programming on windows so you'll have to forgive me if there an obvious answer, but once ripme.jar is loaded in memory what's stopping it from just overwriting the copy on disk with the updated version?

**Comment by buzzlightmonth** [comment]
Exactly, Windows doesn't allow for filed to be removed when they're being execute (or even open in a program).
The batch script might be the easiest solution, other solutions probably include a jar that does only updating, or download the update as `ripme.update.jar` and detect upon launch if the filename includes the word update then delete `ripme.jar`, copy current file into `ripme.jar` and relaunch from there (and delete `ripme.update.jar` if it exists at launch).
