### ISSUE TITLE
Some sites still work on v1.7.49 but stopped working since then

### ISSUE THREAD

**Issue by domonic46** [RipMeApp/ripme#1165]
* Ripme version: 1.7.49 to 1.7.76
* Java version: 
* Operating system:  windows 7

* Exact URL you were trying to rip when the problem occurred: NSFW 
http://anonsharer.org/milf/res/392.html 
https://bbw-chan.nl/booty/res/35027.html
 
Some websites still work on v1.7.49 (and some older versions) but do not work on the newer versions of ripme. It seems to be mainly chan sites that stopped being supported after v1.7.49

2 examples (NSFW):

1. http://anonsharer.org/ 
Example: http://anonsharer.org/milf/res/392.html

2. bbw-chan.nl/
Example: https://bbw-chan.nl/booty/res/35027.html

Both those example sites stiil work on v1.7.49 but do not work on the newer versions of ripme

**Comment by cyian-1756** [comment]
This happened because before 1.7.50 the chan ripper just claimed all URLs with /res/ in them, how ever this had to be changed because it caused a bug

I'll add support for those chans for the next version of ripme

**Comment by domonic46** [comment]
Just to add, other sites with the same issue are the many 4chan archive websites such as thebarchive.com

**Comment by domonic46** [comment]
Just wanted to follow up, any update?

**Comment by cyian-1756** [comment]
@domonic46 

Once #1006 gets merged you'll be able to add support for any chan by editing a line in rip.properties 

Sorry it's taking so long but this got pushed to the back burner

**Comment by cyian-1756** [comment]
This should be fixed by #1006.

To add support for those sites in 1.7.83 all you'll have to do it open rip.properties and add the line 

chans.chan_sites = bbw-chan.nl[bbw-chan.nl]

The format for these entries is SITE.TLD[CDN_SITE.TLD|CDN2_site.TLD] and they should be comma seperated
