### ISSUE TITLE
Update message way to big

### ISSUE THREAD

**Issue by pmajkutewicz** [RipMeApp/ripme#1167]
* Ripme version: 1.7.70
* Java version: 
```
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
```
* Operating system: Linux Mint 19.1

## Expected Behavior

Popup with update info should fit into one monitor and/or have reasonable size

## Actual Behavior

Popup with update info takes 75% of two monitors. It is hard to read.
![ripme](https://user-images.githubusercontent.com/12598208/51209555-c7934780-1910-11e9-895d-3d733c87a80d.jpg)

**Comment by cyian-1756** [comment]
This was fixed in the 1.7.75 update
