### ISSUE TITLE
Ripme not ripping anything 

### ISSUE THREAD

**Issue by cyian-1756** [RipMeApp/ripme#1169]
* Ripme version: Master, commit b76b930d62002f09cabb30d1b421e736cf7d486d
* Java version: 
* Operating system: 

* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Things rip as normal 

## Actual Behavior

Trying to rip any url errors out with 

```
Exception in thread "Thread-5" java.lang.IncompatibleClassChangeError: Expected static field com.rarchives.ripme.ripper.AbstractHTMLRipper.alreadyDownloadedUrls
	at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:99)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:562)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by cyian-1756** [comment]
After checking out some old commits and then switching back to master I can no longer trigger this error. I'm going to test it some more later and if I still can't repro it I'll close this issue

**Comment by rautamiekka** [comment]
What links ?

**Comment by Tush-r** [comment]
IncompatibleClasssChangeError may have been caused by recompilation of a base class( Abstractripper) after the compilation of sub class.
Also alreadyDownloadedUrls field is not static in the master branch.  Maybe switching between the branches caused the error.

**Comment by cyian-1756** [comment]
@Tush-r As I've been unable to reporduce the issue I'm assuming that you were right
