### ISSUE TITLE
HentaiFoundry Ripper does not make a separate folder for each site/artist

### ISSUE THREAD

**Issue by chrsmlls333** [RipMeApp/ripme#1179]
* Ripme version: v1.7.76
* Java version: 1.8.0_191
* Operating system: Microsoft Windows [Version 10.0.17763.253]

* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Most other rippers dump their downloaded pics in a separate, labeled directory.

## Actual Behavior

HentaiFoundry ripper puts all images in `hentai-foundry_pictures/<num>_<artist>-<id>-<title>.ext`

To match other rippers and Ripme expected behaviour, it should output `hentai-foundry_<artist>/<num>_<id>-<title>.ext`

**Comment by chrsmlls333** [comment]
It did? What version are you on? Mine still saved to `hentai-foundry_pictures` when I followed your link or any valid one on my end.

**Comment by buzzlightmonth** [comment]
I'm on version 1.7.76, however am using the latest commit on the master branch.
I checked using the live version and indeed do have this issue, so it was probably fixed on a commit since the last release.

This means that this should be fixed with the next release.

**Comment by chrsmlls333** [comment]
Yeah I think you're right, peering at the code. Thanks for your help! I'll wait for the new release.
