### ISSUE TITLE
vine.co ripper broken

### ISSUE THREAD

**Issue by cyian-1756** [RipMeApp/ripme#118]
* Ripme version: 1.5.15
* Java version: 1.8.0_131
* Operating system: Ubuntu 16.04
* Exact URL you were trying to rip when the problem occurred: https://vine.co/u/954440445776334848
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

The ripper downloads all the images

## Actual Behavior

The ripper returns `Failed to load https://vine.co/api/timelines/users/954440445776334848 after 4 attempts`

**Comment by MrTimscampi** [comment]
For anybody interested in working on this:

Vine shut down and the website is now an archive or (some of ?) the content.

The API doesn't exist anymore, but the pages themselves still seem to be at the same location they were before.  
As a result, a full rewrite of the ripper is necessary.

**Comment by cyian-1756** [comment]
> The API doesn't exist anymore, but the pages themselves still seem to be at the same location they were before.

After some exploring vine seems to have moved to a largely undocumented archive api. Some api calls like `GET https://vine.co/api/users/profiles/vanity/USERNAME` still work, whereas many other do not

**Comment by cyian-1756** [comment]
Is it just me or does vine.co not show any videos? No matter which page I go to on the site no vines load

**Comment by Hrxn** [comment]
Well, I think they (Twitter) planned to shutdown the site some time ago. Maybe they've finally done it.

**Comment by cyian-1756** [comment]
> Well, I think they (Twitter) planned to shutdown the site some time ago. Maybe they've finally done it.

Yea but didn't they also put up a archive? Or are they planning on shutting down the archive as well?

**Comment by Hrxn** [comment]
I'm not sure, but maybe that is the case. I wouldn't be surprised, to be honest.
