### ISSUE TITLE
History with reddit.com string is wiped out - history.json is fine

### ISSUE THREAD

**Issue by timdafweak** [RipMeApp/ripme#119]
* Ripme version: 1.5.15
* Java version: java version "1.6.0_65"
* Operating system: macOS 10.12.6
* Exact URL you were trying to rip when the problem occurred: n/a
* Please include any additional information about how to reproduce the problem:
Upon loading, the history leaves out all reddit.com URLs. Only lists the imgur and other URLs. History.json contains a complete list of all URLs. 

## Expected Behavior
All URLs should be shown

## Actual Behavior
Only imgur and non-reddit.com urls show up in the history tab

**Comment by cyian-1756** [comment]
Can you give me an example URL?

**Comment by timdafweak** [comment]
Sure, try https://www.reddit.com/user/Gingerpuss

Rip and exit and then start ripme.jar and look at history tab.

**Comment by cyian-1756** [comment]
> Rip and exit and then start ripme.jar and look at history tab.

I did and everything seems fine. The url is in history. This might has something to do with your ancient java version, try updating to a more recent version and try ripping the url again

**Comment by revanwolf** [comment]
I have a similar bug but with all history wiped(imgur/instagram/reddit/twitter/etc) since version 1.5.14 with Java 1.8.0_151.

I think the reason is ripme use AppData/Local folder and don't use the folder where it run.

**Comment by cyian-1756** [comment]
> I think the reason is ripme use AppData/Local folder and don't use the folder where it run.

That's pretty odd. I don't see why ripme wouldn't be able to read and write from AppData/Local (Unless you changed the permissions of that folder)

**Comment by revanwolf** [comment]
Because it never have to use the AppData folder, this software is created to be independent(aka only use the folder it is run) but you changed this behaviour.

**Comment by timdafweak** [comment]
Updated Java, added all the URLs again, and the issue is gone. Strange that the latest update to ripme refused to read older history.json entries. Anyway.
