### ISSUE TITLE
Artstation does not download anymore.

### ISSUE THREAD

**Issue by Butterfly-Dragon** [RipMeApp/ripme#1208]
* Ripme version: 1.7.7.8
* Java version: java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
* Operating system: Microsoft Windows [Version 10.0.17763.253]
* Exact URL you were trying to rip when the problem occurred: https://www.artstation.com/alexineskiba
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

downloading the gallery

## Actual Behavior

![image](https://user-images.githubusercontent.com/33538906/52381599-66bfe080-2a72-11e9-8852-add38b51f281.png)

gives me the above error for every artstation gallery.

**Comment by UnforeseenOcean** [comment]
Does it happen with `https://(artistname).artstation.com` too?

**Comment by Butterfly-Dragon** [comment]
I have not checked, the galleries are often completely different, as one is
the professional gallery and yhe oyher is the "casual browser" gallery.

**Comment by Butterfly-Dragon** [comment]
tried to download from artstation right now with the url you said to try. I get an error message saying it does not recognize the page it gets.

![image](https://user-images.githubusercontent.com/33538906/52824531-4a96f180-30b9-11e9-9658-4cb453d4db71.png)

**Comment by Butterfly-Dragon** [comment]
same artist but the "proper" url gives me this: 
![image](https://user-images.githubusercontent.com/33538906/52824738-11ab4c80-30ba-11e9-9ac3-185475c07463.png)
