### ISSUE TITLE
twitter download doesnt work

### ISSUE THREAD

**Issue by shmct** [RipMeApp/ripme#1213]
* Ripme version: V1.7.78
* Java version: 1.8.0
* Operating system: Win 10

## Expected Behavior

download work.

## Actual Behavior
Doesn't work , the log show"Failed to load https://api.twitter.com/oauth2/token after 1 attempts".

![image](https://user-images.githubusercontent.com/9691285/52718893-75147c00-2fdf-11e9-8718-5447a8acc302.png)

**Comment by UnforeseenOcean** [comment]
Please set your Twitter token on rip.properties!
