### ISSUE TITLE
Request - myreadingmanga.info

### ISSUE THREAD

**Issue by UnforeseenOcean** [RipMeApp/ripme#1214]
(All examples below do not contain characters below the age of consent or 18 years of age)

Page example: `https://myreadingmanga.info/zelo-lee-brave-lover-dj-slave-market-jp/`
This page uses lazy loading plugin for Wordpress (that's why I couldn't download it, because my ripper cannot read the `data-lazy-src` tag)
For example:
`<div class="separator" style="clear: both; text-align: center;"><img src="../wp-content/plugins/lazy-load/images/1x1.trans.gif" data-lazy-src="https://4.bp.blogspot.com/-49bdfDMOjLg/W5dxKPsVBNI/AAAAAAALi6Q/EkaRoGuaN7goklza_5LvkyJuYLG0vk52wCLcBGAs/s1600/NSFW1OriginalDone.jpg" border="0" data-original-width="900" data-original-height="1220"><noscript><img src="https://4.bp.blogspot.com/-49bdfDMOjLg/W5dxKPsVBNI/AAAAAAALi6Q/EkaRoGuaN7goklza_5LvkyJuYLG0vk52wCLcBGAs/s1600/NSFW1OriginalDone.jpg" border="0" data-original-width="900" data-original-height="1220" /></noscript></div>`
However, a direct link to images are given in the `<noscript>` tag.
The massive amount of lazy loading BS gets removed as JavaScript loads, leaving only the original image tag.

**Comment by cyian-1756** [comment]
Please make any requests in #38 

It should be easy enough to add support for the site

**Comment by UnforeseenOcean** [comment]
It has been moved, thus this issue is safe to close.
