### ISSUE TITLE
RipMe Hanging On A Link

### ISSUE THREAD

**Issue by goodboi69** [RipMeApp/ripme#1219]
* Ripme version: 1.7.79
* Java version: 8 Update 1.8.0-181-b13
* Operating system: Win10

* Exact URL you were trying to rip when the problem occurred: https://www.reddit.com/user/carmendelrose/
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

To Rip this profile.

## Actual Behavior

Rip starts and then hangs at 98%

[Screenshot](https://user-images.githubusercontent.com/43517545/53120293-83065780-351f-11e9-96b8-cc87281e5021.png)

> Already downloaded https://i.imgur.com/y5TD2WU.mp4
Already downloaded https://i.redd.it/9hy4t1fvjqh21.jpg
https://v.redd.it/obcf51swzph21/DASH_1080 already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\asnz13-obcf51swzph21-Old-.mp4
Already downloaded https://i.imgur.com/qq0Cjcm.mp4
Already downloaded https://i.imgur.com/ZpU7LYb.mp4
Downloading https://v.redd.it/7na3o9ez4lh21/DASH_720 DASH_1080
https://v.redd.it/7na3o9ez4lh21/DASH_720 DASH_1080 : Non-retriable status code 400 while downloading https://v.redd.it/7na3o9ez4lh21/DASH_720 DASH_1080
Already downloaded https://i.imgur.com/OiC83Uf.mp4
Already downloaded https://i.imgur.com/MJ3coQu.mp4
Already downloaded https://i.redd.it/jogjrbpq2lh21.jpg
Already downloaded https://i.redd.it/g8fqfq1ogjh21.jpg
https://v.redd.it/0a4rc00majh21/DASH_720 already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\asavlf-0a4rc00majh21-girl next door-.mp4
Already downloaded https://i.imgur.com/MBJxru4.mp4
Already downloaded https://i.redd.it/hbjo7bo4vih21.jpg
https://v.redd.it/z53pmvajadh21/DASH_1080 already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\as01p2-z53pmvajadh21-Bending over for you-.mp4
https://v.redd.it/frfjp03xg5h21/DASH_720 already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\arlpet-frfjp03xg5h21-Feeling myself-.mp4
https://v.redd.it/ud4pccmv05h21/DASH_720 already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\arky0p-ud4pccmv05h21-Another damn announcement🥰🌹❣️-.mp4
Already downloaded https://i.redd.it/xu2lb3mqt4h21.jpg
Already downloaded https://i.redd.it/n2qm1cmbl4h21.jpg
Already downloaded https://i.imgur.com/xiF3tRf.mp4
Already downloaded https://i.imgur.com/dqSQReg.mp4
https://v.redd.it/esgan7kdc1h21/DASH_480 already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\arftfs-esgan7kdc1h21-golden-.mp4
Already downloaded https://i.imgur.com/OCvNjdt.mp4
Already downloaded https://i.redd.it/pp9jk45mxxg21.jpg
Already downloaded https://i.imgur.com/qZA1b4l.mp4
Already downloaded https://i.imgur.com/JVpV82z.mp4
Already downloaded https://i.imgur.com/LV5tLe6.mp4
https://v.redd.it/sv0z00xqywg21/DASH_1080 already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\ar7wxd-sv0z00xqywg21-Another announcement!!!😇💠💙-.mp4
Already downloaded https://i.imgur.com/BoOU1pO.mp4
Already downloaded https://i.imgur.com/EX6DzVq.mp4
Already downloaded https://i.imgur.com/JVpV82z.mp4
Already downloaded https://i.imgur.com/heUKSgT.mp4
Already downloaded https://i.imgur.com/qZA1b4l.mp4
Already downloaded https://i.imgur.com/JqCamzD.mp4
https://v.redd.it/tbib4fwjdsg21/DASH_1080 already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\ar0gma-tbib4fwjdsg21-Below-.mp4
Already downloaded https://i.redd.it/e0a5dmrelqg21.jpg
https://v.redd.it/uwvl6npt5ig21/DASH_480 already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\aqi0c7-uwvl6npt5ig21-Playing-.mp4
https://v.redd.it/3igdakefjcg21/DASH_1080 already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\aq75lk-3igdakefjcg21-💔-.mp4
Already downloaded https://i.imgur.com/qZA1b4l.mp4
https://v.redd.it/1q1iz5h7fxf21/DASH_720 already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\apfflb-1q1iz5h7fxf21-🍭💖🍭-.mp4
https://v.redd.it/xmo2k944exf21/DASH_480 already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\apfdzk-xmo2k944exf21-Ready position-.mp4
https://v.redd.it/17sgqn9ryuf21/DASH_720 already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\apc061-17sgqn9ryuf21-Taking requests and all sorts 😁💖-.mp4
https://v.redd.it/sxzc5fi6puf21/DASH_720 already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\apbj4z-sxzc5fi6puf21-Look back at it-.mp4
Already downloaded https://i.imgur.com/S5LxqSa.mp4
Already downloaded https://i.imgur.com/JqCamzD.mp4
Already downloaded https://i.redd.it/cv64jwonmsf21.jpg
https://v.redd.it/vea4kiqwpqf21/DASH_720 already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\ap3qyi-vea4kiqwpqf21-balls deep-.mp4
https://v.redd.it/6idu6u284qf21/DASH_1080 already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\ap30xa-6idu6u284qf21-cellulite-.mp4
https://v.redd.it/8a7pu7k03qf21/DASH_1080 already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\ap2zj2-8a7pu7k03qf21-baby blue-.mp4
https://v.redd.it/tye45kzhzmf21/DASH_720 already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\aoyrij-tye45kzhzmf21-🍭-.mp4
Downloading https://v.redd.it/duzsqisezmf21/DASH_720 DASH_1080
https://v.redd.it/duzsqisezmf21/DASH_720 DASH_1080 : Non-retriable status code 400 while downloading https://v.redd.it/duzsqisezmf21/DASH_720 DASH_1080
Already downloaded https://i.redd.it/ok5ybbbcylf21.jpg
Already downloaded https://i.redd.it/5gdid4bm8jf21.jpg
https://v.redd.it/t96fo65f8jf21/DASH_720 already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\aorqvx-t96fo65f8jf21-Jiggle-.mp4
https://v.redd.it/yong83ub7jf21/DASH_720 already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\aorpik-yong83ub7jf21-Cum slut-.mp4
Already downloaded https://i.redd.it/9yqrkhrc1jf21.jpg
Already downloaded https://i.imgur.com/mY1990S.mp4
Already downloaded https://i.redd.it/ulhg3354qif21.jpg
Already downloaded https://i.imgur.com/Z44IrsZ.mp4
https://v.redd.it/rkhdvu4c9df21/DASH_1080 already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\aohuht-rkhdvu4c9df21-Temporary verification💖❤️😻-.mp4
Already downloaded https://i.redd.it/u2z2ffow3df21.jpg
Downloading https://v.redd.it/x99ofieb2df21/DASH_720
Already downloaded https://i.redd.it/p6fr1fgul9f21.jpg
Already downloaded https://i.imgur.com/nYjh2yn.mp4
Already downloaded https://i.imgur.com/xcZApXm.mp4
Already downloaded https://i.redd.it/kq1xrtbf57f21.jpg
https://v.redd.it/uci7eety47f21/DASH_480 already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\ao7dl5-uci7eety47f21-Home alone all weekend. PM me to play😁-.mp4
https://v.redd.it/3tqg31wcf5f21/DASH_720 already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\ao3s0t-3tqg31wcf5f21-Black socks-.mp4
https://v.redd.it/jlsavo5ze5f21/DASH_480 already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\ao3r74-jlsavo5ze5f21-Snapchat fun🧡-.mp4
https://v.redd.it/amgj0uz269e21/DASH_1080 already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\amkmua-amgj0uz269e21-B o o t y-.mp4
Already downloaded https://i.redd.it/ke0pt2cn46e21.jpg
Already downloaded https://i.redd.it/tkargjy4pyc21.jpg
Already downloaded https://i.redd.it/byeuakzctuc21.jpg
https://v.redd.it/kiy70sr1ruc21/DASH_4_8_M already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\ak6fmk-kiy70sr1ruc21-special premium snapchat offer_ $40 lifetime _) today only!-.mp4
Already downloaded https://i.redd.it/2ir90bqtkuc21.jpg
Already downloaded https://i.redd.it/87xlz0fmkuc21.jpg
Already downloaded https://i.redd.it/kbz8ageikuc21.jpg
https://v.redd.it/itqq6cqd7uc21/DASH_4_8_M already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\ak5dqy-itqq6cqd7uc21-bend me over-.mp4
https://v.redd.it/iwgbl1p6d8c21/DASH_4_8_M already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\aj3xh2-iwgbl1p6d8c21-daydreaming-.mp4
Already downloaded https://i.redd.it/fficofw5c8c21.jpg
Already downloaded https://i.redd.it/061skt51c8c21.jpg
Already downloaded https://i.redd.it/4cwnv11xb8c21.jpg
https://v.redd.it/gqlkg72af7c21/DASH_9_6_M already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\aj1tee-gqlkg72af7c21-black and white-.mp4
https://v.redd.it/i9myj1tse7c21/DASH_9_6_M already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\aj1saf-i9myj1tse7c21-bounce _)-.mp4
Already downloaded https://i.redd.it/rexbvzbhd7c21.jpg
https://v.redd.it/wfhhydvzbmb21/DASH_4_8_M already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\ai0g08-wfhhydvzbmb21-filmed a really fun voyeurism clip today!-.mp4
https://v.redd.it/cuvnwzcd9lb21/DASH_2_4_M already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\ahy329-cuvnwzcd9lb21-pretty on pink-.mp4
https://v.redd.it/n9l07arnmkb21/DASH_4_8_M already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\ahx086-n9l07arnmkb21-playing-.mp4
https://v.redd.it/3j0grvbllfb21/DASH_4_8_M already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\ahpajm-3j0grvbllfb21-strip-.mp4
Already downloaded https://i.redd.it/6clnwo7alfb21.jpg
https://v.redd.it/38vg16kuv6b21/DASH_9_6_M already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\ahasts-38vg16kuv6b21-fishnets cured my depression-.mp4
https://v.redd.it/016a4jalq6b21/DASH_4_8_M already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\ahajjm-016a4jalq6b21-drooly for him😛-.mp4
Already downloaded https://i.redd.it/h5zhzu5fq6b21.jpg
Already downloaded https://i.redd.it/5hvcw3e6q6b21.jpg
https://v.redd.it/mj82xh5jp6b21/DASH_4_8_M already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\ahahtj-mj82xh5jp6b21-uploading to my snap all day _)-.mp4
https://v.redd.it/0bbccop5p6b21/DASH_4_8_M already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\ahah4x-0bbccop5p6b21-clit-.mp4
Already downloaded https://i.redd.it/mukcojrsn6b21.jpg
Already downloaded https://i.redd.it/xnrskn6qn6b21.jpg
https://v.redd.it/wnafa6fl90b21/DASH_9_6_M already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\agz4on-wnafa6fl90b21-my dog approves-.mp4
https://v.redd.it/ol4b3itzmza21/DASH_4_8_M already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\agxx7a-ol4b3itzmza21-guys i’m so unsure if i should keep this account or start again _(-.mp4
https://v.redd.it/vljj6vfs8za21/DASH_2_4_M already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\agxacm-vljj6vfs8za21-flash-.mp4
https://v.redd.it/iyzwisal8za21/DASH_4_8_M already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\agxa3h-iyzwisal8za21-drooly-.mp4
https://v.redd.it/j15nailf8za21/DASH_9_6_M already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\agx9sz-j15nailf8za21-sparkly-.mp4
Already downloaded https://i.redd.it/w8byd6na8za21.jpg
https://v.redd.it/68kk7ri48za21/DASH_4_8_M already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\agx9as-68kk7ri48za21-bounce-.mp4
Already downloaded https://i.redd.it/9ld734jmgz821.jpg
Already downloaded https://i.redd.it/l6lqg521dl821.jpg
https://v.redd.it/62gzbbh3b7821/DASH_2_4_M already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\ac58of-62gzbbh3b7821-my premium snap is something to worship...don’t miss out!-.mp4
https://v.redd.it/enxfvq58eo621/DASH_9_6_M already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\a9rmxz-enxfvq58eo621-god i love fishnets!-.mp4
https://v.redd.it/5zx0av4mem621/DASH_9_6_M already saved as Z:\Images\RipMe Rips\reddit_user_carmendelrose\a9oe2r-5zx0av4mem621-sale on today only! happy boxing day💋-.mp4
> Already downloaded https://giant.gfycat.com/GreedyTightJaguarundi.mp4

**Comment by cyian-1756** [comment]
that link rips without issue using ripme 1.7.83
