### ISSUE TITLE
thechive user uploads

### ISSUE THREAD

**Issue by AlexFundorin** [RipMeApp/ripme#1220]
1.7.79
It seems like the app knows about thechive.com (detects the gallery), yet, it can't bulk download all uploads (both jpg and gif) from a specific user, like https://i.thechive.com/Chivette1232 (highly recommend, BTW).
https://i.imgur.com/CL9Ov5U.png

**Comment by AlexFundorin** [comment]
No progress, yet?

**Comment by cyian-1756** [comment]
Can you give me an example link?

**Comment by AlexFundorin** [comment]
It would be great. Thanks in advance.

**Comment by Tush-r** [comment]
> 
> 
> 1.7.79
> It seems like the app knows about thechive.com (detects the gallery), yet, it can't bulk download all uploads (both jpg and gif) from a specific user, like https://i.thechive.com/Chivette1232 (highly recommend, BTW).
> https://i.imgur.com/CL9Ov5U.png

ThechiveRipper only rips from `thechive.com` and not `i.thechive.com`



> 
> 
> Can you give me an example link?
> 
> I'll look into it when I get the chance

I've looked into it. I'll try and add support for `i.thechive.com` by tomorrow.
