### ISSUE TITLE
RipMe rips retweets by default

### ISSUE THREAD

**Issue by puffinkins** [RipMeApp/ripme#1221]
* Ripme version: 1.7.79
* Java version: 1.8.0_144
* Operating system: 6.3.9600
* Exact URL you were trying to rip when the problem occurred: https://twitter.com/ammymma/media
## Expected Behavior
Retweets should not be downloaded by default.

Detail the expected behavior here.

## Actual Behavior 
Ripping a Twitter user, either their media link or their profile link, or even with the ?include_rts=false flag, rips everything including their retweets.

**Comment by J20X9** [comment]
This problem has been brought up a few times (#708, #784, #1049). Will it be fixed any time soon?

**Comment by cyian-1756** [comment]
>  Will it be fixed any time soon?

I wouldn't count on it. I'm pretty busy at the moment and have never used with the twitter api before. I'll see if I can set it up so the user can decide to ripper retweets or not

**Comment by pornismuybae** [comment]
I was thinking this could be worked around by ripping a search but that appears to be broken. Ripping a search throws this error: "Failed to load https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=search&include_entities=true&exclude_replies=true&trim_user=true&count=200&tweet_mode=extended after 1 attempts"

I was trying this link but any search seems to do the same thing.
https://twitter.com/search?l=&q=from%3Agrimiestt
