### ISSUE TITLE
Suggestion: Add Proxy

### ISSUE THREAD

**Issue by ridwan47** [RipMeApp/ripme#1225]
Please Add Proxy Settings. Reddit is banned on my Country for whatever reason. VPN doesn't seem to affect RipMe (on my PC at least. I tried Psiphon and UltraSurf). So, please add proxy server option.

**Comment by cyian-1756** [comment]
We already have a proxy 

See here for how to configure it https://github.com/RipMeApp/ripme/wiki/Config-options#proxysocks. The location of the config you need to edit is listed at the top of the page

**Comment by ridwan47** [comment]
> We already have a proxy option
> 
> See here for how to configure it https://github.com/RipMeApp/ripme/wiki/Config-options#proxysocks. The location of the config you need to edit is listed at the top of the page

I have no idea how to use it. Please help.

**Comment by cyian-1756** [comment]
To set the proxy 

1) Close ripme if it's running

2) Open your rip.proprieties. It's at

  %LOCALAPPDATA%\ripme on Windows

  $HOME/.config/ripme on *Nix

  $HOME/Library/Application Support/ripme on MacOS 

3) add your proxy info in the format of  [user:password]@host[:port]

**Comment by cyian-1756** [comment]
@ridwan47 Did this solve your issue?

**Comment by ridwan47** [comment]
> @ridwan47 Did this solve your issue?

No. I faily educated of tech and stuff and I found it incredibly difficult to figure it out. Here are the screencaps.
![capture_2019-03-03_18-53-28](https://user-images.githubusercontent.com/12793555/53695480-67843200-3de6-11e9-9c5f-3f72eb117cd4.png)

![capture_2019-03-03_18-56-59](https://user-images.githubusercontent.com/12793555/53695483-71a63080-3de6-11e9-9b2f-dd5de75ca5fe.png)

**Comment by cyian-1756** [comment]
> The proxy I use is public and has no username or password.

Is it a socks proxy or http? 

> Here are the screencaps.

The line should be "proxy.socks = 153.126.179.216:8080" (without quotes) 

If that doesn't work try "proxy.http = 153.126.179.216:8080" (without quotes)
