### ISSUE TITLE
Null error when ripping instagrams

### ISSUE THREAD

**Issue by Xailum** [RipMeApp/ripme#1227]
* Ripme version:v1.7.79
* Java version: 
* Operating system: windows 10

* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/amirahdyme/?hl=en
* Please include any additional information about how to reproduce the problem: Enter link into ripme and hit rip.  

## Expected Behavior
Rip the entirety of the linked instagram
Detail the expected behavior here.
rip the instagram into a folder called rips\instagram_amirahdyme and save all the images

## Actual Behavior
the rippeer rips the first few images then gives me a Null error while saying the download is complete. 
[log.txt](https://github.com/RipMeApp/ripme/files/2904221/log.txt)

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Comment by medamriu** [comment]
same problem .

**Comment by Ectomind1990** [comment]
Think it started happening about 15-20 hours ago. Instagram changed their site I guess

**Comment by bugfinder5000** [comment]
Yeah, it seems to be a change on the site. Hopefully, someone is able to fix it soon.

**Comment by escaroda** [comment]
Looks like the it's pagination issue. RipMe rips first page normally but then something happens and `Error: null` appears.
