### ISSUE TITLE
1.5.0 breaks imgur and reddit

### ISSUE THREAD

**Issue by dingydingo** [RipMeApp/ripme#123]
I don't know if I need to restart the puter but as the title states, 1.5.0 breaks imgur and reddit

**Comment by rautamiekka** [comment]
Fill the template !

**Comment by dingydingo** [comment]
https://imgur.com/u3g3ey5 



* Ripme version: 1.6.0
* Java version: Version 8 Update 151 (build 1.8.0_151-b12)
* Operating system: Windows 10 v.1607
* Exact URL you were trying to rip when the problem occurred: all imgur links eg: http://imgur.com/a/lKJmB

**Comment by dingydingo** [comment]
1.4.2.1 worked fine until I upgrade to 1.5.0

**Comment by cyian-1756** [comment]
This should be fixed in 1.6.1, please update and try again

**Comment by cyian-1756** [comment]
Fixed in 1.6.1
