### ISSUE TITLE
HentaiFoundry age gate issue

### ISSUE THREAD

**Issue by UnforeseenOcean** [RipMeApp/ripme#1232]
* Ripme version:
* Java version: 1.8.0_201
* Operating system: 6.1.7601
* Exact URL you were trying to rip when the problem occurred: `https://www.hentai-foundry.com/pictures/user/Karhumies`
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

The ripper goes past the age gate.

## Actual Behavior

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.
[log.txt](https://github.com/RipMeApp/ripme/files/2920262/log.txt)

Forgot to report this.

**Comment by cyian-1756** [comment]
I can't reproduce this

**Comment by UnforeseenOcean** [comment]
![image 239](https://user-images.githubusercontent.com/11834016/53750681-d0a29d00-3eed-11e9-9b5d-9cd74c015deb.png)
It happened again after the latest update.

**Comment by cyian-1756** [comment]
Looking over the log I see a lot of

> Connection refused

Try using a VPN/proxy

**Comment by UnforeseenOcean** [comment]
The page loads fine on all browsers so it's definitely not a network issue on ISP's end... Should I try it regardless?

**Comment by Tush-r** [comment]
> 
> 
> The page loads fine on all browsers so it's definitely not a network issue on ISP's end... Should I try it regardless?

* Close ripme.
* Open your rip.properties file. 
* Edit these two lines( if not present, add them).
`download.timeout = 6000`
`page.timeout = 5000`
* Save rip.properties. Retry.

**Comment by UnforeseenOcean** [comment]
![image 240](https://user-images.githubusercontent.com/11834016/53789854-d1c4e000-3f68-11e9-9f79-a4865193acb1.png)
Wouldn't higher value be better? I'll edit these and try again.

**Comment by UnforeseenOcean** [comment]
![image 241](https://user-images.githubusercontent.com/11834016/53814608-3dc43a00-3fa3-11e9-8822-af24a3a29ff0.png)

**Comment by Tush-r** [comment]
I'm also unable to reproduce the error.
* Try upping the value for `page.timeout = 15000` 
* If the above doesn't work try ripping with your firewall disabled( do turn it on later).

**Comment by cyian-1756** [comment]
Are you using a proxy/vpn?

**Comment by UnforeseenOcean** [comment]
Not at all.

**Comment by cyian-1756** [comment]
@UnforeseenOcean Any change?

**Comment by UnforeseenOcean** [comment]
Will check later.

**Comment by UnforeseenOcean** [comment]
Oh and Twitter ripper seems to ignore the `history.end_rip_after_already_seen` property in all of sudden, it's been downloading the entire page even if there were 20 or more "already downloaded" alerts.

**Comment by UnforeseenOcean** [comment]
1.7.81 still has the problem, will try 1.7.82 after it finishes downloading.

**Comment by UnforeseenOcean** [comment]
1.7.82 solved the problem. You may close this issue.
