### ISSUE TITLE
Ripper Request: Wikifeet

### ISSUE THREAD

**Issue by mkinsane** [RipMeApp/ripme#124]
Please add support for https://www.wikifeet.com/

Example: https://www.wikifeet.com/Cassidy_Klein

Thank you

**Comment by rautamiekka** [comment]
That'll be easy and simple: pics have direct public addresses in folders. Could be different for a vid.

**Comment by mkinsane** [comment]
Thank you for your response! I'll wait, love the jar!

**Comment by metaprime** [comment]
Linking to request issue: #38
