### ISSUE TITLE
Issue to download all xhamster user galleries

### ISSUE THREAD

**Issue by nacache** [RipMeApp/ripme#1247]
* Ripme version: 1.7.80
* Java version:  1.8_201
* Operating system:  Windows 10
* Exact URL you were trying to rip when the problem occurred: https://fr.xhamster.com/users/pascalmoa/photos/5
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Hi, thanks for the wonderful RipMe. I tried to download pages 2 or else of the galleries of this user, but I have an error message who say: can't rip this URL: no compatible ripper found. Can you help me ? The best solution would be to download all galleries of an user, but I didn't found any tutorial who's working !

Thanks guys !

**Comment by cyian-1756** [comment]
remove the /5 from the url and it should work (https://xhamster.com/users/pascalmoa/photos)
