### ISSUE TITLE
1.6.0: Can't rip Instagram

### ISSUE THREAD

**Issue by gomrcong** [RipMeApp/ripme#125]
![2017-10-26_085318](https://user-images.githubusercontent.com/1468723/32031488-a3c96e96-ba2b-11e7-92e1-57e2316a5c22.jpg)

**Comment by cyian-1756** [comment]
What url were you trying to rip? What OS are you running? What version of java?

**Comment by cyian-1756** [comment]
This should be fixed in 1.6.1, please update and try again

**Comment by cyian-1756** [comment]
This was fixed in 1.6.1
