### ISSUE TITLE
8Muses ripper rips at a rate of (# of image per album) times (#of images in album)

### ISSUE THREAD

**Issue by fizzy191** [RipMeApp/ripme#1254]
* Ripme version: 1.7.81
* Java version: 1.8.0_25-b18
* Operating system: Windows 10 build 1803
* Exact URL you were trying to rip when the problem occurred: https://www.8muses.com/comics/album/JAB-Comics/In-The-Elevator
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Link should only rip once per image.

## Actual Behavior

Tries to rip the same image multiple times. It looks like it tries each image 1x per image in the album. So if there are 5 images in the album, it tries 25 (5x5) times. If there are 300 in the album it will try 90k times.

**Comment by Emmortal451** [comment]
I'm seeing the exact same issue. 

Here's the log for the last album I download - [https://pastebin.com/XirMijL8](url) 
The URL of the album is - [https://www.8muses.com/comics/album/Renderotica-Comics/DB-Spencer/NoelleTurtle-Noelle-and-the-Mudgirl](url)

The album above has a total of 36 images and each image URL is processed/attempted 36 times.
