### ISSUE TITLE
Won't seem to accept any links

### ISSUE THREAD

**Issue by subduedreader** [RipMeApp/ripme#126]
* Ripme version: 1.6.0
* Java version: <(Version 8 Update 151 (build 1.8.0_151-b12)>
* Operating system: <Windows 8.1 64-Bit>

## Expected Behavior

Accept links & download them.

## Actual Behavior

Immediately after updating, I tryed to add a link to rip from at least Imgur, Reddit, or Instagram, it refuses to accept the link, giving "Can't rip this URL: com.rarchives.ripme.ripper.rippers.E621Ripper.<int>(java.net.url)". It also seems to not be able to download from the History menu. I tried to start it after removing the old settings, didn't change.

**Comment by Blood-PawWerewolf** [comment]
same here for me.

**Comment by cyian-1756** [comment]
Can I get an example link?

**Comment by cyian-1756** [comment]
This should be fixed in 1.6.1, please update and try again

**Comment by subduedreader** [comment]
It does appear to be working, thanks!
