### ISSUE TITLE
Ripme, ripping Instagram videos even with instagram.download_images_only = true enabled

### ISSUE THREAD

**Issue by thinkpad4** [RipMeApp/ripme#1284]
* Ripme version: 1.7.82
* Java version: Version 8 update 201
* Operating system: Win7 64bit

* Exact URL you were trying to rip when the problem occurred: http://instagram.com/taylorswift
* Please include any additional information about how to reproduce the problem:
@cyian-1756 I have instagram.download_images_only = true enabled in the config file and it's still getting videos
## Expected Behavior
To not get videos with that set to true
Detail the expected behavior here.

## Actual Behavior
Getting videos with that set to true
Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Comment by thinkpad4** [comment]
Anyone else experiencing this?

**Comment by cyian-1756** [comment]
I can confirm that some videos are downloaded even with instagram.download_images_only set to true
