### ISSUE TITLE
I can't download older photos from profiles

### ISSUE THREAD

**Issue by tomodachichihuahua** [RipMeApp/ripme#1285]
* Ripme version: 1.7.82
* Java version: Java SE 12.0.1
* Operating system: Windows 10 Pro

* Exact URL you were trying to rip when the problem occurred: https://twitter.com/mattyan7010
* Please include any additional information about how to reproduce the problem: I was trying to download older photos from this profile (which are many many) but I couldn't. There's no error display or anything, it just doesn't download older pictures. Can you help me? I apologize for any problem. I'm new to Github and I know nothing about this place. Just wanted to post my issue. Thank you for reading.

## Expected Behavior

Detail the expected behavior here.

## Actual Behavior

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Comment by cyian-1756** [comment]
This is a known issue
