### ISSUE TITLE
pornhub ripper some videos wont download

### ISSUE THREAD

**Issue by tokimcbongrip** [RipMeApp/ripme#1288]
* Ripme version: 1.7.83

* Java version:   Version 8 Update 211 (build 1.8.0_211-b12)

* Operating system:  windows 10 pro 64bit  version 1803   OS build 17134.706

* Exact URL you were trying to rip when the problem occurred:  https://www.pornhub.com/view_video.php?viewkey=ph5936bd7e62b4e

* Please include any additional information about how to reproduce the problem:

## Expected Behavior

downloads video

## Actual Behavior

rip me fails to download and returns this error

Error: java.net.malformedURLException: no protocol:

also seeing this alot in the logs

java.lang.classcastexception: org.json.JSONArray cannot be cast to java.lang.string

problem is not just limited to the above url its a whole bunch that it happens for. and it is also random. some videos download some dont

**Comment by rautamiekka** [comment]
The ticket template has all the necessary commands to find the versions.

**Comment by tokimcbongrip** [comment]
Hi sorry i updated java version and windows version in my post to help thank you
