### ISSUE TITLE
Instagram Video cannot re-download once deleted

### ISSUE THREAD

**Issue by pshongwe** [RipMeApp/ripme#1290]
* Ripme version:1.7.83
* Java version: `openjdk version "1.8.0_191"`
* Operating system: Ubuntu Linux 18.04 Bionic
* Exact URL you were trying to rip when the problem occurred:
```Javascript
[
  {
    "modifiedDate": 1556052926361,
    "count": 0,
    "title": "instagram_Bsjo2ajl7wP",
    "url": "https://www.instagram.com/p/Bsjo2ajl7wP/",
    "startDate": 1556052665022,
    "selected": true
  },
  {
    "modifiedDate": 1556053145182,
    "count": 0,
    "title": "instagram_BsjpA3SF2Iv",
    "url": "https://www.instagram.com/p/BsjpA3SF2Iv/",
    "startDate": 1556052773034,
    "selected": true
  }
]
```
* Please include any additional information about how to reproduce the problem:
pick any video link on instagram
## Expected Behavior
If video file has been deleted in local directory, it should re-download

## Actual Behavior
Does not re-download

**Comment by cyian-1756** [comment]
Do you have "Remember URL History" enabled in the configuration menu? If so disable it and try again

**Comment by pshongwe** [comment]
Thanks a lot. That works. Perhaps, this "tick" should not be default. Here i thought it was an issue :)
