### ISSUE TITLE
500px download

### ISSUE THREAD

**Issue by namivan89** [RipMeApp/ripme#1297]
* Ripme version: v1.7.83
* Java version: Version 8 update 201 (build 1.8.0_201-b09)
* Operating system: Windows 7, Version 6.1 (build 7601: Service Pack 1)

* Exact URL you were trying to rip when the problem occurred: https://500px.com/photo/304447023/body-by-photon-hungary
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Detail the expected behavior here.
RipMe downloads the image.

## Actual Behavior

Got error shows on picture. Expected X, Y, Z... 
![Screenshot_6](https://user-images.githubusercontent.com/46872203/57194824-9ab08200-6f4b-11e9-8e96-17a3be111bb3.jpg)

**Comment by cyian-1756** [comment]
Ripme doesn't support ripping single files from 500px. Try shift + right clicking the same and then save as

**Comment by namivan89** [comment]
> Ripme doesn't support ripping single files from 500px. Try shift + right clicking the same and then save as

![image](https://user-images.githubusercontent.com/46872203/57209529-19073580-6fd9-11e9-924f-f003ff5011ec.png)
And what about user's album?

**Comment by cyian-1756** [comment]
>  And what about user's album?

That is support AFAIk. If it fails make a new issue
