### ISSUE TITLE
Feature request: Instagram "tagged" page support

### ISSUE THREAD

**Issue by pinnie** [RipMeApp/ripme#1301]
When visiting https\://www.instagram.com/_username_/tagged/, Instagram displays images that have that username tagged in them.

I'd like to request support for those pages in RipMe. At the moment, the "tagged" URL doesn't seem to be recognized as an "unable to find user" error is displayed when attempting to start a rip. #

**Comment by domonic46** [comment]
Request for IGTV as well

https://github.com/RipMeApp/ripme/issues/38#issuecomment-453629195

**Comment by Isaaku** [comment]
This can be closed since it's already done. 
https://www.instagram.com/<user>/tagged for user tags
https://www.instagram.com/<user>/channel for IGTV
