### ISSUE TITLE
DeviantArt ripper does not download entire gallery

### ISSUE THREAD

**Issue by UnforeseenOcean** [RipMeApp/ripme#1303]
* Ripme version: 1.7.83
* Java version: 1.8.0_201
* Operating system: 6.1.7601
* Exact URL you were trying to rip when the problem occurred: https://www.deviantart.com/heavenhellexe/gallery/?catpath=/ (Warning: NSFW)
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

The full gallery of the user gets ripped.

## Actual Behavior
![Image 125](https://user-images.githubusercontent.com/11834016/57317539-47992380-7133-11e9-89e9-87a9f69d6441.png)
![Image 126](https://user-images.githubusercontent.com/11834016/57317555-5253b880-7133-11e9-848f-fc5f33ff33ae.png)

**Comment by UnforeseenOcean** [comment]
Oh, also can anyone explain what this error message is saying? It had no problem like this before.
![Image 143](https://user-images.githubusercontent.com/11834016/57371808-baa3a800-71ce-11e9-9bc8-64279107e368.png)

**Comment by cyian-1756** [comment]
> Oh, also can anyone explain what this error message is saying?

A unsupported url was passed to ripme. 

> It had no problem like this before.

The DA ripper was recently rewritten to work around the DA api being terrible and useless

**Comment by UnforeseenOcean** [comment]
So what if I want to rip the primary gallery? What should I do? This thing
is making me confused.

**Comment by UnforeseenOcean** [comment]
![Image 149](https://user-images.githubusercontent.com/11834016/57423834-883a8f00-7250-11e9-9520-0d1d62425ce5.png)

**Comment by cyian-1756** [comment]
I'll look into fixing the ripper so it takes all url formats this weekend

**Comment by chrsmlls333** [comment]
Does this cover PDF downloads at all or just the image frame?

**Comment by biznizz** [comment]
Also having issues, using latest Java and on Windows 10.

I'm almost positive it's because of the awful way they've got their site set up now. Noticed that the pics that were downloaded when I tested were older, before this year.

**Comment by MrPlaygon** [comment]
I will take a look into it as well.

**Comment by MrPlaygon** [comment]
@cyian-1756 can you change the DeviantartRipper in line 622 to 
`Http.url(parts[0]).connection().ignoreContentType(true).execute().statusCode() == 404`

that should fix at least the download for now but that part will need some work.

Once I am more familiar with Github I will create a new pull request with more commentary on my code :smile:

**Comment by MrPlaygon** [comment]
> 
> So what if I want to rip the primary gallery? What should I do? This thing is making me confused. The main gallery doesn't have the numbers (IDs, presumably) so if it's expecting the ID I cannot provide it. Example: https://www.deviantart.com/max-dunbar/gallery/ ![Image 149](https://user-images.githubusercontent.com/11834016/57423834-883a8f00-7250-11e9-9520-0d1d62425ce5.png) As you can see, no IDs or folder to be seen, thus I cannot provide the URL in the format the ripper is expecting.

https://www.deviantart.com/max-dunbar/gallery/ should be working fine. I cannot see a reason why it should not. I agree the error message is clearly misleading. Sorry for that.

and the scoutdoodles URL in your image... I am confused why it errors but will look into it.
