### ISSUE TITLE
Add support for fantasti.cc

### ISSUE THREAD

**Issue by dadrilla** [RipMeApp/ripme#1304]
* Ripme version:
* Java version: 
* Operating system: 

* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Detail the expected behavior here.

## Actual Behavior

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Comment by cyian-1756** [comment]
Put any sites requests in #38
