### ISSUE TITLE
Queue Empty After Restart

### ISSUE THREAD

**Issue by Alfonsorb** [RipMeApp/ripme#1309]
* Ripme version: v 1.7.83
* Java version: 
* Operating system:  win 10

* Exact URL you were trying to rip when the problem occurred: instagram
* Please include any additional information about how to reproduce the problem: laptop died while running ripme.jar. Queue list was empty when the computer woke up.

## Expected Behavior

Queue to have previous items after a restart.

## Actual Behavior

My computer went to sleep while running ripme.jar due to low battery. After I plugged it in and it restarted the queue list was empty. It had 100+ items on que beforehand. 

What happened? Can I retrieve the pages that were queued?

I've been able to exit the program and restart it without the queue list emptying itself. The program was never closed, the computer simply went to sleep for a like a minute.

**Comment by cyian-1756** [comment]
> What happened?

I have no idea. It sounds like windows doing something funny to save power when in sleep mode 

> Can I retrieve the pages that were queued?

I doubt it. AFAIK queued items are only saved in the rip.properties file. If ripme can't find them there they're probably lost 

To prevent this in the future I recommend saving urls you want to rip to a text file and then having ripme process that text file (Click the "Down url list" button in the Configuration menu)

**Comment by Alfonsorb** [comment]
> To prevent this in the future I recommend saving urls you want to rip to a text file and then having ripme process that text file (Click the "Down url list" button in the Configuration menu)

Aw it sucks that I lost all the links! I didn't know the feature you just mentioned but I'll start using it. Thanks for the reply!
