### ISSUE TITLE
Certain command line options show as missing

### ISSUE THREAD

**Issue by RussEfarmer** [RipMeApp/ripme#1327]
* Ripme version: v1.7.84
* Java version: java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)```

* Operating system:  Microsoft Windows [Version 10.0.17134.765]

* Exact URL you were trying to rip when the problem occurred: N/A
* Please include any additional information about how to reproduce the problem:
Run ripme from the command line with select options. Occurs with options -a, -f, -l, -p, -s, -t, -u
## Expected Behavior
Trying to rip urls from the command line using options displayed with java -jar ripme.jar -h should work correctly

## Actual Behavior
Error messages state that these options do not exist. If this is intentional, the options should be omitted from the help output.
```
E:\>java -jar ripme.jar -l
[!] Error while parsing command-line arguments: [-l]
org.apache.commons.cli.MissingArgumentException: Missing argument for option: l
        at org.apache.commons.cli.Parser.processArgs(Parser.java:343)
        at org.apache.commons.cli.Parser.processOption(Parser.java:393)
        at org.apache.commons.cli.Parser.parse(Parser.java:199)
        at org.apache.commons.cli.Parser.parse(Parser.java:119)
        at com.rarchives.ripme.App.getArgs(App.java:317)
        at com.rarchives.ripme.App.main(App.java:54)

**Comment by rautamiekka** [comment]
Are you sure you're using those parameters correctly ?

**Comment by RussEfarmer** [comment]
> 
> 
> Are you sure you're using those parameters correctly ?
Even fully specifying everything it would need to start ripping, it still gives the error
```
E:\>java -jar ripme.jar -f --urls-file "list.txt"
[!] Error while parsing command-line arguments: [-f, --urls-file, list.txt]
org.apache.commons.cli.MissingArgumentException: Missing argument for option: f
        at org.apache.commons.cli.Parser.processArgs(Parser.java:343)
        at org.apache.commons.cli.Parser.processOption(Parser.java:393)
        at org.apache.commons.cli.Parser.parse(Parser.java:199)
        at org.apache.commons.cli.Parser.parse(Parser.java:119)
        at com.rarchives.ripme.App.getArgs(App.java:317)
        at com.rarchives.ripme.App.main(App.java:54)
```

**Comment by rautamiekka** [comment]
> > Are you sure you're using those parameters correctly ?
> 
> Even fully specifying everything it would need to start ripping, it still gives the error
> 
> ```
> E:\>java -jar ripme.jar -f --urls-file "list.txt"
> [!] Error while parsing command-line arguments: [-f, --urls-file, list.txt]
> org.apache.commons.cli.MissingArgumentException: Missing argument for option: f
>         at org.apache.commons.cli.Parser.processArgs(Parser.java:343)
>         at org.apache.commons.cli.Parser.processOption(Parser.java:393)
>         at org.apache.commons.cli.Parser.parse(Parser.java:199)
>         at org.apache.commons.cli.Parser.parse(Parser.java:119)
>         at com.rarchives.ripme.App.getArgs(App.java:317)
>         at com.rarchives.ripme.App.main(App.java:54)
> ```

You're still using them incorrectly. `-f` == `--urls-file`.

I think you just don't understand the help text at all.

**Comment by RussEfarmer** [comment]
> 
> 
> > > Are you sure you're using those parameters correctly ?
> > 
> > 
> > Even fully specifying everything it would need to start ripping, it still gives the error
> > ```
> > E:\>java -jar ripme.jar -f --urls-file "list.txt"
> > [!] Error while parsing command-line arguments: [-f, --urls-file, list.txt]
> > org.apache.commons.cli.MissingArgumentException: Missing argument for option: f
> >         at org.apache.commons.cli.Parser.processArgs(Parser.java:343)
> >         at org.apache.commons.cli.Parser.processOption(Parser.java:393)
> >         at org.apache.commons.cli.Parser.parse(Parser.java:199)
> >         at org.apache.commons.cli.Parser.parse(Parser.java:119)
> >         at com.rarchives.ripme.App.getArgs(App.java:317)
> >         at com.rarchives.ripme.App.main(App.java:54)
> > ```
> 
> You're still using them incorrectly. `-f` == `--urls-file`.
> 
> I think you just don't understand the help text at all.

My brain is apparently very small. Closed.
