### ISSUE TITLE
Ripper will not get all of a Deviantart gallery

### ISSUE THREAD

**Issue by critic56** [RipMeApp/ripme#1340]
* Ripme version:1.7.84
* Java version:  java 8.0
* Operating system: Mint 18.3

* Exact URL you were trying to rip when the problem occurred: all
* Please include any additional information about how to reproduce the problem:  This url  https://www.deviantart.com/mrno74 and almost any other I have come across. It will not get all that is there. This particular site at first ripped 80 files, then unchecking save log, and redoing the rip gave me 150
more. But there are 312 files all total. And this is happening almost across the board. And this has been going on for several iterations of the program.

## Expected Behavior

Detail the expected behavior here.

## Actual Behavior

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Comment by rautamiekka** [comment]
I don't see how you'd be able to use the link https://www.deviantart.com/mrno74 since my RipMe 1.7.84 is complaining of invalid DA syntax.

Anyway, the real count of items in the gallery is 283 although it should be 307 (5 journals), and links like https://www.deviantart.com/mrno74/gallery/ don't give the whole content whereas https://www.deviantart.com/mrno74/gallery/?catpath=/ does.

**Comment by critic56** [comment]
Could it be because I am not using the eclipse interface. Which I really dislike. And my mistake I should have given the entire url. Again sorry.

**Comment by critic56** [comment]
Okay now this is a small screenshot of what I'm getting.
![Screenshot at 2019-06-16 14-55-38](https://user-images.githubusercontent.com/34697679/59569473-37843600-9047-11e9-96f0-ad2fab878ff7.png)

**Comment by critic56** [comment]
Here is another Deviantart gallery doing the same thing https://www.deviantart.com/diabolumberto/gallery/?catpath=/ .121 files out of over 700.
