### ISSUE TITLE
failed to extract qhash  from instagram source

### ISSUE THREAD

**Issue by chaoskie** [RipMeApp/ripme#1343]
* Ripme version: 1.7.84
* Java version: ``` java version "1.8.0_211"
  Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
  Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)```
* Operating system: Microsoft Windows [Version 10.0.17134.829]

* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/skoozams_pisya

* Please include any additional information about how to reproduce the problem:
Posting any of the instagram URLs results in the following output:

>Downloading https://www.instagram.com/skoozams_pisya
Rip complete, saved to D:\Program Files (x86)\RipMe\rips\instagram_skoozams_pisya
Unable to extract qhash from page

## Expected Behavior
Downloading contents from URL without a problem and writing them to disk.

## Actual Behavior

Receive an error that states the qhash can't be extracted from the page. (see image)

![image](https://user-images.githubusercontent.com/10385538/59638103-c5e7dd00-9157-11e9-847a-1d31a688bbdb.png)

**Comment by thinkpad4** [comment]
Yep, getting that too

**Comment by UnforeseenOcean** [comment]
Confirmed
![Image 613](https://user-images.githubusercontent.com/11834016/59680747-0e150700-920d-11e9-8b42-3e1519cb4323.png)

**Comment by Rihannakitten** [comment]
https://github.com/RipMeApp/ripme/commit/4a54a085fb2df03819a60e1e982f88930443855b

**Comment by j-debug491** [comment]
Also having this issue

**Comment by alionar** [comment]
> [4a54a08](https://github.com/RipMeApp/ripme/commit/4a54a085fb2df03819a60e1e982f88930443855b)

i just compile the source from this commit and problem solved

**Comment by thinkpad4** [comment]
@alionar are you gonna make a pull request?  I hope @cyian-1756 can release a new version soon, I really need this working again
