### ISSUE TITLE
Instagram: Ripper reporting qhash problem

### ISSUE THREAD

**Issue by Ssurgul** [RipMeApp/ripme#1349]
* Ripme version: 1.7.84 (and in 1.7.83)
* Java version: 
openjdk version "12" 2019-03-19
OpenJDK Runtime Environment (build 12+33)
OpenJDK 64-Bit Server VM (build 12+33, mixed mode, sharing)
--OR--
openjdk 11 2018-09-25
OpenJDK Runtime Environment AdoptOpenJDK (build 11+28)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11+28, mixed mode)

* Operating system: Microsoft Windows [Version 10.0.17763.557]

* Exact URL you were trying to rip when the problem occurred:
Downloading https://www.instagram.com/robot_concept
Downloading https://www.instagram.com/chris_elkins
Downloading https://www.instagram.com/kacosplaytech
Downloading https://www.instagram.com/the_melodic_wallcrawler/

* Please include any additional information about how to reproduce the problem:
Put in any Instagram account for ripping
Hit the Rip button
System will retrieve the data
System errors for any Instagram with the following error: Unable to extract qhash from page

## Expected Behavior

Prior to last week, RipMe was ripping any and all Instagram accounts normally. Either brand new, or selected 're-rip' requests for existing were working just fine. Normally IG accounts would download and close with regularity.

## Actual Behavior

The system is unable to determine anything to do because of the reported 'Unable to extract qhash from page' error.

**Comment by cyian-1756** [comment]
This was fixed in 1.7.85

**Comment by Ectomind1990** [comment]
Confirmed, this error went away in 1.7.85
Possible the fix was partial as it seems there is a new bug in 1.7.85, #1347 but there's no proof they are related
