### ISSUE TITLE
auto update stopped working [edit: update_ripme.bat doesnt have quotes around path = no support for spaces]

### ISSUE THREAD

**Issue by ANaPhOrAX** [RipMeApp/ripme#1351]
* **Ripme version**: 1.7.84
* **Java version**: Version 8 Update 181 (build 1.8.0_181-b13)
* **Operating system**: Windows 10 version 1903 
* **Exact URL you were trying to rip when the problem occurred**: -
* **Please include any additional information about how to reproduce the problem**: run 1.7.84 and try to update when prompted. Click yes, and see what happens. For me, nothing happens.

## Expected Behavior

App is supposed to close, update and re-open after the update

## Actual Behavior

It closes the app, downloads the update, but the app doesn't re-open, and the update just sits in the folder as "ripme.jar.update"

**Comment by logotie** [comment]
Hmmmm, are you still encountering this issue I just tried and it seemed to work for me?

**Comment by mynameisnotryan** [comment]
Have the same exact issue as well. Tried deleting the update files and retrying but it just refuses to update.

**Comment by ANaPhOrAX** [comment]
> Hmmmm, are you still encountering this issue I just tried and it seemed to work for me?

Yep, still encountering it as of right now.

**Comment by cyian-1756** [comment]
@ANaPhOrAX @mynameisnotryan 

Can you post the log/run ripme from the commandline, try to update and post the output? 

@logotie 

> Hmmmm, are you still encountering this issue I just tried and it seemed to work for me?

What OS are you using?

**Comment by ANaPhOrAX** [comment]
> @ANaPhOrAX @mynameisnotryan
> 
> Can you post the log/run ripme from the commandline, try to update and post the output?
> 
> @logotie
> 
> > Hmmmm, are you still encountering this issue I just tried and it seemed to work for me?
> 
> What OS are you using?

im sorry, how would I go about doing that? you're gonna have to explain that to me 😅

**Comment by cyian-1756** [comment]
> im sorry, how would I go about doing that?

Open the folder you have ripme in

Right + right click the background and you should see a menu 

Click "Open command window here" on that menu

type java -jar ripme.jar

press enter

Then just try to update as you normally would, when everything is done post the text in the command window

**Comment by ANaPhOrAX** [comment]
> > im sorry, how would I go about doing that?
> 
> Open the folder you have ripme in
> 
> Right + right click the background and you should see a menu
> 
> Click "Open command window here" on that menu
> 
> type java -jar ripme.jar
> 
> press enter
> 
> Then just try to update as you normally would, when everything is done post the text in the command window

open command window here isn't a default windows feature btw. but i opened cmd and navigated there. I got this:

C:\Program Files X\ripme>java -jar ripme.jar
Loaded C:\Users\Username\AppData\Local\ripme\rip.properties
Loaded log4j.properties
Initialized ripme v1.7.84
Setting locale to en_US
Loading history from C:\Users\Username\AppData\Local\ripme\history.json
Retrieving https://raw.githubusercontent.com/ripmeapp/ripme/master/ripme.json
oldVersion 1.7.84 < latestVersion1.7.85
Found newer version: 1.7.85
New version found, downloading...
Download of new version complete; saved to ripme.jar.update
Checking hash of update
Hash is good
Saved update script to update_ripme.bat
Exiting older version, should execute update script (update_ripme.bat) during exit
Executing: update_ripme.bat
Saved configuration to C:\Users\Martijn\AppData\Local\ripme\rip.properties


So it's showing that it's doing it correctly I guess.. except it's not.

**Comment by ANaPhOrAX** [comment]
Just now I tried deleting everything from the AppData\Local\ripme folder, and running the update again. No change.

**Comment by TehNolz** [comment]
I'm guessing your `ripme.jar` has a space in its file path? As far as I can tell, the code that generates `update_ripme.bat` doesn't take spaces into account, so it creates a broken update script.

**Comment by ANaPhOrAX** [comment]
> I'm guessing your `ripme.jar` has a space in its file path? As far as I can tell, the code that generates `update_ripme.bat` doesn't take spaces into account, so it creates a broken update script.

Yep, it does. But it used to work fine. This is the first time I've had trouble tbh.

**Comment by ANaPhOrAX** [comment]
Checked 1.7.83 against 1.7.84


**1.7.83 .bat file:**

```
@echo off
timeout 1
copy ripme.jar.update ripme.jar
del ripme.jar.update
ripme.jar
del C:\Program Files X\ripme\update_ripme.bat
```


**1.7.84 .bat file:**

```
@echo off
timeout 1
copy ripme.jar.update C:\Program Files X\ripme\ripme.jar
del ripme.jar.update
C:\Program Files X\ripme\ripme.jar
del C:\Program Files X\ripme\update_ripme.bat
```

Can it please be changed to where paths have quotes around them?

**Comment by cyian-1756** [comment]
> Can it please be changed to where paths have quotes around them?

That should be possible

**Comment by ANaPhOrAX** [comment]
> > Can it please be changed to where paths have quotes around them?
> 
> That should be possible

I noticed the newest update still doesn't have the quotes. Same error as before, it doesn't update correctly. Just figured you might've forgotten ^^

**Comment by cyian-1756** [comment]
> Just figured you might've forgotten

Totally slipped my mind. I'll make sure to fix it for the next update

**Comment by rtsketo** [comment]
If this is still an issue, may I fix it?
Should be fairly easy I think.

**Comment by ANaPhOrAX** [comment]
it's an issue again. no quotes, like before.
