### ISSUE TITLE
[bug] mistakenly "downloaded" an imageset to a drive that wasn't plugged in. now i can't redownload it?

### ISSUE THREAD

**Issue by tehgarra** [RipMeApp/ripme#1353]
* Ripme version:
* Java version: 1.7.85
* Operating system:  Win 7 SP1

## Expected Behavior

Redownload of specific gallery files to correct directory

## Actual Behavior
"Already downloaded" notification for all files for same gallery

The gallery itself isn't a problem considering there's no restrictions. Even though the files were "already downloaded", I don't find them anywhere during a search, which makes since because the drive wasn't plugged in. 

After changing to the correct directory attempting to redownload, that's when I got the already downloaded notification. Overwriting existing files doesn't help either.
Here's the [url ](https://xhamster.com/photos/gallery/my-sfw-gallery-10873531)although I already asked someone to try and download it, and they didn't have any problems.

The one thing I do have is
`2019-06-24 06:22:24,708 ERROR ripper.AbstractRipper .downloadFile() The url "" is malformed`
but I've been seeing that since may for xhamster galleries and the images seemed to download fine despite that, so i'm not sure if it's relative.

**Comment by cyian-1756** [comment]
Go to the configuration menu and uncheck remember url history

**Comment by tehgarra** [comment]
Thanks!
