### ISSUE TITLE
Fails to rip content after update to 1.7.85

### ISSUE THREAD

**Issue by nephilimreborn** [RipMeApp/ripme#1355]
* Ripme version: 1.7.85
* Java version: Java 8 211
* Operating system: MacOS 10.14.5

* Exact URL you were trying to rip when the problem occurred: https://old.reddit.com/user/Cheers1848/submitted/

* Please include any additional information about how to reproduce the problem:
General use of the app as usual. Copy URL, Detected Reddit Album and then select Rip. 

## Expected Behavior

Content from provided URL is ripped then placed in proper folder in set location in app configuration.

## Actual Behavior

After selecting Rip or having it pulled from clipboard as expected, Log page goes blank no error or status of request. Confirmed that actual rip did not occur as it doesn't show in Logs section and folder where content is supposed to be placed does not exist. Same issue occurs with other supported URLs like Instagram

[ripme.log](https://github.com/RipMeApp/ripme/files/3326756/ripme.log)

**Comment by cyian-1756** [comment]
Looking over the log it seems that ripme fails to match the url to a ripper when ripAlbum() is called, but matches it fine before that.

Is this happening with all urls or just reddit? Does it work if you use 1.7.84?

**Comment by nephilimreborn** [comment]
> Looking over the log it seems that ripme fails to match the url to a ripper when ripAlbum() is called, but matches it fine before that.
> 
> Is this happening with all urls or just reddit? Does it work if you use 1.7.84?

Happens to all URL's I tested Instagram and Facebook as well, but I use RipMe mostly for Reddit
I tired rolling it back to 1.7.84 and had the same issue.
Everything was fine before this most recent update. No issues at all.

**Comment by cyian-1756** [comment]
> I tired rolling it back to 1.7.84 and had the same issue. Even though I hadnt had an issue with that version previously.

Did you recently update/downgrade your java version?

**Comment by nephilimreborn** [comment]
> > I tired rolling it back to 1.7.84 and had the same issue. Even though I hadnt had an issue with that version previously.
> 
> Did you recently update/downgrade your java version?

Not prior to having issues with this version. After removing and reinstalling the app and it still not working with any links I tried, I did update to the Java version I'm on now to see if I could resolve the issue, without success of course.

**Comment by nephilimreborn** [comment]
Follow up on this issue. I appear to have resolved it. I went ahead and fixed my permissions and removed all traces of Java from my system. Restarted then downloaded the newest release again. All is working as it should I hope this info maybe helps someone else although I am not sure at what point what process fixed the issue as I had tried restarting and reinstalling earlier. Thanks!
