### ISSUE TITLE
Feature Request: Return URLs in a text instead of downloading

### ISSUE THREAD

**Issue by SingitBatch40** [RipMeApp/ripme#1368]
First time on Github so forgive me for my noobiness.

Currently, you put a URL onto RipMe and it downloads the files. I was wondering if its possible to just output the raw, direct, URLs. For example, when I paste in an imgur album, it returns the direct imgur links to a text file or just outputs it onto the screen without the debug/status information also appearing

Thanks

**Comment by nikewall** [comment]
Hey @SingitBatch40 !
There is already a feature in RipMe which functions exactly as you have described.

**To reproduce:**
- Select the "Configuration" tab
- Click into the "Log level: ___" drop-down menu (below "Check for updates")
- Select "Log level: Error"
- Click out of the drop-down menu and click the "Save URLs only" option
- Enter your desired URL in the URL text-box
- Press "Rip"

This will output **ONLY** the URLs of the individual images into a .txt file, which will pop open immediately after the rip is completed, with no debug/status information (as long as it succeeds)!

Hope this helps

**Comment by cyian-1756** [comment]
Closing as the question was answered
