### ISSUE TITLE
Can't find install file.

### ISSUE THREAD

**Issue by CommissarMouse** [RipMeApp/ripme#1371]
* Ripme version:
* Java version: 
* Operating system: 

* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

a .jar file in the download directory

## Actual Behavior

There is no .jar file in the download directory.

**Comment by rautamiekka** [comment]
You need to be more verbose than this.

**Comment by CommissarMouse** [comment]
In what way?  I downloaded what was presented.  The website here says to run ripme.jar.  There is no ripme.jar file in the folder I downloaded.  I checked the folders.  I did not see it.

**Comment by CommissarMouse** [comment]
You know what, never mind.  I'm going to go with something else.  This site is clearly for people that code, and I do not.

**Comment by Isaaku** [comment]
I think you downloaded the sourcecode instead of the program. Is you want to give it a try this is the direct link to the last release (1.7.85) https://github.com/RipMeApp/ripme/releases/download/1.7.85/ripme.jar
