### ISSUE TITLE
Ripme can't download the best video dimension

### ISSUE THREAD

**Issue by liyiecho** [RipMeApp/ripme#1372]
* Ripme version: 1.7.85
* Java version:
 java version "12.0.1" 2019-04-16
Java(TM) SE Runtime Environment (build 12.0.1+12)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)
* Operating system:  Mac OS 10.14.5 
* Exact URL you were trying to rip when the problem occurred: 
https://twitter.com/JimMFelton
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Download the best video dimension. For example,  [this video](https://twitter.com/JimMFelton/status/1146745014753603584) best video dimension is 720x720, but Ripme can only download 480x480.

**Comment by liyiecho** [comment]
change the code
https://github.com/RipMeApp/ripme/blob/5cc990f316ecb2ec35a61319dd9010ca7c6da69a/src/main/java/com/rarchives/ripme/ripper/rippers/TwitterRipper.java#L202-L203
to
```
for (int j = 0; j < variants.length(); j++) {
    JSONObject variant = (JSONObject) variants.get(j);
```
now it can download the best video dimension(the biggest video).

**Comment by nvlquack** [comment]
Can you make next update version that don't have this bug?
