### ISSUE TITLE
Xhamster won't rip

### ISSUE THREAD

**Issue by urfnhh** [RipMeApp/ripme#1374]
* Ripme version:  1.7.85
* Java version:  Version 8
* Operating system:  Windows 10 64-bit version 1903

* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Rip xhamster albums

## Actual Behavior

It just says failed to load and won't rip anything. I tried both friend's only albums and public albums but results are the same.

**Comment by rephormat** [comment]
@urfnhh We can not troubleshoot the issue without URL to test.  Please update your issue with the URL you were attempting to rip.

**Comment by cyian-1756** [comment]
Closing as we can't test with the url
