### ISSUE TITLE
Optional throttling feature

### ISSUE THREAD

**Issue by Kn0p3XX** [RipMeApp/ripme#1386]
* Ripme version: 1.7.86
* Java version: 1.8.0_211
* Operating system: Windows 10 (1809) 64 bit
* Exact URL you were trying to rip when the problem occurred: None
* Please include any additional information about how to reproduce the problem: None

## Expected Behavior

RipMe should rip it slower, preventing getting banned for sudden server traffic for ripping images/videos.

## Actual Behavior

The RipMe Java App rips images/videos quite fast, for some services, it could be too fast and could end up on a IP ban or User Agent ban, if RipMe has one; or something other ban method.

**Comment by rautamiekka** [comment]
Each ripper is hardcoded with throttling of some sort already, according to what you can do at the fastest before the site does something.

**Comment by Kn0p3XX** [comment]
Oh, i didn't knew that.. huh.

**Comment by rautamiekka** [comment]
Of course, if you find a site ain't working with RipMe as intended, open a ticket.

**Comment by Kn0p3XX** [comment]
Okay, thank you nonetheless!
