### ISSUE TITLE
AllPornComic.com New Site Support Request

### ISSUE THREAD

**Issue by ketan232304** [RipMeApp/ripme#1391]
Album Link: https://allporncomic.com/porncomic/velamma-velamma/93-velamma

Image Link: https://i2.wp.com/allporncomic.com/wp-content/uploads/WP-manga/data/manga_5c28c8de27756/43af435bb7b1cb4e393178382ef77027/Page1_1.jpg?ssl=1

**Comment by cyian-1756** [comment]
Support has been added and an update should be out within the next few days.

In the future please make all site support requests in #38
