### ISSUE TITLE
Twitter videos low quality download

### ISSUE THREAD

**Issue by nvlquack** [RipMeApp/ripme#1394]
## Expected Behavior

Expect Twitter videos to be downloaded in highest quality.

## Actual Behavior

Twitter videos are downloaded not in highest but in low quality :(

**Comment by nvlquack** [comment]
Please update the app to download the highest quality twitter videos by default 🥺

**Comment by Isaaku** [comment]
Same as #1372

**Comment by Isaaku** [comment]
@cyian-1756 this is already resolved. Please close this
