### ISSUE TITLE
gfycat-ripper does not rip URL starting with thumbs.gfycat.com

### ISSUE THREAD

**Issue by donney78** [RipMeApp/ripme#1395]
* Ripme version: 1.7.86
* Java version: 1.8.0_221
* Operating system: Win 10 (10.0.18362.267

* Exact URL you were trying to rip when the problem occurred:
As posted on reddit:
https://thumbs.gfycat.com/SilverMixedIberianchiffchaff-size_restricted.gif

## Expected Behavior

Expected behavior would be for ripme to download the gif/mp4.

## Actual Behavior

It does not download the gif/mp4. There is no mention in the log, not even that it has been skipped.
This is the only sign that something went wrong:
![ripme_gfycat_thumbs_error](https://user-images.githubusercontent.com/53912060/62722380-95614880-ba0e-11e9-8d75-88b8e29f2054.jpg)

**Comment by rtsketo** [comment]
I'd like to contribute to the project. May I be assigned to this issue?

**Comment by cyian-1756** [comment]
@rtsketo sure

**Comment by Tejashuske** [comment]
I'd like to contribute to the project. May I be assigned to this issue?
