### ISSUE TITLE
xhamster now redirects to xhamster2 which is not supported by ripme

### ISSUE THREAD

**Issue by skylar01** [RipMeApp/ripme#1401]
* Ripme version: v1.7.86
* Java version: 
* Operating system:  win10 ver 1903

* Exact URL you were trying to rip when the problem occurred: https://xhamster2.com
* Please include any additional information about how to reproduce the problem:
in some way, www.xhamster.com now redirects to www.xhamster2.com which is not supported by ripme

## Expected Behavior

Detail the expected behavior here.

## Actual Behavior

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Comment by skylar01** [comment]
I've read thru the xhamsterripper.java it seems that it converts all links to m.xhamster.com and i'm sort of trying out things to get into the mobile version of xhamster but to no avail, at least on my end idk if others are able to open the link.

**Comment by ruinedJelly** [comment]
In India, https://xhamster.com redirects to https://xhamster.desi (http version is blocked).

**Comment by skylar01** [comment]
> In India, https://xhamster.com redirects to https://xhamster.desi (http version is blocked).

Just a thought, I think no one would prefer http over https right now. If you're refering to the domain (xhamster.com) maybe they had configure something on their end(xhamster).

Just a heads up, I tried using a EU ip now I can access https://xhamster.com though I can't rip anything it seems that https://m.xhamster.com is still down

**Comment by cyian-1756** [comment]
Is this still happening? I can access all the domains listed in this thread and aren't getting any redirects

**Comment by ruinedJelly** [comment]
> Is this still happening? I can access all the domains listed in this thread and aren't getting any redirects

This seems to be region specific, If you have a vpn, please try an Indian server, or a server from skylar01's region. Also, if the  https://m.xhamster.com links are not found/empty, can you add fallback links for https://xhamster2.com and https://xhamster.desi?

**Comment by cyian-1756** [comment]
@ruinedJelly

> Also, if the https://m.xhamster.com links are not found/empty, can you add fallback links for https://xhamster2.com and https://xhamster.desi?

Nope. The ripper only supports the mobile site (because the normal site makes heavy use of javascript). I can however change the ripper to use the mobile version of whatever domain was entered (https://xhamster.desi -> https://m.xhamster.desi)

**Comment by ruinedJelly** [comment]
> Nope. The ripper only supports the mobile site (because the normal site makes heavy use of javascript). I can however change the ripper to use the mobile version of whatever domain was entered (https://xhamster.desi -> https://m.xhamster.desi)

Yes, that should work. Thank you.

**Comment by skylar01** [comment]
> @ruinedJelly
> 
> > Also, if the https://m.xhamster.com links are not found/empty, can you add fallback links for https://xhamster2.com and https://xhamster.desi?
> 
> Nope. The ripper only supports the mobile site (because the normal site makes heavy use of javascript). I can however change the ripper to use the mobile version of whatever domain was entered (https://xhamster.desi -> https://m.xhamster.desi)

That's explains the conversion of the ripper from web to mobile site. @cyian-1756 That should probably work. Thank you
