### ISSUE TITLE
Request: CONFIRM DIALOG FOR QUEUE CLEAR AND QUEUE AUTOSAVE.

### ISSUE THREAD

**Issue by UnforeseenOcean** [RipMeApp/ripme#1402]
* Ripme version: 1.7.86

Could we please implement a simple "Are you sure" dialog for clearing the queue? I accidentally cleared my queue because the "remove selected" and "remove all" option is very close together. This is beyond irritating.

Also, could we implement queue autosave not when the program is closed but after each URL? I hate waiting for an URL to finish ripping so the queue is updated when I close it, not to mention the annoyances that occur when you make a mistake of moving the cursor ever so slightly down and click on Remove All menu, which clears the queue in the memory and blanks out the data.

(Note: The queue is only updated when you hit Stop and close the program. Useless when your queue is vaporized because your mouse jittered while trying to remove links that don't make sense.)

**Comment by rautamiekka** [comment]
I'm absolutely all for this feature.

**Comment by cyian-1756** [comment]
Should be easy enough.

**Comment by Isaaku** [comment]
@cyian-1756 are you working on this?

**Comment by cyian-1756** [comment]
@Isaaku Not at the moment.

**Comment by Isaaku** [comment]
Ok, probably will do this tonight after gym
