### ISSUE TITLE
Pixiv support?

### ISSUE THREAD

**Issue by SavageCourier** [RipMeApp/ripme#1415]
Sorry to bother everyone, but I was wondering if we could get support to use this on Pixiv.

**Comment by Owyn** [comment]
nandaka maintains a pixivutil2 downloader already

**Comment by SavageCourier** [comment]
His Pixiv Downloader doesn't work for me, I try to log in and I can't get it to run.

**Comment by Owyn** [comment]
You need to copy the cookie from the browser, it works for me

**Comment by SavageCourier** [comment]
Okay I'll try that, thank you for the information

**Comment by Isaaku** [comment]
Please request in #38. @cyian-1756 Please close this
