### ISSUE TITLE
We should detach this fork

### ISSUE THREAD

**Issue by cyian-1756** [RipMeApp/ripme#142]
Because of how github treats forks (They don't come up in searches) we should consider detaching this fork so it gets turned into it's own separate project (and will start showing up in searches)

AFAIK to do this @metaprime would have to contact github support

**Comment by cyian-1756** [comment]
The fork was detached

**Comment by metaprime** [comment]
Yes, we have detached from 4pr0n/ripme and all of the folks who forked ripmeapp/ripme directly are still attached to this network.
