### ISSUE TITLE
Does history.end_rip_after_already_seen = X work for Twitter?

### ISSUE THREAD

**Issue by ExodusHour** [RipMeApp/ripme#1420]
* Ripme version: 1.7.87
* Java version:  1.8.0_221
* Operating system:  Windows 10

## Expected Behavior
To stop after 'X' already seen

## Actual Behavior
Will Go through the whole twitter page again.

It works with Instagram pages but everytime I try to re-rip a Twitter page it will go through the whole page.

**Comment by tarantinosaur** [comment]
Where do you set this setting?
