### ISSUE TITLE
nhentai Support?

### ISSUE THREAD

**Issue by SavageCourier** [RipMeApp/ripme#1426]
Suggestion nhentai.net
Since I think some would be unable to open the download files that it gives, as I tried it with multiple extractors.
Sorry, if I'm bothering anyone.

**Comment by Darcahn** [comment]
nhentai doesn't give a torrent file to download the galleries?

**Comment by SavageCourier** [comment]
When I use the download button, it always downloads as a torrent file for me.

**Comment by SavageCourier** [comment]
I found out that nhentai is already supported by ripme, sorry for being a bother.
