### ISSUE TITLE
luscious current url

### ISSUE THREAD

**Issue by bobymcbobx** [RipMeApp/ripme#1447]
* Ripme version:
* Java version: 
* Operating system: 

* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

expects luscious.net/album/albumname or members.luscious.net/album/albumname

## Actual Behavior

new url is old.luscious.net/album/albumname

**Comment by mxlschnxl** [comment]
Got the same issue since October, can't download a single gallery because of this. Also tried fixing it myself by applying some changes to the luscious ripper, didn't work either.

**Comment by cyian-1756** [comment]
Sorry it took so long to get on this
