### ISSUE TITLE
New ripper request: Erocurves.com

### ISSUE THREAD

**Issue by William-jafta** [RipMeApp/ripme#1448]
* Ripme version:
* Java version: 
* Operating system: 

* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Detail the expected behavior here.

## Actual Behavior

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Comment by Isaaku** [comment]
Please request in #38. @cyian-1756 Please close this
