### ISSUE TITLE
Java Exception has occured

### ISSUE THREAD

**Issue by domonic46** [RipMeApp/ripme#145]
* Ripme version: 1.6.5
* Java version: 
* Operating system:  Windows 7
* Exact URL you were trying to rip when the problem occurred: 
* Please include any additional information about how to reproduce the problem:

I can't open the app, it says "A Java Exception has occured" when I click on ripme.jar. The last working version for me is 1.5.15. Any ideas on how to fix this?

**Comment by cyian-1756** [comment]
Sounds like you're running an outdated version of java. Update to java 1.8 or higher

**Comment by domonic46** [comment]
That worked, thank you
