### ISSUE TITLE
Pornhub rips suddenly stopped working yesterday

### ISSUE THREAD

**Issue by tokimcbongrip** [RipMeApp/ripme#1457]
* Ripme version: v1.7.88
* Java version:  v1.8.0_221
* Operating system:  version 1803 (OS Build 17134.1069
* Exact URL you were trying to rip when the problem occurred: https://www.pornhub.com/view_video.php?viewkey=ph57508e334a973
* Please include any additional information about how to reproduce the problem: 

## Expected Behavior

rip videos from pornhub

## Actual Behavior

was ripping files fine, then around 5 pm eastern time yesterday pornhub files stopped ripping and started showing this error for all pornhub links

Failed to download https://www.pornhub.com/view_video.php?viewkey=ph5708e334a973 : could not find 'flashvars'

failed to download  could not find 'flashvars' comes up for all pornhub links i try to rip 

please help  and thank you for all hard work on ripme i have been using it for years now

**Comment by PlebsMacgee** [comment]
Same here, devs work too hard. Made a little post to the issues board. The ripper recognises the album but gives out javaURLException. I suspect it is Pornhub or Java issue the code looks good but I don't know.
I have Ripme version: v1.7.88 which means it has the Meteri fixes in place.
Java version: v1.8.0_231
Windows Update :1903

**Comment by wpw** [comment]
They've switched to a new way of storing/retrieving the direct URL to the videos. It's not out in the open anymore as a property of the `flashVars.mediaDefinitions` object. It's not exactly hidden, either, just scrambled. It's pretty easy to work around if you're using JS since you can concat all the substring variables back together natively, not sure what's required for that in the Java world.

**Comment by IgnusLupin** [comment]
The fix should be to setup or adjust the JAVA code to do the following or some variant of it:

1. On the https://www.pornhub.com/view_video.php?viewkey=phBLAHBLAHBLAHa page.
2. On line 2298 (or close there too... starts with spaces, then ra###...) 
3. Split that line at the first "var quality" string
4. Starting at first "rahttpsra##rahttpsra##" in the right 
   half of the string and store all the raxxxxxraxraxxxxxrax entries in an
   array all the way to the next "flashvars"   i.e. regexp ( + */ )(.*)( + /* ) 
5. Use that array of raxxxxxraxraxxxxxrax data to rebuild from var entries to the left 
    of the "var quality" string.
6. Grab everything between (=) and (var) and remove " + " and extra "s
   i.e. regexp (=)(.*)(" + ")(.*)(") 
7. Skip to every other array value (i.e. with rahttpsra as the first entry, 
   use the 3rd, then the 5th, etc.) to the end of the array.
8. Write each (every other) string read from the array into a string URL variable
9. Use assembled URL string to to grab the mp4 file and rename the mp4 using the html "Title"
   for the https://www.pornhub.com/view_video.php?viewkey=phBLAHBLAHBLAHa page.

Manually did this for a few vids and I was able to directly access/download the mp4 video file.
