### ISSUE TITLE
Instagram profile/media returns 404

### ISSUE THREAD

**Issue by chemistx** [RipMeApp/ripme#146]
* Ripme version: v1.6.5
* Java version: 1.8.0_151 
* Operating system:  Windows 10
* Exact URL you were trying to rip when the problem occurred: Any instagram link
* Please include any additional information about how to reproduce the problem:

putting an instagram link: https://www.instagram.com/lordvader25/  and i get the error " failed to load https://www.instagram.com/lordvader25/media after 3 attempts."

it automatically keep putting "media" after every instagram link, i have test. 
![test](https://user-images.githubusercontent.com/33470380/32525633-fcc9f740-c3ea-11e7-95dd-946a51489463.png)

**Comment by cyian-1756** [comment]
After some looking it seems like they removed their PROFILE/media end point and now they just have the media info in the pages javascript.

**Comment by cyian-1756** [comment]
This should be fixed in 1.6.7
