### ISSUE TITLE
Ripme- How do I install it or run it? Please help

### ISSUE THREAD

**Issue by GrimReaper78** [RipMeApp/ripme#1462]
* Ripme version:
* Java version: 
* Operating system: 

* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Detail the expected behavior here.

## Actual Behavior

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Comment by cyian-1756** [comment]
You can download ripme on the [releases](https://github.com/RipMeApp/ripme/releases) page

To run ripme download ripme.jar and double click it
