### ISSUE TITLE
Proxy settings Working?

### ISSUE THREAD

**Issue by CodeArtificial** [RipMeApp/ripme#1465]
* Ripme version:  v1.7.88
* Java version: Version 8 Update 91
* Operating system: Window 10

* Exact URL you were trying to rip when the problem occurred: 
https://blueborg16.newgrounds.com/art

## Expected Behavior
I use the proxy settings from Psiphon 3 to rip images from blocked website

![image](https://user-images.githubusercontent.com/56638985/67464837-3d7dc980-f66e-11e9-9833-6dd21e369f21.png)

## Actual Behavior
But it attempted many times and failed.
![image](https://user-images.githubusercontent.com/56638985/67464982-859cec00-f66e-11e9-9a6d-f1aa84411945.png)

**Comment by cyian-1756** [comment]
Does the proxy your using require a username or password?

**Comment by CodeArtificial** [comment]
No. Psiphon allows me to connect to a proxy without the use of any username or password.

I used the ports and IP generated by the application.

![image](https://user-images.githubusercontent.com/56638985/67547558-9b231c00-f729-11e9-9527-2b40ee16c0f9.png)

**Comment by cyian-1756** [comment]
Can you post your log file? 

Could you confirm that you can reach the website in a browser?

**Comment by CodeArtificial** [comment]
Yes, I was able to reach the website in a browser multiple times.

Are you talking about the ripme.log file?

**Comment by cyian-1756** [comment]
> Are you talking about the ripme.log file?

Yes

**Comment by CodeArtificial** [comment]
[Uploading ripme.log…]()

**Comment by CodeArtificial** [comment]
Here is the log: [ripme.log](https://github.com/RipMeApp/ripme/files/3801302/ripme.log)

**Comment by CodeArtificial** [comment]
I am not sure how, but in the version of 1.7.89, the program works again. Ripping fine. 
I guess the problem solved, closed?
![image](https://user-images.githubusercontent.com/56638985/68082043-331bb680-fe4a-11e9-9621-bf8cbcdbef10.png)

**Comment by cyian-1756** [comment]
I assume this was an issue of the site serving slightly different content based on IP
