### ISSUE TITLE
Applications hangs when attempting to download certain url

### ISSUE THREAD

**Issue by pornismuybae** [RipMeApp/ripme#1486]
* Ripme version: 1.7.89
* Java version: 11.0.5-ea
* Operating system: Ubuntu 19.10 x86_64 
* Exact URL you were trying to rip when the problem occurred (**nsfw**): https://www.reddit.com/user/jettetje/

## Expected Behavior
The page to be ripped.

## Actual Behavior
Application always hangs after downloading https://i.redd.it/x92hm58hzqw31.png. The rip can be stopped but any rip started after will be stuck on "Starting rip...". The app then can't be closed or ended/killed through htop etc. ripme.log is empty, I'm guessing because of the hang.

This seems similar to #845 but a fix for that was pushed.

**Comment by madhatr** [comment]
Go to issue #1477 and download the testbuild, change the .zip to .jar.    I used the test build on [https://www.reddit.com/user/jettetje/](https://www.reddit.com/user/jettetje/) and it worked fine.

**Comment by pornismuybae** [comment]
Yep! That build's fixed it. Time to get RipMeApp/ripme#1487 merged!
