### ISSUE TITLE
Cannot rip Instagram stories (query_hash is null)

### ISSUE THREAD

**Issue by AdaKCheung** [RipMeApp/ripme#1495]
* Ripme version: 1.7.89
* Java version: 1.8.0_102
* Operating system: macOS 10.12.6
* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/stories/taylorswift/
* Please include any additional information about how to reproduce the problem: Was okay before Oct 23

## Expected Behavior
Download photos/videos of the story

## Actual Behavior
Fail to download

Log message: 
`Failed to load https://www.instagram.com/graphql/query/?query_hash=null&variables={"reel_ids":["11830955"],"precomposed_overlay":false} after 1 attempts`

**Comment by chemistx** [comment]
I'm pretty sure it only rips user post
