### ISSUE TITLE
vk.com galleries/albums ripper *still* not working properly

### ISSUE THREAD

**Issue by ba295** [RipMeApp/ripme#1511]
* Ripme version: 1.7.90
* Java version: Java 8 - 231
* Operating system: Windows 10

https://vk.com/album-45984105_268691406

## Expected Behavior
Copy and Paste album from VK.com, rip all the pictures.

## Actual Behavior
Similar to the previous issue, none of the VK links are getting ripped. The app detects the link when copied and pasted but once you hit [RIP], nothing happens and the app stays stuck in "Starting rip..."
Tested on a new computer and the issue is still there.

**Comment by amigre38** [comment]
I confirm the same, none of the VK album i try are working properly, same behavior than the one reported above.
