### ISSUE TITLE
Issue with subreddit r/2Booty (the only instance I know of) and subreddits not downloading past 1000 downloads when there are more than 1000 posts.

### ISSUE THREAD

**Issue by Necabo1** [RipMeApp/ripme#1517]
* **Ripme version:** 1.7.90
* **Java version:** Version 8 Update 231 (build 1.8.0_231-b11)
* **Operating system:** Windows

* **Exact URL you were trying to rip when the problem occurred:** https://www.reddit.com/r/2Booty/ 
(in second issue especially) and a few other NSFW subreddits
* **Please include any additional information about how to reproduce the problem:** Started the rip, every subreddit seems to stop either a little under or a tiny bit over 1000 downloads, when there are infact more posts. Other problem is that the subreddit r/2Booty (not sure if occurs in other subreddits) gets error message "Error: JSONObject["Video"] not found." and stops the rip completely.

## Expected Behavior

The rip should download past 1000 downloads when there are more than 1000. In the second issue, the ripper should ignore the error and continue if possible, if not possible, then please fix the issue, whatever it might possibly be.

## Actual Behavior

Like said above, the ripper doesn't seem to download past 1000. And in subreddit r/2Booty it gets error message "Error: JSONObject["Video"] not found." and stops the rip.

**Comment by chemistx** [comment]
I think it has to do with reddit api stuff and not Ripme

reddit.com/r/redditdev/comments/30a7ap/does_reddit_api_limit_total_listings_returned_to/
