### ISSUE TITLE
Luscious.net ripper doesn't work

### ISSUE THREAD

**Issue by ShitLordAnal** [RipMeApp/ripme#1525]
* Ripme version: 1.7.90
* Java version: 1.8.0_221-b11
* Operating system: Windows 10 1903

* Exact URL you were trying to rip when the problem occurred: https://members.luscious.net/albums/bikini_258865/
* Please include any additional information about how to reproduce the problem: I didn't touch the settings since I use the software.

## Expected Behavior

Must download the collection.

## Actual Behavior

Error: No image found at : website. Does only that with Luscious.net because it worked fine with PornHub.

**Comment by Necabo1** [comment]
Have you tried with old.luscious.net?
