### ISSUE TITLE
FIX YOUR GOD DAMN BUGS!

### ISSUE THREAD

**Issue by ghost** [RipMeApp/ripme#1534]
GET OFF OF YOUR FUCKING ASSES YOU LAZY CUCKS AND FIX YOUR SHIT ASSHOLES.

**Comment by SileNce5k** [comment]
I think it would help if you said what the bugs are.

**Comment by chemistx** [comment]
I hope they don't plan on fixing whatever bugs you're encountering.

**Comment by pornismuybae** [comment]
Maybe they're referring to an open issue they made? https://github.com/RipMeApp/ripme/issues/1500 anyway, not productive, you're just wasting the time they could be spending fixing bugs on dealing with your bs. Also the glory of open source is that you can get of your own ass and fix it for everyone.
