### ISSUE TITLE
Noticed an extra character in RipMe's FurAffinity code

### ISSUE THREAD

**Issue by rautamiekka** [RipMeApp/ripme#155]
Since 1.0.75, RipMe's FA code has had a `"Login toÂ FurAffinity"` which was added (by accident ?) by @4pr0n in https://github.com/4pr0n/ripme/commit/b0e5fa8cb050740c1491a61666e743623f876cdd?w=1.

Now I can't be sure since the RipMe account pw is wrong, but this may be 1 thing hindering the ability to rip.

**Comment by cyian-1756** [comment]
As of 1.7.9 ripme uses cookies to auth and doesn't need to login
