### ISSUE TITLE
Add comand line support!

### ISSUE THREAD

**Issue by AndrejHatzi** [RipMeApp/ripme#1551]
* Ripme version:
* Java version: 
* Operating system: 

* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Detail the expected behavior here.

## Actual Behavior

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Comment by Isaaku** [comment]
This is already implemented. See https://github.com/ripmeapp/ripme/wiki/How-To-Run-RipMe#command-line-options
