### ISSUE TITLE
Artstation no longer support? It was working just fine last week.

### ISSUE THREAD

**Issue by sinjongthae** [RipMeApp/ripme#1569]
* Ripme version:
* Java version: 1.7.91
* Operating system: Windows 10

Been trying several artstation profile url but none of them are working eg: https://www.artstation.com/lulu_zhang and the result shown as Expected URL to an ArtStation 'project url' or 'user profile url' - got https://www.artstation.com/lulu_zhang instead

even remove 'https://' or change from 'http://' still not working.

![image](https://user-images.githubusercontent.com/16428521/73747762-abb44b00-478a-11ea-8aec-49cbc6a4fcef.png)

**Comment by benni-littau** [comment]
I can confirm that I got the same behavior with version 1.7.91 on Windows and Linux.
"https://ARTIST.artstation.com/" nor "https://www.artstation.com/ARTIST/" are accepted .

Maybe someone has the time to look into it. Thanks in advance!

**Comment by UnforeseenOcean** [comment]
Can confirm; ArtStation ripper does not work anymore.

What does it mean by "project url" or "user profile url"?
