### ISSUE TITLE
VSCO OFFICIALLY BROKEN

### ISSUE THREAD

**Issue by chemistx** [RipMeApp/ripme#1579]
* Ripme version: v1.7.91
* Java version:  
* Operating system: 

* Exact URL you were trying to rip when the problem occurred: vsco.co/username/1
* Please include any additional information about how to reproduce the problem:
 
## Expected Behavior 
To download all of users photos. 

## Actual Behavior

VSCO changed their url  from vsco.co/username/1 to vsco.co/username/ and now it's vsco.co/username/gallery. Now ripme can't download anything due to this change.

**Comment by github-account1111** [comment]
`vsco.co/username/images/1` works fine for me.

**Comment by thinkpad4** [comment]
Still it should be fixed, it uses Gallery now not Images https://vsco.co/rperron/gallery  and the /1 should either be builtin to the code or not needed anymore since Vsco doesn't use the /1 anymore officially

**Comment by goodboi69** [comment]
"/images/1" does not work anymore.

**Comment by NickyNiclas** [comment]
Yeah the vsco.co/<user>/images/# should ideally be changed to just vsco.co/<user>/ and assume /gallery. Maybe time to finish implementation of collection support and video support too. (It currently rips the videos as still images.)

**Comment by felixaufreisen** [comment]
> 
> 
> Yeah the vsco.co/user/images/# should ideally be changed to just vsco.co/user/ and assume /gallery. Maybe time to finish implementation of collection support and video support too. (It currently rips the videos as still images.)

For video support I submitted #1594
