### ISSUE TITLE
Instagram not downloading issue (Null)

### ISSUE THREAD

**Issue by AranciataExcess** [RipMeApp/ripme#1598]
Ripme version: v1.7.91
    Java version:
    java version "1.8.0_221"
    Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
    Java HotSpot(TM) Client VM (build 25.221-b11, mixed mode)
    Operating system:
    Microsoft Windows [Version 10.0.18362.239]

    Exact URL you were trying to rip when the problem occurred:
    https://www.instagram.com/valkyrae/

    Please include any additional information about how to reproduce the problem:
    Copy and paste the link to Ripme. It says rip complete but nothing downloads and you get a Null message in the text output portion. The IG account in question is a public one.

Downloading https://www.instagram.com/valkyrae
Rip complete, saved to \\gwarchive\instagram_valkyrae
null

Started happening maybe 1-2 days ago.

**Comment by ncaos** [comment]
It's still an issue.

**Comment by Isaaku** [comment]
In master i got 137
![image](https://user-images.githubusercontent.com/6236787/83370704-c6d44780-a385-11ea-9f9f-72a9f546ed3f.png), gonna check to see what is happening

**Comment by phuthokx** [comment]
still  an issue 
![image](https://user-images.githubusercontent.com/49843285/83639150-76065e00-a5d4-11ea-99b5-b662da295c50.png)

**Comment by tamenrip** [comment]
Still an issue.

**Comment by bookish1303** [comment]
Still an issue.

**Comment by AranciataExcess** [comment]
Still broken, it's reported in another thread.
