### ISSUE TITLE
e621 Ripper is broke - pls update

### ISSUE THREAD

**Issue by TristanNachgemacht** [RipMeApp/ripme#1604]
Hey this: e621.net had a big update recently and since then the ripper doesn't work anymore. A patch would make me happy. Thanks in advance.

* Ripme version: 1.7.91
* Java version: cant find it sorry qwq
* Operating system: Windows 10 Home x64 (10.0.18363 Build 18363)

**Comment by viktor02** [comment]
e621 changed url from https://e621.net/post/index/1/search to https://e621.net/posts?tags=search&page=1

**Comment by TristanNachgemacht** [comment]
That's supposed to mean something? It's not working for me ;(

**Comment by wickedwzrd** [comment]
Even with manually editing the url to the old format doesn't work. There are images under this search term yet it says nothing has been found.
![Screen Shot 2020-03-19 at 17 31 12](https://user-images.githubusercontent.com/9831909/77117094-aee85b00-6a07-11ea-8464-2f74f1f49e55.png)

**Comment by hellsunicorn** [comment]
I concur with the others. This needs issues desperately needs patching.

**Comment by TristanNachgemacht** [comment]
> I concur with the others. This issue desperately needs patching.

Yeah it would be very nice D:

**Comment by JotaRandom** [comment]
So far every single ripper or tracker related to e621 is broken, this since
e621 update they site.

I think they bróke all the trackers too.

**Comment by blackbirddx** [comment]
I made a fix, try it if you want: https://github.com/blackbirddx/ripme
This is compiled jar (if you don't trust me, check my repo and compile it yourself): [ripme-e621.zip](https://github.com/RipMeApp/ripme/files/4389630/ripme-e621.zip)
Please tell me if you encounter any problems, so I can fix them before making pull request.

**Comment by viktor02** [comment]
> 
> 
> I made a fix, try it if you want: https://github.com/blackbirddx/ripme
> This is compiled jar (if you don't trust me, check my repo and compile it yourself): [ripme-e621.zip](https://github.com/RipMeApp/ripme/files/4389630/ripme-e621.zip)
> Please tell me if you encounter any problems, so I can fix them before making pull request.

I can't create issue in your repo, but i got an error. 
<details>
  <summary>imgs</summary>
  
[Imgur](https://i.imgur.com/1fh6KoC.png) with captcha in url 
[Imgur](https://i.imgur.com/liU1yiI.png) no captcha 
  
</details>

**Comment by blackbirddx** [comment]
Fixed, here's binary: 
[ripme-e621-fix-2.zip](https://github.com/RipMeApp/ripme/files/4392383/ripme-e621-fix-2.zip)

Btw. how did you get the url with captcha?

**Comment by viktor02** [comment]
> Fixed, here's binary:
> [ripme-e621-fix-2.zip](https://github.com/RipMeApp/ripme/files/4392383/ripme-e621-fix-2.zip)
> 
> Btw. how did you get the url with captcha?

Sometimes it gives a cloudflare page when I connect via VPN. I just copy the full url after "human check"

**Comment by viktor02** [comment]
> Fixed, here's binary:
> [ripme-e621-fix-2.zip](https://github.com/RipMeApp/ripme/files/4392383/ripme-e621-fix-2.zip)
> 
> Btw. how did you get the url with captcha?

I still get the 403 error. Is it a problem on my side?

**Comment by blackbirddx** [comment]
> > Fixed, here's binary:
> > [ripme-e621-fix-2.zip](https://github.com/RipMeApp/ripme/files/4392383/ripme-e621-fix-2.zip)
> > Btw. how did you get the url with captcha?
> 
> I still get the 403 error. Is it a problem on my side?

It may be problem with the vpn and cloudflare. As the Ripper suggests, including cookies might solve it, but I never got the cloudflare captcha, so I don't really know what to do about it. Maybe try some other vpn (or connecting without vpn).

**Comment by viktor02** [comment]
> It may be problem with the vpn and cloudflare. As the app suggests, including cookies might solve it, but I never got the cloudflare captcha, so I don't really know what to do about it. Maybe try some other vpn (or connecting without vpn).

The problem is that I connected with and without vpn. And in any case, I get an error.

**Comment by blackbirddx** [comment]
> The problem is that I connected with and without vpn. And in any case, I get an error.
Before the e621 update, were you also getting the captcha? And did the ripper work for you then?

**Comment by viktor02** [comment]
> 
> 
> > The problem is that I connected with and without vpn. And in any case, I get an error.
> 
> Before the e621 update, were you also getting the captcha? And did the ripper work for you then?

I didn't have a captcha before the update. But I didn't use the ripper until now

**Comment by blackbirddx** [comment]
> I didn't have a captcha before the update. But I didn't use the ripper until now

I'll try to find a solution for that. I've been trying to get a captcha by using a couple free vpns, which I hoped would trigger cloudflare protection, but so far it didn't happen. I'll look into couple more and maybe I'll get lucky.

**Comment by viktor02** [comment]
> I'll try to find a solution for that


Try to log in with incognito. I have so without vpn protection CloudFlare triggers. As you come in with vpn - it is not. The problem with 403 is possible due to the blocking of the e621 by provider in Russia. However, error 403 remains even with vpn.

**Comment by TristanNachgemacht** [comment]
Ooof i hate it so much scince the update -__-

**Comment by TristanNachgemacht** [comment]
> 
> 
> Fixed, here's binary:
> [ripme-e621-fix-2.zip](https://github.com/RipMeApp/ripme/files/4392383/ripme-e621-fix-2.zip)
> 
> Btw. how did you get the url with captcha?

There is still the blacklist problem, I cannot download images that are blacklisted for standard users.

**Comment by blackbirddx** [comment]
> There is still the blacklist problem, I cannot download images that are blacklisted for standard users.

They are blacklisted for a reason. Anyway, login cookies might be a solution here, I'll look into it when I find some time. Although it seems like a bit of an overkill to me. Or I could use e621 API to download everything, but then some users might get stuff they don't want to see.

**Comment by blackbirddx** [comment]
> Try to log in with incognito. I have so without vpn protection CloudFlare triggers. As you come in with vpn - it is not. The problem with 403 is possible due to the blocking of the e621 by provider in Russia. However, error 403 remains even with vpn.

I finaly got the captcha - had to install Windows to get some russian vpn working (just couldn̈́t do it on Linux) and I think cookies might really solve it. I'll try to code it and will report if it works.

> They are blacklisted for a reason. Anyway, login cookies might be a solution here, I'll look into it when I find some time. Although it seems like a bit of an overkill to me. Or I could use e621 API to download everything, but then some users might get stuff they don't want to see.

I think I will just add option to config that would enable the global blacklist bypass (would still be disabled by default).

**Comment by viktor02** [comment]
> I finaly got the captcha - had to install Windows to get some russian vpn working (just couldn̈́t do it on Linux) and I think cookies might really solve it. I'll try to code it and will report if it works.

Lol, thank you, i will follow your repo

**Comment by TristanNachgemacht** [comment]
> 
> 
> > Try to log in with incognito. I have so without vpn protection CloudFlare triggers. As you come in with vpn - it is not. The problem with 403 is possible due to the blocking of the e621 by provider in Russia. However, error 403 remains even with vpn.
> 
> I finaly got the captcha - had to install Windows to get some russian vpn working (just couldn̈́t do it on Linux) and I think cookies might really solve it. I'll try to code it and will report if it works.
> 
> > They are blacklisted for a reason. Anyway, login cookies might be a solution here, I'll look into it when I find some time. Although it seems like a bit of an overkill to me. Or I could use e621 API to download everything, but then some users might get stuff they don't want to see.
> 
> I think I will just add option to config that would enable the global blacklist bypass (would still be disabled by default).

It would be very great of you if you could install such a blacklist bypass. Because it's starting to annoy me.

**Comment by blackbirddx** [comment]
So I think I've finally done it. Compiled jar as always:
[ripme-e621fix.zip](https://github.com/RipMeApp/ripme/files/4456019/ripme-e621fix.zip)

Both of the fixes require setting things in config file: https://github.com/RipMeApp/ripme/wiki/Config-options
You also need to find your cookies for e621. I use Cookie Quick Manager in Firefox.

> Try to log in with incognito. I have so without vpn protection CloudFlare triggers. As you come in with vpn - it is not. The problem with 403 is possible due to the blocking of the e621 by provider in Russia. However, error 403 remains even with vpn.

You need to complete the captcha challenge in your browser. After that, two cookies will be set for e621 - __cfduid and cf_clearance. In the config file (rip.properties) create new option e621.cookies and set it to:
__cfduid=<content of the cookie>;cf_clearance=<content of the cookie>
(not entirely sure if the cfduid is strictly necessary, but I rather included it)

Then you need to find out what your browser's user agent is. Just google "what is my user agent". In config create option e621.useragent and set it to your ua.

> There is still the blacklist problem, I cannot download images that are blacklisted for standard users.

At the end I decided against the api method, because technical limitations and me being lazy :) Instead, because I already had cookies for the last fix, I used those.

First you need to log in with an account and have Remember ticked. Then new cookie remember is set for e621, so copy its content. In options create  new option e621.cookies and set it to remember=<content of the cookie>

Then it should stop using the global anonymous user blacklist. Another advantage of being logged in is that it will use your own blacklist, so if you don't want to see something, you can block it. It also allows wildcards (*) in tags.

---------

You can of course combine the two fixes, just set you e621.cookies to:
__cfduid=<cookie>;cf_clearance=<cookie>;remember=<cookie>

Please note, that the cookies have limited lifespan, so eventually you will again have to find your cookies and set them in the config (the captcha I think only lasts couple of hours, the account around a week?)

**Comment by viktor02** [comment]
>Both of the fixes require setting things in config file:
I did as you asked - added a new parameters and saved it. However, this did not work, and importantly, the new parameters was erased from the file.

**Comment by blackbirddx** [comment]
> > Both of the fixes require setting things in config file:
> 
> I did as you asked - added a new parameters and saved it. However, this did not work, and importantly, the new parameters was erased from the file.

You need to do it when the app is closed, then save and run the app

**Comment by hellsunicorn** [comment]
Just tried your latest fix and it worked for me. Thanks a lot, blackbirddx

**Comment by viktor02** [comment]
>You need to do it when the app is closed, then save and run the app

Ok, Apparently that time I was doing something wrong. In any case, it didn’t work for me. I was passed captcha less than 5 minutes ago

<details>

![ripme](https://user-images.githubusercontent.com/19672960/79027767-30aa4f00-7b96-11ea-9b04-528647012eed.PNG)
![ripme2](https://user-images.githubusercontent.com/19672960/79027768-3142e580-7b96-11ea-87c9-c73c13e8eeb2.PNG)


</details>

**Comment by blackbirddx** [comment]
> > You need to do it when the app is closed, then save and run the app
> 
> Ok, Apparently that time I was doing something wrong. In any case, it didn’t work for me. I was passed captcha less than 5 minutes ago
> 
> ![ripme](https://user-images.githubusercontent.com/19672960/79027767-30aa4f00-7b96-11ea-9b04-528647012eed.PNG)
> ![ripme2](https://user-images.githubusercontent.com/19672960/79027768-3142e580-7b96-11ea-87c9-c73c13e8eeb2.PNG)

It's e621.cookie**s**, not e621.cookie.

**Comment by TristanNachgemacht** [comment]
I'm a bit confused right now, I've downloaded version 1.7.92 and still the blacklist is still used, how do I set it to ignore it?

**Comment by viktor02** [comment]
> It's e621.cookie**s**, not e621.cookie.
thank you very much, its work

**Comment by blackbirddx** [comment]
> I'm a bit confused right now, I've downloaded version 1.7.92 and still the blacklist is still used, how do I set it to ignore it?

If you downloaded the official build, my patch is still not part of it. You need to download my version.

Then follow the steps I described a few comments ago [https://github.com/RipMeApp/ripme/issues/1604#issuecomment-611507949](url).

**Comment by blackbirddx** [comment]
> I'm a bit confused right now, I've downloaded version 1.7.92 and still the blacklist is still used, how do I set it to ignore it?

Please let me know if it works for you. I want to make pull request to get this fix into the app, but I first need to know if the patch works.

**Comment by TristanNachgemacht** [comment]
> 
> 
> > I'm a bit confused right now, I've downloaded version 1.7.92 and still the blacklist is still used, how do I set it to ignore it?
> 
> If you downloaded the official build, my patch is still not part of it. You need to download [my version](https://github.com/RipMeApp/ripme/files/4456019/ripme-e621fix.zip).
> 
> Then follow the steps I described [a few comments ago](#issuecomment-611507949).

I just don't understand the steps, can you make me a config or show me exactly where I have to install it with the help of screenshots? That would be really very nice.

**Comment by blackbirddx** [comment]
> I just don't understand the steps, can you make me a config or show me exactly where I have to install it with the help of screenshots? That would be really very nice.

[e621-ripme-fix-howto.pdf](https://github.com/RipMeApp/ripme/files/4494859/e621-ripme-fix-howto.pdf)

**Comment by TristanNachgemacht** [comment]
> > I just don't understand the steps, can you make me a config or show me exactly where I have to install it with the help of screenshots? That would be really very nice.
> 
> [e621-ripme-fix-howto.pdf](https://github.com/RipMeApp/ripme/files/4494859/e621-ripme-fix-howto.pdf)

OMG THX YOU SO MUCH, ITS AMAZING :DD IT WORKS PERFECTLY :+1: :100: :1st_place_medal:

**Comment by blackbirddx** [comment]
You're all welcome :) Hope the pull request gets merged soon, so it may get into the next release.
