### ISSUE TITLE
broken reddit ripper

### ISSUE THREAD

**Issue by DisableGraphics** [RipMeApp/ripme#1612]
* Ripme version: 1.7.92 & 1.7.91
* Java version:  10 & 8 (tested on two os's)
* Operating system:  Ubuntu MATE 18.04 & ReactOS 0.4.14-dev

* Exact URL you were trying to rip when the problem occurred: reddit.com/r/memes
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Detail the expected behavior here.
It should download the images
## Actual Behavior

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.
When I try to download an URL with reddit, the images aren't downloaded. Then it says that the download has ended and if i liked to open the folder.

**Comment by DisableGraphics** [comment]
Yeah, me too. But reddit wasn't down when I had this problem.

**Comment by ANaPhOrAX** [comment]
seems to be related to video files. it's struggling to download a reddit dash video. hangs on that for me.

**Comment by DisableGraphics** [comment]
My problem was when I tried to download photos and videos.

**Comment by ThatOneRoadie** [comment]
I'm having the same issue with https://www.reddit.com/r/Tali/ and it's hanging on "Downloading https://v.redd.it/8ei3lnvfm3731/DASH_720"

**Comment by ThatOneRoadie** [comment]
Think I've got a winner; the post it hangs on has a backslash and forward slash, which is not allowed in a windows file name. Disabling Descriptions/Album titles fixes it as a temporary workaround.

**Comment by DisableGraphics** [comment]
But i'm using Linux...

**Comment by DisableGraphics** [comment]
Closing the issue. The problem has not happened to me since the first time. This issue is useless now.
