### ISSUE TITLE
How can I change where the history and properties are located?

### ISSUE THREAD

**Issue by thinkpad4** [RipMeApp/ripme#164]
I want to have the history and properties files located in the same folder as ripme.jar and not in AppData.  How do I do that

**Comment by cyian-1756** [comment]
That's not possible quite yet, The feature has been written but still needs to be tested before release. It should be part of 1.6.9

**Comment by cyian-1756** [comment]
@thinkpad4 Upgrade to ripme 1.6.9 and copy the rip.properties file into the same dir as ripme.jar, the next time you run ripme.jar it will store all it's config/history files in the same dir as the jar
