### ISSUE TITLE
drawchan.net no longer exists

### ISSUE THREAD

**Issue by cyian-1756** [RipMeApp/ripme#169]
The site drawchan.net no longer exists, support for it and it's unit tests should be removed

**Comment by cyian-1756** [comment]
@metaprime How should we go about removing support for sites? Should we out right remove the ripper, or just comment it out encase the site ever comes back?

**Comment by metaprime** [comment]
If the site comes back we can restore the ripper from the history. No need to keep unneeded files around. Straight-up remove is best.
