### ISSUE TITLE
Doesn't rip second page.

### ISSUE THREAD

**Issue by XarisBarnes** [RipMeApp/ripme#1699]
* Ripme version: 1.7.92
* Java version: Version 8 update 251
* Operating system: Windows 10
* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/sydneylcarlson/
* Please include any additional information about how to reproduce the problem: Just try to rip any instagram profile.

## Expected Behavior

All images get downloaded

## Actual Behavior

The ripper finishes after the first page, without downloading the second page.

**Comment by thisisbobdole** [comment]
I also am having this issue with all instagram rips.

**Comment by thisisbobdole** [comment]
I haven't updated or changed anything, but at some point it started working again.

**Comment by thisisbobdole** [comment]
And at some point it stopped working again, looks like someone else posted about it as well in a new issue

**Comment by tape-** [comment]
Also happening here. Same situtation as thisisbobdole described - the ripper only checks ~15-20 items. It started working again normally and checking the entire Instagram profile a couple of weeks ago, then at some point in the last week or so went back to only checking one page.
