### ISSUE TITLE
Instagram ripper broken

### ISSUE THREAD

**Issue by cyian-1756** [RipMeApp/ripme#17]
* Ripme version: 1.5.2
* Java version (output of `java -version`): openjdk version "1.8.0_131"
* Operating system: Ubuntu 16.04
* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/p/BWQalN4g5L1/ [WARNING] nasty infection gore
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

The album rips

## Actual Behavior

ripme outputs

`org.jsoup.HttpStatusException: HTTP error fetching URL. Status=404, URL=https://www.instagram.com/p/media/`

**Comment by rautamiekka** [comment]
Any less nasty links ?

**Comment by cyian-1756** [comment]
> Any less nasty links ?

https://www.instagram.com/p/BUNN7BHBBiU/

**Comment by rautamiekka** [comment]
> https://www.instagram.com/p/BUNN7BHBBiU/

Same happens as with OP's.

**Comment by lukepayne** [comment]
The Instagram ripper is designed to pull down a user's whole album, not individual images. Perhaps this should be listed as an enhancement request.

To rip this image, enter the page URL, eg: https://www.instagram.com/teethvids/ or https://www.instagram.com/starwars/ , then rip and find the image you wanted.

**Comment by cyian-1756** [comment]
Well I feel stupid. I thought the album was a album, not an individual picture
