### ISSUE TITLE
Ripping from reddit doesn't rip linked redgif.com videos

### ISSUE THREAD

**Issue by AesopMcLean** [RipMeApp/ripme#1703]
* Ripme version: v1.7.92  
* Java version: java version "1.8.0_251"  
                      Java(TM) SE Runtime Environment (build 1.8.0_251-b08)  
                      Java HotSpot(TM) Client VM (build 25.251-b08, mixed mode)  
* Operating system: Microsoft Windows [Version 10.0.18363.900]  

* Exact URL you were trying to rip when the problem occurred: https://www.reddit.com/user/Cumkitten99/submitted/  
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

It should have downloaded all images PLUS the following videos:  
https://www.redgifs.com/watch/indeliblegreatafricanparadiseflycatcher  
https://www.redgifs.com/watch/distantdecisivefowl
https://www.redgifs.com/watch/unfinishedunimportantcockatoo
https://www.redgifs.com/watch/bewitchedpoliticalbobcat

## Actual Behavior

It downloads all images fine, but does not download any of the redgifs.com videos.
Log is attached as log.txt
[log.txt](https://github.com/RipMeApp/ripme/files/4895487/log.txt)

This is just one example, but all subreddits and user pages I've used RipMe with haven't downloaded any redgifs.com videos.
Gfycat links seem to work fine.

**Comment by revanwolf** [comment]
There is a redgifs ripper on ripme but it is still not released but you can compile the latest source code to have this version.

Beware : the RedGifs server are very laggy/glitchy so some files could not be downloaded.
