### ISSUE TITLE
Unable to download full Instagram profiles

### ISSUE THREAD

**Issue by zxqro** [RipMeApp/ripme#1715]
* Ripme version: 1.7.92
* Java version: 1.8.0_261
* Operating system:  Windows 10 Pro  (Version 10.0.19041.264) 

* Exact URL you were trying to rip when the problem occurred: https://instagram.com/*USERNAME* (Example URLs: https://www.instagram.com/lindseypelas/ & https://www.instagram.com/_celinasmith/)
* Please include any additional information about how to reproduce the problem:
When trying to rip full instagram profiles - it stop the ripping process at around 20 images, no matter how many pictures the profile has.

## Expected Behavior

Rip all pictures from instagram profiles.

## Actual Behavior

Instead of downloading the full profile, it is downloading the first 20 images, +- a couple.

It seems like instagram might be restricting it?
I know when you are not signed in to Instagram, it will only allow you to scroll down a certain bit - after it will force you to sign in to continue viewing pictures. Could this be what is causing the issue?

Logsattached 

Log for instagram.com/_celinsamith: [log.txt](https://github.com/RipMeApp/ripme/files/4986508/log.txt)
 

Log for instagram.com/lindseypelas: [log.txt](https://github.com/RipMeApp/ripme/files/4986492/log.txt)

**Comment by zxqro** [comment]
I tried adding the session ID found in the cookie in "Chrome DevTools - Application - Cookies" in the rip.properties file. (instagram.session_id = MYSESSIONIDHERE) - and the result remains the same.

**Comment by thisisbobdole** [comment]
https://github.com/RipMeApp/ripme/issues/1699

**Comment by menial717** [comment]
Been having this issue for the past month. Just tried with v1.7.90 as well with the same result. Its an issue with a change within instagram i think

**Comment by zxqro** [comment]
This can be solved by using #1724 
Just tried to make a build myself and it works all fine.
Closing this issue as there is a solution available...
