### ISSUE TITLE
RipMe 1.6.9 not downloading all images from reddit user page

### ISSUE THREAD

**Issue by rippythefish** [RipMeApp/ripme#174]
* Ripme version: 1.6.9
* Java version:  (build 1.8.0_151-b12)
* Operating system:  Win 10 Pro
* Exact URL you were trying to rip when the problem occurred: https://www.reddit.com/user/venusfoxx
* Please include any additional information about how to reproduce the problem: Click "rip"

## Expected Behavior

Rips all images by user as displayed/linked on user page

## Actual Behavior

Skips considerable images and gifycat links

**Comment by metaprime** [comment]
Can you provide logs and more information about which images were skipped that you think should be present? My rip grabbed 236 items, and the user has posted 279 links (many of which are cross-post/duplicate). https://www.reddit.com/user/VenusFoxx/submitted/

Logs: https://pastebin.com/FF7eKFH8

**Comment by mne41906** [comment]
Not OP, but issue persists in 1.6.10. I've noticed it misses gfycat links that start with `https://gfycat.com/gifs/detail/` which seems to be the new default share link when creating a gfy. It also misses erome links.

**Comment by metaprime** [comment]
@mne41906 Thanks!

**Comment by metaprime** [comment]
https://github.com/RipMeApp/ripme/issues/90

**Comment by rippythefish** [comment]
Sorry it took so long to reply.

While I do get a lot of the users posted images when scraping their user page - some gifycat links do not rip and seem to be ignored. I don't see references to the ones I would expect to see.

As a for reference, here is one that did not pull: https://gfycat.com/gifs/detail/BlondNimbleAsianelephant

And here are the ones that did:
> Already downloaded http://i.imgur.com/lRQIWFL.png
Already downloaded http://i.imgur.com/2kxP6Ki.png
Already downloaded http://i.imgur.com/fKty2re.png
Already downloaded http://i.imgur.com/K4ivyFe.png
Already downloaded http://i.imgur.com/QsZ8mOS.png
Already downloaded https://i.redd.it/h4bzkxwuhhxz.jpg
Already downloaded http://i.imgur.com/bZQPBXa.jpg
Already downloaded http://i.imgur.com/6vhgryZ.jpg
Already downloaded http://i.imgur.com/gidI2eY.jpg
Already downloaded https://i.redd.it/i0v2wkgdyywz.jpg
Already downloaded https://i.redd.it/nu6i8ifyxywz.jpg
Already downloaded https://i.redd.it/k2bfq45mwywz.jpg
Already downloaded https://i.redd.it/la4z45wjwywz.jpg
Already downloaded https://i.redd.it/5gquzdr6wywz.jpg
Already downloaded https://i.redd.it/597gccf1wywz.jpg
Already downloaded https://i.redd.it/3dqdn534ewwz.jpg
Already downloaded https://i.redd.it/vh9qdvctdwwz.jpg
Already downloaded https://i.redd.it/a11ygxrhdwwz.jpg
Already downloaded https://i.redd.it/q70n7giadwwz.jpg
Already downloaded https://i.redd.it/0q3ywld7dwwz.jpg
Already downloaded https://i.redd.it/lm5an5x1dwwz.jpg
Already downloaded https://i.redd.it/gl5ka9ysyvwz.jpg
Already downloaded https://i.redd.it/u9ioj8hqyvwz.jpg
Already downloaded https://i.redd.it/oozceabmyvwz.jpg
Already downloaded https://i.redd.it/d3gh8aedyvwz.jpg
Already downloaded https://i.redd.it/1e74gq9ftqwz.jpg
Already downloaded https://i.redd.it/dmtjmbqdtqwz.jpg
Already downloaded https://i.redd.it/r5bhq1bbtqwz.jpg
Already downloaded https://i.redd.it/mfbwisn8tqwz.jpg
Already downloaded https://i.redd.it/gwn3i956tqwz.jpg
Already downloaded https://i.redd.it/9x5cue3srqwz.jpg
Already downloaded https://i.redd.it/vw4z96qm3pwz.jpg
Already downloaded https://i.redd.it/a3fejmacmowz.jpg
Already downloaded https://i.redd.it/f5237d26lowz.jpg
Already downloaded https://i.redd.it/h7navl30lowz.jpg
Already downloaded https://i.redd.it/zxxfh8nh2nwz.jpg
Already downloaded https://i.redd.it/xzafifv0abwz.jpg
Already downloaded https://i.redd.it/85muig7x9bwz.jpg
Already downloaded https://i.redd.it/q92uk3w7mawz.jpg
Already downloaded https://i.redd.it/prak6zthi3wz.jpg
Already downloaded https://i.redd.it/exmos3lei3wz.jpg
Already downloaded https://i.redd.it/gy8r5k7643wz.jpg
Already downloaded https://i.redd.it/zeo2frbrj2wz.jpg
Already downloaded https://i.redd.it/8u4sq4ukj2wz.jpg
Already downloaded https://i.redd.it/ld9aw9nfj2wz.jpg
Already downloaded https://i.redd.it/t69rra0tunvz.jpg
Already downloaded https://i.redd.it/yssx04grunvz.jpg
Already downloaded https://i.redd.it/asmroj2punvz.jpg
Already downloaded https://i.redd.it/yv6lqolmunvz.jpg
Already downloaded http://i.imgur.com/i1isvNz.jpg
Already downloaded http://i.imgur.com/uubxOKB.jpg
Already downloaded http://i.imgur.com/i1isvNz.jpg
Already downloaded http://i.imgur.com/uubxOKB.jpg
Already downloaded https://i.redd.it/m6krjknt9kvz.jpg
Already downloaded https://i.redd.it/1wgmhu325kvz.jpg
Already downloaded https://i.redd.it/cv0g9h2z4kvz.jpg
Already downloaded https://i.redd.it/2ozsobiw4kvz.jpg
Already downloaded https://i.redd.it/jz5gadnt4kvz.jpg
Already downloaded https://i.redd.it/t9kj4jgnfhvz.jpg
Already downloaded https://i.redd.it/1oor33cgehvz.jpg
Already downloaded https://i.redd.it/86o72vmeehvz.jpg
Already downloaded https://i.redd.it/hpkfhplaehvz.jpg
Already downloaded http://i.imgur.com/kKd7Cy8.jpg
Already downloaded http://i.imgur.com/UvzkZQm.jpg
Already downloaded https://i.redd.it/zsap50ohchvz.jpg
Already downloaded https://i.redd.it/yr5g4p32chvz.jpg
Already downloaded https://i.redd.it/nixuc89xbhvz.jpg
Already downloaded https://i.redd.it/rh62ujdrbhvz.jpg
Already downloaded https://i.redd.it/cbebvibqbhvz.jpg
Already downloaded https://i.redd.it/iqrbeu5kbhvz.jpg
Already downloaded https://i.redd.it/h9etycjgbhvz.jpg
Already downloaded https://i.redd.it/hemiqwhcbhvz.jpg
Already downloaded https://i.redd.it/9hpb9du7bhvz.jpg
Already downloaded https://i.redd.it/vbu4tn83bhvz.jpg
Already downloaded https://i.redd.it/8rz34ezqahvz.jpg
Already downloaded https://i.redd.it/9a8lnugrogvz.jpg
Already downloaded http://i.imgur.com/zYL2ypO.jpg
Already downloaded http://i.imgur.com/nX9Hs6X.jpg
Already downloaded https://i.redd.it/jgylladub8vz.jpg
Already downloaded https://i.redd.it/rjg7wa5kb8vz.jpg
Already downloaded http://i.imgur.com/4mXHOZy.jpg
Already downloaded http://i.imgur.com/E0EZo5z.jpg
Already downloaded http://i.imgur.com/l8r6XuW.jpg
Already downloaded http://i.imgur.com/qVNyORZ.jpg
Already downloaded http://i.imgur.com/4mXHOZy.jpg
Already downloaded http://i.imgur.com/E0EZo5z.jpg
Already downloaded http://i.imgur.com/l8r6XuW.jpg
Already downloaded http://i.imgur.com/qVNyORZ.jpg
Already downloaded http://i.imgur.com/4mXHOZy.jpg
Already downloaded http://i.imgur.com/E0EZo5z.jpg
Already downloaded http://i.imgur.com/l8r6XuW.jpg
Already downloaded http://i.imgur.com/qVNyORZ.jpg
Already downloaded https://i.redd.it/asmpwjop0ouz.jpg
Already downloaded https://i.redd.it/e3lxe9zi0ouz.jpg
Already downloaded https://i.redd.it/zh6mhld10ouz.jpg
Already downloaded https://i.redd.it/4hdpbmhnznuz.jpg
Already downloaded https://i.redd.it/15d3isdcznuz.jpg
Already downloaded https://i.redd.it/4y3azah7znuz.jpg
Already downloaded https://i.redd.it/fnngyfd8jnuz.jpg
Already downloaded https://i.redd.it/wmseutu09nuz.jpg
Already downloaded https://i.redd.it/385auq8b4juz.jpg
Already downloaded https://i.redd.it/ugv2o2t54juz.jpg
Already downloaded https://i.redd.it/4zjgvrkw3juz.jpg
Already downloaded https://i.redd.it/3luketke2juz.jpg
Already downloaded https://i.redd.it/rqzhvfbb2juz.jpg
Already downloaded https://i.redd.it/jtu9mam42juz.jpg
Already downloaded https://i.redd.it/8xj3mshs1juz.jpg
Already downloaded https://i.redd.it/boys4zi42iuz.jpg
Already downloaded https://i.redd.it/mkmeeb5y1iuz.jpg
Already downloaded https://i.redd.it/7mkeohsu1iuz.jpg
Already downloaded https://i.redd.it/foi099ef1iuz.jpg
Already downloaded https://i.redd.it/er21hiw91iuz.jpg
Already downloaded https://i.redd.it/epqd7mb71iuz.jpg
Already downloaded https://i.redd.it/xpelbf6mzhuz.jpg
Already downloaded https://i.redd.it/j2mq5vi7ohuz.jpg
Already downloaded https://giant.gfycat.com/VibrantSlowIvorybilledwoodpecker.mp4
Already downloaded https://giant.gfycat.com/VibrantSlowIvorybilledwoodpecker.mp4
Already downloaded https://i.redd.it/kl9xg6a3v7uz.jpg
Already downloaded https://i.redd.it/16sqh9c3g6uz.jpg
Already downloaded https://i.redd.it/szgf6ugzf6uz.jpg
Already downloaded https://i.redd.it/xjh2rt1xf6uz.jpg
Already downloaded https://i.redd.it/n1p5zterf6uz.jpg
Already downloaded https://i.redd.it/cahsnxrjd6uz.jpg
Already downloaded https://i.redd.it/e4j05tpbd6uz.jpg
Already downloaded https://i.redd.it/krjkb23h95uz.jpg
Already downloaded https://i.redd.it/7iiviyj295uz.jpg
Already downloaded https://i.redd.it/j8rr3542b4uz.jpg
Already downloaded https://i.redd.it/sptmyhie52uz.jpg
Already downloaded https://i.redd.it/xg3fb6tb52uz.jpg
Already downloaded https://i.redd.it/xfet8oofoxtz.jpg
Already downloaded https://i.redd.it/n7zefyrdoxtz.jpg
Already downloaded https://i.redd.it/l2ku24k7axtz.jpg
Already downloaded https://i.redd.it/nfny1pkw9xtz.jpg
Already downloaded https://i.redd.it/e7i02p2e9xtz.jpg
Already downloaded https://i.redd.it/tkqij6479xtz.jpg
Already downloaded https://i.redd.it/qfcoju7svvtz.jpg
Already downloaded https://i.redd.it/9cpmz7cmvvtz.jpg
Already downloaded https://i.redd.it/aacizk1kvvtz.jpg
Already downloaded https://i.redd.it/m1fssj34vvtz.jpg
Already downloaded https://i.redd.it/ubsduip6vptz.jpg
Already downloaded https://i.redd.it/xalfrenp8otz.jpg
Already downloaded https://i.redd.it/msxlbuc92ktz.jpg
Already downloaded https://i.redd.it/noyb0q7etjtz.jpg
Already downloaded https://i.redd.it/cisxg9r6tjtz.jpg
Already downloaded https://i.redd.it/ro876tdhretz.jpg
Already downloaded https://giant.gfycat.com/ElatedQuerulousBernesemountaindog.mp4
Already downloaded https://i.redd.it/ubhygrhvm7tz.jpg
Already downloaded https://i.redd.it/pahddk0ti7tz.jpg
Already downloaded https://i.redd.it/2wlvx75ji7tz.jpg
Already downloaded https://i.redd.it/hcmx1uzbx6tz.jpg
Already downloaded https://i.redd.it/zqseothre3tz.jpg
Already downloaded https://i.redd.it/0x8snytrh2tz.jpg
Already downloaded https://i.redd.it/p0n9zqr422tz.jpg
Already downloaded https://i.redd.it/2iu29ouk12tz.jpg
Already downloaded https://i.redd.it/iyk5ifwkw1tz.jpg
Already downloaded https://i.redd.it/qu7dtvd8q1tz.jpg
Already downloaded https://i.redd.it/eap86wa0q1tz.jpg
Already downloaded https://i.redd.it/cjitwcuzi0tz.jpg
Already downloaded https://i.redd.it/zklrfpts9zsz.jpg
Already downloaded https://i.redd.it/mkfom25d3zsz.jpg
Already downloaded https://i.redd.it/t3kwk3663zsz.jpg
Already downloaded https://giant.gfycat.com/AcademicMemorableDwarfrabbit.mp4
Already downloaded https://i.redd.it/jcwb4p4q2zsz.jpg
Already downloaded https://i.redd.it/upd4rz0o2zsz.jpg
Already downloaded https://i.redd.it/hrzn8gfz0zsz.jpg
Already downloaded https://i.redd.it/1dq21w7y0zsz.jpg
Already downloaded https://i.redd.it/283ycw3m9ysz.jpg
Already downloaded https://i.redd.it/9kc1zer22ysz.jpg
Already downloaded https://i.redd.it/ipdsjq6s1ysz.jpg
Already downloaded https://i.redd.it/zbz8sx7k1ysz.jpg
Already downloaded https://i.redd.it/befqg31fzxsz.jpg
Already downloaded https://i.redd.it/47n01g6azxsz.jpg
Already downloaded https://i.redd.it/3djszn2uxxsz.jpg
Already downloaded https://i.redd.it/l3n8tondfxsz.jpg
Already downloaded https://i.redd.it/8r60052i9xsz.jpg
Already downloaded https://i.redd.it/aje5f5kp1xsz.jpg
Already downloaded https://i.redd.it/0xq7yvydpwsz.jpg
Already downloaded http://i.imgur.com/SxMutfL.png
Already downloaded http://i.imgur.com/q3QlSuW.jpg
Already downloaded http://i.imgur.com/7TdpQ1L.jpg
Already downloaded http://i.imgur.com/ysWfRG4.jpg
Already downloaded http://i.imgur.com/VoKLutu.jpg
Already downloaded http://i.imgur.com/Uov4TGd.jpg
Already downloaded http://i.imgur.com/ScDfqke.jpg
Already downloaded https://i.redd.it/f4d4xpe6tgsz.jpg
Already downloaded https://i.redd.it/9sbl0x0kwfsz.jpg
Already downloaded https://i.redd.it/exzlp5rc7fsz.jpg
Already downloaded http://i.imgur.com/f912PRZ.jpg
Already downloaded http://i.imgur.com/rszrhT7.jpg
Already downloaded http://i.imgur.com/c6ar6F3.jpg
Already downloaded http://i.imgur.com/l9os5kZ.jpg
Already downloaded https://i.redd.it/fjuarjfrvesz.jpg
Already downloaded https://i.redd.it/ou5c0aumvesz.jpg
Already downloaded https://i.redd.it/2wtdwzffvesz.jpg
Already downloaded https://i.redd.it/9ry1dc96vesz.jpg
Already downloaded https://i.redd.it/li13ho9obesz.jpg
Already downloaded https://i.redd.it/nwj3332jpasz.jpg
Already downloaded https://i.redd.it/9mvj5w1adasz.jpg
Already downloaded https://i.redd.it/w86neh7kr4sz.jpg
Already downloaded https://i.redd.it/o33405mlq4sz.jpg
Already downloaded https://i.redd.it/763q7e9tt2sz.jpg
Already downloaded https://i.redd.it/6d4bijpmt2sz.jpg
Already downloaded https://i.redd.it/x4yq9e1gq2sz.jpg
Already downloaded https://i.redd.it/bh1j0xzxxzrz.jpg
Already downloaded https://i.redd.it/54mx1cdaxzrz.jpg
Already downloaded https://i.redd.it/inijcugk0zrz.jpg
Already downloaded https://i.redd.it/pi2zv8b70zrz.jpg
Already downloaded https://i.redd.it/wo7vmnl5cxrz.jpg
Already downloaded https://i.redd.it/gfek4dzvbxrz.jpg
Already downloaded https://i.redd.it/j6wep21qbxrz.jpg
Already downloaded https://i.redd.it/60mu7wa1xprz.jpg
Already downloaded https://i.redd.it/wqs9c02eqorz.jpg
Already downloaded https://i.redd.it/n7kmaikh9orz.jpg
Already downloaded https://i.redd.it/9e0cvw62axqz.jpg
Already downloaded https://i.redd.it/l25i519l5wqz.jpg
Already downloaded https://i.redd.it/dndt1nu0bvqz.jpg
Already downloaded https://i.redd.it/a964fxw8vuqz.jpg
Already downloaded https://i.redd.it/cupfk7c3tuqz.jpg
Already downloaded https://i.redd.it/hiiwuc6okuqz.jpg
Already downloaded https://i.redd.it/iip9e6czjuqz.jpg
Already downloaded https://i.redd.it/8ysoz6799uqz.jpg
Already downloaded https://i.redd.it/bpqcvws2xtqz.jpg
Already downloaded https://i.redd.it/54rhoy68ttqz.jpg
Already downloaded https://i.redd.it/929nzis9qtqz.jpg
Already downloaded https://i.redd.it/achqn188otqz.jpg
Already downloaded http://i.imgur.com/MjTa7GJ.jpg
Already downloaded http://i.imgur.com/gMfKCFV.jpg
Already downloaded http://i.imgur.com/I8qvR9k.jpg
Already downloaded https://i.redd.it/ctog13ugktqz.jpg
Already downloaded https://i.redd.it/shrcs5wwksqz.jpg
Already downloaded https://i.redd.it/h4w69apm5sqz.jpg
Already downloaded https://i.redd.it/vu5yoqgrzrqz.jpg
Already downloaded https://i.redd.it/stjd13mnzrqz.jpg
Already downloaded https://i.redd.it/jwwldoa4njqz.jpg
Already downloaded https://i.redd.it/9leb73chmjqz.jpg
Already downloaded https://i.redd.it/j7dbjw2zijqz.jpg
Already downloaded http://i.imgur.com/e6auO5b.jpg
Already downloaded http://i.imgur.com/7rqbE0t.jpg
Already downloaded http://i.imgur.com/sDUmCAp.jpg
Already downloaded https://i.redd.it/t7jzirm3pdqz.jpg
Already downloaded https://i.redd.it/l1qnc16h0bqz.jpg
Already downloaded https://i.redd.it/wcv5937pyaqz.jpg
Already downloaded https://i.redd.it/h2x035k1prpz.jpg
Already downloaded https://i.redd.it/r8t7wyf61ppz.jpg
Already downloaded https://i.redd.it/177qf9ikyjpz.jpg
Already downloaded https://i.redd.it/glw1m6fqwapz.jpg
Already downloaded https://i.redd.it/gqg18k9cylnz.jpg
Already downloaded https://i.redd.it/e8yrckll15nz.jpg
Already downloaded https://i.redd.it/1ax1pzwvwcmz.jpg
Already downloaded https://i.redd.it/z7b0uoffucmz.jpg
Already downloaded https://i.redd.it/b2d2foaq87mz.jpg
Already downloaded https://i.redd.it/jq68isvp87mz.jpg
Already downloaded https://i.redd.it/4huki9uc55lz.jpg
Already downloaded https://i.redd.it/zemkd3rdm4lz.jpg
Already downloaded https://i.redd.it/pvnrzkjkc4lz.jpg
Already downloaded https://i.redd.it/vk5k9qp8a4lz.jpg
Already downloaded https://i.redd.it/ydkazbim64lz.jpg
Already downloaded https://i.redd.it/bprkcfdsy3lz.jpg
Already downloaded https://i.redd.it/ngcll05dt3lz.jpg
Already downloaded https://i.redd.it/8fuhgkhap3lz.jpg
Rip complete, saved to H:\Reddit Rips\reddit_user_venusfoxx

**Comment by metaprime** [comment]
@rippythefish Thanks for the additional info. This issue was a duplicate of #90 so we're tracking there now.
