### ISSUE TITLE
Failure to rip all instagram posts.

### ISSUE THREAD

**Issue by woundedmonk** [RipMeApp/ripme#1740]
* Ripme version: v1.7.93
* Java version: version 8 update 261 (build 1.8.0_261-b12)
* Operating system: windows 10 home version 10.0.18362 Build 18362
* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/thatsstrange/ and https://www.instagram.com/intraventus/
* Please include any additional information about how to reproduce the problem: seems to be occurring across all instagram pages.

## Expected Behavior

Expected to rip all instagram posts (835 and 217 respectively on the above links.)

## Actual Behavior

Only ripped 12 and 15 posts respectively on the above links.

**Comment by detroyecl** [comment]
I have the same issue. Instagram itself only seems to load a few photos at a time as you scroll manually in a browser which matches up with the amount of photos downloaded.

**Comment by Cathbhadh** [comment]
As a temporary solution: https://github.com/RipMeApp/ripme/issues/1719#issuecomment-680696082

**Comment by ANaPhOrAX** [comment]
temporary fix doesn't work anymore

**Comment by thinkpad4** [comment]
Anyone find a way to rip IG again?

**Comment by AranciataExcess** [comment]
It's only downloading the first page in IG, subsequent pages aren't downloading (was using temp fix in https://github.com/RipMeApp/ripme/issues/1719#issuecomment-680696082 )

**Comment by Wiiplay123** [comment]
Only ripping page one for me too on RipMe v1.7.93
