### ISSUE TITLE
Used it once, worked perfectly. The second time I used it, all it would do is make a notepad document listing all the url's

### ISSUE THREAD

**Issue by tangre** [RipMeApp/ripme#1750]
* Ripme version: v1.7.93
* Java version:  not sure, please let me know how to find this.
* Operating system:  Windows 10

* Exact URL you were trying to rip when the problem occurred: prefer not to say
* Please include any additional information about how to reproduce the problem: 

## Expected Behavior

All media is downloaded and stored in a rip folder

## Actual Behavior

instead of downloading all images/videos, it just creates a .txt listing out the url's of all of the items.

**Comment by tangre** [comment]
I figured out the problem

**Comment by rautamiekka** [comment]
The template gives you the platform-independent command to find the Java version !
