### ISSUE TITLE
Fix Imagefap Rip Please! ASAP - Error Imagefap Captcha blocking from downloading

### ISSUE THREAD

**Issue by FIXIMAGEFAPNOW** [RipMeApp/ripme#1753]
* Ripme version:
* Java version: 
* Operating system: 

* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

## Expected Behavior -should download galleries from imagefap but will not anymore.

Detail the expected behavior here.  

## Actual Behavior

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

1.) Error Imagefap Captcha blocking from downloading: cannot donwload anymore because imagefap is throwing captcha and ripme can't get to the gallery to download -please fix asap!

**Comment by epeternally** [comment]
Imagefap are cracking down on mass downloads, I'm hoping the devs can implement a delay between downloads to avoid tripping their bot check. Even if it slows down the process significantly, you'd still be saving a lot of manual inputs.

**Comment by drpal230** [comment]
It looks like imagefap blocks rips after a few galleries worth, I'm not sure exactly how many files. It's definitely IP-based though - I'm able to work around it by using a VPN. I connect to my VPN through a proxy server, download rips until it throws a captcha, then switch servers and start again. It's a bit unwieldy but at least it allows to still download whole IF galleries in bulk.
