### ISSUE TITLE
Feature Request: Instagram Download by hashtag

### ISSUE THREAD

**Issue by ERasnier** [RipMeApp/ripme#178]
I'm a complete beginner at programming so I can't really say if this is possible but it would cover pretty much everything that can be downloaded from Instagram aside from private accounts. And maybe place each download in folders by username.

**Comment by cyian-1756** [comment]
Can you give me an example URL?

**Comment by ERasnier** [comment]
https://www.instagram.com/explore/tags/woodworking/?hl=en

**Comment by ERasnier** [comment]
Forgot that there's also location specific photos and videos. Here's an example of that. https://www.instagram.com/explore/locations/492698296/el-topo-mexican/?hl=en

**Comment by cyian-1756** [comment]
Taking a quick look it seems like it should be possible

**Comment by cyian-1756** [comment]
After some more searching it doesn't seem possible to group photos by username here. The json data on the page only has the user_id and you need access to IGs api to turn an ID into a username

**Comment by ERasnier** [comment]
Is there any way of at least tying the photos with a link to it?

**Comment by cyian-1756** [comment]
> Is there any way of at least tying the photos with a link to it?

Yea, the link_ID is in the JSON. All you have to do to get the link is go to instagram.com/p/link_ID

**Comment by cyian-1756** [comment]
This was partly implemented in 1.6.13 (You can now rip by tag but not by location)

**Comment by ERasnier** [comment]
Thanks! It doesn't download the next page after it says so in log and finishes.

**Comment by cyian-1756** [comment]
> It doesn't download the next page after it says so in log and finishes.

Oh balls. It looks like IG is throwing "Recent posts from \#HASHTAG are currently hidden because the community has reported some content that may not meet Instagram's community guidelines. Learn more" if you hit any page with "?max_id=" in it.

I'll look for a work around

**Comment by cyian-1756** [comment]
It looks like I'm going to need to start hitting "https://www.instagram.com/graphql/query/?query_id=" to get the needed JSON

**Comment by cyian-1756** [comment]
Support for this was added a while back
