### ISSUE TITLE
Invalid save path generates NullPointerException rather than error message

### ISSUE THREAD

**Issue by crystalattice** [RipMeApp/ripme#1785]
* Ripme version:1.7.93
* Java version: 11.0.9.hs  and 8.0.272.open
* Operating system: Ubuntu 20.10

* Exact URL you were trying to rip when the problem occurred: Any currently supported URL
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

A warning or other notification telling the user that the save path provided is invalid.

## Actual Behavior

An invalid path for file saving results in the GUI either flashing and returning with no information or, in the command line, a NullPointerException with no additional message about an invalid path

[!] Failed to rip URL ...
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.util.Arrays$ArrayList.<init>(Arrays.java:3813)
	at java.util.Arrays.asList(Arrays.java:3800)
	at com.rarchives.ripme.utils.Utils.getOriginalDirectory(Utils.java:519)
	at com.rarchives.ripme.ripper.AlbumRipper.setWorkingDir(AlbumRipper.java:201)
	at com.rarchives.ripme.ripper.AbstractRipper.setup(AbstractRipper.java:179)
	at com.rarchives.ripme.App.rip(App.java:102)
	at com.rarchives.ripme.App.handleArguments(App.java:183)
	at com.rarchives.ripme.App.main(App.java:78)

**Comment by OmarMorales71** [comment]
@crystalattice Hello can you help me with an invalid url to see the error?

**Comment by crystalattice** [comment]
I thought I had included one in the bug report, but apparently not. Here is
an example URL: https://www.reddit.com/r/GothStyle

**Comment by OmarMorales71** [comment]
@crystalattice Reviewing the behavior of this process, this exception arises from videos (to be specific mp4 formats). An error message is displayed in the user's log and the user does not try to download it again.

**Comment by madhatr** [comment]
This catch and log won't close the issue right? Still need to find why there was an exception and fix it so we can download the mp4.

**Comment by soloturn** [comment]
can you pls try the binary here:
https://github.com/ripmeapp2/ripme/actions
