### ISSUE TITLE
Ripper doesn't show what's being downloaded.

### ISSUE THREAD

**Issue by tehloxely** [RipMeApp/ripme#179]
It would be nice if I knew what was currently downloading. The app currently only shows what's completed.

![untitled](https://user-images.githubusercontent.com/1208778/32703769-a49bca9e-c7c8-11e7-8503-3e70437be7d7.png)

**Comment by cyian-1756** [comment]
What URL where you trying to rip?

**Comment by tehloxely** [comment]
It does that for my entire queue. RipMe used to tell me what I am currently downloading.

**Comment by cyian-1756** [comment]
> RipMe used to tell me what I am currently downloading.

It still should. Try clearing your config files and reruning ripme

**Comment by metaprime** [comment]
Copy your config file here and take a screenshot of your settings and that might help us figure out what happened in your case.

**Comment by tehloxely** [comment]
What file is the config file?

**Comment by metaprime** [comment]
rip.properties

**Comment by tehloxely** [comment]
`# Download threads to use per ripper
threads.size = 2

# Overwrite existing files
file.overwrite = false

# Number of retries on failed downloads
download.retries = 1

# File download timeout (in milliseconds)
download.timeout = 60000

# Page download timeout (in milliseconds)
page.timeout = 5000

# Maximum size of downloaded files in bytes (required)
download.max_size = 104857600

# Don't retry on 404 errors
error.skip404 = true

# API creds
twitter.auth = VW9Ybjdjb1pkd2J0U3kwTUh2VXVnOm9GTzVQVzNqM29LQU1xVGhnS3pFZzhKbGVqbXU0c2lHQ3JrUFNNZm8=
tumblr.auth = JFNLu3CbINQjRdUvZibXW9VpSEVYYtiPJ86o8YmvgLZIoKyuNX
gw.api = gonewild

twitter.max_requests = 10

clipboard.autorip = false

download.save_order = true
prefer.mp4 = true
rips.directory = H:\\Rips
auto.update = false
log.level = Log level: Error
play.sound = false
download.show_popup = false
log.save = true
urls_only.save = false
album_titles.save = true
descriptions.save = true
window.x = 1448
window.y = 69
window.w = 428
window.h = 420
remember.url_history = true
window.position = false
`

![untitled](https://user-images.githubusercontent.com/1208778/33618647-19660228-d9b1-11e7-8a31-fb010a469f32.jpg)

**Comment by cyian-1756** [comment]
Is this still an issue?

**Comment by cyian-1756** [comment]
This should be fixed in 1.7.36
