### ISSUE TITLE
Ripme fails to work on DEs without tray icons 

### ISSUE THREAD

**Issue by cyian-1756** [RipMeApp/ripme#1804]
* Ripme version: 1.7.94
* Java version: 
* Operating system:  Ubuntu 18.04

* Exact URL you were trying to rip when the problem occurred: Happens with any
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Ripme rips in back ground 

## Actual Behavior

Ripme errors out with `null` due the lack of a tray icon in my DE

**Comment by rautamiekka** [comment]
I know I added a bypass for this, but I can't find it anymore.

Or is this case something totally else that doesn't trigger the bypass ?

**Comment by cyian-1756** [comment]
> Or is this case something totally else that doesn't trigger the bypass ?

In this case it was [this line](https://github.com/RipMeApp/ripme/blob/19ea20dcd62d6ea1197073ce9a7236c5c1f47556/src/main/java/com/rarchives/ripme/ui/MainWindow.java#L1284)

**Comment by rautamiekka** [comment]
> > Or is this case something totally else that doesn't trigger the bypass ?
> 
> In this case it was [this line](https://github.com/RipMeApp/ripme/blob/19ea20dcd62d6ea1197073ce9a7236c5c1f47556/src/main/java/com/rarchives/ripme/ui/MainWindow.java#L1284)

Ah, that makes sense.
