### ISSUE TITLE
Xhamster tests are failing

### ISSUE THREAD

**Issue by saladzic** [RipMeApp/ripme#1837]
Version: Master Branch

The Junit tests for Xhamster fail. I assume that the error comes from the changed HTML structure. The CI fails as well because the tests fail.

**Comment by saladzic** [comment]
Link to failed CI: https://github.com/RipMeApp/ripme/runs/1851822433?check_suite_focus=true

**Comment by saladzic** [comment]
I added the fix and it seems that all tests pass now in my local IDE. But the CI still fails at Xhamster and I don't know why.
Can someone help me?

<img width="182" alt="test-result" src="https://user-images.githubusercontent.com/69090391/107824020-08284e00-6d81-11eb-9178-a680b4a58570.png">

**Comment by soloturn** [comment]
if it works sometimes or on some places i'd merge it and use the "flaky" tag for the test.

a side note, [your pull request contains 2 commits](https://github.com/ripmeapp2/ripme/pull/1), one of them is already on main. i did it not the correct way i guess. i took your commit via "cherry-pick" the following way and with it changed its hash when it landed on [ripme2 branch main](https://github.com/ripmeapp2/ripme/commits/main):

```
> git remote -v
origin	git@github.com:RipMeApp/ripme.git (fetch)
rm	git@github.com:ripmeapp2/ripme.git (fetch)
...

> pr=1831 git fetch origin pull/$pr/head:pr-$pr && git checkout pr-$pr
...
 * [new ref]           refs/pull/1831/head -> pr-1831

> git cherry-pick b94f6465
> git push rm
```

**Comment by saladzic** [comment]
Very good, thanks for the cherry-pick!
Yeah, I messed up my pull requests a bit and I'm sorry about that :/ I'm still very new to GitHub and still trying to get my start. Mainly I'm impressed with the CI/CD pipelines :D

Can I close this issue or should I change something before?
