### ISSUE TITLE
Program stops ripping after one item in queue

### ISSUE THREAD

**Issue by floriankorstanje** [RipMeApp/ripme#1848]
* Ripme version: 1.7.94
* Java version: openjdk version "11.0.10" 2021-01-19
* Operating system: Ubuntu 20.04.2 LTS
* Exact URL you were trying to rip when the problem occurred: https://www.reddit.com/r/cats/top/?t=all
* Please include any additional information about how to reproduce the problem: I have 3 subreddits in the queue and I just clicked rip

## Expected Behavior
It downloads all the images on the 3 subreddits and saves them.

## Actual Behavior
After doing one subreddit (r/cats top=all) it stops and I have to click "Stop" and then "Rip" again to make it continue to the next item in the queue. Even after waiting 10 minutes it's still waiting if I don't do anything about it.

**Comment by soloturn** [comment]
can you try the ripme2 binary please, it has most pull requests in:
https://github.com/ripmeapp2/ripme/actions

**Comment by floriankorstanje** [comment]
> can you try the ripme2 binary please, it has most pull requests in:
> https://github.com/ripmeapp2/ripme/releases

This seems to work! Thank you
