### ISSUE TITLE
Derpibooru.org doesnt work - Remember System

### ISSUE THREAD

**Issue by socalledkion** [RipMeApp/ripme#1851]
* Ripme version: 1.7.94 (e621 patch)
* Java version: java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)
* Operating system: Microsoft Windows [Version 10.0.19041.804]
* Exact URL you were trying to rip when the problem occurred: https://derpibooru.org/tags/artist-colon-amy-dash-gamy?page=1&q=artist%3Aamy-gamy

*Informations: Derpibooru does not seem to work. It would be great if you could add that. 
It would also be nice to have a remember cookie system behind it so that you can bypass the filter. 

Thanks in advance ~ **Kion**

**Comment by rautamiekka** [comment]
I need to warn that Derpibooru provides a very functional non-slow API which doesn't hide much anything (you need an acc and the API key from your settings), which'd be a better idea than scanning the website.

^ Sure the website doesn't change next to at all, but I'm sure they're providing the API to lessen the load on their systems.

If all else fails, gallery-dl is your best bet. The config is very involved, though, it's JSON and the config docs format requires using some brain cells.

**Comment by socalledkion** [comment]
> If all else fails, gallery-dl is your best bet. The config is very involved, though, it's JSON and the config docs format requires using some brain cells.

First of all, thank you for the reply. Unfortunately I am a complete 0 at something like this and would like to integrate this into RIPME, is there a possibility?

**Comment by rautamiekka** [comment]
> > If all else fails, gallery-dl is your best bet. The config is very involved, though, it's JSON and the config docs format requires using some brain cells.
> 
> First of all, thank you for the reply. Unfortunately I am a complete 0 at something like this and would like to integrate this into RIPME, is there a possibility?

Not without a whole new OAuth 2.0 infrastructure, pretty sure. I just checked to refresh my memory, and noticed Derpibooru had been supported before, but it was a mix of HTML and JSON parsing, both direct HTTP requests; dunno if the direct JSON requests are possible anymore.

With the minute or 2 long checking through the code I couldn't find if RipMe is able to visit another page to click a button and return to another to scan the page, so there's that.

**Comment by socalledkion** [comment]
> > > If all else fails, gallery-dl is your best bet. The config is very involved, though, it's JSON and the config docs format requires using some brain cells.
> > 
> > 
> > First of all, thank you for the reply. Unfortunately I am a complete 0 at something like this and would like to integrate this into RIPME, is there a possibility?
> 
> Not without a whole new OAuth 2.0 infrastructure, pretty sure. I just checked to refresh my memory, and noticed Derpibooru had been supported before, but it was a mix of HTML and JSON parsing, both direct HTTP requests; dunno if the direct JSON requests are possible anymore.
> 
> With the minute or 2 long checking through the code I couldn't find if RipMe is able to visit another page to click a button and return to another to scan the page, so there's that.

Does it mean it won't work? Or will not be possible?

**Comment by rautamiekka** [comment]
^ With API, not possible ATM IIUC. With website scanning, after fixing the ripper.
