### ISSUE TITLE
Inactive on startup. Throws NullPointerException

### ISSUE THREAD

**Issue by ub34s0ldat3n55** [RipMeApp/ripme#1853]
* Ripme version:
```
ripme -v
1.7.94
```

* Java version: 
```
java -version
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment (build 15.0.2+7)
OpenJDK 64-Bit Server VM (build 15.0.2+7, mixed mode)
```
Results are the same for `openjdk8`

* Operating system: 
``` 
ArchLinux 5.11.2-arch1-1 
Using XFCE
 ```

I just installed RipMe and it launches in the dock. I have not made any configuration. Execution stalls at: 
```
ripme
Loaded file:/usr/share/java/ripme.jar!/rip.properties
Setting locale to default
Loaded log4j.properties
Initialized ripme v1.7.94
Getting key select.save.dir in en_US value Select Save Directory
Getting key loading.history.from.configuration in en_US value Loading history from configuration
Loading history from configuration
Exception in thread "main" java.lang.NullPointerException: Cannot read the array length because "<local3>" is null
        at com.rarchives.ripme.ui.MainWindow.loadHistory(MainWindow.java:1186)
        at com.rarchives.ripme.ui.MainWindow.<init>(MainWindow.java:186)
        at com.rarchives.ripme.App.main(App.java:89)
```
Like #446 it says it's inactive and does not work.
It prints: `Getting key tray.hide in en_US value Hide` when switching windows.

**Comment by soloturn** [comment]
so this is the relevant code: https://github.com/RipMeApp/ripme/blob/master/src/main/java/com/rarchives/ripme/ui/MainWindow.java#L1186

```
                String[] dirs = Utils.getWorkingDirectory()
                        .list((dir, file) -> new File(dir.getAbsolutePath() + File.separator + file).isDirectory());
                for (String dir : dirs) {
```
stackoverflow says:
https://stackoverflow.com/questions/65737245/java-lang-nullpointerexception-cannot-read-the-array-length-because-local3

"This way your member variable stays uninitialized."

**Comment by soloturn** [comment]
please try latest from here:
https://github.com/ripmeapp2/ripme/releases

**Comment by ub34s0ldat3n55** [comment]
> please try latest from here:
> https://github.com/ripmeapp2/ripme/releases

This one did work. Thanks.
