### ISSUE TITLE
Why i cannot download this link?!

### ISSUE THREAD

**Issue by Cheatsgt** [RipMeApp/ripme#1906]
Hello, I have tried this tool but why can't I download this link? https://www.luscious.net/albums/keqing_415510/
(This link just Example The other links also don't work)

**Comment by michelangelo404** [comment]
> Hello, I have tried this tool but why can't I download this link? https://www.luscious.net/albums/keqing_415510/
> (This link just Example The other links also don't work)

What's the error output?
I'm using v1.7.95 and the link works

**Comment by Cheatsgt** [comment]
@michelangelo404 it says "Failed to Repeat Download for the fifth time", Does the internet affect because in my country the site is blocked?

**Comment by Cheatsgt** [comment]
ini fotofoto nya ununtuk eror  @michelangelo404 
![IMG_20210804_165320](https://user-images.githubusercontent.com/88219711/128161565-f7261993-03ab-46f4-8f96-c434ee3e8442.jpg)

**Comment by Cheatsgt** [comment]
Here the eror message @michelangelo404 
![IMG_20210804_165320](https://user-images.githubusercontent.com/88219711/128161775-a8bea295-927f-4a51-87d4-0a6796774c2e.jpg)

**Comment by michelangelo404** [comment]
@Cheatsgt if the site is blocked in your country, you can't rip albums, due to ISP limitations.
Maybe try with a proxy or a VPN

**Comment by Cheatsgt** [comment]
@michelangelo404  Thank You
