### ISSUE TITLE
[Request] DeviantArt error 403 login problem

### ISSUE THREAD

**Issue by michelangelo404** [RipMeApp/ripme#1907]
* Ripme version: 1.7.95
* Java version: OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
* Operating system: Lubuntu 18.04 LTS

Hi, i'm trying this app, the first site I've tested is DeviantArt, I noticed that the site need the user to login in order to download albums. What I suggest is: is it good to implement a function where, inside the app, the user submits DeviantArt login credentials, then RipMeApp saves it so it is possible to rip from deviantart?

**Comment by soloturn** [comment]
sounds good, would be excellent if you d create a pull request.

**Comment by michelangelo404** [comment]
I noticed that in DeviantArtripper.java the login function is implemented, so the Error 403 it's a bug. Need further investigation
