### ISSUE TITLE
E621 Login

### ISSUE THREAD

**Issue by Dacraun** [RipMeApp/ripme#1921]
* Ripme version: **v1.7.95**
* Java version:  jre1.8.0_301 (x64)
* Operating system:  Windows 10 64 bit

* Exact URL you were trying to rip when the problem occurred:
* https://e621.net/posts?page=1&tags=instant_loss_2koma

## Expected Behavior

I want RipMe to download things according to my blacklists, not the visitor version.

## Actual Behavior

RipMe tells me that some pictures are blacklisted by default (that's fine) and that I should try logging in by following a wiki page to use my own blacklist:

**_Some posts are blacklisted. Consider logging in. Search for "e621" in this wiki page: https://github.com/RipMeApp/ripme/wiki/Config-options_**

Except that e621 does not figure on said wiki page.
Is there a way to log in through these config options despite this?

**Comment by thisonefox** [comment]
You need the e621 patch version; Download it here: https://workupload.com/archive/JSR4gQuc
And read the pdf for instructions. Enjoy

**Comment by Dacraun** [comment]
Thank you kindly @thisonefox
You're fantastic, and your fix works wonders. :D

**Comment by thisonefox** [comment]
> 

No problem :3 Enjoy ^w^ Just remember it's still linked to your own blacklist. So when you blacklist "young" it will still not download it ^^" So you can create your own filters now 👍
