### ISSUE TITLE
Ripper crashes when closing confirmation window

### ISSUE THREAD

**Issue by jendeukieee** [RipMeApp/ripme#1975]
* Ripme version: 1.7.95
* Java version: 1.8.0_321
* Operating system: 10.0.22000.613
* Exact URL you were trying to rip when the problem occurred: None
* Please include any additional information about how to reproduce the problem:
Going into History, clicking Clear and pressing X on the confirmation window
## Expected Behavior
Clicking X on the confirmation window would close it and goes back to the main window to continue ripping

## Actual Behavior
Ripper crashes
No errors are shown in the log file.

**Comment by soloturn** [comment]
merged here: https://github.com/ripmeapp2/ripme/releases

**Comment by jendeukieee** [comment]
Oh, thanks a lot, didn't know there was an updated version of RipMe
