### ISSUE TITLE
Download from tumblr archive

### ISSUE THREAD

**Issue by ikoutone** [RipMeApp/ripme#198]
* Ripme version: 1.6.10
* Java version: 1.8.0_151
* Operating system: Microsoft Windows [Version 10.0.16299.19]
* Exact URL you were trying to rip when the problem occurred: http://scandalousgaijin.tumblr.com/archive
* Please include any additional information about how to reproduce the problem:

## Expected Behavior
Archive download starts

## Actual Behavior
Message "Expected format: http://subdomain[.tumblr.com][/tagged/tag|post/postno]

**Comment by cyian-1756** [comment]
@LilianaFilipa Go ahead

**Comment by johanneszab** [comment]
Hi!

I'm the author of a different open source Tumblr ripper/backup application. There is no need to add a ripper for the [/archive](http://mywallpapercollections.tumblr.com/archive/) tumblr pages. They contain the same posts as the [normal blog site](http://mywallpapercollections.tumblr.com/) but in a different view.

The archive view allows the visitor to filter the posts based on [post type](http://mywallpapercollections.tumblr.com/archive/filter-by/link) (e.g. photo, video, audio, ..) and to show only posts of a [specific month](http://mywallpapercollections.tumblr.com/archive/2012/11), but in principle the same can be achieved with the [already implemented api v2 ripper](https://www.tumblr.com/docs/en/api/v2#posts).

**Comment by cyian-1756** [comment]
> There is no need to add a ripper for the /archive tumblr pages. They contain the same posts as the normal blog site but in a different view.

Neat. Thanks for the info!
