### ISSUE TITLE
Instagram: support individual posts (pictures, albums)

### ISSUE THREAD

**Issue by metaprime** [RipMeApp/ripme#20]
See discussion in #17 

## Expected Behavior

Instagram ripper can handle ripping posts when starting from a profile page. Should be able to handle links to individual posts.

## Actual Behavior

Trying to rip a page which is a direct link to a post does not work.

**Comment by PaulBGD** [comment]
I'm working on this. While adding `/media` to the end of a post URL returns the 1st image, it doesn't return anything special for getting the other images for an album. So currently I have something written that will only work for single image posts.

**Comment by cyian-1756** [comment]
This was done in #239
