### ISSUE TITLE
Feature request: Instagram download when private account

### ISSUE THREAD

**Issue by whoamikyo** [RipMeApp/ripme#200]
there is the possibility to put option to enter with some instagram's credentials to download when the user has a private account.

think it respects, very useful in some cases.

**Comment by cyian-1756** [comment]
> there is the possibility to put option to enter with some instagram's credentials to download when the user has a private account.

After some looking around there seems to be a lot of work on reverse engineering IGs private api so support for private accounts could be added

**Comment by tehloxely** [comment]
Here's what the error in the log looks like for me.

> 2017-11-18 14:18:17,771 ERROR ripper.AbstractRipper .run() Got exception while running ripper:
java.io.IOException: No images found at https://www.instagram.com/carlie.howell/
	at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:80)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:413)
	at java.lang.Thread.run(Unknown Source)

**Comment by metaprime** [comment]
@tehloxely Is that the actual link you got the error for (interestingly https://www.instagram.com/_______/ is a real profile, but doesn't look like it's private and it ripped just fine for me).

It's much easier for us to diagnose problems and verify fixes if you give us the actual URL that is causing the problem.

**Comment by beefykitten** [comment]
[Here's an example.](https://www.instagram.com/nubiafelipeti/)  Hopefully you guys can get this figured out, because it would be a handy feature to have.

**Comment by Isaaku** [comment]
@cyian-1756 this is already implemented
