### ISSUE TITLE
Suggeston: Bandcamp ripper

### ISSUE THREAD

**Issue by jEsuSdA** [RipMeApp/ripme#203]
Hi!

It will be fine to having a bandcamp.com ripper to allow download mp3 from albums. ;)

Thanks!

**Comment by rautamiekka** [comment]
Links ?

**Comment by jEsuSdA** [comment]
E.g. one album:
https://losultimosbanistas.bandcamp.com/album/expedici-n-lp-2015

The audio files can be downloaded by Video DownloadHelper, but only a file after other.

;)

**Comment by rautamiekka** [comment]
FWIW, `youtube-dl` can get Bandcamp albums and weeklies, at least.

**Comment by jEsuSdA** [comment]
Great news!! I did't know that.
Thank you! ;)

**Comment by metaprime** [comment]
Tracking request in #38
