### ISSUE TITLE
Disabled tests: XhamsterRipperTest test cases are flaky in Travis CI

### ISSUE THREAD

**Issue by cyian-1756** [RipMeApp/ripme#206]
* Ripme version: 1.6.10
* Java version:  openjdk version "1.8.0_151"

* Operating system:  Ubuntu 16.04
* Exact URL you were trying to rip when the problem occurred: Unit tests
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

The tests pass

## Actual Behavior

The test fails with `junit.framework.AssertionFailedError: Failed to download a single file from https://xhamster.com/photos/gallery/sexy-preggo-girls-9026608`

This has happened randomly with 2 my PRs (#204 and #199). All openJDK tests pass and only the Xhamster unit test fails. This doesn't happen all time, just seemly at random leading me to believe this is an issue on xhamsters end.

There have been been problems with the xhamster ripper before, caused by xhamster using different CDNs and invalid SSL certs for certain regions , I imagine this is what is causing this test failure (It would explain why it fails seemingly at random)

**Comment by cyian-1756** [comment]
@metaprime I found the issue! Xhamster seems to be in the middle of a site redesign and returns the new site layout some what randomly. You can check out the new site by clicking the "new xhamster" button at of top of any xhamster page

A pretty simple work around for this is to use the mobile version of xhamster

**Comment by metaprime** [comment]
@cyian-1756 ah, I guess they are A/B testing the new layout. Using the mobile site seems like a good solution (until they start to rewrite that as well).
