### ISSUE TITLE
pichunter ripper

### ISSUE THREAD

**Issue by handsomebananas** [RipMeApp/ripme#208]
* Ripme version: 1.6.11
* Java version: 1.8.0_151
* Operating system: Win10

https://github.com/RipMeApp/ripme/issues/38#issuecomment-344999723
Sorry, forgot to clarify what under tags/models/sites just list of photosets.

For example: http://www.pichunter.com/tags/Sex the first photoset will be http://www.pichunter.com/gallery/3270642/Its_not_only_those_who#11
We need to download all of the photosets under tag/Sex instead of only one photo.

And adding the download option from pichunter.com/gallery will be great.

**Comment by sxnfxsed** [comment]
I second the ability to rip from /gallery urls

**Comment by cyian-1756** [comment]
I made a PR that adds support for galleries, it should be in the 1.6.12 release.

**Comment by handsomebananas** [comment]
@cyian-1756, something went wrong.
Ripme 1.6.12
[ripme.log](https://github.com/RipMeApp/ripme/files/1483796/ripme.log)

**Comment by cyian-1756** [comment]
@handsomebananas It's looks like I messed up the regex a bit. You can rip some urls by removing everything after the #

**Comment by cyian-1756** [comment]
This is fixed in 1.6.13
