### ISSUE TITLE
Downloading blank files

### ISSUE THREAD

**Issue by Hydrobolt** [RipMeApp/ripme#210]
<img width="783" alt="2017-11-16 22_02_43-instagram_haitiancocaine" src="https://user-images.githubusercontent.com/12200864/32927359-178c179e-cb1a-11e7-9c80-69973eedbf43.png">

* Ripme version: 1.6.11
* Java version: Version 8 Update 111
* Operating system: Windows 10
* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/yuval65/?hl=en
* Please include any additional information about how to reproduce the problem: Happens with every (public) Instagram rip

## Expected Behavior

Download as normal

## Actual Behavior

Instead of downloading X-amount of photos from a user's page it turns into .file files which cannot be opened.

**Comment by thinkpad4** [comment]
Seeing this too

**Comment by metaprime** [comment]
Duplicate of #211, fixed in #213
