### ISSUE TITLE
Where to group what function

### ISSUE THREAD

**Issue by XeonPhobia** [RipMeApp/ripme#22]
I'm working on ripping Imgsrc.ru, it has the following steps:

Get URLs to albums
    Each page contains 50 URLs that can easily be sanitized into the album URL. (What method do I use for this?)

Each album URL contains a number of sub-URLs. (What method do I use for this?)

Each sub-URL do I use the following methods to download all images from the site.
    getURLsFromPage()
    downloadURL()
This is the part that works just fine.

**Comment by cyian-1756** [comment]
> Each page contains 50 URLs that can easily be sanitized into the album URL. (What method do I use for this?)

getUrlsFromPage

> Each album URL contains a number of sub-URLs. (What method do I use for this?)

AFAIk there is no built in method, you'll have to write your own. You can check the myhentaicomics ripper to see how I did it

> Each sub-URL do I use the following methods to download all images from the site.
> getURLsFromPage()
> downloadURL()
> This is the part that works just fine.

I didn't quite any stand why you meant there could you reword it?
