### ISSUE TITLE
Use history.json from gui on headless server

### ISSUE THREAD

**Issue by sxnfxsed** [RipMeApp/ripme#221]
Is there a way to use the history.json file that the gui outputs in the cli. I want to transfer a lot to a server and I cant seen to find a way to get it to work with the file I have.

**Comment by cyian-1756** [comment]
> Is there a way to use the history.json file that the gui outputs in the cli.

Not at this time, but it should easy to implement 

> I want to transfer a lot to a server and I cant seen to find a way to get it to work with the file I have.

What exactly are you trying to do?

**Comment by sxnfxsed** [comment]
I don't know any other way of transferring the urls I already have saved in the history.json except dragging it there. I wouldn't know how to write a script to grab the urls from the json either. It's too many to just copy and paste to a urls.txt

**Comment by cyian-1756** [comment]
> I don't know any other way of transferring the urls I already have saved in the history.json except dragging it there.

Couldn't you just ssh the file over? Or use ftp/sftp

Why do you want the history file?

**Comment by sxnfxsed** [comment]
I did but the program doesnt support the json in cli. Its a fresh server that I want to use for my ripping instead of my home connection, I want to transfer the history file that I already have to the server and rip from there

**Comment by cyian-1756** [comment]
> I want to transfer the history file that I already have to the server and rip from there

You mean rerip from the history file? You should be able to do that by copying the file to the server and running ripme with the -r flag.

**Comment by cyian-1756** [comment]
> Dunno if I'm doing something wrong, I added a screenshot of the outputs.

Where are you putting the history file? It should go either in ~/.config/ripme or in the same dir as ripme (If you're running in portable mode)

**Comment by sxnfxsed** [comment]
The file is in the same directory as the jar, its all in the my home folder.  How do I run it portable mode?

**Comment by cyian-1756** [comment]
> The file is in the same directory as the jar, its all in the my home folder.

Then try moving it to ~/.config/ripme

> How do I run it portable mode?

Copy or create a file named rip.properties in the same dir as ripmr
