### ISSUE TITLE
Hushpix album not working

### ISSUE THREAD

**Issue by HASJ** [RipMeApp/ripme#223]
* Ripme version: 1.6.13
* Java version: 1.8.0_151
* Operating system: 10.0.16299.64
* https://hushpix.com/album/gKcu/
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

For images to be found and ripped.

## Actual Behavior

```
Rip complete, saved to D:\Downloads\rips\hushpix.com_Naked_Women_is_Our_Specialty
No images found at https://hushpix.com/album/gKcu
```

**Comment by cyian-1756** [comment]
It looks like hushpix implemented one of those stupid "Click here if you agree to access our site" pages. The ripper will have to be modified to hit the url the agree button leads to and send the cookies it receives with every request it makes

**Comment by metaprime** [comment]
I installed EditThisCookie to inspect the cookies. Looks like we need to send the cookie ("AGREE_CONSENT", "1")
