### ISSUE TITLE
InstagramRipper does not download slideshows anymore

### ISSUE THREAD

**Issue by ULBAZOR** [RipMeApp/ripme#224]
* Ripme version: 1.6.13
* Java version: 8 update 151
* Operating system: Windows 10 Pro 64-bit
* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/instagram/ (It did not rip this slideshow for example: https://www.instagram.com/p/BZRhGLyj6AN/)
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

The InstagramRipper is supposed to rip the entire slideshow, meaning it is supposed to download all of the images and videos in the post.

## Actual Behavior

The InstagramRipper does not rip slideshows at all. It only downloads the first image or video in the post, but not the rest. Then it simply moves on to the rest of the posts in the Instagram account. If I am not mistaken this issue first appeared after upload date/time started being added to the filenames of the ripped images and videos, in version 1.6.11. I was the one who requested the feature.

**Comment by metaprime** [comment]
Fill out the template when you report an issue, otherwise it is very difficult to help you.

What version are you running? What URL are you ripping?

**Comment by thinkpad4** [comment]
I think this is what they mean https://www.instagram.com/p/BZ4egP7njW5/?hl=en  I think that is a Instagram Slideshow  10 images in one post in that example

**Comment by cyian-1756** [comment]
I can fix this pretty easily by just making a request to every image page when downloading, but that will slow down ripping by a great deal.

**Comment by metaprime** [comment]
From looking at the source of https://www.instagram.com/hilaryduff/, it looks like each type of post gets an overlay. We will know if it's an album by the `coreSpriteSidecarIconLarge` -- so we only have to make additional requests to those pages.

```html
<div class="_70iju">
    <div class="_mck9w _gvoze _f2mse">
        <a href="/p/BaPuZQLHNmD/?taken-by=hilaryduff">
            <div class="_e3il2">
                <div class="_4rbun">
                    <img alt="⚾️" class="_2di5p" style="" sizes="293px" srcset="https://scontent-sea1-1.cdninstagram.com/t51.2885-15/s150x150/e35/22427587_124814561559558_8080514684299509760_n.jpg 150w,https://scontent-sea1-1.cdninstagram.com/t51.2885-15/s240x240/e35/22427587_124814561559558_8080514684299509760_n.jpg 240w,https://scontent-sea1-1.cdninstagram.com/t51.2885-15/s320x320/e35/22427587_124814561559558_8080514684299509760_n.jpg 320w,https://scontent-sea1-1.cdninstagram.com/t51.2885-15/s480x480/e35/22427587_124814561559558_8080514684299509760_n.jpg 480w,https://scontent-sea1-1.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/22427587_124814561559558_8080514684299509760_n.jpg 640w"
                        src="https://scontent-sea1-1.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/22427587_124814561559558_8080514684299509760_n.jpg">
                </div>
                <div class="_si7dy"></div>
            </div>
        </a>
    </div>
    <div class="_mck9w _gvoze _f2mse">
        <a href="/p/BaNPpaHn2zU/?taken-by=hilaryduff">
            <div class="_e3il2">
                <div class="_4rbun">
                    <img alt="Well I had an amazing afternoon with Naomi from 
@makeawishamerica she wanted to sing a serious #fbf  of mine #whynot  and I literally had to print out lyrics lol ❤️ Naomi you are beautiful and courageous inside and out and I loved singing with you and eating cupcakes the “right” way.  Thank you
@riskybusinessMB for helping us out on the 🎸!! ❤️" class="_2di5p" style="" sizes="293px" srcset="https://scontent-sea1-1.cdninstagram.com/t51.2885-15/s150x150/e15/22426828_141902046430454_5870838973550559232_n.jpg 150w,https://scontent-sea1-1.cdninstagram.com/t51.2885-15/s240x240/e15/22426828_141902046430454_5870838973550559232_n.jpg 240w,https://scontent-sea1-1.cdninstagram.com/t51.2885-15/s320x320/e15/22426828_141902046430454_5870838973550559232_n.jpg 320w,https://scontent-sea1-1.cdninstagram.com/t51.2885-15/s480x480/e15/22426828_141902046430454_5870838973550559232_n.jpg 480w,https://scontent-sea1-1.cdninstagram.com/t51.2885-15/s640x640/e15/22426828_141902046430454_5870838973550559232_n.jpg 640w"
                        src="https://scontent-sea1-1.cdninstagram.com/t51.2885-15/s640x640/e15/22426828_141902046430454_5870838973550559232_n.jpg">
                </div>
                <div class="_si7dy"></div>
            </div>
            <div class="_lxd52">
                <div class="_jnyq2">
                    <span class="_c3aqk _8scx2 coreSpriteSidecarIconLarge">Post</span> <!-- NOTE: coreSpriteSidecarIconLarge -->
                </div>
            </div>
        </a>
    </div>
    <div class="_mck9w _gvoze _f2mse">
        <a href="/p/BaKGaoGn2a3/?taken-by=hilaryduff">
            <div class="_e3il2">
                <div class="_4rbun">
                    <img alt="#tb to last years melt down for class mates valentine gifts. 30 times is a lot to write your name 😂"
                        class="_2di5p" style="" sizes="293px" srcset="https://scontent-sea1-1.cdninstagram.com/t51.2885-15/s150x150/e15/c0.90.720.720/22426914_1957760624512820_2152579570862129152_n.jpg 150w,https://scontent-sea1-1.cdninstagram.com/t51.2885-15/s240x240/e15/c0.90.720.720/22426914_1957760624512820_2152579570862129152_n.jpg 240w,https://scontent-sea1-1.cdninstagram.com/t51.2885-15/s320x320/e15/c0.90.720.720/22426914_1957760624512820_2152579570862129152_n.jpg 320w,https://scontent-sea1-1.cdninstagram.com/t51.2885-15/s480x480/e15/c0.90.720.720/22426914_1957760624512820_2152579570862129152_n.jpg 480w,https://scontent-sea1-1.cdninstagram.com/t51.2885-15/s640x640/e15/c0.90.720.720/22426914_1957760624512820_2152579570862129152_n.jpg 640w"
                        src="https://scontent-sea1-1.cdninstagram.com/t51.2885-15/s640x640/e15/c0.90.720.720/22426914_1957760624512820_2152579570862129152_n.jpg">
                </div>
                <div class="_si7dy"></div>
            </div>
            <div class="_lxd52">
                <div class="_u3xlu">
                    <span class="_my8ed _8scx2 coreSpriteVideoIconLarge">Video</span> <!-- NOTE: coreSpriteVideoIconLarge -->
                </div>
            </div>
        </a>
    </div>
</div>
```

**Comment by metaprime** [comment]
Also we should support ripping individual instagram posts (so one doesn't have to rip an entire profile), and have the profile ripper call into the method which rips individual picture, video, and album (slideshow) posts.

**Comment by metaprime** [comment]
FWIW I don't think those class names (like `<div class="_lxd52">`) are randomly generated. I think it's probably pre-compiled from their sources where they use longer, more descriptive names. It makes me a little nervous to depend on those names to remain the same though, so we should focus on the CSS matcher for names that are really clear (something like) `div > a span.coreSpriteSidecarIconLarge`

**Comment by metaprime** [comment]
Also @ULBAZOR @thinkpad4 - when was the last time this behavior worked correctly? It would be helpful to know because we might be able to pinpoint the change that broke it (assuming it wasn't broken by the site changing source).

**Comment by cyian-1756** [comment]
@metaprime 

> From looking at the source of https://www.instagram.com/hilaryduff/, it looks like each type of post gets an overlay. We will know if it's an album by the coreSpriteSidecarIconLarge -- so we only have to make additional requests to those pages.

All that HTML is generated via javascript. The only static data that is the page JSON, but after some further looking it seems like you can tell slide shows frpm tge __typename field in the pages JSON 

> Also we should support ripping individual instagram posts (so one doesn't have to rip an entire profile)

I'm 99% sure that's already in 1.6.13

> assuming it wasn't broken by the site changing source

AFAIK it was. IG removed the /media endpoint a few days ago and I rewrote the ripper to

**Comment by ULBAZOR** [comment]
@metaprime @cyian-1756 I updated my first comment, please read through it again.

**Comment by thinkpad4** [comment]
@metaprime Honestly, I can't remember.  I thought it did but I can't remember what version it was.  I do remember some rips having more files then the post number of the IG page.

**Comment by metaprime** [comment]
@cyian-1756:

@thinkpad4's link didn't work for me in 1.6.13

https://www.instagram.com/p/BZ4egP7njW5/?hl=en
https://www.instagram.com/p/BZ4egP7njW5

```
E:\dev\ripme>java -jar ripme.jar -u https://www.instagram.com/p/BZ4egP7njW5
Loaded E:\dev\ripme\rip.properties
Loaded log4j.properties
Initialized ripme v1.6.13
sanitized URL is https://www.instagram.com/p/BZ4egP7njW5
[!] Given URL is not valid. Expected URL format is http://domain.com/...
```

And the UI gives this error ("Unable to find user in <URL>")

![image](https://user-images.githubusercontent.com/7526632/32998395-87090db6-cd4f-11e7-819f-9a4a7623d577.png)

**Comment by metaprime** [comment]
The CLI error seems to be a separate bug that affects all URLs. I'll investigate and either fix or open a bug.

**Comment by cyian-1756** [comment]
> And the UI gives this error ("Unable to find user in ")

Looks like I added support for it in a local branch but never merged it, I'll make a PR for it in the next little bit

**Comment by cyian-1756** [comment]
@metaprime I added support for ripping from single posts and support for downloading slideshows (When ripping from single posts, not when ripping an entire account) in #239, but the regexs might still be a bit flaky
