### ISSUE TITLE
Code Cleanup: What is nbactions.xml?

### ISSUE THREAD

**Issue by metaprime** [RipMeApp/ripme#225]
https://github.com/RipMeApp/ripme/blob/master/nbactions.xml

@EraYaN who last edited this file -- do you know if this is needed?

**Comment by EraYaN** [comment]
It's a Netbeans project file for maven-based building if I recall correctly. Can easily be removed I think it should probably not have been committed,.

http://wiki.netbeans.org/Nbactions.xml

**Comment by metaprime** [comment]
@EraYaN ah, thanks. I'm not sure if anyone uses Netbeans on this project anymore. I've been updating .vscode project files for those who want to use that. There's also an eclipse .project file. I'm on the fence about whether any of that should be checked in...

**Comment by metaprime** [comment]
Anyway as for nbactions.xml, it has been removed. Thanks for the info. Closing this issue.
