### ISSUE TITLE
url_history populated even when "Save URLs only" is checked

### ISSUE THREAD

**Issue by metaprime** [RipMeApp/ripme#237]
* Ripme version: 1.6.13
* Java version: 1.8.0_151
* Operating system: Microsoft Windows [Version 10.0.15063]
* Exact URL you were trying to rip when the problem occurred: http://motherless.com/G4DAA18D
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

I interpret "Save URLs only" as a preview function. At any rate, the main goal of url_history is to prevent re-downloading content that has already been downloaded (and maybe renamed or deleted). "Save URLs only" does not benefit from url_history.

## Actual Behavior

* Check "Save URLs only"
* Rip
* Uncheck "Save URLs only"
* Rip again, nothing gets downloaded

**Comment by cyian-1756** [comment]
@metaprime This was fixed a while ago [by changing this if](https://github.com/RipMeApp/ripme/blob/6ed509aa06f4179f7c9652700e783b7707c97d15/src/main/java/com/rarchives/ripme/ripper/AbstractRipper.java#L199)
