### ISSUE TITLE
Broken site audit: FlickrRipper (flickr.com)

### ISSUE THREAD

**Issue by metaprime** [RipMeApp/ripme#243]
See src/test/java/com/rarchives/ripme/tst/ripper/rippers/FlickrRipperTest.java

Test page: https://www.flickr.com/photos/leavingallbehind/sets/72157621895942720/

**Comment by cyian-1756** [comment]
Looks like flickr now includes a block of JS with all the images on the page in it.

**Comment by cyian-1756** [comment]
After a bit pf digging it looks like flickr gives us an API key in the line `root.YUI_config.flickr.api.site_key = "$api_key";`. This should allow use to the REST api (https://api.flickr.com/services/rest) to get all the image data (date taken, link, description ect)
