### ISSUE TITLE
[Feature Request] Confirmation for clearing history.

### ISSUE THREAD

**Issue by KryptonicDragon** [RipMeApp/ripme#25]
* Ripme version: 1.5.2
* Java version (output of `java -version`): 1.8.0_131
* Operating system: Windows 10 64-Bit Home

It would be nice if the "clear" button in the history tab would ask for confirmation, to prevent accidentally clearing history.

**Comment by rautamiekka** [comment]
And a simple thing to implement, as well.

**Comment by dikshaa42** [comment]
i have implemented this feature :).

**Comment by metaprime** [comment]
@dikshaa42 Please open a pull request with your fix.

**Comment by cyian-1756** [comment]
This was added a ways back.
