### ISSUE TITLE
WordpressRipper: konradokonski.com previously supported but now cannot rip

### ISSUE THREAD

**Issue by metaprime** [RipMeApp/ripme#266]
* Ripme version: 1.6.13
* Java version: 1.8.0_151
* Operating system: Microsoft Windows [Version 10.0.15063]
* Exact URL you were trying to rip when the problem occurred: http://www.konradokonski.com/sawdust/
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

These links are in WordpressRipper.java:

http://www.konradokonski.com/sawdust/
http://www.konradokonski.com/wiory/

konradokonski.com is a wordpress site and we should be able to rip it.

## Actual Behavior

These sites are not supported by the ripper. ("No compatible ripper found")

**Comment by metaprime** [comment]
Removing confirmed tag because I probably don't know how this ripper was supposed to work. @cyian-1756 is this ripper working correctly? Which link should we use for testing?

**Comment by cyian-1756** [comment]
> is this ripper working correctly?

Nope, it should match http://www.konradokonski.com/sawdust/

> Which link should we use for testing?

Either or. The only difference between that should be that one's in English and the other in Polish

**Comment by metaprime** [comment]
@cyian-1756 Thanks

**Comment by cyian-1756** [comment]
@metaprime I can't repo this. Entering http://www.konradokonski.com/sawdust/comic/get-up/ into ripme rips the entire comic.
