### ISSUE TITLE
Erome error

### ISSUE THREAD

**Issue by chnc23** [RipMeApp/ripme#279]
* Ripme version: v1.7.2
* Java version: 1.8.0_31
* Operating system: windows 10
* Exact URL you were trying to rip when the problem occurred: https://www.erome.com/a/Ep1KuVGY
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Download all contents of the link (videos and images)

## Actual Behavior

Downloading https://www.erome.com/a/Ep1KuVGY
Rip complete, saved to C:\Users\Chnc\Downloads\rips\erome_Ep1KuVGY
Failed to load https://www.erome.com/a/Ep1KuVGY after 1 attempts
report.

**Comment by cyian-1756** [comment]
I can't repo this. Can you reach https://www.erome.com/a/Ep1KuVGY in a web browser?
