### ISSUE TITLE
eroshare links should download from mirror

### ISSUE THREAD

**Issue by cyian-1756** [RipMeApp/ripme#28]
The site spacescience.tech provides a mirror of eroshare (With content being hosted on the Internet Archive's Wayback Machine). The mirrors been up for ~ a month 

The eroshare ripper should both rip from spacescience.tech when given a eroshare link (https://eroshare.com/dt0kt9hu -> https://spacescience.tech/dt0kt9hu) and accept spacescience.tech links

**Comment by metaprime** [comment]
Looks like this mirror is down but there's a new one: via https://eroshae.com/ -- content also sourced from wayback machine. Example: https://eroshae.com/dt0kt9hu (NSFW)

**Comment by metaprime** [comment]
I see you already updated your PR with eroshae.

(copying my comment from the PR:)

> Also, rather than relying on a rehost, we could actually set up the redirects to internet archive / wayback machine on our own. There's basically two things to look for: the site pages (which are backed up in wayback machine) and the content, which is also hosted on the internet archive, and we can pull the link format directly out of a rehost like eroshae and extrapolate the redirect.
