### ISSUE TITLE
Change folder name in imaearn rip from imagearn_106465 the album name as find on the "tittle" metatag

### ISSUE THREAD

**Issue by chaos4455** [RipMeApp/ripme#280]
* Ripme version: 1.7.2
* Java version:  8.6? i think
* Operating system:  Windows Seven
* Exact URL you were trying to rip when the problem occurred: http://imagearn.com/gallery.php?id=106462
* Please include any additional information about how to reproduce the problem:

## Expected Behavior
I expect the RipMe can name the folder from: imagearn_106465 that are now to: Varias Da Boua 
(im a noob but i wannt to sugest to extract the name from the page title as i can see  "<title>Bambole Brasil - Image Earn</title>")

i will be very satisfacted because i have waited since 2009 to can rip these site. I thank in advice, for an earlyer problem that has solved by the team, thats occour when the site redir the images to a diferent host, but it is just a commentary. Thanks team for all the great work.

Detail the expected behavior here.

I expect that the name of folder can be brought by the page title in the website imagearn instead of the number of album like: imagearn_106465

## Actual Behavior

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Comment by chaos4455** [comment]
Deam team, only a question.
Is possible to ask a new improvement to support downloads from http://imgsrc.ru?

Thanks in advice one more time.

**Comment by EgorGornak** [comment]
Hello! Can i try do this task?

**Comment by cyian-1756** [comment]
@EgorGornak Go right ahead.

**Comment by cyian-1756** [comment]
This was fixed in 1.7.3
