### ISSUE TITLE
Suggestion: Add U18Chan to supported sites.

### ISSUE THREAD

**Issue by AnonFapperBoi** [RipMeApp/ripme#315]
* Ripme version: Latest one
* Java version: Latest Java
* Operating system: 10

Can you guys add U18Chan as a supported site? The link looks like this https://u18chan.com/board/u18chan/fur/topic/1276776  Is this doable by any chance? I would like to see this implemented in the next version.

**Comment by rautamiekka** [comment]
'Latest' is an invalid answer.

**Comment by metaprime** [comment]
Tracking in #38
