### ISSUE TITLE
Video link not stored in history file

### ISSUE THREAD

**Issue by elric29200** [RipMeApp/ripme#317]
* Ripme version: 1.7.6
* Java version: dunow
* Operating system: linux
* Please include any additional information about how to reproduce the problem:

If you remove all your download folders and ask for a "re-rip checked", it will download only new pictures not stored in the history files. That is what is expected. 
But it will also download all the videos. New ones but also old ones. At least from Instagram.
So i guess the video links are not stored in the history file and look always new to ripme.

**Comment by cyian-1756** [comment]
This was fixed a while ago
