### ISSUE TITLE
Cannot rip from tumblers containing sensitive media

### ISSUE THREAD

**Issue by Rivalz906** [RipMeApp/ripme#323]
* Ripme version: 1.7.6
* Java version: 1.8.0_144
* Operating system: Microsoft Windows [Version 6.3.9600]
* Exact URL you were trying to rip when the problem occurred: https://m8aa.tumblr.com/
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Get all images from tumbler blog.

## Actual Behavior

All images failed to rip, most likely because tumbler is marked as containing sensitive media.

Perhaps being able to input tumbler account credentials into the ripper could fix this?

**Comment by cyian-1756** [comment]
This was fixed in 1.7.8
