### ISSUE TITLE
Art Station support

### ISSUE THREAD

**Issue by singhs-apps** [RipMeApp/ripme#33]
* Ripme version: 1.5.2
* Java version (output of `java -version`): 
* Operating system: MacOs Sierra
* Exact URL you were trying to rip when the problem occurred: https://www.artstation.com/artist/yangqi917
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

the expected behavior is that it is supposed to download the files.

## Actual Behavior

"Can't rip this URL: com.rarchives.ripme.ripper.rippers (null) does not appear to be a valid package"

**Comment by metaprime** [comment]
This is a request for a new ripper. Closing with link to #38 (catch-all issue for requests).

Thanks for your request!
