### ISSUE TITLE
URL history no longer seems to be working

### ISSUE THREAD

**Issue by keokitsune** [RipMeApp/ripme#330]
* Ripme version: 1.7.7

recently i noticed that ripme has started to re download files that have already been downloaded and removed by duplicate detection. iv treed reverting to earlier versions but it continues to have this issue, the URL history is enabled and but the file that stores the URL list no longer updates with the new downloads, it seems to have stopped at 1377kb.  not sure why it no longer works, whether something has delinked the file to the program or if 1377kb is a set limit or something.

**Comment by cyian-1756** [comment]
Well that shouldn't happen. What OS are you on? What java version? Are you running ripme normally or in portable mode?

**Comment by keokitsune** [comment]
win 10, java is v8 (build 1.8.0_151-b12), no portable mode. i deleted the app data folder a little bit ago to reinstall the program and see if it starts working again, just haven't gotten to it yet. 

leading up to this i hadn't done anything different then normal, it just seemed to stop keeping track.

**Comment by cyian-1756** [comment]
Did you uncheck the "remember url history" checkbox?

**Comment by keokitsune** [comment]
no, its still checked

**Comment by rephormat** [comment]
@keokitsune Is this still an issue?

**Comment by rephormat** [comment]
@cyian-1756 no response from author.  Recommend closing.
