### ISSUE TITLE
Twitter "Protected Tweets" cant rip.

### ISSUE THREAD

**Issue by theaverageuser** [RipMeApp/ripme#331]
* Ripme version:
* Java version: 
* Operating system: 
* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

Failed to load https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=2crzy4yah&include_entities=true&exclude_replies=true&trim_user=true&include_rts=false&count=200 after 1 attempts

## Expected Behavior

Detail the expected behavior here.

## Actual Behavior

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Comment by cyian-1756** [comment]
Please fill out the issue template.

**Comment by tehloxely** [comment]
Here's an example. Windows 10. RipMe v1.7.59.
I am not following this person: https://twitter.com/littlekeish
RipMe's Error:
> Failed to load https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=littlekeish&include_entities=true&exclude_replies=true&trim_user=true&count=200&tweet_mode=extended after 1 attempts

**Comment by kevin51jiang** [comment]
@tehloxely 

If you read into what protected tweets are, they are tweets that only followers can see. However the ripme default API key (as far as I know) doesn't follow anyone and therefore cannot see any of the tweets that user made.

In order for you to rip protected tweets you need to:

1. Make your own account, then follow the specified user
2. Make an API key for that account, by following instructions [here](https://developer.twitter.com/en/docs/basics/authentication/guides/access-tokens.html)
3. Add that API key into the `rip.properties` file that ripme uses.

**Comment by cyian-1756** [comment]
I'm closing this as @kevin51jiang has pointed out this is something that can't be fixed on ripmes end
