### ISSUE TITLE
Tumblr ripper not working | Non-retriable status code 400

### ISSUE THREAD

**Issue by KryptonicDragon** [RipMeApp/ripme#336]
* Ripme version: 1.7.7
* Java version: 1.8.0_151
* Operating system: Microsoft Windows [Version 10.0.16299.98] (64-bit)

RipMe isn't downloading everything from any of the tumblr blogs I've used.

My normal use-case for RipMe is that I open it and hit "Re-rip checked" in the history tab every once-in-a-while, but I've noticed that it hasn't downloaded anything from any tumblr that was posted after October 9th.
I went to another computer that had never had RipMe used on it (also Windows 10), downloaded the latest version of RipMe from the GitHub releases page (v1.7.7), and tried a few tumblrs. I was met with a log filled with red text repeating "Non-retriable status code 400 while downloading". This happens with any tumblr link I give it.

**Comment by cyian-1756** [comment]
Can you post an example URL?

**Comment by cyian-1756** [comment]
This is pretty weird, hitting any of these links with wget or in a browser returns the image. I have no idea why ripme is only getting 400 errors

**Comment by cyian-1756** [comment]
For some weird reason downloading the images over https works fine, but using http returns a 400 error despite the fact that tumblr returns the non-https links to images

**Comment by onigumo1990** [comment]
I think this could be the same issue with the two issues I made:
[https://github.com/RipMeApp/ripme/issues/329](https://github.com/RipMeApp/ripme/issues/329)
[https://github.com/RipMeApp/ripme/issues/318](https://github.com/RipMeApp/ripme/issues/318)

Running wget or opening in browser works fine on the images that report errors, but I get the same error message reported here

**Comment by cyian-1756** [comment]
@onigumo1990 It must be a bug in ripme then

**Comment by Lyte3000** [comment]
It happens when the URL that it downloads images from has a space in it
