### ISSUE TITLE
Error download from imegearn

### ISSUE THREAD

**Issue by chaos4455** [RipMeApp/ripme#34]
Deam team.

Can we solve the issue from error to download from imagearn?

**Comment by cyian-1756** [comment]
What url are you trying to rip? Can you post ripmes log/the error you get?

**Comment by chaos4455** [comment]
Dear Friend,

The problem looks like related whith a web host change ou cache, or similar,
 because the link change to http://img.imagearn.com/imags/04032009/374916.jpg but when we go to the link, the link changes to http://images1.pornxs.com/imags/04032009/374916.jpg

i will be very glad and happy if the problem can be solved.

Thanks in advance team

Sorry for bad english


Original galery http://imagearn.com/gallery.php?id=18320


Here is the log

Downloading http://imagearn.com/gallery.php?id=18320
Downloading http://img.imagearn.com/imags/1236186509437.jpeg
Downloading http://img.imagearn.com/imags/1236186509152.jpeg
http://img.imagearn.com/imags/1236186509437.jpeg : Non-retriable status code 404 while downloading http://img.imagearn.com/imags/1236186509437.jpeg
Downloading http://img.imagearn.com/imags/123618650965.jpeg
http://img.imagearn.com/imags/1236186509152.jpeg : Non-retriable status code 404 while downloading http://img.imagearn.com/imags/1236186509152.jpeg
Downloading http://img.imagearn.com/imags/1236186509294.jpeg
http://img.imagearn.com/imags/123618650965.jpeg : Non-retriable status code 404 while downloading http://img.imagearn.com/imags/123618650965.jpeg
Downloading http://img.imagearn.com/imags/123618650977.jpeg
http://img.imagearn.com/imags/1236186509294.jpeg : Non-retriable status code 404 while downloading http://img.imagearn.com/imags/1236186509294.jpeg
Downloading http://img.imagearn.com/imags/1236186510291.jpeg
http://img.imagearn.com/imags/123618650977.jpeg : Non-retriable status code 404 while downloading http://img.imagearn.com/imags/123618650977.jpeg
Downloading http://img.imagearn.com/imags/1236186510558.jpeg
http://img.imagearn.com/imags/1236186510291.jpeg : Non-retriable status code 404 while downloading http://img.imagearn.com/imags/1236186510291.jpeg
Downloading http://img.imagearn.com/imags/1236186510224.jpeg
http://img.imagearn.com/imags/1236186510558.jpeg : Non-retriable status code 404 while downloading http://img.imagearn.com/imags/1236186510558.jpeg
Downloading http://img.imagearn.com/imags/1236186510450.jpeg
http://img.imagearn.com/imags/1236186510224.jpeg : Non-retriable status code 404 while downloading http://img.imagearn.com/imags/1236186510224.jpeg
Downloading http://img.imagearn.com/imags/1236186510634.jpeg
http://img.imagearn.com/imags/1236186510450.jpeg : Non-retriable status code 404 while downloading http://img.imagearn.com/imags/1236186510450.jpeg
Downloading http://img.imagearn.com/imags/1236186511556.jpeg
http://img.imagearn.com/imags/1236186510634.jpeg : Non-retriable status code 404 while downloading http://img.imagearn.com/imags/1236186510634.jpeg
Downloading http://img.imagearn.com/imags/1236186511147.jpeg
http://img.imagearn.com/imags/1236186511556.jpeg : Non-retriable status code 404 while downloading http://img.imagearn.com/imags/1236186511556.jpeg
Downloading http://img.imagearn.com/imags/1236186511664.jpeg
http://img.imagearn.com/imags/1236186511147.jpeg : Non-retriable status code 404 while downloading http://img.imagearn.com/imags/1236186511147.jpeg
Downloading next page
http://img.imagearn.com/imags/1236186511664.jpeg : Non-retriable status code 404 while downloading http://img.imagearn.com/imags/1236186511664.jpeg
Rip complete, saved to C:\Users\user\Desktop\rips\imagearn_18320

**Comment by cyian-1756** [comment]
Looks like they changed their image hosting address. I should have it fixed in the next few days

**Comment by chaos4455** [comment]
thanks for that.

**Comment by cyian-1756** [comment]
@chaos4455 I've made the PR the fix should be in one of the next few updates
