### ISSUE TITLE
Download only images on Instagram?

### ISSUE THREAD

**Issue by beefykitten** [RipMeApp/ripme#341]
Hello.

As per the title, I'd like the option to download only images on Instagram.  Assuming that it's even possible, would you consider making such an option available?

Thanks for your time.

**Comment by cyian-1756** [comment]
> would you consider making such an option available?

Yea it should be possible with some changes to the IG ripper

**Comment by thinkpad4** [comment]
I would very much like this too

**Comment by cyian-1756** [comment]
Can someone post an IG account that has both images and videos?

**Comment by thinkpad4** [comment]
Here you go, https://www.instagram.com/taylorswift/?hl=en

**Comment by thinkpad4** [comment]
@cyian-1756 Have you gotten this working?  I don't see a option in the latest release 1.7.10 unless I'm looking in the wrong place.

**Comment by cyian-1756** [comment]
@thinkpad4 I did get this working, but forgot to make a PR for it. I just made a PR for it (#378), it should be in ripme 1.7.11

**Comment by thinkpad4** [comment]
Sweet, looking forward to it.  Thanks

**Comment by cyian-1756** [comment]
As of 1.7.11 the IG ripper will only download images if you set the config option `instagram.download_images_only` to true (instagram.download_images_only = true) in rip.properties

**Comment by thinkpad4** [comment]
@cyian-1756 does it have to manually added?  I ran 1.7.11 and I didn't see a new checkbox in the config section of the program nor a entry in the rip.properties

**Comment by cyian-1756** [comment]
@thinkpad4 

> does it have to manually added?

Yes it does

>  I ran 1.7.11 and I didn't see a new checkbox in the config section of the program

That's because I can't fit any more checkboxes there without stretching the window

**Comment by thinkpad4** [comment]
@cyian-1756 Thanks for letting me know.  Thought I had messed something up.  Works GREAT.  Thanks again

**Comment by cyian-1756** [comment]
@thinkpad4 [There's also a page on ripme various config options and what they do](https://github.com/RipMeApp/ripme/wiki/Config-options)
