### ISSUE TITLE
Add more Tumblr api keys

### ISSUE THREAD

**Issue by cyian-1756** [RipMeApp/ripme#343]
We should add a few more tumblr api keys to ripme so that users don't run into 429 errors as often. I think having 5 total api keys would be enough

**Comment by rautamiekka** [comment]
Better make it unlimitedly iterative, so that you can add as many keys as you please.

**Comment by cyian-1756** [comment]
> Better make it unlimitedly iterative, so that you can add as many keys as you please.

I'm thinking of just putting all the keys in a list and then randomly choosing one of them

**Comment by YDdraigGoch** [comment]
Wasn't there, once upon a time, the ability for the user to use their own API key. I think it was with a config file? Also, I'm getting Error:null when I try to rip a blog. Is that related to everyone using one API key, or a separate issue? Thanks.

**Comment by cyian-1756** [comment]
@YDdraigGoch 

> Wasn't there, once upon a time, the ability for the user to use their own API key.

You can still do that. You just need to set `tumblr.auth` to your api key in the config file rip.properties 

> Is that related to everyone using one API key

Yup.

**Comment by YDdraigGoch** [comment]
Thanks for the quick response. My questions are sorted :P I didn't realise rip.properties was in my appdata folder when I was used to it being in the same file as the application. Changed to my API and the null error is no more.

**Comment by cyian-1756** [comment]
@YDdraigGoch 

If you need any more info we have a [wiki page](https://github.com/RipMeApp/ripme/wiki/Config-options) on ripmes various config options

**Comment by cyian-1756** [comment]
The api keys have been added so I'm closing this
