### ISSUE TITLE
I dont want it to create subfolder per downloaded image what to do ?

### ISSUE THREAD

**Issue by ShockvaWe** [RipMeApp/ripme#344]
I dont want it to create subfolder per downloaded image what to do ?

**Comment by ShockvaWe** [comment]
Why noone answers, am i so dumb ?

**Comment by cyian-1756** [comment]
> I dont want it to create subfolder per downloaded image what to do ?

Ripme creates a new folder for every album it rips, there's no way to change that at this time.

**Comment by ShockvaWe** [comment]
Which code file is about it ? Maybe i can modify.


21 Ara 2017 02:29 tarihinde "cyian-1756" <notifications@github.com> yazdı:

**Comment by cyian-1756** [comment]
> Which code file is about it ? Maybe i can modify.

I believe it's `abstractRipper.java`
