### ISSUE TITLE
Can I use this great program to backup all my own imgur images?

### ISSUE THREAD

**Issue by Maveee** [RipMeApp/ripme#345]
Hi, first of all love this program.

Was wondering if it was possible to scrape all my uploaded imgur images? (also those **not in albums**)
Got 75k images on there and would like a way to backup them.

Thanks!

**Comment by cyian-1756** [comment]
> Got 75k images on there and would like a way to backup them.

AFAIK ripme can only download ~300 images from a user account (Because imgur doesn't list all images for unauthed users)

You might want to check out some program that uses the imgur api

**Comment by rautamiekka** [comment]
If you can **view every pic on a single page at once in your browser (either in full form or can easily manipulate the links into full form)** _while authed_ **you _in theory_ could** load the whole HTML which links to the files, which you can then save, process and then download the pics.

But given it's 75k pics it takes an age to browse, and costs tons of data. Not to mention RAM ...

If the browser does any kinda memory saving on the HTML it won't work that easily ...

**Comment by jwshields** [comment]
You can download a copy of your imgur archive through your settings page on imgur itself.
https://imgur.com/account/settings
Click on "Download account images"

**Comment by Maveee** [comment]
@jwshields unfortunately this feature stops working once your total amount of wallpapers is in the few thousands...

@rautamiekka thanks, I can do it this way although I will still need to click next page 1218.75 times 

@cyian-1756 any suggestions to what programs I should check?

**Comment by cyian-1756** [comment]
@Maveee No idea, I'd try searching for a imgur exporter or something like that

**Comment by rautamiekka** [comment]
There's also a native, direct way to DL an album of yours by going to the album listing and clicking the gear icon in top right corner of the album.

Dunno how many pics that supports ...

**Comment by rautamiekka** [comment]
There's an export-into-PDF script made in Ruby: https://github.com/hdabrows/imgur_album_exporter/blob/master/imgur_album_exporter.rb

**Comment by cyian-1756** [comment]
I'm closing this as the question has been answered.
