### ISSUE TITLE
Subreddit ripme Error "Failed to Load"

### ISSUE THREAD

**Issue by JamesBond00072** [RipMeApp/ripme#346]
* Ripme version: v1.7.8
* Java version: 8
* Operating system: Windows 10: Version 1703
* Exact URL you were trying to rip when the problem occurred: https://www.reddit.com/r/HentaiPetgirls/
* Please include any additional information about how to reproduce the problem: I copied and pasted the link into the "URL" box. Then I clicked "Rip."

## Expected Behavior

I expected for pictures or files to start copying over into the linked rip save directory

## Actual Behavior

The exact error "Failed to load https://www.reddit.com/r/HentaiPetgirls/.jsn after 1 attempts"

**Comment by cyian-1756** [comment]
This is working fine on my end, it was probably just a network issue
