### ISSUE TITLE
DeviantArt pic description files aren't written since RipMe 1.7.3

### ISSUE THREAD

**Issue by rautamiekka** [RipMeApp/ripme#350]
* Ripme version: 1.7.3+
* Java version:  Oracle Java SE 8 Update 152 x64
* Operating system:  Window$ 7 Ultimate SP1 x64
* Exact URL you were trying to rip when the problem occurred: Any, but (so far SFW) https://avebellez.deviantart.com/ used while testing #349
* Please include any additional information about how to reproduce the problem: 1.7.3, 1.7.7 and 1.7.8 (the tested offending versions) all show the same. 1.7.2 works fine.

## Expected Behavior
The text file having same name as the pic should be written containing the description for the pic.

## Actual Behavior
The file doesn't get written at all.

**Comment by cyian-1756** [comment]
I can't repro this, you mind posting the log?

**Comment by rautamiekka** [comment]
I'll get back on this when it rehappens cuz I'm unable to repro as well; I've been using 1.7.2 to bypass the problem, so dunno if that has had an effect.
