### ISSUE TITLE
reddit user case sensitive

### ISSUE THREAD

**Issue by albaldi** [RipMeApp/ripme#353]
* Ripme version: 1.7.8
* Java version: openjdk version "1.8.0_144"
* Operating system: archlinux
* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

https://www.reddit.com/user/sexyflowerwater  
https://www.reddit.com/user/SexyFlowerWater  
Are the same redditors, but ripme put them in different directory:  
reddit_user_sexyflowerwater  
reddit_user_SexyFlowerWater

## Expected Behavior

ripme should be case insensitive or get the username in some proper way (author in json?)

## Actual Behavior

ripme treat sexyflowerwater and SexyFlowerWater as different redditor.

**Comment by rephormat** [comment]
Could this be resolved simply by forcing lowercase?

**Comment by rephormat** [comment]
@cyian-1756 Fixed with PR #400.  Recommend close.
