### ISSUE TITLE
Gfycat url variant not parsing

### ISSUE THREAD

**Issue by GarryDoes** [RipMeApp/ripme#356]
So when users post their gfycat links to reddit,  a lot of the time they copy the URL from the 'details' section that each video has.  The link would look like this ;
gfycat.com/gifs/detail/DetailedExemplaryBlackpanther

instead of this 

gfycat.com/DetailedExemplaryBlackpanther

As you can see the difference is just the '/gifs/detail/'  part. The link without the '/gifs/detail/' part will download as expected.  The link with the '/gifs/detail/' goes unrecognised  and they just get ignored.   

P.S. Its just a lucky coincidence that the word 'Detailed' is one of the randomly chosen words that got generated this time.

**Comment by kevin51jiang** [comment]
I dunno how to use gitHub properly, but I'll try to fix it.

**Comment by kevin51jiang** [comment]
@cyian-1756 

Close this issue?
