### ISSUE TITLE
Some gfycat doesn't work

### ISSUE THREAD

**Issue by fearme123123** [RipMeApp/ripme#361]
#* Ripme version: Latest
* Java version:  1.8
* Operating system: 
* Exact URL you were trying to rip when the problem occurred: https://gfycat.com/gifs/detail/FlickeringMassiveBaiji {NSFW}
* Please include any additional information about how to reproduce the problem:

No idea, I just noticed that a lot of the videos and gifs weren't downloading-

## Expected Behavior
Supposed to download the videos

## Actual Behavior
Error message: http://prntscr.com/ht46pq

**Comment by kevin51jiang** [comment]
@cyian-1756 
Close this issue?
