### ISSUE TITLE
hentai.cafe regex doesn't match title with a 0 in them

### ISSUE THREAD

**Issue by wankio** [RipMeApp/ripme#366]
* Ripme version: 1.7.9
 
https://hentai.cafe/fu-ta-tsun-sis-dere-sis/ this work
https://hentai.cafe/fu-ta-120-interested/ this not work [fu-ta] 120% Interested , i think 120% is the problem

and autorip from clipboard is not working too

**Comment by cyian-1756** [comment]
This was fixed in 1.7.10

**Comment by wankio** [comment]
autorip from clipboard still not working
