### ISSUE TITLE
filename length issues

### ISSUE THREAD

**Issue by ravenstorm767** [RipMeApp/ripme#369]
* Ripme version: 1.7.9
* Java version: version 8 update 144
* Operating system: windows 10 laptop and windows 8.1 desktop
* Exact URL you were trying to rip when the problem occurred: 8muses.com in particular
* Please include any additional information about how to reproduce the problem: would like to request options to shorten or customize file names of downloaded files

## Expected Behavior

want to download galleries from 8muses with manageable filenames

## Actual Behavior

it keeps downloading files with extremely long filenames. for now i can remedy it by going to every folder and doing a batch rename but id like to have an option to choose whether output files use the original filenames or just a simple naming system like 1,2,3,4 and etc. according to their position in the gallery

**Comment by cyian-1756** [comment]
It should be possible to add a config option that will download 8muse images with just the image number as the name

**Comment by metaprime** [comment]
Can someone post a URL so that others can repro and test fixes?

**Comment by rephormat** [comment]
@metaprime @cyian-1756 
Recommend closing this if @ravenstorm767 does not respond with details to clean up abandoned issues.  Thoughts?

**Comment by cyian-1756** [comment]
> Thoughts?

Leave it open. I've run into the same issue with 8muses

**Comment by bmitchell1** [comment]
you can try this url

https://www.8muses.com/comics/album/Renderotica-Comics/Supafly/Hollys-Freaky-Encounters-Night-Shift-Nurse

I even rip to c:\rips and with the filename being
C:\rips\8muses_Renderotica_Comics\Hollys-Freaky-Encounters---Night-Shift-Nurse001_GPibTgX+kYukj9M0RB6HMHRsOKARt70LwqkgqFL7D26pGBesA5WIKsTOs3PM5EXbU8IBwxtePVF9pj7OTou5ZsnpjYx8i56Z2NqTnSvC7rTKX9BHQY0kT4Wiq62JLw9q-kDpHb0EmCXfvfD9jXmldokEbDw0FMywgm25Q+LYaID8pc-g3ephrYfpZGsyB+NG.jpg

It doesn't open properly in some imageviewers until I manually shorten the names.

**Comment by cyian-1756** [comment]
@ravenstorm767 

I've managed to fix this issue, it should be in ripme 1.7.25/1.8.0

@bmitchell1 

Thanks for the link!

**Comment by cyian-1756** [comment]
This was fixed in 1.7.25 to enable it add "8muses.use_short_names = true" to your rip.properties file
