### ISSUE TITLE
(Converted from comment) Imagebam not working

### ISSUE THREAD

**Issue by metaprime** [RipMeApp/ripme#37]
Converted from: https://github.com/4pr0n/ripme/issues/502#issuecomment-306664381 by @Flip32 

> Hi, It seems Imagebam it's not working! And when does, the pics come smaller.
> Can you help me?
>
> ex.: http://www.imagebam.com/gallery/72c5utvqv44wcqnkc9vzapm5yck8j1cr

**Comment by cyian-1756** [comment]
I can't repo this. Ripping http://www.imagebam.com/gallery/72c5utvqv44wcqnkc9vzapm5yck8j1cr seems to rip the entire album from all pages and all the images are full sized

**Comment by metaprime** [comment]
Thanks for investigating. I'll try it also a bit later and if I can't repro I'll close this.

**Comment by metaprime** [comment]
Seems to work for me (tried a quick rip urls-only). Verifying whether the images are full size or not will take a bit closer of a look.

**Comment by cyian-1756** [comment]
I've tested this again and I am able to rip the whole album and all the images are downloaded in their full size. I'm closing this as can't repo
