### ISSUE TITLE
hentai-foundry need account to download full Pictures

### ISSUE THREAD

**Issue by wankio** [RipMeApp/ripme#373]
* Ripme version: 1.7.9

ex : http://www.hentai-foundry.com/pictures/user/gaiidraws
It only downloaded 67/78 pictures without account

and ripme should getlink from user profile
http://www.hentai-foundry.com/user/BloadEsefo/profile
to
- http://www.hentai-foundry.com/pictures/user/BloadEsefo
- http://www.hentai-foundry.com/pictures/user/BloadEsefo/scraps

**Comment by cyian-1756** [comment]
Can you link to the images not being downloaded?

**Comment by wankio** [comment]
http://www.hentai-foundry.com/pictures/user/gaiidraws/559026/Patron-reward-sketch-12 
http://www.hentai-foundry.com/pictures/user/gaiidraws/551016/Goth-Girl
...
