### ISSUE TITLE
autorip from clipboard not working on hentai.cafe

### ISSUE THREAD

**Issue by wankio** [RipMeApp/ripme#380]
* Ripme version: lastest

autorip from clipboard not working on hentai.cafe, other links work pretty good, i dont know why...or it's because .cafe domain ?

**Comment by mariobrosse** [comment]
Not working anywhere !!!!

**Comment by cyian-1756** [comment]
What OS are you using? What version of ripme? What version of Java? Can you provide a link that isn't autoripping?

**Comment by wankio** [comment]
1.7.11
windows 10 64bit
lastest version of java

all the links on hentai.cafe

**Comment by wankio** [comment]
so clipboard feature will be supported in the future ?

**Comment by cyian-1756** [comment]
@wankio 

>  so clipboard feature will be supported in the future ?

tbh I have no idea why it isn't working right now. I'll get on fixing it in the next little while

**Comment by rephormat** [comment]
Is this still an issue?  I can not reproduce.  I'm running Windows 10 Pro.

**Comment by cyian-1756** [comment]
@rephormat 

I can repo this on ubuntu 16.04 with ripme 1.7.13 using the link https://hentai.cafe/nanao-yukiji-personalized-guidance/

**Comment by rephormat** [comment]
@cyian-1756 

Interesting.  Not sure why though.

**Comment by wankio** [comment]
so it can fixed ?

**Comment by cyian-1756** [comment]
@wankio It seems like can be fixed, I'll get on it today

**Comment by cyian-1756** [comment]
@wankio I've managed to fix it, the fix should be out in the 1.7.17 update

**Comment by cyian-1756** [comment]
The issue was this monster of a regex, which doesn't match all possible domains

```
"\\b(((ht|f)tp(s?)://|~/|/)|www.)" +
"(\\w+:\\w+@)?(([-\\w]+\\.)+(com|org|net|gov" +
"|mil|biz|info|mobi|name|aero|jobs|museum" +
"|travel|[a-z]{2}))(:[\\d]{1,5})?" +
"(((/([-\\w~!$+|.,=]|%[a-f\\d]{2})+)+|/)+|\\?|#)?" +
"((\\?([-\\w~!$+|.,*:]|%[a-f\\d{2}])+=?" +
"([-\\w~!$+|.,*:=]|%[a-f\\d]{2})*)" +
"(&(?:[-\\w~!$+|.,*:]|%[a-f\\d{2}])+=?" +
"([-\\w~!$+|.,*:=]|%[a-f\\d]{2})*)*)*" +
"(#([-\\w~!$+|.,*:=]|%[a-f\\d]{2})*)?\\b");
```

It should be changed to match anything starting with "http://" or "https://" and ending in .*

**Comment by wankio** [comment]
oh it's so fast.. thank you

..... some gallery have chapter like this : https://hentai.cafe/saitom-saitom-box/ ....but seem like it only can download first chapter

**Comment by cyian-1756** [comment]
> but seem like it only can download first chapter

yup. I'll add support for multi chapter ripping in the next few days
