### ISSUE TITLE
Auto stop IG rip after ## of files skipped?

### ISSUE THREAD

**Issue by beefykitten** [RipMeApp/ripme#382]
Another feature request, if you're able/willing:

After ripping an IG feed, I usually wait a couple days then re-rip it to grab new content.  What I'd like is for the ripper stop automatically after it begins to hit files already downloaded in previous rips.  Allowing the user to set the number of collisions before stopping would be preferred, but certainly isn't mandatory.

I hope that makes sense to someone other than just me.

Thanks for your time.

**Comment by cyian-1756** [comment]
> What I'd like is for the ripper stop automatically after it begins to hit files already downloaded in previous rips

This should be pretty easy to add.

> I hope that makes sense to someone other than just me.

It does

**Comment by cyian-1756** [comment]
As of 1.7.21 this is possible by setting the "history.end_rip_after_already_seen" option in rip.properties. 

Example: Adding "history.end_rip_after_already_seen = 5" to your rip.properties will cause ripme to end the current rip after it hits 5 urls that are already downloaded

[See here for all of ripmes config option](https://github.com/RipMeApp/ripme/wiki/Config-options)
