### ISSUE TITLE
Question - How is the Queue used?

### ISSUE THREAD

**Issue by vile80r** [RipMeApp/ripme#386]
* Ripme version: 1.7.12
* Java version: 8 update 51
* Operating system: Windows 10 Pro

The app is working great for me. Good work. My only question is what the Queue area should do? I was thinking that it may work similar to some data mining programs I've used in the past. Essentially it allowed me to write a list of URLs I wanted to rip but I can't seem to write in that area or do anything.

**Comment by vile80r** [comment]
I figured out how to use the Queue. Just keep pasting in urls and click Rip button and it adds the url to the queue. 

Being able to paste a list directly into the Queue would be more intuitive tho

**Comment by cyian-1756** [comment]
> Being able to paste a list directly into the Queue would be more intuitive tho

I agree
