### ISSUE TITLE
RipMe only rips the first couple hundred images from twitter account

### ISSUE THREAD

**Issue by ModokiMokona** [RipMeApp/ripme#390]
* Ripme version: 1.7.14
* Java version: 1.8.0_151
* Operating system: Windows version 6.1.7601
* Exact URL you were trying to rip when the problem occurred: https://twitter.com/tkmiz/
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

RipMe downloads all the images posted on the twitter account.

## Actual Behavior

RipMe downloads the first 291 images, then shows "rip complete".

**Comment by ItsKevin16** [comment]
It also fails to download pictures that are posted from the same tweet. It also doesn't download all the videos.

**Comment by Norithiel** [comment]
For me it can download multiply pictures from the same tweet, but can't donwload pics from replies (even self-replies). For example there 4 pics in one tweet and 4 more pics in the reply for this tweet by the same user. And ripme doesn't see the pics in the answer.

Ripme version: 1.7.14

**Comment by Hydrobolt** [comment]
I've had this same issue since November. Only downloading 5 of +1000

**Comment by perridan** [comment]
same issue to me [confirmed]

**Comment by cyian-1756** [comment]
This should be fixed in 1.7.53, if anyone wants to test it and confirm that would be great

**Comment by tarantinosaur** [comment]
It's giving me this 

> error: jsonobject["bitrate"] not found

**Comment by cyian-1756** [comment]
@tarantinosaur 

Looks like I forgot to push all my changes, I should have a fix out later today
