### ISSUE TITLE
when trying to download any album they all turn into text.url files 

### ISSUE THREAD

**Issue by Shulkguy15** [RipMeApp/ripme#395]
* Ripme version:1.7.13
* Java version: 
* Operating system: 
* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Detail the expected behavior here.

## Actual Behavior

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Comment by kevin51jiang** [comment]
Can you please add/finish the template with all the information? 

We can't fix it if we don't know what your situation is. :P

**Comment by kevin51jiang** [comment]
Can you please add/finish the template with all the information? 

We can't fix it if we don't know what your situation is. :P

**Comment by Shulkguy15** [comment]
Sorry i forgot(im new here)

**Comment by kevin51jiang** [comment]
@Shulkguy15 

Can you tell us what operating system you were running, what url you were trying to download, and what Java version you were using? 

Thanks!

**Comment by Shulkguy15** [comment]
I fixed it now

**Comment by aaether32323** [comment]
It doesn't look like you fixed it on my end?

**Comment by Shulkguy15** [comment]
yah i was going to do that sorry for the trouble

**Comment by cyian-1756** [comment]
@Shulkguy15 Is this still an issue?

**Comment by rephormat** [comment]
@cyian-1756 no response from author.  Recommend closing.
