### ISSUE TITLE
Cannot rip Pixiv.net galleries (nsfw)

### ISSUE THREAD

**Issue by Moxfi** [RipMeApp/ripme#399]
* Ripme version: 
1.7.14

* Java version: 
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

* Operating system: 
Microsoft Windows [Version 10.0.15063]

* Exact URL you were trying to rip when the problem occurred:
NSFW - https://www.pixiv.net/member_illust.php?id=361249

* Please include any additional information about how to reproduce the problem:
Attempting to rip any Pixiv.net results in "No compatible ripper found"

## Expected Behavior
Expected a working rip, but Pixiv isn't supported yet.

## Actual Behavior
Can't rip the gallery.

**Comment by kevin51jiang** [comment]
Probably add this to #38. Aggregated lists make it easier to track.

**Comment by metaprime** [comment]
Closing as it is now linked to #38.
