### ISSUE TITLE
xHamster Gallery Ripper broken as of 2017-06-09

### ISSUE THREAD

**Issue by Demiglitch** [RipMeApp/ripme#4]
As seen in the old issue notification [here](https://github.com/4pr0n/ripme/issues/575), xHamster Gallery ripping no longer works due to the URL changing.

>  jimbotomato commented 15 days ago
> Previously:
> xha*****.com/photos/gallery/@@numbers@@/@@name@@.html
> 
> Now:
> xha******.com/photos/gallery/@@name@@-@@numbers@@

**Comment by lukepayne** [comment]
I've got a fix for this, but the PR is on the old repo. Awaiting feedback on whether it can be moved across.

**Comment by metaprime** [comment]
Merged as RipMeApp/ripme@cfab32d
