### ISSUE TITLE
Make VSCO ripper support profiles

### ISSUE THREAD

**Issue by kevin51jiang** [RipMeApp/ripme#402]
* Ripme version: Current
* Java version:  All
* Operating system:  All
* Exact URL you were trying to rip when the problem occurred: n/a
* Please include any additional information about how to reproduce the problem: n/a

## Expected Behavior

When creating VSCO ripper, it was based on HTML Ripper. However, it seems like the folks at [this project](https://github.com/HuggableSquare/vsco-dl) seem to have a VSCO ripper working for profiles in Ruby. 

Since it uses JSON (and I don't understand it), is there anyone who would like to implement full profile ripping?

## Actual Behavior

Cannot rip VSCO profiles.

**Comment by thinkpad4** [comment]
@cyian-1756 any progress on implementing this?

**Comment by cyian-1756** [comment]
@kevin51jiang 

> Ripme version: Current

Try to avoid putting current as the ripme version, because ripme tends to update pretty often

@thinkpad4 

> any progress on implementing this?

I've not even looked into it yet, however it is next on my todo list

**Comment by thinkpad4** [comment]
Sweet, looking forward to it

**Comment by cyian-1756** [comment]
I think I have this working in #657 does anyone have a link to a large (2000+ image) profile so I can test the multi-page support?

**Comment by kevin51jiang** [comment]
https://vsco.co/chouindy/images/1
