### ISSUE TITLE
[NSFW] Bugs in some of Luscious' Galleries

### ISSUE THREAD

**Issue by flamingheart95** [RipMeApp/ripme#404]
* Ripme version: 1.7.14
* Java version: Ver 8 Update 161 (build 1.8.0_161-b12)
* Operating system: WIn 10 ver.1703 OS build 15063.0 64 bit
* Exact URL you were trying to rip when the problem occurred: https://luscious.net/albums/blowjobs-4_92769/ 
* There are a few of them in this domain that doesn't download correctly. Ripme only catch 1 Image or not full album.

Logs:
Downloading https://luscious.net/albums/blowjobs-4_92769/
Downloading next page
Downloading https://cdnio.luscious.net/Shadezy/79/lusciousnet_lusciousnet_blow-290_204796122.jpg
Downloaded .\rips\luscious_blowjobs-4_92769\001_lusciousnet_lusciousnet_blow-290_204796122.jpg
Rip complete, saved to C:\Users\Le\Desktop\Ripme\rips\luscious_blowjobs-4_92769

**Comment by flamingheart95** [comment]
I did a few more tries and some of them just not working proberly:
luscious.net/albums/blowjob-hentai_114246/
Logs:
Downloading http://luscious.net/albums/blowjob-hentai_114246/
Already downloaded https://cdnio.luscious.net/pignon153/65/lusciousnet_lusciousnet_yzxkey077_551271824.png
Downloading next page
Already downloaded https://cdnio.luscious.net/pignon153/517/lusciousnet_lusciousnet_yzxkey076_788239748.png
Downloading next page
Already downloaded https://cdnio.luscious.net/pignon153/262/lusciousnet_lusciousnet_p0010_2046229205.1024x0.jpg
Downloading next page
Already downloaded https://cdnio.luscious.net/pignon153/932/lusciousnet_lusciousnet_p0007_851738225.jpg
Downloading next page
Already downloaded https://cdnio.luscious.net/pignon153/253/lusciousnet_lusciousnet_img532_1310171246.1024x0.png
Downloading next page
Rip complete, saved to C:\Users\Le\Desktop\Ripme\rips\luscious_blowjob-hentai_114246

**Comment by hyperju1ce31** [comment]
could fix the problem?
