### ISSUE TITLE
Tumblr rate limit has been exceeded

### ISSUE THREAD

**Issue by Moxfi** [RipMeApp/ripme#405]
* Ripme version: v1.7.14

* Java version: 
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

* Operating system: Microsoft Windows [Version 10.0.15063]

* Exact URL you were trying to rip when the problem occurred: bbc-chan.tumblr.com (NSFW)

* Please include any additional information about how to reproduce the problem:
Attempting to rip bbc-chan.tumblr.com results in:
Downloading http://api.tumblr.com/v2/blog/bbc-chan.tumblr.com/posts/photo?api_key=JFNLu3CbINQjRdUvZibXW9VpSEVYYti[REDACTED]&offset=0
Tumblr rate limit has been exceeded
Rip complete, saved to <path>\rips\tumblr_bbc-chan.tumblr.com

## Expected Behavior

Expected to be able to rip the tumblr after changing to my own tumblr-key in rip.properties

## Actual Behavior

Tumblr rate limit still exceeded.

I'd like to know if my method of changing the key was the correct idea, despite it not working

**Comment by farid-fari** [comment]
@cyian-1756 so how does one change the API key correctly? I'm having the same issue here

**Comment by cyian-1756** [comment]
@Moxfi Any update?

**Comment by cyian-1756** [comment]
I'm closing this @Moxfi if this is still an issue leave a comment and I'll reopen it

**Comment by Moxfi** [comment]
Hi! Sorry for not updating earlier - I need to change my notif. settings.

"Changing the API key should've worked. Is the api key in the error message your api key?"
-Yes, hence the [REDACTED]

Ripping "bbc-chan.tumblr.com" works right now (currently downloading and succeeding in each file), so I can't really give more information on the issue. I've updated RipMe to v1.7.19 few days ago, so I'm not sure if I'm running with your dev API key or mine - does the automatic update change the key to your dev API or keep mine? Didn't pull Ripme.jar apart since everything seems to be okay for now.

You can keep the issue closed as it has resolved itself mysteriously.

**Comment by cyian-1756** [comment]
> does the automatic update change the key to your dev API or keep mine?

Updates shouldn't change the api key.

**Comment by juanspeed** [comment]
Hi, I have the same problem. When I want to download from tumblr, it says "Tumblr rate limit has been exceeded"

**Comment by cyian-1756** [comment]
@juanspeed Are you using your own api key or one of ripmes default keys?

**Comment by juanspeed** [comment]
@cyian-1756  I'm using the default keys.

**Comment by cyian-1756** [comment]
@juanspeed 

>  I'm using the default keys.

Then you're going to run into rate limit issues. If you want to download from tumblr without running into that you need to make an account and get your own api keys

**Comment by fernandezh1983** [comment]
hi...how can i fix this issue? I am having the same problem.. :(

i am not sure how to apply for the api key as there are questions in the tumblr form that I dont know what answers to provide for

**Comment by cyian-1756** [comment]
> i am not sure how to apply for the api key as there are questions in the tumblr form that I dont know what answers to provide for

@fernandezh1983 

Which questions?

**Comment by Hrxn** [comment]
Try the steps listed here: 
https://github.com/mikf/gallery-dl/blob/master/docs/configuration.rst#extractortumblrapi-key--api-secret

**Comment by myt00** [comment]
> 
> 
> Try the steps listed here:
> https://github.com/mikf/gallery-dl/blob/master/docs/configuration.rst#extractortumblrapi-key--api-secret

where and how to write key? rip.properties? there only "tumblr.auth" line. no line for secret key.
