### ISSUE TITLE
No compatible ripper

### ISSUE THREAD

**Issue by Thorazin** [RipMeApp/ripme#407]
* Ripme version: 1.7.14
* Java version:  9.0.4 +11
* Operating system:  macOS 10.13.4 beta 1
* Exact URL you were trying to rip when the problem occurred: https://www.pornhub.com/view_video.php?viewkey=ph5a4e7d8a6d2b8
* Please include any additional information about how to reproduce the problem: I know I was ripping select videos before from pornhub, now I get an error message telling me I have no compatible ripper

## Expected Behavior
Detail the expected behavior here. I expected it to begin downloading the video.

## Actual Behavior
Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.  Error message
![screen shot 2018-02-01 at 7 01 40 pm](https://user-images.githubusercontent.com/36058075/35711407-5f4da13e-0782-11e8-9a47-47f90c9b7ef9.png)

**Comment by kevin51jiang** [comment]
Confirmed. Doesn't work with any other video URLs too (or so it seems).

**Comment by kevin51jiang** [comment]
Maybe the whole ripper needs a redo? (The bulk of the code was written in 2014, so some changes might be necessary.

**Comment by tehloxely** [comment]
Youtube-DL would be a better option for downloading videos like this https://github.com/rg3/youtube-dl
