### ISSUE TITLE
8Muse Archives

### ISSUE THREAD

**Issue by Oni1314** [RipMeApp/ripme#409]
* Ripme version:
* Java version: 
* Operating system: 
* www.8muses.com/comix
* Please include any additional information about how to reproduce the problem:
just try to rip some lage Archives like Ferres
https://www.8muses.com/comix/album/BroadSword-Comics/Tarot-Witch-of-the-Black-Rose

## Expected Behavior
Rip the Archif and give short filenames

## Actual Behavior

Large archives stops ripping with error *null*
Filenames are so long I can not even rename them
Archives did not get riped compleatly

**Comment by cyian-1756** [comment]
The 8muses ripper is a bit of a hack and should largely be rewritten once #313 gets merged

**Comment by Oni1314** [comment]
ok. thank to know.

**Comment by cyian-1756** [comment]
@Oni1314 

I'm rewriting the 8muses ripper, can you post some albums that produce null errors/don't download competely?

**Comment by Oni1314** [comment]
https://www.8muses.com/comix/album/DmitrysFuta_com-Art
https://www.8muses.com/comix/album/Fansadox-Comics

can you also loo into the problem with the long filenames?

**Comment by cyian-1756** [comment]
> can you also loo into the problem with the long filenames?

That's next on my list, it should be easily fixed

**Comment by cyian-1756** [comment]
After some more looking it seems that it will take a bit of work to fix the long filename issues, but the other issues are fixed in #417

**Comment by cyian-1756** [comment]
@Oni1314 the 1.7.15 fixed most of these issue aside from the long filename issue

**Comment by Oni1314** [comment]
@cyian-1756 Thanks.
Thansk for the update, I will try it out an report if someting makes problems.
The file name are really a pain. sometimes I canßt even rename them.

**Comment by Oni1314** [comment]
@cyian-1756
I tried it and it gives me the following error

Rip complete, saved to F:\RM Down\8muses_DmitrysFuta.com_Art
null
Downloading https://www.8muses.com/comix/album/DmitrysFuta_com-Art/Erotic
Downloading https://www.8muses.com/comix/picture/DmitrysFuta_com-Art/Erotic/476
Rip complete, saved to F:\RM Down\8muses_DmitrysFuta.com_Art_Erotic
null
Downloading https://www.8muses.com/comix/album/DmitrysFuta_com-Art/Erotic
Downloading https://www.8muses.com/comix/picture/DmitrysFuta_com-Art/Erotic/476
Rip complete, saved to F:\RM Down\8muses_DmitrysFuta.com_Art_Erotic
null

**Comment by cyian-1756** [comment]
> https://www.8muses.com/comix/album/DmitrysFuta_com-Art/Erotic

It looks like this is failing because it contains sub albums and images, I'll get on fixing it

**Comment by cyian-1756** [comment]
@Oni1314 1.7.16 should fix the issues with https://www.8muses.com/comix/album/DmitrysFuta_com-Art/Erotic
