### ISSUE TITLE
RipMe tells me the photos already exist, and doesn't download them; but the photos don't exist, and were never downloaded. 

### ISSUE THREAD

**Issue by JamesSampsan** [RipMeApp/ripme#427]
* Ripme version: 1.7.17
* Java version: 
* Operating system:  Win10
* Exact URL you were trying to rip when the problem occurred: 4Chan HR threads, Imagefap, and more
* Please include any additional information about how to reproduce the problem:
Honestly not sure on how to reproduce the problem. 

## Expected Behavior

Detail the expected behavior here.

## Actual Behavior

I'll put in a 4chan HR thread or Imagefap gallery, and it will say it downloaded the items, but clicking the "open folder" button does nothing. The photos just don't exist. Then when I try and re-rip the gallery, RipMe orange-errors and tells me the photo already exist in a location. I've searched the filename, and where RipMe tells me it downloaded the image, but it's not there. Reinstalling RipMe and clearing the history don't seem to fix the problem. 

Sometimes, it will get the "new pictures" just fine, but RipMe never saved the previous pictures. For example, I'll run RipMe, and it will say it downloaded 100 images, but the folder and pictures don't exist. Then I try and re-rip the URL to get everything and it will tell me they already exist and it didn't download. I then re-rip the URL a few days later after more pictures have been posted, and it will download the new images just fine, but still not download the previous non-existent files.

 Changing the save directory and re-ripping seems to download all the images, but still wish there was a feature to "forget" what it downloaded in the past.

**Comment by cyian-1756** [comment]
There should be a file called "url_history.txt" (I believe it's in app_data\ripme), delete that file and try again.

**Comment by rephormat** [comment]
@JamesSampsan Is this resolved now?

**Comment by rephormat** [comment]
@cyian-1756 No response from Author.  Recommend closing.

**Comment by JamesSampsan** [comment]
Sorry, I don't check my email / Github very often. 

Deleting the url_history.txt seems to have fixed the problem for now, but I only ran RipMe a few times over the past few days.
