### ISSUE TITLE
Motherless ripper hasn't worked for many updates.

### ISSUE THREAD

**Issue by Puxta** [RipMeApp/ripme#428]
* Ripme version:  1.3+
* Java version: Says completed, doesn't download files.
* Operating system: win 10
* Exact URL you were trying to rip when the problem occurred:  Any motherless urls
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

When url is entered, and ripped.  All files in album to be downloaded across all pages.

## Actual Behavior

When url is entered, and ripped - Urls are scanned, and completes without any downloading.

**Comment by cyian-1756** [comment]
Can you provide a test url?

**Comment by rephormat** [comment]
@cyian-1756 Can not recreate.  No response from Author.  Recommend closing.

**Comment by cyian-1756** [comment]
@Puxta If you comment with a test url I'll reopen this
