### ISSUE TITLE
Option to skip to next URL in history when existing file is encountered

### ISSUE THREAD

**Issue by lunarprops** [RipMeApp/ripme#432]
Could an option be added to skip to the next URL in history when an existing file is encountered? I delete unwanted images after ripping, and don't want them to redownload.

**Comment by rautamiekka** [comment]
Isn't the URL history exactly for this ? It should skip re-downloading the file you deleted when it notices the link is in URL history.

**Comment by lunarprops** [comment]
You're right. I had assumed it was also checking whether the file exists during a re-rip. Closing.
