### ISSUE TITLE
Ripper won't rip mp4's from Tumblr.

### ISSUE THREAD

**Issue by L3sb0t** [RipMeApp/ripme#433]
* Ripme version: 1.7.19
* Java version:  Version 8 Update 161 (build 1.8.0_161-b12)
* Operating system: Windows 10 x64
* Exact URL you were trying to rip when the problem occurred: http://gowillworld.tumblr.com/ and https://elraysworld.tumblr.com/ .
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

I post the URL and expect all posts on the Tumblrs to rip to their appropriate folders.

## Actual Behavior

Only the images and gifs rip leaving out the mp4's and leaving me an "error: null" message.

**Comment by cyian-1756** [comment]
@L3sb0t Why did you close this?

**Comment by cyian-1756** [comment]
Also can you post a smaller tumblr with videos? Both of the ones you posted are over 5000 items which makes checking them for a video post to test with rather difficult.
