### ISSUE TITLE
Not working , its not connecting to the network

### ISSUE THREAD

**Issue by gevin456** [RipMeApp/ripme#437]
* Ripme version:
* Java version: 
* Operating system: 
* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Detail the expected behavior here.

## Actual Behavior

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Comment by cyian-1756** [comment]
Please fill out the issue template

**Comment by cyian-1756** [comment]
It's been 3 days so I'm closing this, fill out the issue template and leave a comment and I'll reopen it

**Comment by gevin456** [comment]
sorry for the delay,, will update
