### ISSUE TITLE
Suggestion: Add an if seen feature

### ISSUE THREAD

**Issue by MildPanda** [RipMeApp/ripme#439]
**If you don't wanna read the whole thing, which is fine, just read the bold please**
I've directly messaged one of the developers for ripme about this before and never even gotten a response. My rip history which I rip from somewhat frequently would probably takes days if I didn't have this feature coded for me on an older version of ripme.

I'd love to have this done to the main ripme for everyone and myself **what the feature would do is it checks to see if set number of images have already been downloaded/seen in a row then skip to next download URL** 

I don't know anything about coding but I was able to transfer the seen me code over to a newer version of ripme (back when imgur broke and 4pr0n actually fixed it)  but currently am unable to and I'm finally ready to share. I have included a zip of my current ripme and **I don't know where all the code for it is located as I didn't make it but I know the keyword "seen" is located in Mainwindow.java and albumripper.java** 
[ripme - custom.zip](https://github.com/RipMeApp/ripme/files/1755960/ripme.-.custom.zip)

**Comment by rautamiekka** [comment]
This is what the URL history is for, isn't it ? And RipMe won't DL what you already have on the drive.

**Comment by Opzon** [comment]
@rautamiekka I used the most recent version of ripme and it seems like it does keep track of what it has downloaded but wont skip to next URL which makes the program waste time on a url that could have many hundreds of urls to check through.

**Comment by rautamiekka** [comment]
^ If it was up to me it wouldn't work like that.

**Comment by Opzon** [comment]
May I ask why you wouldn't want it to do that? Having that feature would save time to quickly get to the newer content to download. I don't want to leave the program running for a long time. This feature just makes the process faster.

**Comment by rautamiekka** [comment]
^ You wouldn't be able to re-visit a link.

**Comment by Opzon** [comment]
If it was a variable setting (which my ripme has an input box and a config setting to change) you could put it up to 99 so it would be possible, or just have a checkbox to enable/disable the feature.

**Comment by cyian-1756** [comment]
> I've directly messaged one of the developers for ripme about this before

Who did you message and where? I'm one of the devs and AFAIK I've never gotten a message from you before. Also please don't message the devs for feature requests, just make an issue

It should be possible to implement this feature, all we have to do is keep track the how many urls fail with "already downloaded" and skip to the next url if that number is above X (were the user sets X)

**Comment by MildPanda** [comment]
It was a very long time ago and I think over reddit under a different name, it was only 1 message requesting it. Wont happen again, sorry. Thanks for your continued support on this awesome program! Hope to see this feature, would be amazing thanks!!

**Comment by cyian-1756** [comment]
After some looking it seems like we can't skip after exactly X (without making this something that has to be implemented per ripper which is something I try to avoid). 

The only way I can think to make this work is checking if the number of images that failed with "already downloaded" is great then X every time getURLsFromPage runs, but getURLsFromPage might run thru more than X images before returning (The myhentaicomics ripper is an example of this, it runs thru 15 images before getURLsFromPage returns)

That being said this is still possible to implement but depending on the ripper it might run thru more than X images before skipping to the next item in the queue

**Comment by cyian-1756** [comment]
Anyone have an idea what this option should be called in the config file? Right now I have it as "skip_after_already_seen" but I think it's a bit long and doesn't really explain what this is for

**Comment by MildPanda** [comment]
Now that you mention it, I remember the guy that created it said he did something weird because his initial implementation didn't work and I do notice on my ripme that it will check just a couple more images than specified. I greatly appreciate you implementing this! 

Perhaps just Skip_already_seen?

**Comment by cyian-1756** [comment]
> Skip_already_seen

that still doesn't really tell the user what it does. Maybe history.end_rip_after_already_seen

Anyhow this feature should be in 1.7.20 which should release in the next day or so

**Comment by MildPanda** [comment]
Alright, thanks a bunch! Can't wait.

**Comment by cyian-1756** [comment]
@MildPanda This should be working in ripme 1.7.21, just add the line "history.end_rip_after_already_seen = X" where X is the number of urls you want to try and rip before ending the rip and jumping to the next item

**Comment by thinkpad4** [comment]
@cyian-1756 Don't forget to add that info to the config options wiki page

**Comment by cyian-1756** [comment]
@thinkpad4 thanks for reminding me!
