### ISSUE TITLE
RipMe

### ISSUE THREAD

**Issue by ashu-22** [RipMeApp/ripme#44]
I have installed the RipMe 1.5.3 version.But as per bounty requirement, the need is around at 1.5.2 version and Os requirement is Windows 10 and Java Version requirement is (V8 131).
I tried it to run that on RipMe 1.5.3 version.It would not work out. 
and show that error is for URL attachment is not valid.

Cannot rip this URL: No compatible ripper found!

**Comment by rautamiekka** [comment]
Those are the versions he tested, not the versions he requires to be compatible with.

But the compatibility won't be a problem anyway, regardless of what he required to be compatible with.

**Comment by metaprime** [comment]
I don't understand the context (I'm assuming now that this comment was in fact actually meant to reply to https://github.com/RipMeApp/ripme/issues/27 although it wasn't clear at the time)

I don't understand the problem you're having.

**Comment by metaprime** [comment]
Since this discussion belongs under #27, I'm closing this issue.

Sorry for the confusion.
