### ISSUE TITLE
RipMe doesn't download all images and videos of a Twitter user.

### ISSUE THREAD

**Issue by tarantinosaur** [RipMeApp/ripme#445]
* Ripme version: 1.7.21
* Java version: 1.8.0_121
* Operating system: Windows version 6.3.9600
* https://twitter.com/_PomHub
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

RipMe downloads all of his 89 images and videos.

## Actual Behavior

It only downloaded 23 images and 1 video.

**Comment by perridan** [comment]
I have the same issue since a lot of time confirmed

**Comment by Xirious** [comment]
It's downloading random images for me when trying to download a Twitter user's profile, using main url or main url/media.

**Comment by tarantinosaur** [comment]
Is bumping allowed?

**Comment by cyian-1756** [comment]
Taking a quick look at the ripper it seems that it doesn't get images/videoes from retweets

**Comment by tarantinosaur** [comment]
Why did you close it? Try ripping this https://twitter.com/DevirginizerTop/ (warning: gay porn); RipMe doesn't download all images and videos uploaded by the user. I really don't care about the retweets. I'm gonna make a new issue.

**Comment by cyian-1756** [comment]
> Why did you close it?

It was auto closed when I merged in PR #705 which fixes this bug. The fix will be in ripme 1.7.53

**Comment by cyian-1756** [comment]
@tarantinosaur 

This should be fixed in 1.7.53, can you test and confirm?

**Comment by wankio** [comment]
tested and have same error, cannot download full images/videos

**Comment by cyian-1756** [comment]
@tarantinosaur 

@wankio

> It's giving me "Error: jsonobject["bitrate"] not found".

That should be fixed in 1.7.54

**Comment by OwlDragon** [comment]
@cyian-1756 @tarantinosaur @wankio I have the same error in some cases download some images but finaly get Error: jsonobject["bitrate"] not found".

**Comment by cyian-1756** [comment]
@OwlDragon 

>  I have the same error in some cases download some images but finaly get Error: jsonobject["bitrate"] not found".

What link are you trying to rip? Are you using ripme 1.7.54?

**Comment by tarantinosaur** [comment]
@cyian-1756 

How do I make it "forget" past rips? I'm trying to re-download https://twitter.com/DevirginizerTop and I've already deleted its folder but RipMe is still saying it's been downloaded already.

**Comment by tarantinosaur** [comment]
Btw, is it possible to make the date stamps of the downloaded files the same with the date they were actually uploaded? The [Twitter downloader extension](https://chrome.google.com/webstore/detail/twitter-media-downloader/cblpjenafgeohmnjknfhpdbdljfkndig?hl=en) that I'm using does that.

**Comment by tarantinosaur** [comment]
I can't know if it really downloads all the media uploaded by the user since it downloads retweets...

**Comment by cyian-1756** [comment]
> How do I make it "forget" past rips?

Uncheck "Remember url history"

> Btw, is it possible to make the date stamps of the downloaded files the same with the date they were actually uploaded? 

It should be. I'll get on adding it

> Now, I can't tell if it really downloads all the media uploaded by the user since it also downloads retweets

I'll look into it some more, but as far as I could tell that's the only way to get all of a users images

**Comment by wankio** [comment]
https://imgur.com/a/ExuO38X
https://twitter.com/luyexiN1N6/media dont know why some video downloaded lower resolution

when i test and check it's just downloaded 11/12 vid (missing this https://twitter.com/luyexiN1N6/status/997812917079871489)

i'm not check tweet/retweet pics yet
