### ISSUE TITLE
Ripper 1.5.2 Issue

### ISSUE THREAD

**Issue by ashu-22** [RipMeApp/ripme#46]
Still, I have got the No compatible rip is found on URL.
These are the messages I have got know.

Please let me know the substitute for this?

**Comment by rautamiekka** [comment]
Stop making these tickets that're only duplicates and just create confusion !

**Comment by ashu-22** [comment]
Sorry But I have got the same compatibility issue.what kind of approach, I should be followed there to solving out the problem.

**Comment by cyian-1756** [comment]
> Sorry But I have got the same compatibility issue

Then provide the url you're trying to rip

> what kind of approach, I should be followed there to solving out the problem.

If you want to make a new ripper you should read the wiki and some other rippers, if you want a site to be supported you should make a comment with the site and an example album in #38

**Comment by metaprime** [comment]
Duplicate of #27
