### ISSUE TITLE
Erome.com not supported? 

### ISSUE THREAD

**Issue by seattle255** [RipMeApp/ripme#463]
* Ripme version: 1.7.23
* Java version: 
* Operating system:  MacOS
* Exact URL you were trying to rip when the problem occurred: https://www.erome.com/Jay-Jenna
* Please include any additional information about how to reproduce the problem: Attempt to rip anything from erome.com or reddit users who post to erome. 

## Expected Behavior

Downloads erome.com videos. 

## Actual Behavior

Does not download erome.com videos. 

As the above states or implies, Ripme does not appear to rip anything posted to erome.com. This is a reasonably common host among Reddit users, so it may be worth adding. See e.g. https://www.reddit.com/user/Jay-Jenna/overview for a user who uploads to erome as well as imgur and similar.

**Comment by cyian-1756** [comment]
It looks like erome changed something and that's causing the ripper to fail with "java.lang.NullPointerException". I've no idea why it's not reporting this error in the GUI tho

**Comment by M4-220** [comment]
any chance this is getting looked at? this ones a big one for me, appreciate the hard work :)
