### ISSUE TITLE
Problems accessing at least 2 sites

### ISSUE THREAD

**Issue by Butterfly-Dragon** [RipMeApp/ripme#468]
* Ripme version: 1.7.24
* Java version: 1.8.0_161
* Operating system: Windows 10.0.16299.251
* Exact URL you were trying to rip when the problem occurred:
any webtoon or deviantart galleries.
examples below.
* Please include any additional information about how to reproduce the problem:
## Expected Behavior
downloading the galleries from the urls provided
## Actual Behavior
Downloading http://www.webtoons.com/en/sf/nano-list/ep-1/viewer?title_no=700&episode_no=1
Rip complete, saved to D:\Downloads\Ripme\rips\webtoons_nano-list
Failed to load http://www.webtoons.com/en/sf/nano-list/ep-1/viewer?title_no=700&episode_no=1 after 10 attempts
Downloading http://www.webtoons.com/en/fantasy/the-gamer/ep-1/viewer?title_no=88&episode_no=1
Rip complete, saved to D:\Downloads\Ripme\rips\webtoons_the-gamer
Failed to load http://www.webtoons.com/en/fantasy/the-gamer/ep-1/viewer?title_no=88&episode_no=1 after 10 attempts
Downloading http://www.webtoons.com/en/sf/2015-space-series/ep-1-exodus-jinsoo-bae/viewer?title_no=391&episode_no=1
Rip complete, saved to D:\Downloads\Ripme\rips\webtoons_2015-space-series
Failed to load http://www.webtoons.com/en/sf/2015-space-series/ep-1-exodus-jinsoo-bae/viewer?title_no=391&episode_no=1 after 10 attempts
Downloading http://www.webtoons.com/en/action/darbi/ep-1-everything-hates-you-1/viewer?title_no=1098&episode_no=1
Rip complete, saved to D:\Downloads\Ripme\rips\webtoons_darbi
Failed to load http://www.webtoons.com/en/action/darbi/ep-1-everything-hates-you-1/viewer?title_no=1098&episode_no=1 after 10 attempts
Downloading http://www.webtoons.com/en/sf/dents/ch-1/viewer?title_no=671&episode_no=1
Rip complete, saved to D:\Downloads\Ripme\rips\webtoons_dents
Failed to load http://www.webtoons.com/en/sf/dents/ch-1/viewer?title_no=671&episode_no=1 after 10 attempts
Downloading http://www.webtoons.com/en/horror/have-you-any-fear/chapter-1-ring-around-the-rosie/viewer?title_no=1197&episode_no=1
Rip complete, saved to D:\Downloads\Ripme\rips\webtoons_have-you-any-fear
Failed to load http://www.webtoons.com/en/horror/have-you-any-fear/chapter-1-ring-around-the-rosie/viewer?title_no=1197&episode_no=1 after 10 attempts
Downloading http://www.webtoons.com/en/romance/i-love-yoo/prologue/viewer?title_no=986&episode_no=1
Rip complete, saved to D:\Downloads\Ripme\rips\webtoons_i-love-yoo
Failed to load http://www.webtoons.com/en/romance/i-love-yoo/prologue/viewer?title_no=986&episode_no=1 after 10 attempts
Downloading http://www.webtoons.com/en/fantasy/nothing-special/chapter-1/viewer?title_no=1188&episode_no=1
Rip complete, saved to D:\Downloads\Ripme\rips\webtoons_nothing-special
Failed to load http://www.webtoons.com/en/fantasy/nothing-special/chapter-1/viewer?title_no=1188&episode_no=1 after 10 attempts
Downloading http://www.webtoons.com/en/comedy/boyfriend-of-the-dead/ep-1-the-girl/viewer?title_no=1102&episode_no=1
Rip complete, saved to D:\Downloads\Ripme\rips\webtoons_boyfriend-of-the-dead
Failed to load http://www.webtoons.com/en/comedy/boyfriend-of-the-dead/ep-1-the-girl/viewer?title_no=1102&episode_no=1 after 10 attempts
Downloading http://www.webtoons.com/en/fantasy/winter-moon/ep-1-florence/viewer?title_no=1093&episode_no=1
Rip complete, saved to D:\Downloads\Ripme\rips\webtoons_winter-moon
Failed to load http://www.webtoons.com/en/fantasy/winter-moon/ep-1-florence/viewer?title_no=1093&episode_no=1 after 10 attempts
Downloading http://www.webtoons.com/en/fantasy/unordinary/prologue/viewer?title_no=679&episode_no=1
Rip complete, saved to D:\Downloads\Ripme\rips\webtoons_unordinary
Failed to load http://www.webtoons.com/en/fantasy/unordinary/prologue/viewer?title_no=679&episode_no=1 after 10 attempts
Downloading https://gerozodath.deviantart.com/gallery/?catpath=/
Rip complete, saved to D:\Downloads\Ripme\rips\deviantart_gerozodath
Failed to load https://gerozodath.deviantart.com/gallery/?catpath=/ after 10 attempts
Downloading https://papillonstudio.deviantart.com/gallery/?catpath=/
Rip complete, saved to D:\Downloads\Ripme\rips\deviantart_papillonstudio
Failed to load https://papillonstudio.deviantart.com/gallery/?catpath=/ after 10 attempts
Downloading https://sinto-risky.deviantart.com/gallery/?catpath=/
Rip complete, saved to D:\Downloads\Ripme\rips\deviantart_sinto-risky
Failed to load https://sinto-risky.deviantart.com/gallery/?catpath=/ after 10 attempts
Downloading https://sukoshisukunai.deviantart.com/gallery/?catpath=/
Rip complete, saved to D:\Downloads\Ripme\rips\deviantart_sukoshisukunai
Failed to load https://sukoshisukunai.deviantart.com/gallery/?catpath=/ after 10 attempts
Downloading https://scrson.deviantart.com/gallery/?catpath=/
Rip complete, saved to D:\Downloads\Ripme\rips\deviantart_scrson
Failed to load https://scrson.deviantart.com/gallery/?catpath=/ after 10 attempts
Downloading https://tamoerae.deviantart.com/gallery/?catpath=/
Rip complete, saved to D:\Downloads\Ripme\rips\deviantart_tamoerae
Failed to load https://tamoerae.deviantart.com/gallery/?catpath=/ after 10 attempts
Downloading https://bangela-sama.deviantart.com/gallery/?catpath=/
Rip complete, saved to D:\Downloads\Ripme\rips\deviantart_bangela-sama
Failed to load https://bangela-sama.deviantart.com/gallery/?catpath=/ after 10 attempts
Downloading https://mintbreakart.deviantart.com/gallery/?catpath=/
Rip complete, saved to D:\Downloads\Ripme\rips\deviantart_mintbreakart
Failed to load https://mintbreakart.deviantart.com/gallery/?catpath=/ after 10 attempts
Downloading https://ochrejelly.deviantart.com/gallery/?catpath=/
Rip complete, saved to D:\Downloads\Ripme\rips\deviantart_ochrejelly
Failed to load https://ochrejelly.deviantart.com/gallery/?catpath=/ after 10 attempts
Downloading https://shizen1102.deviantart.com/gallery/?catpath=/
Rip complete, saved to D:\Downloads\Ripme\rips\deviantart_shizen1102
Failed to load https://shizen1102.deviantart.com/gallery/?catpath=/ after 10 attempts
Downloading https://deilan12.deviantart.com/gallery/?catpath=/
Rip complete, saved to D:\Downloads\Ripme\rips\deviantart_deilan12
Failed to load https://deilan12.deviantart.com/gallery/?catpath=/ after 10 attempts
Downloading https://fredericandres.deviantart.com/gallery/?catpath=/
Rip complete, saved to D:\Downloads\Ripme\rips\deviantart_fredericandres
Failed to load https://fredericandres.deviantart.com/gallery/?catpath=/ after 10 attempts
Downloading https://atomictiki.deviantart.com/gallery/?catpath=/
Rip complete, saved to D:\Downloads\Ripme\rips\deviantart_atomictiki
Failed to load https://atomictiki.deviantart.com/gallery/?catpath=/ after 10 attempts
Downloading https://xxnikichenxx.deviantart.com/gallery/?catpath=/
Rip complete, saved to D:\Downloads\Ripme\rips\deviantart_xxnikichenxx
Failed to load https://xxnikichenxx.deviantart.com/gallery/?catpath=/ after 10 attempts
Downloading https://senryuji.deviantart.com/gallery/?catpath=/
Rip complete, saved to D:\Downloads\Ripme\rips\deviantart_senryuji
Failed to load https://senryuji.deviantart.com/gallery/?catpath=/ after 10 attempts
Downloading https://don-pitayin.deviantart.com/gallery/?catpath=/
Rip complete, saved to D:\Downloads\Ripme\rips\deviantart_don-pitayin
Failed to load https://don-pitayin.deviantart.com/gallery/?catpath=/ after 10 attempts
Downloading https://madeleineink.deviantart.com/gallery/?catpath=/
Rip complete, saved to D:\Downloads\Ripme\rips\deviantart_madeleineink
Failed to load https://madeleineink.deviantart.com/gallery/?catpath=/ after 10 attempts
Downloading https://justduet.deviantart.com/gallery/?catpath=/
Rip complete, saved to D:\Downloads\Ripme\rips\deviantart_justduet
Failed to load https://justduet.deviantart.com/gallery/?catpath=/ after 10 attempts
Downloading https://hidaomori.deviantart.com/gallery/?catpath=/
Rip complete, saved to D:\Downloads\Ripme\rips\deviantart_hidaomori
Failed to load https://hidaomori.deviantart.com/gallery/?catpath=/ after 10 attempts
Downloading https://marcelievsky.deviantart.com/gallery/?catpath=/
Rip complete, saved to D:\Downloads\Ripme\rips\deviantart_marcelievsky
Failed to load https://marcelievsky.deviantart.com/gallery/?catpath=/ after 10 attempts
Downloading https://dantiger.deviantart.com/gallery/?catpath=/
Rip complete, saved to D:\Downloads\Ripme\rips\deviantart_dantiger
Failed to load https://dantiger.deviantart.com/gallery/?catpath=/ after 10 attempts
Downloading https://cecihoney.deviantart.com/gallery/?catpath=/
Rip complete, saved to D:\Downloads\Ripme\rips\deviantart_cecihoney
Failed to load https://cecihoney.deviantart.com/gallery/?catpath=/ after 10 attempts

**Comment by rautamiekka** [comment]
Smells like a network problem or a network hardware problem on your end; can't repro.

**Comment by Butterfly-Dragon** [comment]
Sorry, i checked with the ISP and they deny involvement, i checked the router and everything passes through, so unless there is a DNS problem i don't know what to think. I can access the sites fine with my browser.

**Comment by cyian-1756** [comment]
Can you post the url you were trying to rip?

**Comment by cyian-1756** [comment]
> They are literally clickable and linked in the original post.

Just saw that. Next time please include the link after the "Exact URL you were trying to rip when the problem occurred:" line

> If you want me to do some special logging or send you specific files tell me which settings you wish me to enforce.

Click the "Save Logs" checkbox in the configuration tab and then try to rip the album again. Then please post the log file (It should be in the same dir as ripme.jar)

**Comment by Butterfly-Dragon** [comment]
[rips.zip](https://github.com/RipMeApp/ripme/files/1807812/rips.zip)

The zip on my previous message had logs and everything but not the logs that you needed (might still be useful for settings and other stuff) here's a bunch of tries i made it do along with a gallery that works (but had already downloaded everything from it so that it won't bog you with the actual images)

**Comment by cyian-1756** [comment]
Looking over your logs they're filled with `java.net.SocketTimeoutException: Read timed out` and you have an up to date version of java so this is definitively a issue with your network/computer

Try running `curl http://www.webtoons.com/en/sf/nano-list/ep-1/viewer?title_no=700&episode_no=1` from power shell and post the output.

What DNS provider/IP are you using? 

What Anti-virus are you using?

Does your anti-virus include any kind of proxy or 'Web protection"?

Can you try downloading from a different network (Coffee shop, tethered to your phone ect)?

**Comment by Butterfly-Dragon** [comment]
It started a couple of days ago.

I use Google DNSes.

And the provider is an italian one but i contacted it and checked for anything related to network problems.

I switched router and i even removed the firewall testing with the firewall off and then with a different firewall.

running ``` curl http://www.webtoons.com/en/sf/nano-list/ep-1/viewer?title_no=700&episode_no=1 ``` gives me the following output:

``` 
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\[REDACTED]> curl http://www.webtoons.com/en/sf/nano-list/ep-1/viewer?title_no=700&episode_no=1
At line:1 char:70
+ ... ://www.webtoons.com/en/sf/nano-list/ep-1/viewer?title_no=700&episode_ ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmpersandNotAllowed

PS C:\Users\[REDACTED]> curl "http://www.webtoons.com/en/sf/nano-list/ep-1/viewer?title_no=700&episode_no=1"


StatusCode        : 200
StatusDescription : OK
Content           :

























                    <!doctype html>

                    <html lang="en">
                    <head>
                    <title>Ep. 1 - 1 | Nano List</title>







                    <meta charset="utf-8">
                    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>




                    <link ...
RawContent        : HTTP/1.1 200 OK
                    Connection: keep-alive
                    X-XSS-Protection: 1; mode=block
                    X-Frame-Options: DENY
                    X-Content-Type-Options: nosniff
                    Content-Language: en
                    Vary: Accept-Encoding
                    X-Varnish: 2719103873
                    Ag...
Forms             : {}
Headers           : {[Connection, keep-alive], [X-XSS-Protection, 1; mode=block], [X-Frame-Options, DENY],
                    [X-Content-Type-Options, nosniff]...}
Images            : {@{innerHTML=; innerText=; outerHTML=<img width="92" height="87" class="_thumbnailImages" alt="Ep.
                    1" src="http://webtoons.static.naver.net/image/bg_transparency.png" data-url="http://webtoon.phinf.
                    naver.net/20160628_75/1467105987663jIFvn_JPEG/146710598763670012.jpg?type=q90">; outerText=;
                    tagName=IMG; width=92; height=87; class=_thumbnailImages; alt=Ep. 1;
                    src=http://webtoons.static.naver.net/image/bg_transparency.png; data-url=http://webtoon.phinf.naver
                    .net/20160628_75/1467105987663jIFvn_JPEG/146710598763670012.jpg?type=q90}, @{innerHTML=;
                    innerText=; outerHTML=<img width="92" height="87" class="_thumbnailImages" alt="Ep. 2"
                    src="http://webtoons.static.naver.net/image/bg_transparency.png" data-url="http://webtoon.phinf.nav
                    er.net/20160628_33/1467108903032g75jx_JPEG/146710890300770022.jpg?type=q90">; outerText=;
                    tagName=IMG; width=92; height=87; class=_thumbnailImages; alt=Ep. 2;
                    src=http://webtoons.static.naver.net/image/bg_transparency.png; data-url=http://webtoon.phinf.naver
                    .net/20160628_33/1467108903032g75jx_JPEG/146710890300770022.jpg?type=q90}, @{innerHTML=;
                    innerText=; outerHTML=<img width="92" height="87" class="_thumbnailImages" alt="Ep. 3"
                    src="http://webtoons.static.naver.net/image/bg_transparency.png" data-url="http://webtoon.phinf.nav
                    er.net/20160628_36/1467108970845SLHw9_JPEG/146710897081770037.jpg?type=q90">; outerText=;
                    tagName=IMG; width=92; height=87; class=_thumbnailImages; alt=Ep. 3;
                    src=http://webtoons.static.naver.net/image/bg_transparency.png; data-url=http://webtoon.phinf.naver
                    .net/20160628_36/1467108970845SLHw9_JPEG/146710897081770037.jpg?type=q90}, @{innerHTML=;
                    innerText=; outerHTML=<img width="92" height="87" class="_thumbnailImages" alt="Ep. 4"
                    src="http://webtoons.static.naver.net/image/bg_transparency.png" data-url="http://webtoon.phinf.nav
                    er.net/20160628_178/14671090117389Cv1p_JPEG/146710901171070042.jpg?type=q90">; outerText=;
                    tagName=IMG; width=92; height=87; class=_thumbnailImages; alt=Ep. 4;
                    src=http://webtoons.static.naver.net/image/bg_transparency.png; data-url=http://webtoon.phinf.naver
                    .net/20160628_178/14671090117389Cv1p_JPEG/146710901171070042.jpg?type=q90}...}
InputFields       : {@{innerHTML=; innerText=; outerHTML=<input class="input_chk" id="chk_dontview" type="checkbox">;
                    outerText=; tagName=INPUT; class=input_chk; id=chk_dontview; type=checkbox}}
Links             : {@{innerHTML=<span>skip content</span>; innerText=skip content; outerHTML=<a onclick="document.getE
                    lementById('content').tabIndex=-1;document.getElementById('content').focus();return false;"
                    href="#content"><span>skip content</span></a>; outerText=skip content; tagName=A; onclick=document.
                    getElementById('content').tabIndex=-1;document.getElementById('content').focus();return false;;
                    href=#content}, @{innerHTML=WEBTOON; innerText=WEBTOON; outerHTML=<a class="btn_logo
                    NPI=a:home,g:en_en" href="http://www.webtoons.com/en/">WEBTOON</a>; outerText=WEBTOON; tagName=A;
                    class=btn_logo NPI=a:home,g:en_en; href=http://www.webtoons.com/en/}, @{innerHTML=Nano List;
                    innerText=Nano List; outerHTML=<a title="Nano List" class="subj NPI=a:end,g:en_en"
                    href="http://www.webtoons.com/en/sf/nano-list/list?title_no=700">Nano List</a>; outerText=Nano
                    List; tagName=A; title=Nano List; class=subj NPI=a:end,g:en_en;
                    href=http://www.webtoons.com/en/sf/nano-list/list?title_no=700}, @{innerHTML=<em>Next
                    Episode</em>; innerText=Next Episode; outerHTML=<a title="Next Episode" class="pg_next
                    _nextEpisode NPI=a:next,g:en_en"
                    href="http://www.webtoons.com/en/sf/nano-list/ep-2/viewer?title_no=700&amp;episode_no=2"><em>Next
                    Episode</em></a>; outerText=Next Episode; tagName=A; title=Next Episode; class=pg_next
                    _nextEpisode NPI=a:next,g:en_en;
                    href=http://www.webtoons.com/en/sf/nano-list/ep-2/viewer?title_no=700&amp;episode_no=2}...}
ParsedHtml        : System.__ComObject
RawContentLength  : 268359



PS C:\Users\[REDACTED]>
```

**Comment by Butterfly-Dragon** [comment]
![image](https://user-images.githubusercontent.com/33538906/37357248-316cc79c-26e8-11e8-8dcc-2c38c3d06cc3.png)
this is litterally what i see after logging into a tethered connection with my phone

**Comment by cyian-1756** [comment]
Well this is weird. If this was a network issue/the sites banned your ip then the curl would have failed. I doubt googles DNS is doing anything fucky

So it looks like this is either an issue with Java or a very strange issue with ripme

**Comment by cyian-1756** [comment]
>  this is litterally what i see after logging into a tethered connection with my phone

Then yup this is either Java or ripme.

Can you try using an older version of ripme to see if this is a regression?

**Comment by cyian-1756** [comment]
Try ripping "https://www.webtoons.com/en/sf/nano-list/ep-1/viewer?title_no=700&episode_no=1"

**Comment by cyian-1756** [comment]
The only other things I can think to try are reinstalling java/rebooting windows

**Comment by Butterfly-Dragon** [comment]
![image](https://user-images.githubusercontent.com/33538906/37357477-d671cf94-26e8-11e8-9c80-e756e8a3d3ec.png)

🤔 okay this is weird, i have not updated Java in months and with that version i had no problems let me check one last thing....

![image](https://user-images.githubusercontent.com/33538906/37357538-ff64b830-26e8-11e8-8df8-b9779e62dc6c.png)
so nothing different in the last 2 days either, because the update was today.

**Comment by rautamiekka** [comment]
And if none of the above helps, the next probable cause is your phone. I know by experience a tethered connection through Android devices is really limited by the integral firewall (if there's such thing).

**Comment by Butterfly-Dragon** [comment]
Rebooted several times already and reinstalled java too.

I used the tethered phone just for the one try since you asked me to check with a different provider

**Comment by Butterfly-Dragon** [comment]
sorry i mixed rautmiekka with cyian

**Comment by cyian-1756** [comment]
@Butterfly-Dragon 

Try running `ping webtoons.com` and `ping www.webtoons.com` from powershell and post the output here

**Comment by cyian-1756** [comment]
Also are only webtoons and DA failing or can you not rip from any site?

**Comment by Butterfly-Dragon** [comment]
all other sites rip fine

``` Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\[REDACTED]> ping webtoons.com

Pinging webtoons.com [210.89.164.19] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 210.89.164.19:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),
PS C:\Users\simon> ping www.webtoons.com

Pinging us.webtoons.com [203.104.164.11] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 203.104.164.11:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),
PS C:\Users\[REDACTED]>
``` 

🤔 weird i can get to the site very fine.

![image](https://user-images.githubusercontent.com/33538906/37358631-dc413ba0-26eb-11e8-9044-4d911032421f.png)

**Comment by Butterfly-Dragon** [comment]
i repeat every single other site i tried rips fine and has no problem

**Comment by cyian-1756** [comment]
Then this has to be something that both webtoons and DA do.

It looks like WT doesn't responded to any pings (Even I get timeouts trying to ping them) but DA responds to pings

It looks like DA uses cloudflare but WT doesn't.

Can you try running ripme as admin?

**Comment by Butterfly-Dragon** [comment]
![image](https://user-images.githubusercontent.com/33538906/37359586-4a6fa538-26ee-11e8-8681-ac07a21d4c38.png)

🤔🤷

let me try a version of ripme a bit more ancient since you updated it quite often and i tried just the one before the one i use now.

**Comment by cyian-1756** [comment]
Can you ping deviantart.com and post the output? The only thing I can think of that might be causing this is your internet is just slow and it's taking to long to connect to WT and DA

**Comment by Butterfly-Dragon** [comment]
yep ripme version 18 had the same results.

also yes WT and DA rippers have always been very slow compared to the other rippers, DA in particular has always been extremely sluggish, i thought it was a safety against being banned for hammering the site. WT is quick to download the images on one page but takes forever to download the next page.

Let me ping deviantart.

``` Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\simon> ping https://www.deviantart.com/
Ping request could not find host https://www.deviantart.com/. Please check the name and try again.
PS C:\Users\simon> ping www.deviantart.com

Pinging www.deviantart.com [52.84.150.26] with 32 bytes of data:
Reply from 52.84.150.26: bytes=32 time=80ms TTL=238
Reply from 52.84.150.26: bytes=32 time=74ms TTL=238
Reply from 52.84.150.26: bytes=32 time=82ms TTL=238
Reply from 52.84.150.26: bytes=32 time=78ms TTL=238

Ping statistics for 52.84.150.26:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 74ms, Maximum = 82ms, Average = 78ms
PS C:\Users\simon>
[''']

**Comment by cyian-1756** [comment]
> time=80ms

That's pretty fast.

The only other thing I can think to fix this is raising the time out. Go to the configuration tab of ripme and change the time out to 60000000

**Comment by Butterfly-Dragon** [comment]
![image](https://user-images.githubusercontent.com/33538906/37360384-645848a4-26f0-11e8-91be-476534a26541.png)

![image](https://user-images.githubusercontent.com/33538906/37360399-729d04c2-26f0-11e8-8851-43ebeb77b6b9.png)

i.... suppose it gets ignored? It definitively did not wait 1 years : 47 weeks : 0 days : 4 hours : 51 minutes : 15.00 seconds to give me this answer 🤣🤣🤣🤣

**Comment by cyian-1756** [comment]
> i.... suppose it gets ignored?

Yea it looks like. I'll have to get on fixing that

Change the line "page.timeout = 5000" to "page.timeout = 50000" in %APPDATA%/ripme/rip.properties

**Comment by Butterfly-Dragon** [comment]
![image](https://user-images.githubusercontent.com/33538906/37360798-80a1a040-26f1-11e8-85b3-1e4065babc02.png)
let's see....

![image](https://user-images.githubusercontent.com/33538906/37360852-ae0d7874-26f1-11e8-82b8-5658cbfe617e.png)
now it's working

🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬 <= that's me spamming curses. Let me pick up a calendar because i'm going to name each and every saint in there.

**Comment by cyian-1756** [comment]
Well I feel stupid that timeout wasn't the first fucking thing I said to check, but at least it's working now
