### ISSUE TITLE
Instagram not working

### ISSUE THREAD

**Issue by domonic46** [RipMeApp/ripme#469]
* Ripme version: 1.7.24
* Java version:  8 update 151
* Operating system: Windows 7
* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/privatekanye
* Please include any additional information about how to reproduce the problem:

Instagram ripper isn't working at all for me for any instagram account. The ripper just gives me an error message: "JSONObject["TagPage"] not found." I've tried different versions of the ripper and still have the same issue. Anyone know what the issue could be and how to fix it?

**Comment by cyian-1756** [comment]
It looks like they changed their JSON structure.

**Comment by thinkpad4** [comment]
Was coming here to report the same thing
