### ISSUE TITLE
ripme

### ISSUE THREAD

**Issue by ashu-22** [RipMeApp/ripme#47]
Still, I have got the same compatibility issue out there.You have to look it out on your own.

**Comment by rautamiekka** [comment]
Stop making these tickets that're only duplicates and just create confusion !

**Comment by cyian-1756** [comment]
I'm closing this because you're spamming at this point. As metaprime pointed out you should be commenting on #27 not making new issues and if you do make a new issue you shouldn't give it a title like "ripme"
