### ISSUE TITLE
Not reading history file

### ISSUE THREAD

**Issue by Cottoneyes** [RipMeApp/ripme#475]
* Ripme version: 1.5.7 through to current version
* Java version:  1.8.0_161
* Operating system:  Windows 10 ver 10.0.16299.309
* Exact URL you were trying to rip when the problem occurred: Any
* Please include any additional information about how to reproduce the problem: Switching to different versions of Ripme doesn't help.

## Expected Behavior

History tab populates.

## Actual Behavior

History tab was blank after updating, and then remained blank after downgrading. The history.json file had the correct history in it, but ripme wouldn't read it. I overwrote it (sorry, accident) with an older history.json that had half as many entries and it read fine. The broken history.json had about 450 entries, the replacement has about 250.

Is there a way to repopulate a history.json file using the folder names in the ripme folder, as those fully document my actual history of using ripme? Edit: maybe a tool that goes through the rips folder and uses the folder names to guess the url and populate history.json?

**Comment by cyian-1756** [comment]
> Is there a way to repopulate a history.json file using the folder names in the ripme folder, as those fully document my actual history of using ripme?

Nope

I have no idea what could've caused the issues with the history file, I've seen it go past 450 entries without issue

**Comment by Cottoneyes** [comment]
Hmm :/ Do you think I could DIY a way to detect a folder name, take the relevant part, determine what it is (reddit user, imgur album, etc), put it into a correctly formatted link, and then append it onto history.json with a fake date etc?

**Comment by cyian-1756** [comment]
> Hmm :/ Do you think I could DIY a way to detect a folder name, take the relevant part, determine what it is (reddit user, imgur album, etc), put it into a correctly formatted link, and then append it onto history.json with a fake date etc?

You *could* but it would be a massive pain

**Comment by Cottoneyes** [comment]
Entered everything back into ripme manually, that's a solid half hour I'll never get back. Going to be keeping backups of history.json from now on, I suppose
