### ISSUE TITLE
instagram error

### ISSUE THREAD

**Issue by rotnemmoc** [RipMeApp/ripme#479]
* Ripme version: 1.7.26
* Java version: Java 8 Update 161 
* Operating system: macOS Sierra 10.12.6
* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/juliazanettini/
* Please include any additional information about how to reproduce the problem: Other instagram pages seem to be ripped fine, the error only happened with this specific url.

## Expected Behavior

To rip the page.

## Actual Behavior

It reaches 589 files and then "Error: Unterminated string at 89976 [character 0 line 3]" appears and the rip stops.

**Comment by pinnie** [comment]
I get the same error at 589 on that particular account, but I've ripped about ten in total since updating to 1.7.26, all without issues. Just tried another with 1205 posts, and it went fine.

Windows 7 64-bit, Java 8 update 161, RipMe  1.7.26 with max threads 1.

**Comment by esteves023** [comment]
I'm getting error "Unterminated string at 175648 [character 0 line 3]"
It will only rip the 12 first pictures. Apparently they have changed their whole code, since trying to download the whole page on a regular web browser won't work either.

**Comment by cyian-1756** [comment]
It looks like there was an issue with unterminated " characters in the JSON. I'll merge the fix tomorrow and push out an update

**Comment by pinnie** [comment]
Finally ran into a page that produces a similar error.

URL: https://www.instagram.com/elyseknowlzy/
Error: Unterminated string at 36194 [character 0 line 3]

**Comment by cyian-1756** [comment]
This is fixed in 1.7.27
