### ISSUE TITLE
erome URLs not downloaded when ripping via reddit profiles

### ISSUE THREAD

**Issue by cppsse** [RipMeApp/ripme#482]
* Ripme version: 1.7.27
* Java version: openjdk version 1.8.0_131 and 1.8.0_151
* Operating system: Debian 9.3 and Debian 8.10
* Exact URL you were trying to rip when the problem occurred: https://www.reddit.com/user/Chipware
* Please include any additional information about how to reproduce the problem:

alias ripme='java -jar /usr/local/bin/ripme.jar -l . -u'

When ripping via a reddit profile, links to erome pics/vids do not download.

chip@omv01:/mnt$ ripme https://www.reddit.com/user/Chipware
Loaded /home/chip/.config/ripme/rip.properties
Loaded log4j.properties
Initialized ripme v1.7.27
[+] Creating directory: ./reddit_user_Chipware
[!] Unable to rip URL: https://www.erome.com/a/UAAbTeLi

However, when accessing the link directly, it works:

chip@omv01:/mnt$ ripme https://www.erome.com/a/UAAbTeLi
Loaded /home/chip/.config/ripme/rip.properties
Loaded log4j.properties
Initialized ripme v1.7.27
[+] Creating directory: ./erome_UAAbTeLi_Screen_Shot_2018-01-31_at_4.37.21_PM
Retrieving https://www.erome.com/a/UAAbTeLi
    Downloading file: https://s4.erome.com/49/UAAbTeLi/FUqP2mfy.png Retry #1
[+] Saved https://s4.erome.com/49/UAAbTeLi/FUqP2mfy.png as ./erome_UAAbTeLi_Screen_Shot_2018-01-31_at_4.37.21_PM/001_FUqP2mfy.png

**Comment by tehloxely** [comment]
I just came here to post this. It happened for this user: https://www.reddit.com/user/irisansley
