### ISSUE TITLE
VkRipper unable to download images in their original size

### ISSUE THREAD

**Issue by gorvinsky** [RipMeApp/ripme#490]
* Ripme version:
* Java version: 1.8.0_111
* Operating system: Microsoft Windows [Version 10.0.16299.309]
* Exact URL you were trying to rip when the problem occurred: https://vk.com/album-156891750_249435170
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Download all images in their original size.

## Actual Behavior

Downloaded images not in their original size.

**Comment by kevin51jiang** [comment]
I get the size from RipMe what I would get by downloading by hand.

Are you just dealing with VK compressing the photos?

**Comment by gorvinsky** [comment]
This is the comparison of the first image in the album that I posted in my original description.

What I get from Ripper: https://i.imgur.com/PBnwhNC.jpg
Dimensions: 715 x 1080

What I get from downloading by hand: https://i.imgur.com/N4vZi0h.jpg
Dimensions: 1431 x 2160

If this is due to some settings about compression, please tell me where I can change it so that it will download the original size.
