### ISSUE TITLE
Hentai Foundry - No images found

### ISSUE THREAD

**Issue by Dota2isGreat** [RipMeApp/ripme#494]
* Ripme version: v1.2.13
* Java version: Java 8 Update 161
* Operating system: Microsoft Windows Version 10.0.16299
* Exact URL you were trying to rip when the problem occurred: https://www.hentai-foundry.com/pictures/user/Sparrow
* Please include any additional information about how to reproduce the problem: Seems to fail on all different types of users.

## Expected Behavior

Downloads all images.

## Actual Behavior

Produces error that states "No images found at https://www.hentai-foundry.com/pictures/user/Sparrow"

**Comment by cyian-1756** [comment]
1.2.13 is massively outdated. Update to [1.7.28 and HF will work](https://github.com/RipMeApp/ripme/releases/download/1.7.28/ripme.jar)
