### ISSUE TITLE
GUI opens when trying to run 1.7.29 via command line

### ISSUE THREAD

**Issue by clb92** [RipMeApp/ripme#497]
* Ripme version:
1.7.29
* Java version:
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
* Operating system:
Microsoft Windows [Version 10.0.16299.309]
* Exact URL you were trying to rip when the problem occurred:
Any URL
* Please include any additional information about how to reproduce the problem:
I open command prompt, type `java -jar ripme.jar -u '<any URL here>'`

## Expected Behavior

I expect it to start ripping, outputting status in the command line, like any previous version did.

## Actual Behavior

The command line outputs:

    Loaded C:\Users\Christoffer\AppData\Local\ripme\rip.properties
    Loaded log4j.properties
    Initialized ripme v1.7.29

And then the GUI opens, and nothing is ripped (unless I manually do it in the GUI). ![Screenshot](https://user-images.githubusercontent.com/4537419/38236035-44216514-3723-11e8-90f5-5b31f5a08644.png)

**Comment by clb92** [comment]
I can force it to detect headless by doing this:

    java -Djava.awt.headless=true -jar ripme.jar -u '<any URL here>'

**Comment by MrTimscampi** [comment]
Indeed, this seems to be an issue.

I'll push a fix for it ASAP.

**Comment by MrTimscampi** [comment]
Feel free to compile the branch headless-fix on my fork while waiting for this to get merged in.

You need a JDK and Maven, then simply ./build.sh or ./build.bat and it should output you a .jar in the target subdirectory.

**Comment by clb92** [comment]
Thanks!

Should I close this issue in the mean time?

**Comment by MrTimscampi** [comment]
It'll auto-close once it's merged in, usually, so you can leave it open.
