### ISSUE TITLE
Only downloads individual pages, not full album, on Motherless

### ISSUE THREAD

**Issue by sevengali** [RipMeApp/ripme#50]
* Ripme version: 1.5.7
* Java version: 1.8.0_144
* Operating system: Ver: 10.0.15063, Winver: 1703 (15063.540)
* Exact URL you were trying to rip when the problem occurred: Does it for any album
* Please include any additional information about how to reproduce the problem: Download any album with more than 80 images and it'll only download the first page (80 images).

## Expected Behavior

Downloads full album

## Actual Behavior

Downloads just the page given in the url

**Comment by cyian-1756** [comment]
Can you post an example URL?

**Comment by rautamiekka** [comment]
https://github.com/4pr0n/ripme/issues/119 (sorry, it's the old place of RipMe)

**Comment by sevengali** [comment]
Here's one that's not working: http://motherless.com/G0BA60E6 (NSFW of course)

It's images only (the entire gallery is, not just an images only section of a gallery), I hadn't tried videos yet. It also doesn't work if you go to the "Images only" link.

Done a little more testing.

As you may have noticed in the links supplied by @rautamiekka, the pics only links start with `GI` (motherless.com/GIxxx), videos are `GV`, all uploads (includes both pics and vids) are also `GM` and the base album is just `G`. You can't simply browse through the base album, it has to be in one of those sections.

When giving RipMe this link, it isn't accounting for the I/V/M after the G when finding the next pages, log will read:

    Downloading http://motherless.com/G0BA60E6
    Downloading http://motherless.com/G0BA60E6?page=2

etc. When they should be `GIBA60E6?page=2`. If you go to the page 2 link RipMe is trying to parse, it'll show you the first page. If you hand RipMe the correct page 2 link directly, it'll download the second page.

Not sure why that is happening (as it works fine for your link) but hopefully that helps
