### ISSUE TITLE
Now I'm getting instagram downloads first page and then stops downloading 

### ISSUE THREAD

**Issue by thinkpad4** [RipMeApp/ripme#500]
@cyian-1756 
* Ripme version: 1.7.30
* Java version: 
* Operating system: Windows 7 SP1 64bit
* https://www.instagram.com/taylorswift/?hl=en
* Please include any additional information about how to reproduce the problem:
This https://github.com/RipMeApp/ripme/issues/496 is happening to me too
## Expected Behavior
To rip all the images
Detail the expected behavior here.
I will test on another computer tomorrow, I just wanted to get a baseline issue report submitted
## Actual Behavior
It stops after 12 images
Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.
Downloading https://www.instagram.com/taylorswift/
Downloading https://scontent-lga3-1.cdninstagram.com/vp/7792a0a139ff223771016b0fb3d287ed/5B75EABD/t51.2885-15/e35/29714401_2059820137620603_8423014927173681152_n.jpg
Downloading https://scontent-lga3-1.cdninstagram.com/vp/190bd78e521fd948aaecaf62eff5adec/5B707C10/t51.2885-15/e35/29414603_1241515229314646_6354830218137436160_n.jpg
Downloaded .\rips\instagram_taylorswift\2018_04_02_04_05_29714401_2059820137620603_8423014927173681152_n.jpg
Downloaded .\rips\instagram_taylorswift\2018_03_30_07_34_29414603_1241515229314646_6354830218137436160_n.jpg
Downloading https://scontent-lga3-1.cdninstagram.com/vp/cf967aa251f6c85402f77f2e0390350b/5ACAC42B/t50.2886-16/29903735_353165361861741_4629928398095908864_n.mp4
Downloading https://scontent-lga3-1.cdninstagram.com/vp/b8945687eae86a21dfa50c5748f09b09/5B6FE4F0/t51.2885-15/e35/29401620_1640058212750571_4499431030897246208_n.jpg
Downloaded .\rips\instagram_taylorswift\2018_03_23_06_56_29401620_1640058212750571_4499431030897246208_n.jpg
Downloading https://scontent-lga3-1.cdninstagram.com/vp/50e8b39a83b30e8649a11b63fe4129b1/5ACAED80/t50.2886-16/28665816_589152044757394_8683226414155038720_n.mp4
Downloaded .\rips\instagram_taylorswift\2018_03_30_05_05_29903735_353165361861741_4629928398095908864_n.mp4
Downloading https://scontent-lga3-1.cdninstagram.com/vp/a14281f7f3400dc50809864229166650/5ACADFA3/t50.2886-16/28837135_338587463328687_1199948067898392576_n.mp4
Downloading https://scontent-lga3-1.cdninstagram.com/vp/a13caba9e4ad66c29b4afb9cab2c80fc/5ACADE66/t50.2886-16/29148034_355063958339213_8840582324979499008_n.mp4
Downloading https://scontent-lga3-1.cdninstagram.com/vp/e48a67418ef8b760aabb6b585c281465/5ACAC1B5/t50.2886-16/28550255_2384189174940483_4281097317592858624_n.mp4
Downloaded .\rips\instagram_taylorswift\2018_03_13_09_05_28665816_589152044757394_8683226414155038720_n.mp4
Downloading https://scontent-lga3-1.cdninstagram.com/vp/55ce41af37a19b6400265d468fadd830/5B56CCFE/t51.2885-15/e35/27577173_956597491173322_4321447117999570944_n.jpg
Downloading https://scontent-lga3-1.cdninstagram.com/vp/110705c702908d68444546464eb7b0e8/5ACACCC7/t50.2886-16/28115031_1837072512970628_8646749600507494400_n.mp4
Downloaded .\rips\instagram_taylorswift\2018_03_12_01_24_29148034_355063958339213_8840582324979499008_n.mp4
Downloaded .\rips\instagram_taylorswift\2018_02_12_05_24_27577173_956597491173322_4321447117999570944_n.jpg
Downloading https://scontent-lga3-1.cdninstagram.com/vp/465e26032bf78a2265af81f854392089/5ACB03B0/t50.2886-16/27307596_108941136565807_5612826767522791424_n.mp4
Downloading https://scontent-lga3-1.cdninstagram.com/vp/82cdfdc35f3bcce02d5dbed5456f12c0/5B6A7145/t51.2885-15/e35/27581950_162897054258501_7305091775327109120_n.jpg
Downloading next page
Downloading https://scontent-lga3-1.cdninstagram.com/5B75EABD/t51.2885-15/e35/29714401_2059820137620603_8423014927173681152_n.jpg
Downloaded .\rips\instagram_taylorswift\2018_03_05_01_03_28550255_2384189174940483_4281097317592858624_n.mp4
Downloaded .\rips\instagram_taylorswift\2018_02_05_10_08_27581950_162897054258501_7305091775327109120_n.jpg
https://scontent-lga3-1.cdninstagram.com/5B75EABD/t51.2885-15/e35/29714401_2059820137620603_8423014927173681152_n.jpg : Non-retriable status code 403 while downloading https://scontent-lga3-1.cdninstagram.com/5B75EABD/t51.2885-15/e35/29714401_2059820137620603_8423014927173681152_n.jpg
Downloaded .\rips\instagram_taylorswift\2018_02_27_10_32_28115031_1837072512970628_8646749600507494400_n.mp4
Downloaded .\rips\instagram_taylorswift\2018_03_13_08_43_28837135_338587463328687_1199948067898392576_n.mp4
Downloaded .\rips\instagram_taylorswift\2018_02_07_09_12_27307596_108941136565807_5612826767522791424_n.mp4
Rip complete, saved to D:\Downloads\rips\instagram_taylorswift

**Comment by cyian-1756** [comment]
Looks like the next page url is 403ing. An example of the new next page url is https://www.instagram.com/graphql/query/?query_hash=42323d64886122307be10013ad2dcc44&variables=%7B%22id%22%3A%2211830955%22%2C%22first%22%3A12%2C%22after%22%3A%22AQBiVSvckh-CSmrmVGjvUYTiHGwMGMOEx_E-hfEQeN77eJaDZUZUla2I6Re8zIm1TfkqhdVVqTZMMQn7VQd-2JgAkzhs_bTn8pVPY-vTcqfzfA%22%7D

**Comment by cyian-1756** [comment]
The decode url is https://www.instagram.com/graphql/query/?query_hash=42323d64886122307be10013ad2dcc44&variables={"id":"11830955","first":12,"after":"AQBiVSvckh-CSmrmVGjvUYTiHGwMGMOEx_E-hfEQeN77eJaDZUZUla2I6Re8zIm1TfkqhdVVqTZMMQn7VQd-2JgAkzhs_bTn8pVPY-vTcqfzfA"}

The decode old url is https://www.instagram.com/graphql/query/?query_hash=42323d64886122307be10013ad2dcc44&variables={"id":"11830955","first":100,"after":"1708327261253270775"}

**Comment by cyian-1756** [comment]
It seems that IG now wants a cookie to be sent along with the request

**Comment by cyian-1756** [comment]
It looks like the only cookie the api cares about is ig_pr

**Comment by cyian-1756** [comment]
And it looks like that cookie can be any value

**Comment by cyian-1756** [comment]
This is a heads up to whoever is working on this the next time the IG ripper breaks, it's probably because the ig_pr cookie has to be set a real value and not just "1"

**Comment by cyian-1756** [comment]
I'm reopening this because the issue has come back

**Comment by thinkpad4** [comment]
Damn that was fast of them

**Comment by cyian-1756** [comment]
I'm reopening this because the issue has come back again

**Comment by cyian-1756** [comment]
This was fixed in 1.7.33
