### ISSUE TITLE
[suggested site] artstation.com

### ISSUE THREAD

**Issue by Butterfly-Dragon** [RipMeApp/ripme#501]
Okay, sorry, i don't know where i can suggest a new site so if this is not the place, let me know.

Here's a couple of random galleries with thumbnails that in some cases have mini subgalleries
https://www.artstation.com/duongnguyenminhthuan
https://www.artstation.com/yankyohara

Do you think adding this site would be doable?

**Comment by cyian-1756** [comment]
> Okay, sorry, i don't know where i can suggest a new site so if this is not the place, let me know.

We have a issue for suggesting new sites [here](https://github.com/RipMeApp/ripme/issues/38)

**Comment by Butterfly-Dragon** [comment]
okay, I wrote there ;)
