### ISSUE TITLE
Instagram Ripper is broke.. again

### ISSUE THREAD

**Issue by daniga999** [RipMeApp/ripme#505]
* Ripme version: 1.7.31
* Java version: 
* Operating system: win 8.1
* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

A full profile ripped 

## Actual Behavior

It only downloads 20 pictures and it stops like it is done. I suppose it isn't going to the other page or something.

**Comment by cyian-1756** [comment]
This should be fixed in 1.7.32

**Comment by pmanuth** [comment]
1.7.32 broke again :(

**Comment by thinkpad4** [comment]
@cyian-1756 Yep, it's broken again.

**Comment by cyian-1756** [comment]
@thinkpad4 I know, no idea what's wrong with it however

**Comment by liamyoun** [comment]
Instagram is working well.
Try removing the last ' / ' of the URL.

Not 'https://www.instagram.com/explore/tags/coffee/'
Try 'https://www.instagram.com/explore/tags/coffee'

**Comment by planetrocky** [comment]
@liamyoun doesn't make any difference, it still only downloads the first page

**Comment by marcoqu** [comment]
@cyian-1756 
`x-instagram-gis` is now `md5(rhx_gis + ":" + csrf_token + ":" + params)`, without the user agent.

**Comment by thinkpad4** [comment]
@cyian-1756 it broke again it looks like

**Comment by cyian-1756** [comment]
@thinkpad4 What url are you trying to rip?

**Comment by thinkpad4** [comment]
I feel like a derp, I must of been limited after ripping a large album.  I'm sorry

**Comment by cyian-1756** [comment]
@thinkpad4 No problem
