### ISSUE TITLE
RipMe 1.7.33 doesnt download full albums.

### ISSUE THREAD

**Issue by sqvist** [RipMeApp/ripme#511]
* Ripme version: 1.7.33
* Java version: java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
* Operating system: Microsoft Windows [Version 10.0.16299.371]
* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/m0llys/
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

User has 173 posts. RipMe should download all.

## Actual Behavior

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

Ripme only retrieves 16, recieves "Non-retriable status code 403 while" on 1 of them.

**Comment by cyian-1756** [comment]
I can't reproduce this. Ripping https://www.instagram.com/m0llys/ with ripme 1.7.33 3 images do error out on but besides that it rips the entire album fine. You might've been rate limited by IG if you were ripping many albums

**Comment by sqvist** [comment]
How much is "too much" then? 
I retried today with another album (1200+), they all "failed to download" sadly :(

**Comment by cyian-1756** [comment]
> How much is "too much" then?

No idea.

>  I retried today with another album (1200+), they all "failed to download" sadly :(

Yea, it looks like IG is cracking down a bit

**Comment by cyian-1756** [comment]
It looks like iG changed yet again

**Comment by icemouton** [comment]
dang that's too bad! I can also confirm it fails even on smaller IG accounts...

**Comment by psykodelik** [comment]
Agreed on the slow fetch option. With one download thread but Remember URL history unchecked (at large amounts of URLs (50k+), this becomes an unintended drain on performance speed), an album of 3103 posts completed with only 2113 files downloaded due to being rate-limited by insta whilst downloading. It was the first album I had tried that day: https://www.instagram.com/jessgearyx/

**Comment by thinkpad4** [comment]
Looks like it stopped working again.  Won't download more than 12 files

**Comment by pmanuth** [comment]
Same here. 12 pics and it stops. Maybe I'm being rate limited too.

Btw, right after trying ripme which stops after 12 pics, I tried the Chrome Extension - DownAlbum. It managed to download but it stops working if > 1000 images. It will timeout and you just have to wait another 30-60mins or so to continue and it will download the rest of the images. 

Could someone see how is that extension implemented? Perhaps it is using a different way.

**Comment by Hrxn** [comment]
Is it this one? https://github.com/inDream/DownAlbum

**Comment by sqvist** [comment]
Sadly still a problem in 1.7.35 :(

**Comment by planetrocky** [comment]
Can confirm still only fetching first page on some IG accounts

**Comment by HASJ** [comment]
https://www.instagram.com/kathyzworld/

Still broken. Curiously enough, not even JDownloader is getting past the 12 images. I guess IG is cracking down on downloaders.

**Comment by pinnie** [comment]
They seem to be rate-limiting by IP if I grab around 1000 images in a given period (an hour?). After RipMe stops, if I visit Instagram in my browser, I'll get "failed to load" when trying to scroll past the first page of an album, so it's not just a RipMe thing.

For albums <1000 images, I can just wait in between rips. Problem is with really large albums, which it seems might be impossible to finish. After grabbing the first ~1000 images, if I change IP and run RipMe again, it runs through all the previous pages first (by necessity?) which seems to be counted by the rate limiter - I'll get maybe 50 additional images before the new IP gets rate-limited as well.

**Comment by planetrocky** [comment]
Does Instagram have a restful api? Or is it just streamed always from the latest Instagram post?
Does ripme redownload all images on a re-rip?

If I have time, I’ll look into it; but I’m superbusy writing code at work.

**Comment by kevin51jiang** [comment]
AFAIK Instagram really doesn't like you using its api of you're not a legitimate app. If I remember correctly, ripme just streams the images to download.

**Comment by cyian-1756** [comment]
This was fixed quite a few releases ago
