### ISSUE TITLE
Unable To Rip A Comic From Webtoons

### ISSUE THREAD

**Issue by Butterfly-Dragon** [RipMeApp/ripme#514]
* Ripme version:
1.7.33

* Java version:
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

* Operating system:
Microsoft Windows [Version 10.0.16299.371]

* Exact URL you were trying to rip when the problem occurred:
https://www.webtoons.com/en/super-hero/war-cry/ep-1/viewer?title_no=1247&episode_no=1

* Please include any additional information about how to reproduce the problem:

## Expected Behavior
Ripping the comic series like it happens in any other comic of the webtoons site.

## Actual Behavior
"No compatible Ripper Found" error

**Comment by cyian-1756** [comment]
@Butterfly-Dragon This is fixed in 1.7.34
