### ISSUE TITLE
There should be a tool to grab the __cfduid and cf_clearance cookies from sites

### ISSUE THREAD

**Issue by cyian-1756** [RipMeApp/ripme#516]
A lot of websites are behind cloudflare, which means ripme can't rip them a deal of the time (Whenever the site own sets cloudflare to I'm being attacked mode). In order to rip from these sites ripme need the  __cfduid and cf_clearance cookies, but in order to get these cookies one must run some arbitrary JS sent by cloudflare. It should be simple enough to write a tool that takes a list of sites, opens them using phantomJS (Or any other headless browser), gets the __cfduid and cf_clearance cookies and writes them to the rip.properties under the name SITENAME.cfduid and SITENAME.cf_clearance

**Comment by kevin51jiang** [comment]
Are the cookies supposed to be for like the whole distribution or is it supposed to run every time someone is ripping something?

**Comment by cyian-1756** [comment]
> Are the cookies supposed to be for like the whole distribution or is it supposed to run every time someone is ripping something?

It should be before the user tries to rip from a site that is in "I'm under attack" mode. It would be pretty pointless to distribute these cookies as the important one (That you need to get pass CFs browser check) expires every hour.

**Comment by cyian-1756** [comment]
I wrote a very basic version of this [here](https://github.com/cyian-1756/cfCookieGrabber). It doesn't work very well yet (It doesn't write the cookies to a file or anything) and it requires firefox

**Comment by psykodelik** [comment]
Have you seen this project?

https://github.com/Anorov/cloudflare-scrape

**Comment by rautamiekka** [comment]
> I wrote a very basic version of this [here](https://github.com/cyian-1756/cfCookieGrabber). It doesn't work very well yet (It doesn't write the cookies to a file or anything) and it requires firefox

So you've already started experimenting with Selenium. Good, that saves me a bit of writing; I was gonna suggest using a **headless** Selenium.

But I got some links that might help you a bit:
- https://www.youtube.com/watch?v=nqaY0UgRcFQ
    - Also has useful links in comments.
    - Uses Firefox in the example, but if you need Chrome that should be easily done too.
- https://thefriendlytester.co.uk/2017/04/new-headless-chrome-with-selenium.html
