### ISSUE TITLE
Trying to download a reddit page, all I get is a text file

### ISSUE THREAD

**Issue by Thorazin** [RipMeApp/ripme#520]
* Ripme version: 1.7.35
* Java version:  9.0.1
* Operating system:  Mac OS 10.13.5 Beta
* Exact URL you were trying to rip when the problem occurred: https://www.reddit.com/r/funsized/
* Please include any additional information about how to reproduce the problem: 

## Expected Behavior

Detail the expected behavior here.  

I expected it to download the pictures as normal.

## Actual Behavior  

It downloaded a text file.

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

![ripme](https://user-images.githubusercontent.com/36058075/38904386-b7b341d0-426f-11e8-935b-0c162b71f01e.png)

**Comment by cyian-1756** [comment]
It seems you have the option "Save URLs only" checked. Go to the configuration tab and uncheck it

**Comment by Thorazin** [comment]
Duh, okay.  Thanks.
