### ISSUE TITLE
only pulling the first page on instagram. 

### ISSUE THREAD

**Issue by Benwebdev** [RipMeApp/ripme#522]
* Ripme version: 1.7.35
* Java version: 
* Operating system: 
* Exact URL you were trying to rip when the problem occurred: Public instagram: 
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

RIP all the images, page for page like a boss. 

## Actual Behavior

Only downloading first page and then throwing the toys out the pram.

I'm sure instagram have just messed with the endpoints again right?

**Comment by Hrxn** [comment]
> I'm sure instagram have just messed with the endpoints again right?

Yes, exactly. Same issues with other projects, etc.
Although I think it should be doable, as of writing this comment here 😄 

_(Keep request signing, but remove CSRFToken, and limit item-count to 50?)_
