### ISSUE TITLE
tumblr malformedURLException unknown protocol HTTPSS

### ISSUE THREAD

**Issue by erofanboy** [RipMeApp/ripme#523]
* Ripme version: 1.7.35
* Java version: 1.8.0_161
* Operating system: 
* Exact URL you were trying to rip when the problem occurred: https://doubledmaster.tumblr.com/
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Detail the expected behavior here.

## Actual Behavior

throws malformedURLexception: unknown protocol: httpss  (mention the double s)
[log.txt](https://github.com/RipMeApp/ripme/files/1926927/log.txt)

**Comment by erofanboy** [comment]
Hi @cyian-1756 , I've verified on another computer, same problem exist.

I'm willing to provide more info, just give a sign which info you want.

**Comment by cyian-1756** [comment]
@erofanboy Does this happen on all tumblr albums or just this one? How far in does it happen (I've ripped about 300 images from that account and haven't gotten an error)?

**Comment by erofanboy** [comment]
It happens on all albums. This is very strange. This evening I will take a closer look on my devices. I'll give an update then
