### ISSUE TITLE
Hentai-Foundry stopping after one image

### ISSUE THREAD

**Issue by Kylis** [RipMeApp/ripme#53]
* Ripme version: 1.5.7
* Java version: 8 Update 144
* Operating system: Win10
* Exact URL you were trying to rip when the problem occurred: http://www.hentai-foundry.com/pictures/user/JLullaby
* Please include any additional information about how to reproduce the problem:

It downloaded the first image in the 207 image album and then stopped claiming it was done and returning "Error: null"

**Comment by rautamiekka** [comment]
Although I confirm it downloaded only 1 pic, I also confirm the page says it lists 1 item out of 1 items despite the 'Pictures' tab reading 207. This happens regardless of browser (Firefox 54.0.1 x64, Chrome 60.0.3112.101 x64, Internet Explorer 11.x x64) and adblocking.

2 options:
1) The site is coded this way to force you to register. That or it's a bug.
2) The uploader has done something.

My money is on the site forcing registration.

**Comment by Kylis** [comment]
The are definitly 207 pictures there. I have an account with them, how can I get ripme to take advantage of me being signed in?

**Comment by rautamiekka** [comment]
^ Judging from RipMe code the ripper doesn't login but otherwise knows what it's doing, so this is a 'website changed' issue. Or do you know if HF did this before, @Kylis ?

**Comment by Kylis** [comment]
It has required a login to access all the images for quite awhile. I am unsure about for exactly how long but at least the last few months.

**Comment by rautamiekka** [comment]
^ In which case it's a 'website changed' issue. The ripper has been updated 9 times, latest one 4 months ago, plus its creation, so the site has changed quite a bit over the 3 years RipMe has supported it, since 1.0.68.

**Comment by Kylis** [comment]
Not sure how to or even if I can change the label to this issue to reflect its a 'website changed' issue.

**Comment by rautamiekka** [comment]
^ Neither of us can. If you could you'd know.

**Comment by Kylis** [comment]
I suppose it could also use a authentication code from the cookies for staying logged in if that is possible. I am guessing thats what the twitter and tumbler ripper do?

**Comment by cyian-1756** [comment]
> I am guessing thats what the twitter and tumbler ripper do?

The tumblr ripper uses an API key not cookies

**Comment by Kylis** [comment]
Yes but might that key be in one of the cookies it leaves on your system? I am not saying use the cookie I am saying use some data that might be found in the cookie that is telling it this system is signed in till X date.

**Comment by cyian-1756** [comment]
> Yes but might that key be in one of the cookies it leaves on your system?

Nope. You need to log in to tumblr and create a new app to get an API key

**Comment by aa9000095** [comment]
The problem comes from the site having an automatic image filter which, by default, block quite a lot of tags/types of images.

It can be solved by using a cookie where the filters are modified to allow everything or by connecting to an account where the filters are modified to allow everything.

**Comment by Kylis** [comment]
Yeah, it would be nice if it could just essentially piggieback on my account that I am signed in on.

**Comment by cyian-1756** [comment]
This is fixed in 1.7.38
