### ISSUE TITLE
Ripme keeps popping txt files containing urls

### ISSUE THREAD

**Issue by samt108** [RipMeApp/ripme#548]
* Ripme version: 1.7.39
* Java version: "Java is not recognized as an internal or external command"
* Operating system: Windows 1709
* Exact URL you were trying to rip when the problem occurred: don't know
* Please include any additional information about how to reproduce the problem: just ripping a whole bunch of urls seems to produce the problem

## Expected Behavior

Not opening any .txt files

## Actual Behavior

Opens a huge number until I eventually stop the program

**Comment by cyian-1756** [comment]
Is it actually opening the txt files or just writing them? Is "Save URLs only" checked? If so uncheck it

**Comment by samt108** [comment]
Yes, it was opening the files. Yes, it was checked. I unchecked it and it seems to be fixed. What does that button do?

**Comment by cyian-1756** [comment]
> What does that button do?

Instead of downloading the files it just saves the file urls to a text file so they can be downloaded by something besides ripme
