### ISSUE TITLE
A JSONObject text must begin with '{' at 1 [character 2 line 1] error on instagram 

### ISSUE THREAD

**Issue by bossman762x39** [RipMeApp/ripme#557]
* Ripme version: 1.7.39
* Operating system:macos 
 i am using the ripme GUI and 2 days ago could rip instagram but today it comes up with 
A JSONObject text must begin with '{' at 1 [character 2 line 1]  and its not a private profile and i even tried same profiles i did 2 days ago and they dont work today. any fix? i am new to code so please be as simple as possible. i am currently just using the GUI for ripme

**Comment by cyian-1756** [comment]
What url are you trying to rip?

**Comment by bossman762x39** [comment]
https://www.instagram.com/p/BhpebLTDI09/?taken-by=bossman19 is the specific one but it does it with every instagram link i try

**Comment by cyian-1756** [comment]
It's working fine for me. Wait a bit and then try again

**Comment by bossman762x39** [comment]
thank you. waited a few mins and it started working again. not sure what happened did not install anything new but working fine now thanks.
