### ISSUE TITLE
Piig

### ISSUE THREAD

**Issue by GreenTeaLord** [RipMeApp/ripme#558]
* Ripme version:
* Java version: 
* Operating system: 
* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Detail the expected behavior here.

## Actual Behavior

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Comment by cyian-1756** [comment]
@GreenTeaLord It seems you made an empty issue

**Comment by cyian-1756** [comment]
I'm closing this because it's blank
