### ISSUE TITLE
Pauses between pages at Deviantart

### ISSUE THREAD

**Issue by AlexFundorin** [RipMeApp/ripme#56]
v1.5.7
When downloading galleries, there's a huge pause between pages with "downloading next page" message in log. I've tried reducing and increasing timeout in settings to get rig of that pause, but it isn't working.
Tried with random galleries.

P.S. It would also be nicie to have an extra option in settings, that would allow to download not only the main gallery, but also the folders. Thanks.

**Comment by rautamiekka** [comment]
Sadly, that huge pause is a problem on DA's end, at least for 99% of the time. You should use only 1 thread for that reason and if possible not run multiple RipMe instances, with a minimum of 6000 milliseconds (6 seconds) timeout. It doesn't seem like you'll get banned anytime soon, though, but the pause will just get worse. My advice by experience is let it run for max 45mins and if it doesn't get anywhere regardless of the timeout, stop it and re-start.

The support for recursive ripping at DA is broken (https://github.com/4pr0n/ripme/issues/550, back at the old GitHub location) and there aren't many ppl who can write the Java, and those ppl are busy with other stuff.

**Comment by AlexFundorin** [comment]
Thank you for the clarification.
