### ISSUE TITLE
Ripme only getting the first 12 or so images on Instagram again

### ISSUE THREAD

**Issue by thinkpad4** [RipMeApp/ripme#563]
@cyian-1756 * Ripme version: 1.7.41
* Java version: Latest
* Operating system: Win7 sp1 64bit
* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/taylorswift
* Please include any additional information about how to reproduce the problem:
Only getting the first 12 images again
## Expected Behavior
To get the whole album
Detail the expected behavior here.
Get the whole album
## Actual Behavior
Only getting the first page or 12 images
Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Comment by pinnie** [comment]
1.7.43 was working fine for me last night, but now getting this behaviour for any album I try. Default settings. Album pages loading fine in browser, so IP hasn't been rate limited.
