### ISSUE TITLE
not fully ripping reddit profiles

### ISSUE THREAD

**Issue by tokimcbongrip** [RipMeApp/ripme#572]
* Ripme version:1.7.44
* Java version: unsure
* Operating system: win 10 
* Exact URL you were trying to rip when the problem occurred: https://www.reddit.com/user/slothgonewild
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

 rip all images

## Actual Behavior 

only rips an image or two happens on all reddit user profiles

**Comment by kevin51jiang** [comment]
Are you using the redesign?

**Comment by kevin51jiang** [comment]
Can't reproduce. Managed to download 98 images, and that user posted ~100 images.

@tokimcbongrip can you go into your command prompt and type in `java --version` and post what shows up?

**Comment by tokimcbongrip** [comment]
sorry complete user error. i figured it out. recently lost my download drive. when i went to re rip favs i didnt realize i had to delete the url logs. so it was only downloading new stuff not old. im sorry for the false alarm i fixed it. thanks for the speedy attempt at help.
