### ISSUE TITLE
DeviantArt won't download past the first page of a gallery

### ISSUE THREAD

**Issue by daBomb61978** [RipMeApp/ripme#59]
Once the newest 24 images are downloaded, RipMe believes it is at 100% and stops. Is there a configuration to make sure the entire gallery downloads?

**Comment by rephormat** [comment]
Please provide an example URL for troubleshooting.

**Comment by daBomb61978** [comment]
[Example](https://orioto.deviantart.com/gallery/)

Well, this is weird. I deleted the old files and tried it again, and now it's downloading the rest of the gallery, too. I guess all I had to do was try again? Thanks anyway!
