### ISSUE TITLE
Hentai2read erroring out with "Must supply a valid URL"

### ISSUE THREAD

**Issue by cyian-1756** [RipMeApp/ripme#593]
* Ripme version: 1.7.45
* Java version:  1.8.0_171
* Operating system:  Ubuntu 16.04
* Exact URL you were trying to rip when the problem occurred: https://hentai2read.com/sm_school_memorial/1/
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

The album rips

## Actual Behavior

The ripper errors out with Must supply a valid URL

**Comment by btracer** [comment]
You need to link on manga preview page, You link is for just first page of this manga. Delete "/1/" in the end of link and this would be work.

**Comment by cyian-1756** [comment]
> You need to link on manga preview page, You link is for just first page of this manga.

The ripper should work with either.
