### ISSUE TITLE
Xhamster url country prefix

### ISSUE THREAD

**Issue by andrebertini** [RipMeApp/ripme#596]
Hello, I would like to ask for an improvement.
The url of xhamster now contains a country prefix, here for me which is Brazil the url begins with pt
https://en.xhamster.com/
When I paste the link in the ripme it accuses error that does not recognize the url

**Comment by rephormat** [comment]
@andrebertini Please provide the version or ripme, java version, operating system, and url you are using so we can attempt to reproduce.  Using the latest version of ripme 1.7.51 I was able to download a test url using the country prefix above.

**Comment by andrebertini** [comment]
Hi,Current Version 1.7.51Java Version 8, Atualization 171 - Build 1.8.0_171-b11Operation System Windows 7 Pro - 64 bitsURL https://pt.xhamster.com/photos/gallery/silvana-7105696
Msg: Can`t rip this URL: No compatible ripper found
Thanks
    Em terça-feira, 12 de junho de 2018 21:09:00 BRT, rephormat <notifications@github.com> escreveu:  
 
 
@andrebertini Please provide the version or ripme, java version, operating system, and url you are using so we can attempt to reproduce. Using the latest version of ripme 1.7.51 I was able to download a test url using the country prefix above.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub, or mute the thread.

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Xhamster url country prefix · Issue #596 · RipMeApp/ripme

Hello, I would like to ask for an improvement. The url of xhamster now contains a country prefix, here for me wh...
 |

 |

 |





| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Build software better, together

GitHub is where people build software. More than 28 million people use GitHub to discover, fork, and contribute ...
 |

 |

 |
