### ISSUE TITLE
Deviantart login fails

### ISSUE THREAD

**Issue by SpiritQuaddicted** [RipMeApp/ripme#599]
* Ripme version: 1.7.46
* Java version: 
openjdk version "9.0.4"
OpenJDK Runtime Environment (build 9.0.4+11)
OpenJDK 64-Bit Server VM (build 9.0.4+11, mixed mode)

* Operating system: Linux
* Exact URL you were trying to rip when the problem occurred: https://marko-djurdjevic.deviantart.com/gallery/
* Please include any additional information about how to reproduce the problem: Happens with any DA urls

## Expected Behavior

ripme uses my credentials from ~/.config/ripme/rip.properties

deviantart.username=foo
deviantart.password=bar

## Actual Behavior

```
Retrieving https://marko-djurdjevic.deviantart.com/gallery/
Failed to login: 
java.io.IOException: No auth_secure or auth cookies received
	at com.rarchives.ripme.ripper.rippers.DeviantartRipper.loginToDeviantart(DeviantartRipper.java:467)
	at com.rarchives.ripme.ripper.rippers.DeviantartRipper.getFirstPage(DeviantartRipper.java:130)
	at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:86)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:533)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by cyian-1756** [comment]
It looks like DA changed how their login system works

**Comment by cyian-1756** [comment]
Looks like DA has started outright blocking automatic logins

**Comment by SpiritQuaddicted** [comment]
Thanks!

**Comment by cyian-1756** [comment]
@SpiritQuaddicted To login using ripme 1.7.52 you have to use cookies and not your username and password. To do so login to DA using a web browser (and be sure to click the remember me button) and then view your cookies (how exactly to do this will differ based on your browser) and copy the auth, auth_secure and userinfo into rip.properties. 

The entry in rip.properties should look like "auth=AUTH_COOKIE_GOES_HERE;auth_secure=AUTH_SECURE_COOKIE_GOES_HERE;userinfo=USERINFO_GOES_HERE
