### ISSUE TITLE
Instagram error : Unterminated string at 65631 [character 65632 line 1] 

### ISSUE THREAD

**Issue by Dler666** [RipMeApp/ripme#601]
When launching RipMe on this IG : 
https://www.instagram.com/janduxo 

It stops and says  
Error : Unterminated string at 65631 [character 65632 line 1]

**Comment by cyian-1756** [comment]
> Does it workfor you ?

Yes

**Comment by Dler666** [comment]
It works completely ? 

For me after 90~ photos it stops

What should i do ?

**Comment by kevin51jiang** [comment]
Confirmed it's not working.

It's messing up while trying to get the next page.

**Comment by cyian-1756** [comment]
Found the issue, it seems that the json is randomly cut off, it's ends with `:{"edges":[{"node":{"text":"How many siblings do you have?  </body></html>`.

**Comment by cyian-1756** [comment]
Looks like this is a bug with Jsoup it self



If you run the following code

```
URLConnection connection = new URL("https://www.instagram.com/graphql/query/?query_hash=" + qHash
                        + "&variables=" + vars).openConnection();
                connection.setRequestProperty("User-Agent", USER_AGENT);
                connection.setRequestProperty("x-instagram-gis", ig_gis);
                BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()));
                String line;
                StringBuilder sb = new StringBuilder();
                while ((line = in.readLine()) != null) {
                    sb.append(line);
                }
                in.close();
```
`sb.toString()` returns the full JSON but `Jsoup.parse(sb.toString()))` only returns the first 65632 chars
