### ISSUE TITLE
hentai2read ripper can only download the first issue of a multi-issue manga.

### ISSUE THREAD

**Issue by stalwartmonkey** [RipMeApp/ripme#604]
* Ripme version: 1.7.46
* Java version: 
* Operating system: 
* Exact URL you were trying to rip when the problem occurred: 
https://hentai2read.com/ghost_love/ 
https://hentai2read.com/ghost_love/1/

* Please include any additional information about how to reproduce the problem:
## Actual Behavior

Ripme app can only download the first issue of a manga, if there are multiple issues listed.

If you copy/paste either https://hentai2read.com/ghost_love/ or https://hentai2read.com/ghost_love/1/ it downloads issue number 1. But if you try https://hentai2read.com/ghost_love/2/1/ or any others, it throws an error, saying that it expected something different. 

## Expected Behavior

Ideally, ripme should download all issues if you give it the root comic address, or download one at a time if given the more specific address. If doing both is too much of a pain to code, just downloading one at a time is preferable.

**Comment by cyian-1756** [comment]
> But if you try https://hentai2read.com/ghost_love/2/1/ or any others, it throws an error, saying that it expected something different.

I can confirm this. As a temopry workaround you can enter the URL as https://hentai2read.com/ghost_love/2

**Comment by cyian-1756** [comment]
@stalwartmonkey 

As of 1.7.47 ripping a url in the format of https://hentai2read.com/ghost_love will download every issue
