### ISSUE TITLE
JSON error ripping twitter accounts

### ISSUE THREAD

**Issue by DopefishJustin** [RipMeApp/ripme#639]
* Ripme version: v1.7.50
* Java version: 1.8.0_171
* Operating system: Microsoft Windows [Version 6.3.9600]

* Exact URL you were trying to rip when the problem occurred: https://twitter.com/dopefishjustin

Any twitter account fails with this error:

Error while parsing JSON: {"rate_limit_context":{"application":"UoXn7coZdwbtSy0MHvUug"},"resources":{}}

Used to work until today.

**Comment by kevin51jiang** [comment]
That's just twitter saying to you you're using it too much, and they want you to slow down. 

That said, maybe we could implement an API key switcher like with tumblr. Might be something to update.

**Comment by DopefishJustin** [comment]
The message is the same on two computers with different IPs so it's built in somewhere, it's not mine. A configurable key would be good, apparently I do have a key from a while back.

**Comment by kevin51jiang** [comment]
Would you look at that, the option to change Twitter API keys is already in the app.

Go into `rip.properties`, and in the `twitter.auth` field, you want to put your API key after it gets encoded using [this website](https://www.base64encode.org/).

To get a consumer API key, follow [this video](https://www.youtube.com/watch?v=1p8veF-sIIo)

**Comment by cyian-1756** [comment]
@kevin51jiang 

> That said, maybe we could implement an API key switcher like with tumblr. Might be something to update.

AFAIK twitter requires a cellphone number be provided in order to make a new account. I imagine this would make making throwaways for api keys more difficult

**Comment by tehloxely** [comment]
I just got this error today as well. And I haven't used RipMe in over 2 days.

**Comment by cyian-1756** [comment]
@tehloxely 

> And I haven't used RipMe in over 2 days.

The rate limit is attached to the api key which all ripme users share

**Comment by DopefishJustin** [comment]
It's working again.
