### ISSUE TITLE
Not Downloading 4chan Images

### ISSUE THREAD

**Issue by JSHueurgh** [RipMeApp/ripme#664]
Not downloading images on 4chan.
It does download WEBM's
![1020a816742eba4e9fbb11c87526d42d](https://user-images.githubusercontent.com/39962503/40989152-dd142bce-68e4-11e8-9be4-465733a402fe.png)
![5f1c823ff0efcb564f343827fe2ed771](https://user-images.githubusercontent.com/39962503/40989155-df758e80-68e4-11e8-9c8a-76b60fd3a7c9.png)
Possibly to do with the hosting server 'is3', this is where images are being hosted now.

**Comment by cyian-1756** [comment]
@JSHueurgh What url were you trying to rip?

**Comment by JSHueurgh** [comment]
http://boards.4chan.org/b/thread/770735540
Any url from 4chan that had the images hosted on an 'is3.4chan' link wasn't working, the WEBM's would download because they are on a 'i.4cdn' link.
Images that have the url 'is2.4chan work'.

**Comment by cyian-1756** [comment]
@JSHueurgh 

> URL - 'http://boards.4chan.org/b/thread/770735540'

That link is 404ing

**Comment by kevin51jiang** [comment]
It's a ripme issue. 

Found in ChanRipper.java

```
new ChanSite(Arrays.asList("boards.4chan.org"), Arrays.asList("4cdn.org", "is.4chan.org", "is2.4chan.org"))
```

It's an easy enough fix. 

@cyian-1756 

4chan links 404 quite often because old threads are basically deleted.
