### ISSUE TITLE
FurAffinity ripper downloading less-than-expected images

### ISSUE THREAD

**Issue by UnforeseenOcean** [RipMeApp/ripme#671]
* Ripme version: 1.7.50
* Java version: 1.8.0_114
* Operating system: 6.1.7601
* Exact URL you were trying to rip when the problem occurred: https://www.furaffinity.net/user/grisser/
* Please include any additional information about how to reproduce the problem:
Attempt to download using that exact link.
## Expected Behavior
Downloaded entire album.

## Actual Behavior
Downloaded only 36 or fewer pictures.

**Comment by cyian-1756** [comment]
Attempting to rip https://www.furaffinity.net/user/grisser/ makes ripme throw an error, ripping https://www.furaffinity.net/gallery/grisser/ downloads 176 images

**Comment by UnforeseenOcean** [comment]
It's still a problem; It's supposed to get at least 500 images from that user. For every user I throw at it, it only downloads 36 (or fewer pictures if the user has less than 36 pictures)

**Comment by cyian-1756** [comment]
@UnforeseenOcean 

Trying upgrading to 1.7.51 and see if anything changes

> It's supposed to get at least 500 images from that user.

How do you know? Does FA have an image count or something I'm just not seeing? Because that user only appears to have 4 pages of images in their gallery

**Comment by UnforeseenOcean** [comment]
It must be due to NSFW filter. Try logging in. Also, yes, it does have a counter.
![image 295](https://user-images.githubusercontent.com/11834016/41177181-1f3545e0-6b9e-11e8-8c98-1739a41ec8d1.png)

**Comment by cyian-1756** [comment]
> It must be due to NSFW filter

In that case either FA changed how their logins work or ripmes account got banned, I'll get on fixing it

**Comment by cyian-1756** [comment]
@UnforeseenOcean 

Logging in I still can't get more than 171 images from https://www.furaffinity.net/gallery/grisser/, is there some setting I have to turn on to view NSFW content?

**Comment by cyian-1756** [comment]
@UnforeseenOcean Can you retest with ripme 1.7.52?

**Comment by UnforeseenOcean** [comment]
Testing now. Will update once the results come in.

**Comment by cyian-1756** [comment]
> Update: Gets stuck at DeviantART link.

You mind explaining in a bit more detail?

**Comment by UnforeseenOcean** [comment]
It just hangs at "Downloading https://username.deviantart.com/?catpath=" That's all.

Also, if there are a lot of files that are being skipped, this happens:
![image 434](https://user-images.githubusercontent.com/11834016/41500606-d5d41e84-71cf-11e8-9fe1-24dd2bddef5d.png)

**Comment by cyian-1756** [comment]
> It just hangs at "Downloading https://username.deviantart.com/?catpath=" That's all.

That's weird, I have no idea where it would be getting a DA link from. Are you sure you're ripping https://www.furaffinity.net/gallery/grisser/ and only that url?

**Comment by UnforeseenOcean** [comment]
Since I could not batch-deselect the links from History tab, I had to run the ripper against all 180 links. I will let you know if it works when it goes around to the desired link.

**Comment by cyian-1756** [comment]
> Since I could not batch-deselect the links from History tab, I had to run the ripper against all 180 links

You could always just enter the url into the text field at the top of ripme and click rip.

**Comment by UnforeseenOcean** [comment]
Solved, removed all other entries.

Also, how can I use my own account for downloading?

**Comment by UnforeseenOcean** [comment]
It seems to be working fine now.

**Comment by cyian-1756** [comment]
> Also, how can I use my own account for downloading?

Login to FA in a web browser (be sure to click remember me), view your cookies (How to do this will depend on your web browser) and then add the FA cookies to rip.properties.

When done you should have a line in rip.properties that reads "furaffinity.cookies = a=cookieA;b=cookieB"

**Comment by cyian-1756** [comment]
> It seems to be working fine now.

Then I'm going to close this issue
