### ISSUE TITLE
Windows 7/10: Pin the app to Start Menu or Taskbar

### ISSUE THREAD

**Issue by tehloxely** [RipMeApp/ripme#677]
Please add the ability to pin the program to the Start menu or the Task Bar. It would make it easier to find the program and use it.

**Comment by kevin51jiang** [comment]
If you follow [this tutorial for the start menu](https://www.howto-connect.com/add-remove-items-on-start-menu-on-windows-10/) and [this one for the taskbar](https://www.wikihow.com/Pin-a-Program-to-the-Windows-10-Taskbar) you should find that RipMe already supports being pinned to the start menu/taskbar just like every other program.

**Comment by tehloxely** [comment]
You cannot do that with the current version of RipMe.

**Comment by Hrxn** [comment]
Create a shortcut (shortcut file, `.LNK`), you can 'pin' those as it's intended.

**Comment by tehloxely** [comment]
Explain please.

**Comment by cyian-1756** [comment]
@tehloxely Right click ripme.jar, select "Create shortcut", pin the short cut to your taskbar/startmenu

**Comment by tehloxely** [comment]
@cyian-1756 That doesn't work either.

**Comment by Hrxn** [comment]
![2018-06-14_064959](https://user-images.githubusercontent.com/12064918/41392174-54feedc0-6f9f-11e8-82df-5fda26fd1723.png)

**Comment by metaprime** [comment]
Adding the requested feature is not something we can do AFAIK, that's a Java and/or Windows issue to manage. The shortcut workaround is the best option here.

**Comment by tehloxely** [comment]
@Hrxn No can do. and @metaprime The shortcut option doesn't work.
![asdasdasdasdas](https://user-images.githubusercontent.com/1208778/41443791-f344f66a-700c-11e8-815d-961e9a89f5de.png)

**Comment by cyian-1756** [comment]
@tehloxely 

Try the steps out lined [here](https://superuser.com/questions/975687/how-to-pin-an-executable-jar-to-start-in-windows-10#1018304)

I'm closing this as this is an issue with windows and not something that can be fixed on ripmes end
