### ISSUE TITLE
furaffinityRipper can disclose users IP addresses

### ISSUE THREAD

**Issue by cyian-1756** [RipMeApp/ripme#680]
* Ripme version: 1.7.51
* Java version:  NA
* Operating system: NA

* Exact URL you were trying to rip when the problem occurred: NA
* Please include any additional information about how to reproduce the problem: NA

Because the furaffinityRipper logs in inorder to download nsfw posts, furaffinity.net logs the ip of every ripme user who rips from the site. This on it's own would be fine but *any user of ripme could log in and see the ip of any other user*. This is at least a minor concern 

Thankfully FA only shows the last 100 logins and deletes this data every 6 months and it doesn't include what pages where accessed

That being said ripme should both warn users that this data is publicly viewable and give them the option to use their own login instead of ripmes shared login

**Comment by cyian-1756** [comment]
I think that ripme should remove the cookies from the jar and instead read them from ripme config file. This would allow users to use their own accounts (And get rid of any privacy concerns)

We could also move the current shared account cookies to the wiki and include a warning that using the shared account will disclose some user data. 

@kevin51jiang @rautamiekka I'd like to hear both of your inputs on this

**Comment by kevin51jiang** [comment]
Like most people. I'm lazy. 
I don't want to spend the extra 2 minutes going onto the wiki and getting the right API keys, nor do I want to have to go online to reset everything to a default stage.

I'd prefer everything to be included as is, however, give a config option to change the cookies of every single ripper, and give a popup on the first startup about "Change API keys if you want privacy", but that should be the extent of which would be responsible enough for us. A good balance between privacy and convenience.

After all, we are an open source project, they can come onto GitHub to investigate the code, should they choose it, and most of all Java can be easily decompiled so they're even able to prove that our release versions are being compiled from the same source.

**Comment by rautamiekka** [comment]
Not using a shared acc also prevents FA from connecting the dots that'd indicate use of shared acc, avoiding getting that acc banned and the site taking appropriate measures against automated downloading.

Sounds good to me.

**Comment by metaprime** [comment]
I think it makes sense to have the default cookies (I want this program to "just work", but since I'm also concerned about privacy, maybe pop up a warning the first time to the effect that "ripme will use a shared cookie and may result in disclosure of your information to other ripme users, if you'd like to use your own user login cookie instead, see the wiki" blah blah

**Comment by cyian-1756** [comment]
As ripme now warns users about the shared login and gives them the option to use their own cookies I'm closing this
