### ISSUE TITLE
Hitomi, Tsumino, etc does not rip now

### ISSUE THREAD

**Issue by Helliane** [RipMeApp/ripme#686]
* Ripme version: 1.7.51
* Java version:  N/A
* Operating system:  Windows 10

Hitomi, Tsumino, ehentai does not rip now, it only rips the urls and opens a text with url to each picture instead of the pictures itself.

**Comment by cyian-1756** [comment]
You have the option "Save urls only" in the configuration menu checked. Uncheck it everything should go back to normal
