### ISSUE TITLE
Can't Rip anything

### ISSUE THREAD

**Issue by Seaweedx** [RipMeApp/ripme#688]
When i open the RipMe.jar with Java i can see the window but it says "Inactive" and i cant RIP or get in the Configurations options. How do i run the program? I'm using windows 10, 64-bit and my Java is 8.

Edit: RipMe version 1.7.51

**Comment by cyian-1756** [comment]
> When i open the RipMe.jar with Java i can see the window but it says "Inactive" and i cant RIP or get in the Configurations options.

To rip something paste a url into the text field next to the rip button and then press rip, to open the configuration menu click the tab that says "Configuration"

**Comment by Seaweedx** [comment]
Like i said, that doesn't work. Nothing happens when i click the options. It's like clicking on your desktop, none of the options work including others (Log, History, Queue, Configurations and Rip)
There is only a blank space and it says "Inactive" above the options.

**Comment by Seaweedx** [comment]
I am not very familiar on how to record a video on my desktop (in other words, outside of games), but i will try.
There is a possibility of me doing something wrong, but i clearly followed the "How to install Java" and "How to run RipMe.jar" guides.

**Comment by rautamiekka** [comment]
What's your Java version ?

**Comment by Seaweedx** [comment]
Latest version, 8.

**Comment by rautamiekka** [comment]
^ No, you didn't state which Update in the OP, in this case Java SE 8 **Update 171**.

Hmm, I guess it's another Win10-exclusive bug by Micro$oft. Uninstalling SE8u171 and installing an SE10 might solve the problem.

**Comment by cyian-1756** [comment]
@Seaweedx 

Can you start ripme from the command line (`java -jar path/to/ripme.jar`), try to rip something and post the output?

**Comment by Seaweedx** [comment]
@cyian-1756 
That actually worked ! After few unsuccessful attempts because i wasn't sure how to type the address, since my windows is in Japanese and copying the address adds some symbols that Command Prompt apparently doesn't read.

Thank you so much for the help, I will try to Rip Albums now and see how it goes 👍 
![screenshot 278](https://user-images.githubusercontent.com/40184136/41298784-ac548976-6e6a-11e8-82fd-bd934d939c28.png)

**Comment by cyian-1756** [comment]
> That actually worked ! 

Yay!

But I'd still link to figure out why ripme wasn't working, can you post the command line output?

**Comment by Seaweedx** [comment]
Of course!

java -jar D:Ripp/ripme.jar

**Comment by cyian-1756** [comment]
> java -jar D:Ripp/ripme.jar

And what appeared after that? Also how where you starting ripme before (Clicking the jar, pinning it to your taskbar and running it)?

**Comment by Seaweedx** [comment]
At first i opened RipMe.jar by Righ clicking > Open With > Java
And you saw the result which was the video i posted.

After you told me this command and i tried i posted screenshot of the RipMe working properly, as you can see there are other options below than just a blank space.
I also ripped my first album, the one i tried ripping in the video and it was fast, with full quality images downloaded.

**Comment by cyian-1756** [comment]
> At first i opened RipMe.jar by Righ clicking > Open With > Java
 > And you saw the result which was the video i posted.

That's really strange. There shouldn't be any difference between starting ripme by clicking it vs from the command line

**Comment by Seaweedx** [comment]
Well, i don't know i started it few more times by right clicking > open with > java, and that still doesn't work, but it does work with the command prompt!
I guess i'll open it like this, i don't mind as long as it works.

**Comment by cyian-1756** [comment]
I'm going to close this as you got it working, but I still have no idea why starting it via clicking isn't working
