### ISSUE TITLE
E621 Won't download when a "Order:Score" is in URL

### ISSUE THREAD

**Issue by thedxdan** [RipMeApp/ripme#692]
* Ripme version: 1.7.51
* Java version: 
* Operating system:  WIN 10

* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem: https://e621.net/post/index/1/derpy_hooves%20order:Score

## Expected Behavior

Detail the expected behavior here. To download all images by order of score 

## Actual Behavior Recieved error telling me incorrect URL

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.
![image](https://user-images.githubusercontent.com/40245857/41369381-9d85100a-6f3c-11e8-9eda-67664d1993c9.png)

**Comment by thedxdan** [comment]
Anyone know a way to bypass or fix this?

**Comment by rautamiekka** [comment]
^ Looks simple to me but I can't test it: the RegEx (https://github.com/RipMeApp/ripme/blob/master/src/main/java/com/rarchives/ripme/ripper/rippers/E621Ripper.java#L99) which throws that error doesn't see the colon as a valid character.
