### ISSUE TITLE
Reddit & its limits

### ISSUE THREAD

**Issue by samsepiol59** [RipMeApp/ripme#696]
Hello, I've started ripping images heavy subreddits (models, actresses, etc) and something strange's happening.

I know reddit has a 1000 posts limit on its API, so I wasn't surprised when /r/DaisyRidley downloaded just less than 1000 images (I assume they count deleted ones too?). But then I tried and rip /r/NatalieDormer and I was surprised to be greeted with close to 2000 images. Why is this happening?

By the way, I'm on Linux.

**Comment by cyian-1756** [comment]
> I assume they count deleted ones too?

Yup

> But then I tried and rip /r/NatalieDormer and I was surprised to be greeted with close to 2000 images. Why is this happening?

Because some posts are links to more than one image (Mainly imgur galleries) and ripme downloads all images from these galleries

**Comment by cyian-1756** [comment]
As this question has been answered I'm closing this issue
