### ISSUE TITLE
Java Process Not Ending On Close, And Duplicating On Relaunch

### ISSUE THREAD

**Issue by Davrial** [RipMeApp/ripme#70]
* Ripme version: 1.5.7 (Issue has been around longer though)
* Java version: 1.8.0_141
* Operating system: Windows 10
* Exact URL you were trying to rip when the problem occurred: N/A
* Please include any additional information about how to reproduce the problem: Close the window, then view processes

## Expected Behavior
Closing application ends processes

## Actual Behavior

When I close the application, the Java process keeps running in the background, visible in Task Manager. It doesn't even reduce in memory occupancy, it just stays there. Launching the program again doesn't even fix this or "resume" using this leftover process, and actually creates _another_ Java process instead.

This issue has been around for multiple updates of RipMe, multiple Java updates, and multiple Windows updates, as well as full re-installs of RipMe and Java, so I'm fairly certain this is not an issue with my computer.

It's easy to end the process of course, but it's a real pain that I have to pull up Task Manager just to do so whenever I close RipMe.

**Comment by cyian-1756** [comment]
I've never run into this on Ubuntu 16.04 (using openjdk version "1.8.0_131") and I run ripme every hour or so.

So it seems like this might be a windows only bug

**Comment by rautamiekka** [comment]
@Davrial Try updating to Update 144 and try this problem again after a reboot. If it doesn't, check out (my comment at) https://github.com/4pr0n/ripme/issues/412

**Comment by Davrial** [comment]
@rautamiekka I tried disabling "restore window position" like that person in the other thread did and it seems to have fixed the problem. That seems like a really weird and specific bug.

**Comment by rautamiekka** [comment]
^ Yeah, it's a weird thing, and like @metaprime put it, disturbing development.

**Comment by metaprime** [comment]
I'm thinking at this point that we could just disable the "restore window position" option. How many people really care if the window is always launched centered in the middle of the screen as opposed to reappearing where they left it last? It would be nice if we could disable that functionality only on Windows. I forget, is there a way to detect platform in Java?

**Comment by rautamiekka** [comment]
^
>I forget, is there a way to **_detect platform_** in **_Java_**?

(Highlight is mine) Sure, easily googled. Or is there something very precise you need ?

**Comment by metaprime** [comment]
Yeah I'm implementing this now.

**Comment by metaprime** [comment]
From poking further, it's not setting the window position that seems to cause the issue, it's something going wrong with saving the window position when the window is closed. Same workaround applies, just in an additional place in the code. Updating.
