### ISSUE TITLE
Pornhub ripper failing

### ISSUE THREAD

**Issue by cyian-1756** [RipMeApp/ripme#711]
* Ripme version: 1.7.52
* Java version:  1.8.0_171
* Operating system:  Ubuntu 16.04

* Exact URL you were trying to rip when the problem occurred: https://www.pornhub.com/view_video.php?viewkey=ph5a329fa707269
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Ripme should rip the video

## Actual Behavior

Ripme errors out with "could not find 'flashvars'"

**Comment by rautamiekka** [comment]
If you feel lazy, you can take the code from `youtube-dl`.

**Comment by cyian-1756** [comment]
Trying to rip this again it worked, so it looks like this is an intermittent issue (Maybe pornhub is sometimes returning a "are you a human?" page or something)

**Comment by tehloxely** [comment]
Just use youtube-dl. They update so often that it's a useful program to have.

**Comment by rephormat** [comment]
@cyian-1756 can you retest with the latest version.  I am able to successfully download without issue on Linux Mint 19.

**Comment by cyian-1756** [comment]
I've not seen this issue pop up again in the last few weeks so I'm closing this
