### ISSUE TITLE
New Ripper ‒ weheartit.com

### ISSUE THREAD

**Issue by bored** [RipMeApp/ripme#721]
There's 3 _areas_ I'd like to see supported if possible:
1. A user's hearts - this is similar to a tumblr blog as it shows any original/self uploaded content and any content the user has re-hearted (re-tweeted, re-blogged, etc.).
Example: https://weheartit.com/sad

1. A user's uploads - this is very similar to a user's hearts except only original/self uploaded content is shown.
Example: https://weheartit.com/sad/uploads

1. Collections - user's can create collections (albums) consisting of either their own and/or other user's content.
Example: https://weheartit.com/sad/collections/142270657-sad
<hr>

There's some unofficial API documentation that might come in handy [here](https://github.com/jordan-wright/weheartit-api).

**Comment by cyian-1756** [comment]
@bored 

Please make any site requests in the sites request issue [here](https://github.com/RipMeApp/ripme/issues/38)

**Comment by bored** [comment]
@cyian-1756 apologies, I only made it in a separate issue because #710 was dealt with. Personally I think it makes more sense to handle them separately since issues don't scale well but I'll post it over there, thanks!

**Comment by cyian-1756** [comment]
> Personally I think it makes more sense to handle them separately since issues don't scale well

Yea, but if you have a different issue for every site then other issues end up getting buried
