### ISSUE TITLE
Saving posts/albums/etc in sub-directory of the save directory *Enhancement*

### ISSUE THREAD

**Issue by inthebrilliantblue** [RipMeApp/ripme#726]
Would it be possible to add an argument flag to save albums/posts/whatever under a sub-directory of the directory we tell it to save to? Example:

Grab http://reddit.com/r/testreddit and save to /savedir
Picture post saved to /savedir/randomname1/picture.jpg
Album post saved to /savedir/randomname2/1.jpg
                                ...
                                /savedir/randomname2/n.jpg

The sub-directory name could be date saved or user-defined in some way.

I really only want this feature for reddit posts, where some posts by users are only a few pictures or so, while others can be hundreds of pictures and videos. Id really like the ability to group them in their own "post folder" instead of having tons of files in the same directory.

**Comment by cyian-1756** [comment]
> Would it be possible to add an argument flag to save albums/posts/whatever under a sub-directory of the directory we tell it to save to?

It should be.

**Comment by inthebrilliantblue** [comment]
Closing issue as this functionality has been added.
