### ISSUE TITLE
ripme 1.7.54 expected url format http got https on deviantart

### ISSUE THREAD

**Issue by critic56** [RipMeApp/ripme#729]
* Ripme version: 1.7.54
* Java version: openjdk java9 runtime
* Operating system:  linux mint 18.4

* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

## Expected Behavior to download a deviantart gallery

Detail the expected behavior here.

## Actual Behavior expected url format :http got https

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Comment by cyian-1756** [comment]
What url were you trying to rip?

**Comment by critic56** [comment]
I tried to rip many. Here are a couple ariverkao (ariver.kao) | DeviantArt
<https://www.deviantart.com/ariverkao/>   aromasensei (Ann Ivanova) |
DeviantArt <https://www.deviantart.com/aromasensei>   diabolumberto
(cédric) | DeviantArt <https://www.deviantart.com/diabolumberto/>   martaino
(Martin) | DeviantArt <https://www.deviantart.com/martaino/>
DarkShadowArtworks
(Dark Shadow) | DeviantArt <https://www.deviantart.com/darkshadowartworks/>

**Comment by hatabbich** [comment]
same here (( dunno what to do

**Comment by Wiiplay123** [comment]
deviantArt changed their profile URL scheme today, the ripper needs to be updated to be able to take both the old and the new format of URL. It seems to give up on trying to get the second page for me even when I give it the old URL, I'm assuming because it redirects to the new URL.

**Comment by cyian-1756** [comment]
> It seems to give up on trying to get the second page for me even when I give it the old URL, I'm assuming because it redirects to the new URL.

Checking a random DA gallery it seems that they've changed how the next page works entirely

**Comment by Wiiplay123** [comment]
Really not looking forward to having to redo my custom code that I have in my personal version of RipMe to match the latest version once this gets fixed :(

(I have two custom skipping modes in my personal fork that make scanning galleries WAY faster but one is at the cost of not recognizing literature, and the other is at the cost of immediately giving up if all the images on the page were already saved.)

**Comment by cyian-1756** [comment]
This has been fixed
