### ISSUE TITLE
Instagram fail

### ISSUE THREAD

**Issue by Dler666** [RipMeApp/ripme#740]
Hello, for this account : https://www.instagram.com/mieshatate

After 1621 rips it says : 

Error : null

Could you fix that please ?

**Comment by cyian-1756** [comment]
I can't reproduce this on ripme 1.7.55

**Comment by cyian-1756** [comment]
I stopped the rip after 1800 images

**Comment by Dler666** [comment]
Ok i retried and it worked fine, sorry for the inconvenience ^^
