### ISSUE TITLE
`final` functions ?

### ISSUE THREAD

**Issue by rautamiekka** [RipMeApp/ripme#747]
* Ripme version: N/A
* Java version:  N/A
* Operating system:  N/A

* Exact URL you were trying to rip when the problem occurred: N/A
* Please include any additional information about how to reproduce the problem: N/A

## Expected Behavior

There are lots of functions in the program which always `return` the same value, for example `false`.

## Actual Behavior

Shouldn't these functions be `final` for that reason ? That's what I understood when I read about `final` functions.

**Comment by cyian-1756** [comment]
> There are lots of functions in the program which always return the same value, for example false.

Can you give some examples?

> Shouldn't these functions be final for that reason ?

I believe so

**Comment by rautamiekka** [comment]
^ About every ripper in RipMe has functions like https://github.com/RipMeApp/ripme/blob/master/src/main/java/com/rarchives/ripme/ripper/rippers/DeviantartRipper.java#L46 in DA ripper for a string and https://github.com/RipMeApp/ripme/blob/master/src/main/java/com/rarchives/ripme/ripper/rippers/DeviantartRipper.java#L54 for a boolean.

Both are overriding ones though.

**Comment by cyian-1756** [comment]
Those be finaled, but I don't see much point. AFAIK all finaling a function does is stop it from being  overridden or hidden

**Comment by rautamiekka** [comment]
^ Those are overriding, not overridden.

**Comment by cyian-1756** [comment]
> ^ Those are overriding, not overridden.

I know, I'm saying it would prevent then from being overridden again (At least I'm pretty sure it would)

**Comment by rautamiekka** [comment]
^ Why'd you override anything from a ripper which already overrides that function from higher up ? Like a subripper ?

**Comment by cyian-1756** [comment]
>  Why'd you override anything from a ripper which already overrides that function from higher up ? 

I don't see any reason you would
