### ISSUE TITLE
Feature Request: Remember used urls

### ISSUE THREAD

**Issue by samt108** [RipMeApp/ripme#75]
Instead of just having a history of URLs ripped, it would be nice to keep a history of actual image URLs. That way I can rip to one place and store everything in another (i.e. not have to have my external HD connected in order to rip).

**Comment by cyian-1756** [comment]
I agree that something like this should be implemented

I say add a check in addURLToDownload() so (if a config option is true) it skips already downloaded URLs

**Comment by rautamiekka** [comment]
And I proposed a possible storage format in https://github.com/RipMeApp/ripme/issues/18#issuecomment-314286281

**Comment by cyian-1756** [comment]
I almost have this working in [this](https://github.com/cyian-1756/ripme/tree/remember_downloaded) fork

**Comment by cyian-1756** [comment]
With my last push to https://github.com/cyian-1756/ripme/tree/remember_downloaded ripme now remembers and skips downloaded urls (For any ripper that uses `addURLToDownload` at least). I still have to go some more testing/make the clear history button remove the url_history file but that should only take 2 or 3 days, unless I find any major errors

**Comment by cyian-1756** [comment]
Done in 1.6.8
