### ISSUE TITLE
There are some HentaiFoundry links that are not working after attempted (Some work some don't)

### ISSUE THREAD

**Issue by TTPython** [RipMeApp/ripme#756]
* Ripme version: v1.7.57
* Java version:  Version 8  Update 91
* Operating system: Wind 10
* Exact URL you were trying to rip when the problem occurred: 

* Exact URL you were trying to rip when the problem occurred: 
* Please include any additional information about how to reproduce the problem:

* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Some links doesn't work. It said; "Failed to Load after # attempted" with these Hentai Foundry link:
https://www.hentai-foundry.com/pictures/user/Akiru
https://www.hentai-foundry.com/pictures/user/Axsens
(maybe some more)

**Comment by cyian-1756** [comment]
I can't reproduce this. Both urls work fine for my on 1.7.57

**Comment by cyian-1756** [comment]
@TTPython If this is still an issue comment and I'll reopen this
