### ISSUE TITLE
DeviantArt rips from unspecified users

### ISSUE THREAD

**Issue by adamus1red** [RipMeApp/ripme#758]
* Ripme version: 1.7.56
* Java version: 1.8.0_171
* Operating system: 10.0.17134.112
* Exact URL you were trying to rip when the problem occurred: https://www.deviantart.com/wlop/
* Please include any additional information about how to reproduce the problem:

Enter the above URL into the RIP url text box and press rip button,

## Expected Behavior

Rips images only uploaded by that user

## Actual Behavior

When ripping, a users gallery it will follow to other users and then rip from their page.
e.g. when ripping from wlop it also rips a single image from landerphotography

`Downloading https://www.deviantart.com/wlop/
Downloading https://orig00.deviantart.net/ebda/f/2018/182/2/b/android_mystic_in_a_sports_coat_by_khonger-dcfz49d.jpg
Downloaded D:\rips\deviantart_wlop\android_mystic_in_a_sports_coat_by_khonger-dcfz49d.jpg
Downloading https://orig00.deviantart.net/2d4d/f/2018/182/4/e/00c0e465_f5ae_4717_ad85_65cc185b2ea1_by_landerphotography-dcfz47v.jpg
Downloaded D:\rips\deviantart_wlop\00c0e465_f5ae_4717_ad85_65cc185b2ea1_by_landerphotography-dcfz47v.jpg`

**Comment by rautamiekka** [comment]
Technically neither `khonger` nor `landerphotography` is what you want since both usernames point to a different person. Did you rip the `wlop`'s gallery or did you stop at those near the beginning ?

**Comment by cyian-1756** [comment]
It looks like DA changed their HTML layout in the last few days, meaning ripme can't get the username or gallery ID anymore. I'll get on fixing this and push an update
