### ISSUE TITLE
On linux ripme should check for it's config files under ~/.config/ripme

### ISSUE THREAD

**Issue by cyian-1756** [RipMeApp/ripme#76]
* Ripme version: 1.5.7
* Java version: 1.8.0_131
* Operating system: Ubuntu 16.04
* Exact URL you were trying to rip when the problem occurred: Any
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Ripme should check for it's various config files (rip.properties, history.json) under /home/$USER/.config/ripme instead of just writing new in which ever dir it was run from

## Actual Behavior

Ripme just generates new config files in whatever dir it was run from

**Comment by rautamiekka** [comment]
You got a point, but similar would have to be implemented for other platforms as well (for instance, I think >=MacOS X never used such notation).

I think, technically, there's such a place on Window$ too, but that's far more tedious to find than on Linux.

And I've no idea how it's done on *BSD, which might even differ on different distros.

**Comment by cyian-1756** [comment]
After a bit of looking I've found the following for where to put config files on various OS

Windows: %APPDATA%/ripme/

MacOS: Either the same as linux (I'm not 100% sure if MacOS has ~/.config) or ~/Library/Application Support/ripme

*BSD: BSD is pretty unixy so I assume ~/.config will exist and if not just write the config info where ever the user ran ripme from

Linux/Unix/*nix like system: ~/.config/ripme

**Comment by qjex** [comment]
Hello. I am new here. I want to start working on this issue. Is is good to follow @cyian-1756 advice about default paths. Default MacOS path for configs: ~/Library/Application Support/

**Comment by cyian-1756** [comment]
> Is is good to follow @cyian-1756 advice about default paths?

I say yea. On most *nix like OSs (minus MacOS) the default path for config files in ~/.config/$Name_of_the_program and on windows people just seem to dump everything in %APPDATA%

**Comment by metaprime** [comment]
For Windows you'd probably want `%LOCALAPPDATA%\ripme` instead of `%APPDATA%\ripme` but TBH I don't really know the difference. I think the intent is that `%APPDATA%` which directs to `%USERPROFILE%\AppData\Roaming` is used for settings that will be synced between systems (though this is still up to the apps individually), and %LOCALAPPDATA% is for the installation on the current system.

**Comment by rautamiekka** [comment]
^ Yes, that's how M$ intended it and for once I don't need to disagree with them.

**Comment by MrTimscampi** [comment]
This could help: https://github.com/harawata/appdirs

It's a Java library made specifically for this kind of thing.
