### ISSUE TITLE
Make RipMe Paths Windows-safe

### ISSUE THREAD

**Issue by kevin51jiang** [RipMeApp/ripme#762]
* Ripme version:
* Java version:  
* Operating system: java 9.0.1

* Exact URL you were trying to rip when the problem occurred: https://www.8muses.com/comix/album/Affect3D-Comics/TheDude3DX/Lust-Unleashed-The-Urge-To-Explore (from the the eight-muses test)
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Windows has a path limit of 260 characters, including "drive letter, colon, backslash, name components separated by backslashes, and a terminating null".

It  is expected that on windows systems ripme respects these rules and warns the user about it or does not create the file if it will be longer than the 260 char path limit. If it is over Explorer.exe throws a "The file name is too long." error and does not allow the user to interact with the file at all.
## Actual Behavior

However this does not limit languages like java to creating longer paths.  If RipMe does this there is no way to use default windows explorer to read/write/modify the file.

Managed to get the following path: 
L:\Documents\NetBeansProjects\RipMe\rips\8muses_TheDude3DX_Lust_Unleashed_-_The_Urge_To_Explore\Lust-Unleashed---The-Urge-To-Explore\011_6FH0ubbB1JyFHjZD3KACbuJ7Ftyep1x0EeT329NowL9eemedfjaaHzun... (truncated)

**Comment by rephormat** [comment]
@kevin51jiang I can not reproduce this issue.  The random string of characters after the index number is missing in my download. e.g. L:\Documents\NetBeansProjects\RipMe\rips\8muses_TheDude3DX_Lust_Unleashed_-_The_Urge_To_Explore\Lust-Unleashed---The-Urge-To-Explore\011_.jpg  

Here are my specs:

Ripme version:  v.1.7.56
Windows version:  Microsoft Windows [Version 10.0.17134.112]
Java version:  java version "1.8.0_161"

**Comment by kevin51jiang** [comment]
It might have been a ripme error that it named the file badly, but either way I believe it is prudent to at least have safeguards in place.

**Comment by kevin51jiang** [comment]
@cyian-1756  1.7.51 or earlier (this happened a while ago)

Even if the program names it sensible things, there is always the possibility that the user has the download location very deep into the folder tree.

This issue is to ensure safeguards are put in place so that explorer.exe is always able to read/write whatever ripme downloads.

**Comment by rautamiekka** [comment]
^
>This issue is to ensure safeguards are put in place so that explorer.exe is always able to read/write whatever ripme downloads.

The only way to ensure there are minimum possible chances for too long path to occur is to name every file with a number starting from zero.

**Comment by cyian-1756** [comment]
Safety checks to ensure filenames aren't too long were implemented a few versions ago
