### ISSUE TITLE
Error:Null _ Non-retriable status code 403 while downloading

### ISSUE THREAD

**Issue by phaelon74** [RipMeApp/ripme#767]
* Ripme version: v1.7.49
* Java version:  1.8.0_161
* Operating system:  Windows 10 - Build 17134.112

* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/kaylafitz3/
* Please include any additional information about how to reproduce the problem: Problem is occuring on multiple Instagram pages.

## Expected Behavior

Rip all pictures, across multiple pages

## Actual Behavior

Rips the first page of pictures, anywhere from 10-15, then stalls and states Error:Null

Downloading https://scontent-ort2-1.cdninstagram.com/vp/77e85e68dd2471717dc7f166ac4fe2a3/5BE29AF0/t51.2885-15/e35/33937823_1986706038325868_4457999053350764544_n.jpg
Downloading https://scontent-ort2-1.cdninstagram.com/5BCAE66A/t51.2885-15/e35/36113744_1756273254421081_4010830869789933568_n.jpg
Downloaded C:\Users\user\Documents\CV\IG Rips\instagram_kaylafitz3\2018_06_19_06_06_35376823_391127651382908_7601445218830778368_n.jpg
Downloaded C:\Users\user\Documents\CV\IG Rips\instagram_kaylafitz3\2018_06_28_08_17_BklNorvhBuX35371011_2126594844275447_7418499334511001600_n.jpg
https://scontent-ort2-1.cdninstagram.com/5BCAE66A/t51.2885-15/e35/36113744_1756273254421081_4010830869789933568_n.jpg : Non-retriable status code 403 while downloading https://scontent-ort2-1.cdninstagram.com/5BCAE66A/t51.2885-15/e35/36113744_1756273254421081_4010830869789933568_n.jpg
Downloaded C:\Users\user\Documents\CV\IG Rips\instagram_kaylafitz3\2018_06_15_12_34_33937823_1986706038325868_4457999053350764544_n.jpg
Rip complete, saved to C:\Users\user\Documents\CV\IG Rips\instagram_kaylafitz3
null

**Comment by cyian-1756** [comment]
> Ripme version: v1.7.49

Ripme 1.7.49 is outdated and has a broken updater, please install [1.7.56](https://github.com/RipMeApp/ripme/releases/download/1.7.56/ripme.jar) and try again

**Comment by phaelon74** [comment]
You rock Cyian-1756!!  I was thinking something newer was needed but the auto-updater was not working :(.

**Comment by cyian-1756** [comment]
@phaelon74 

I'm closing this issue. If this issue is still present in ripme 1.7.57 leave a comment and I'll reopen it

**Comment by phaelon74** [comment]
Sorry sir, yes we can close it.  All of the previous pages work perfectly with the updated version.  Thanks again!!
