### ISSUE TITLE
Deviantart - downloads random images

### ISSUE THREAD

**Issue by MrSolution98** [RipMeApp/ripme#768]
* Ripme version: v1.7.56
* Java version:  10.0.1
* Operating system:  8.1

## Expected Behavior
On deviantart.com:
1. Download personal favorites folder using appropriate link 
2. Download a user's gallery 

## Actual Behavior
1. Downloads random images I haven't seen before, and, each time they are different
2. Says there are no images found in the gallery even though there are... Could it be because they are NSFW?

**Comment by IcedKoohii** [comment]
Same Here! I tried to download A page and got basically all of the newest deviations!
I'm sure it has something to do with the change in url formatting

**Comment by cyian-1756** [comment]
This has already been fixed and the fix will be out in the next version of ripme

> Download personal favorites folder using appropriate link

AFAIK favorites ripping currently broken, I have to get on fixing it
