### ISSUE TITLE
deviantart no longer works after they changed their url

### ISSUE THREAD

**Issue by cake22** [RipMeApp/ripme#770]
* Ripme version: v1.7.56
* Java version:  Version 8 Update 171 (build 1.8.0_171-b11)
* Operating system: macOS High Sierra
* Exact URL you were trying to rip when the problem occurred: (NSFW!!!!!)https://www.deviantart.com/victorzulu/gallery/?catpath=/

## Expected Behavior

Download all images from user gallery

## Actual Behavior

Deviantart no longer works since they've updated their urls. Downloads random pictures instead.

**Comment by cyian-1756** [comment]
This has already been fixed and will be out in the next version of ripme
