### ISSUE TITLE
I Couldn't Download From Deviantart Either,

### ISSUE THREAD

**Issue by IcedKoohii** [RipMeApp/ripme#774]
* Ripme version:
* Java version: 
* Operating system: 

* Exact URL you were trying to rip when the problem occurred: https://www.deviantart.com/kibbitzer/gallery/51429391/Reference-Sheets
* Please include any additional information about how to reproduce the problem:

## Expected Behavior
Paste Link
"DeviantArt Gallery Detected"
click rip
Gallery Downloads

## Actual Behavior
Paste Link
 "DeviantArt Gallery Detected"
Click Rip
Does nothing and says Error: No Images Found at deviantart.com/XXXXX

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Comment by kevin51jiang** [comment]
Can you please tell us what ripme version you have, what java you have, and what OS you have?

**Comment by IcedKoohii** [comment]
RIPME and Java are both up to date
I Have Windows 10 Home

Specifically, I cannot download gallery folders(E.G: https://www.deviantart.com/kibbitzer/gallery/51429391/Reference-Sheets)
also sometimes, the ripper starts automatically, and downloads the previous link i tried to rip

**Comment by rephormat** [comment]
User's environment:

- Ripme version: v1.7.57
- Java version: Version 8 Update 171 (build 1.8.0_171-b11)
- Operating system: Windows 10
