### ISSUE TITLE
ArtStation- JSONArray[50] not found error

### ISSUE THREAD

**Issue by lkq00172** [RipMeApp/ripme#776]
* Ripme version: 1.7.57
* Java version:  9.0.4
* Operating system:  Windows 7 Ultimate SP1 IE10 (64 bit) (6.1.7601)

* Exact URL you were trying to rip when the problem occurred: https://www.artstation.com/kuvshinov_ilya
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Rip all the images within the artist's portfolio page

## Actual Behavior

Produce error JSONArray[50] not found after downloading about 50-60 images.

![capture](https://user-images.githubusercontent.com/40853313/42312131-2d06b0f4-805d-11e8-9b01-6df7ee85bccd.PNG)

**Comment by cyian-1756** [comment]
Any other ArtStation links doing this or only this one?

@mbc07 you want to take a crack at fixing this?

**Comment by cyian-1756** [comment]
Looks like the issue is the ripper assumes that the json data at `https://www.artstation.com/users/USER/projects.json` but this is only true for users with less than 50 posts

**Comment by mbc07** [comment]
So, every JSON is limited to 50 projects but more can be accessed through `https://www.artstation.com/users/<user-id>/projects.json?page=1`,  `https://www.artstation.com/users/<user-id>/projects.json?page=2`, `https://www.artstation.com/users/<user-id>/projects.json?page=N`

Looks simple to handle, but I'm busy with other projects. I'll see if I can do something, but don't expect any ETA...

**Comment by mbc07** [comment]
Err, I only noticed you've already developed a bug fix now ¯\_(ツ)_/¯

Anyway, handling this case was easier than I thought (took me less than 15 minutes to implement) so I pushed my approach to this issue in PR #816, which also fixes an off-by-one error I haven't noticed before. Either one fixes the issue, so I'll leave to you to pick one :)

**Comment by cyian-1756** [comment]
> Err, I only noticed you've already developed a bug fix now ¯\(ツ)/¯

Happens to the best of us
