### ISSUE TITLE
hitomiRipper broken

### ISSUE THREAD

**Issue by cyian-1756** [RipMeApp/ripme#781]
* Ripme version: 1.7.57
* Java version:  1.8
* Operating system:  Ubuntu 16.04

* Exact URL you were trying to rip when the problem occurred: https://hitomi.la/galleries/975973.html
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Rips the album 

## Actual Behavior

Errors out with https://hitomi.la/galleries/975973.js

**Comment by stalwartmonkey** [comment]
Also, When it did download an album, it named it with the number of the album on the website, instead of the correct album name. It would be great to get that fixed. I already have about 60 folders downloaded, and it's gonna be a pain in the ass to rename them all.
