### ISSUE TITLE
twitter and retweets

### ISSUE THREAD

**Issue by eroeggplant** [RipMeApp/ripme#784]
how do i download only things posted from a twitter account and not retweets?

**Comment by cyian-1756** [comment]
Not ripping retweets should be the default behaviour in 1.7.57

**Comment by outlaw240** [comment]
I'm getting the complete opposite behaviour on 1.7.58. It seems to be exclusively downloading retweets instead of the user's actual tweets.

**Comment by cyian-1756** [comment]
@outlaw240 what link are you trying to rip?

**Comment by novascotia131** [comment]
@cyian-1756 perhaps add 'include_rts=false' in the twitter ripper? Currently there's no value for 'include_rts' so I think by default it is true.

**Comment by wankio** [comment]
tested with 236 media files, it download over 1000+ files :)
