### ISSUE TITLE
RipMe Window Resizing Issue

### ISSUE THREAD

**Issue by tehloxely** [RipMeApp/ripme#789]
RipMe 1.7.58
Windows 10

If something fails, the window will resize to the error. Please have it wrap the text.
See screenshot.
![resizeissue](https://user-images.githubusercontent.com/1208778/42424193-e2a0922a-82d5-11e8-9f81-232ebf6077ed.jpg)

**Comment by samuelpbowman** [comment]
#805 addresses this
