### ISSUE TITLE
Facing problems with 8muses

### ISSUE THREAD

**Issue by BurhanDanger** [RipMeApp/ripme#793]
* Ripme version: `1.7.58`
* Java version:  
```
openjdk version "1.8.0_172"
OpenJDK Runtime Environment (build 1.8.0_172-b11)
OpenJDK 64-Bit Server VM (build 25.172-b11, mixed mode)
```

* Operating system:  `ArchLinux`

* Exact URL you were trying to rip when the problem occurred: `https://www.8muses.com/comics/album/TG-Comics/Sturkwurk/The-Chamber/Chapter-11-21`

## Actual Behavior

Doesn't continue beyond something similar to " 99% - 5 pending , completed 542, errored 0"

Log:  https://ptpb.pw/7XM6

**Comment by cyian-1756** [comment]
This is a case of 8muses being 8muses. Sometimes connections randomly time out or get a server error. As this is on 8muses end there's not much that can be done to fix it. If I were you I'd just try to rip the album again
