### ISSUE TITLE
Feature request: Stop ripping when x "already downloaded" was detected

### ISSUE THREAD

**Issue by Gwynei** [RipMeApp/ripme#803]
Lets say you rip a gallery with images.
Then, a week later, you rip the same gallery again. In the beginning it will start downloading images. Until the point that you were on the first time. It is typically seen when the yellow "already downloaded" start appearing more and more. 

I'd wish an option exist that you could skip/stop the queue when ripme detects 10 or more already downloaded in a row.

I'm not a java developer so I am unfortunately not able to contribute on this great project myself.

**Comment by cyian-1756** [comment]
> I'd wish an option exist that you could skip/stop the queue when ripme detects 10 or more already downloaded in a row.

It does. The option is history.end_rip_after_already_seen. You can read about it's usage [here](https://github.com/RipMeApp/ripme/wiki/Config-options#historyend_rip_after_already_seen)
