### ISSUE TITLE
Error Thrown When Opening And Trying To Rip Any URL

### ISSUE THREAD

**Issue by MrRossDoughty** [RipMeApp/ripme#817]
* Ripme version: 1.7.59
* Java version: openjdk version "10.0.1" 2018-04-17
* Operating system: Linux Mint 19.0

* Exact URL you were trying to rip when the problem occurred: All URLs
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Rip Images

## Actual Behavior

Output of error log here: https://pastebin.com/WY6uz9Z6

When opening the program. Also when trying to rip any url, it fails as if it cannot find the url.

**Comment by cyian-1756** [comment]
Is Mint 19 based on Ubuntu 18.04? If so follow [these instructions](https://stackoverflow.com/questions/6784463/error-trustanchors-parameter-must-be-non-empty/50103533#50103533) to fix it

**Comment by cyian-1756** [comment]
@MrRossDoughty 

Did you get it working?

**Comment by MrRossDoughty** [comment]
Hey thanks for the advice, I got it working last night. More of a java thing than a issue with the ripper eh?

**Comment by cyian-1756** [comment]
> More of a java thing than a issue with the ripper eh?

Yup
