### ISSUE TITLE
Ripme using default (?) api. Not the one I inputted. 

### ISSUE THREAD

**Issue by Alfonsorb** [RipMeApp/ripme#842]
* Ripme version: 1.7.60
* Java version:  version 10.0.2
* Operating system: win10

* Exact URL you were trying to rip when the problem occurred: https://overbarawatch.tumblr.com/
* Please include any additional information about how to reproduce the problem:

This issue happens with any tumblr account.

## Expected Behavior

Should rip the tumblr 

Detail the expected behavior here.

## Actual Behavior

Downloading http://api.tumblr.com/v2/blog/overbarawatch.tumblr.com/posts/photo?api_key=FQrwZMCxVnzonv90rg[redacted]&offset=0
Tumblr rate limit has been exceeded

Worth noticing that the api_key isn't the one I inputted on the rip.properties folder. Also, should the ripme.jar file be inside the source code folder?

**Comment by Alfonsorb** [comment]
Issue resolved itself after I downloaded the ripme.jar file and folder again.

**Comment by cyian-1756** [comment]
This was most likely caused by you editing rip.properties well ripme was still running. Any changes made to rip.properties well ripme is running are overwritten when ripme exits
