### ISSUE TITLE
I cant update to 1.7.60 - running mac OS 10.7.5 

### ISSUE THREAD

**Issue by Diskburner** [RipMeApp/ripme#843]
* Ripme version:
* Java version: 
* Operating system: 

* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Detail the expected behavior here.

## Actual Behavior

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Comment by cyian-1756** [comment]
What version of ripme are you running?

**Comment by cyian-1756** [comment]
Is the update button not working? What exact problem are you having?

**Comment by Diskburner** [comment]
What I click the update button, it generates "an update available"s creen. But not update occurs.

http://img18056.imagevenue.com/img.php?image=66772_1_122_619lo.jpg

**Comment by Diskburner** [comment]
Some sites are ripping, not imagefap. I think thy have change the servers and host that points to the content. They have another  "sister" site

**Comment by cyian-1756** [comment]
You can manually update by downloading the latest release from [this page](https://github.com/RipMeApp/ripme/releases)
