### ISSUE TITLE
How to configure RipMe to rip only recent items from a source

### ISSUE THREAD

**Issue by thawatchai** [RipMeApp/ripme#848]
I'm interested only recent items from a source. Is it possible to configure RipMe to rip only the recent items?

Thank you in advance for your answer. 👍

**Comment by cyian-1756** [comment]
Set `history.end_rip_after_already_seen` in rip.properties to the max number of old files you want ripme to try to download before ending the rip

For example `history.end_rip_after_already_seen = 10` would cause ripme to end the rip after finding 5 files that had already been downloaded. Make sure you also have 'remember URL history' checked

You can read about this and all the only config opens on [this wiki page](https://github.com/RipMeApp/ripme/wiki/Config-options)

**Comment by thawatchai** [comment]
Thank you very much. It works perfectly.
