### ISSUE TITLE
rip.properties?

### ISSUE THREAD

**Issue by andrerdxd** [RipMeApp/ripme#85]
Cant seem to find rip.properties, and keep getting error null trying to rip a tumblr page. Im using windows 10.

**Comment by rautamiekka** [comment]
For the record: it's auto-generated on start.

**Comment by andrerdxd** [comment]
it wasnt generated but after i kept changing settings it appeared

**Comment by metaprime** [comment]
If the file is not found it should use the version of the file that is packaged into the JAR. If you can get any additional information about the problem, that would be appreciated.
