### ISSUE TITLE
my ripple properties not showing something shown in wiki

### ISSUE THREAD

**Issue by Thorazin** [RipMeApp/ripme#850]
* Ripme version: 1.7.60
* Java version:  10.0.2 JRE
* Operating system:  MacOS 10.13.6

* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Detail the expected behavior here. I was reading the wiki and see what I think is a setting that should be in ripe.properties to limit how many already downloaded links a rip will try before stopping the rip.

## Actual Behavior

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report. I went to ripe.properties and the expected setting was not there.  pictured below is the wiki thing I was expecting to see which was not in my properties.

![screen shot 2018-08-02 at 7 58 58 pm](https://user-images.githubusercontent.com/36058075/43618737-ac3c7f28-968f-11e8-839c-346d8c6f2ee2.png)

**Comment by cyian-1756** [comment]
> ictured below is the wiki thing I was expecting to see which was not in my properties.

By default it's not in your properties file. If you want to use the feature you can just edit rip.properties to add it

**Comment by rephormat** [comment]
@cyian-1756 No response from requester after 11 days.  Recommend closing.

**Comment by Thorazin** [comment]
I was actually really sick, this reminded me. I will try that and get back.
