### ISSUE TITLE
JSON error while downloading

### ISSUE THREAD

**Issue by UnforeseenOcean** [RipMeApp/ripme#851]
* Ripme version: 1.7.60
* Java version: 1.8.0_181
* Operating system: 6.1.7601
* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/vrustov
* Please include any additional information about how to reproduce the problem:
Redownload an already downloaded URL.

## Expected Behavior
It continues onto next page.

## Actual Behavior
![image 330](https://user-images.githubusercontent.com/11834016/43637903-a6b6f52a-9751-11e8-957e-164567b22bd4.png)

**Comment by UnforeseenOcean** [comment]
Additionally "null" error appears too.
![image 332](https://user-images.githubusercontent.com/11834016/43643356-03da6638-9766-11e8-8de8-f2fe61c9aec2.png)

**Comment by cyian-1756** [comment]
I can't reproduce this. Using 1.7.60 I managed to rip over 100 images without issue

**Comment by UnforeseenOcean** [comment]
Looks like the error is random. Don't really know what's causing it.

**Comment by cyian-1756** [comment]
> Don't really know what's causing it.

Check save logs, keep using ripme until you get the error again and then upload the logs here and I'll see if I can figure out what's causing this

**Comment by rephormat** [comment]
@cyian-1756 No response from reporter after 11 days.  Recommend closing.
