### ISSUE TITLE
Ripper uses default api instead my api.

### ISSUE THREAD

**Issue by L3sb0t** [RipMeApp/ripme#859]
* Ripme version: 1.7.61
* Java version: 1.8.0_181-b13
* Operating system: Windows 10 Home
* Exact URL you were trying to rip when the problem occurred: https://maceleven.tumblr.com/
* Please include any additional information about how to reproduce the problem: N/A

## Expected Behavior

Expected ripper to use the api key I typed into the properties file in order to exceed the Tumblr download limit.

## Actual Behavior

Ripper used default api key, met the Tumblr download limit, and didn't download any images giving me a red "Tumblr rate limit has been exceeded" message.

Note: When I edited the properties file the ripper wasn't running.

**Comment by cyian-1756** [comment]
Can you post your log (With your api key redacted)?

**Comment by L3sb0t** [comment]
# Download threads to use per ripper
threads.size = 5

# Overwrite existing files
file.overwrite = false

# Number of retries on failed downloads
download.retries = 1

# File download timeout (in milliseconds)
download.timeout = 60000

# Page download timeout (in milliseconds)
page.timeout = 5000

# Maximum size of downloaded files in bytes (required)
download.max_size = 104857600

# Don't retry on 404 errors
error.skip404 = true

# API creds
twitter.auth = VW9Ybjdjb1pkd2J0U3kwTUh2VXVnOm9GTzVQVzNqM29LQU1xVGhnS3pFZzhKbGVqbXU0c2lHQ3JrUFNNZm8=
tumblr.auth = (redacted).api = gonewild

twitter.max_requests = 10

clipboard.autorip = false

download.save_order = true

**Comment by cyian-1756** [comment]
That's your config file, I meant ripmes log file (Be sure to check "Save Logs")

**Comment by L3sb0t** [comment]
Do you mean the "log4j" file? Sorry, kinda new to computer jargon. My "Save Logs" box was unchecked so I don't know if it saved the logs.

**Comment by cyian-1756** [comment]
> My "Save Logs" box was unchecked so I don't know if it saved the logs.

In that case check the check box, attempt the rip again and then post log

**Comment by cyian-1756** [comment]
> src/main/resources/

That's not the right config file. That's the config file that ripme uses if it can't find it's config file. Edit the config file at %LOCALAPPDATA%\ripme\rip.properties

**Comment by L3sb0t** [comment]
Thanks, that worked! It's using my key again.
