### ISSUE TITLE
Instagram albums not full res

### ISSUE THREAD

**Issue by daniga999** [RipMeApp/ripme#86]
* Ripme version: 1.5.7
* Java version: Version 6 Update 144
* Operating system: Windows 8.1
* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/gromova_asya_/
* Please include any additional information about how to reproduce the problem: I manually saved the latest picture (full res) of said album and compared it to the same picture (downloaded w/ ripme). 

## Expected Behavior

Instagram albums with full res pics

## Actual Behavior

The pictures are a mishmash of different resolutions.

**Comment by rautamiekka** [comment]
It's true some pics are 1080p but most others are 640x800, but that's the way on the website. Dunno if that's intentional on the photographer's end though, but it does beg the question "Why different resolution ?".

**Comment by cyian-1756** [comment]
This should be fixed in version 1.5.9
