### ISSUE TITLE
Txt File Upload/Parse in GUI

### ISSUE THREAD

**Issue by ellis1884** [RipMeApp/ripme#870]
Sorry not sure if this is the correct place to request features, but could I please request the ability to upload/parse text files in the GUI?

**Comment by ellis1884** [comment]
within the Graphical interface, can we have the ability to parse a text-file list into it that includes all the respective urls/sites to be ripped, at present I can only digest this via CLI.

Sorry does this is this help?
thanks,

**Comment by cyian-1756** [comment]
This feature will be in ripme 1.7.62

**Comment by ellis1884** [comment]
amazing! many thanks!


________________________________

**Comment by cyian-1756** [comment]
This was added in 1.7.62. You can find it in the configuration tab
