### ISSUE TITLE
Feature Request: Tumblr raw image

### ISSUE THREAD

**Issue by sankeyxavier** [RipMeApp/ripme#88]
Tumblr enables images to be viewed at their original image resolution if you modify the image url like the following: 

http://68.media.tumblr.com/695d241dadc1a43ef67c3b1f77456a02/tumblr_owwhxyI4K31vike5ho1_1280.jpg

https://media.tumblr.com/695d241dadc1a43ef67c3b1f77456a02/tumblr_owwhxyI4K31vike5ho1_raw.jpg

Iv'e heard that not all images are not like this, most notably images before 2013, but I haven't encountered any as of yet.

**Comment by rautamiekka** [comment]
You can give any resolution in place of `1280` and you get the closest to it. Since it seems all pics are max 1280 in all cases nowadays, giving `1000000` (1 million) doesn't make any more difference than `9999`.

**Comment by Hrxn** [comment]
This is new to me. Good one, how did you find this?

I could've sworn that this was different in the past, i.e. `..._1280.jpg` not limiting the image dimensions to 1280 px, in either width or height. But apparently, that is how it's working. Makes sense, too.

Not sure on how many tumblr logs this already "works", but this is an important addition, definitively. There are many good photography blogs on tumblr, and getting the 'original'/uploaded image is really relevant here..

**Comment by rautamiekka** [comment]
^ When I found stuff I wanted and it showed up as 1280, I figured I'll try things like 1920. Well, to my surprise it worked, but only half-way: the resolution was still 1280 although the file and link was named 1920.

So I went and tried that with `wget` on many links with the same result. Of course, all of them were posted within a few years, so it may not apply to the oldest ones ...

**Comment by MrTimscampi** [comment]
The _raw trick doesn't seem to work anymore.

**Comment by rautamiekka** [comment]
^ Oh for fuck's sake ... Damn Tumblr.

**Comment by sankeyxavier** [comment]
just change the beginning to the 68 to data

http://data.tumblr.com/695d241dadc1a43ef67c3b1f77456a02/tumblr_owwhxyI4K31vike5ho1_raw.jpg

**Comment by rautamiekka** [comment]
^
>http://data.tumblr.com/695d241dadc1a43ef67c3b1f77456a02/tumblr_owwhxyI4K31vike5ho1_raw.jpg

That worked, but it's terribly slow. The number technique didn't work but it wouldn't need to.

**Comment by cyian-1756** [comment]
When this is added I think it should be a config option so users can disable if they wish

**Comment by cyian-1756** [comment]
This was done in 1.7.9, to enable it you need to add the line `tumblr.get_raw_image = true` to your rip.properties file
