### ISSUE TITLE
tumblr raw urls returns 403 error

### ISSUE THREAD

**Issue by holdit** [RipMeApp/ripme#884]
Just a fyi. It seems that tumblr changed something on their side and raw files now return a 403 error. Works fine without _tumblr.get_raw_image = true_.

* Ripme version: 1.7.63
* Java version: Java 8 Update 181
* Operating system: macOS High Sierra (10.13.6)

**Comment by cyian-1756** [comment]
Can you post a tumblr link I can use to test this?

**Comment by rautamiekka** [comment]
It's been said on Tumblr by an 'MLP' artist that Tumblr removed the whole raw files thing, so there probly (likely) ain't a fix for this.

**Comment by holdit** [comment]
> @cyian-1756 Can you post a tumblr link I can use to test this?

Most pages with pictures. For example: https://picsthatmakeyougohmm.tumblr.com/post/177528943929/hmmm

ripme log:

```
Downloading http://api.tumblr.com/v2/blog/picsthatmakeyougohmm.tumblr.com/posts?id=177528943929&api_key=1nEIsa70wZWuVvkj9nrwSmD6HqW7gPxrdhFHimBzpH8AU6QQfy
Downloading http://data.tumblr.com/c43ff54c6483365572f0d1f6943376be/tumblr_pe5zp1JMAS1wsbn2ao1_raw.jpg
http://data.tumblr.com/c43ff54c6483365572f0d1f6943376be/tumblr_pe5zp1JMAS1wsbn2ao1_raw.jpg : Non-retriable status code 403 while downloading http://data.tumblr.com/c43ff54c6483365572f0d1f6943376be/tumblr_pe5zp1JMAS1wsbn2ao1_raw.jpg
Rip complete, saved to /Users/user/Documents/ripme/rips/tumblr_picsthatmakeyougohmm.tumblr.com_post_177528943929
```

The folder is created, but no file is saved.

If @rautamiekka is right, then this feature is dead.

**Comment by rautamiekka** [comment]
https://addons.mozilla.org/en-GB/firefox/addon/tumblr-high-quality/ has been updated 12 August 2018 which now takes you to 1280 versions instead of raws. So yeah, it sure seems the feature is dead, damned Tumblr.

Here's the source code to it:
```javascript
function getImageRawUrl (url) {
var regex = /^(.*?)(\d*\.)(media\.(tumblr\.com(\/.*?\/)?.*_))(\d*)(\d*\.[^#]*)(#dnr)?$/i;
var match = regex.exec(url);
if (match && !match[8] && match[6] !== '1280') {
	//if (match[5])
	//	url = 'https://data.' + match[4] + 'raw' + match[7];
	//else
		url = match[1] + match[3] + '1280' + match[7];
}
return url;
}

function redirect (oldUrl, newUrl) {
	if(oldUrl === newUrl)
		return;

	setTimeout(() => {
		window.history.replaceState({foo:'bar'}, 'DNR', oldUrl + '#dnr');
		window.location.href = newUrl;
	}, 10);
}
```
