### ISSUE TITLE
imgur GIFs are skipped when ripping reddit_user

### ISSUE THREAD

**Issue by cppsse** [RipMeApp/ripme#895]
* Ripme version: 1.7.63
* Java version: 1.7.63
* Operating system: Debian 8.11
* Exact URL you were trying to rip when the problem occurred: https://reddit.com/user/EllaBellaRose

When ripping a reddit_user, imgur GIFs download as JPG only, however when ripping a reddit_post directly, both the JPG and MP4 download.  Is this because of GIFVbot?  Logs:

via ripme reddit_user:
> [+] Creating directory: ./reddit_user_EllaBellaRose
Setting locale to default
 [...]
    Downloading file: https://i.imgur.com/WiB6g58h.jpg Retry #1
[+] Saved https://i.imgur.com/WiB6g58h.jpg as ./reddit_user_EllaBellaRose/4moj04Hot_Anal_Double_Penetration_GIF__M-25_F-33_WiB6g58h.jpg

via ripme reddit_post (https://www.reddit.com/r/MasterOfAnal/comments/4moj04/hot_analdouble_penetration_gif_m25f33/)
> [+] Creating directory: ./reddit_post_4moj04
Setting locale to default
    Downloading file: https://i.imgur.com/WiB6g58h.jpg Retry #1
    Downloading file: https://i.imgur.com/WiB6g58.mp4 Retry #1
[!] Unable to rip URL: https://www.reddit.com/r/livven/wiki/gifv-bot
[!] Unable to rip URL: https://github.com/Livven/GifvBot)_
[+] Saved https://i.imgur.com/WiB6g58h.jpg as ./reddit_post_4moj04/4moj04Hot_Anal_Double_Penetration_GIF__M-25_F-33_WiB6g58h.jpg
[+] Saved https://i.imgur.com/WiB6g58.mp4 as ./reddit_post_4moj04/d3x1fl3WiB6g58.mp4

**Comment by cyian-1756** [comment]
Looks like `getFilesFromURL` in RipUtils assumes that any imgur url without a "," or "/a/" in it is a image. I'll get on fixing this
