### ISSUE TITLE
Can't rip from yuki.la

### ISSUE THREAD

**Issue by Cerberuschan** [RipMeApp/ripme#907]
* Ripme version: 1.7.63
* Java version: 1.8.0_181_b13
* Operating system: Windows 10 Pro Ver 1803

* Exact URL you were trying to rip when the problem occurred: https://yuki.la/aco/476224

## Expected Behavior
it should download like any normal 4chan archive

## Actual Behavior
can't find ripper for the site

**Comment by Cerberuschan** [comment]
no advancements on this matter? could you take at look at this plz? it would be really helpful if you could implement this ripper

thx

**Comment by cyian-1756** [comment]
I've almost got it working, I just need to fix the image downloading (They currently all fail with a 301 redirect). I should be finished tomorrow or the day after and in the next release of ripme
