### ISSUE TITLE
Add patch script for *nix systems

### ISSUE THREAD

**Issue by cyian-1756** [RipMeApp/ripme#91]
* Ripme version: NA
* Java version:  NA
* Operating system:  Ubuntu 16.04
* Exact URL you were trying to rip when the problem occurred: NA
* Please include any additional information about how to reproduce the problem: NA

## Expected Behavior

There should be a patch script written in python or bash so users on *nix like OSs can easily make a new release without having to edit files by hand

## Actual Behavior

The patch script is written in powershell which runs on few *nix OSs and that few users have installed

**Comment by haposik** [comment]
Hi! I am new here. And i am ready to contribute to your project by adding a new patch script, written in python or bash, as my first PR

**Comment by cyian-1756** [comment]
@haposik Great! You can read the windows patch script (patch.ps1) to get idea what the script needs to do

**Comment by rautamiekka** [comment]
Will be a fair work porting the PowerShell since its syntax is something monstrous.

**Comment by cyian-1756** [comment]
@rautamiekka Yea, powershell doesn't have the prettiest syntax, but at least most of the heavy lifting is done by sed which has a very nice syntax
