### ISSUE TITLE
8muses not ripping pictures in full resolution

### ISSUE THREAD

**Issue by Derperino** [RipMeApp/ripme#912]
* Ripme version: v.1.7.63
* Java version: Version 9.0.4 Build 9.0.4+11
* Operating system: Windows 10
* Exact URL you were trying to rip when the problem occurred:https://www.8muses.com/comics/album/Affect3D-Comics/X3Z/Dungeon-Prologue

## Expected Behavior 

When downloading albums, the images should be saved in full resolution

## Actual Behavior

All images were downloaded with a resolution of 1200x675 instead of 1920x1080

This also happened with other albums as well.

**Comment by biladina** [comment]
when I look at image album, the resolution just 1200x675, how do you know the image size 1920x1080??

like this one (just 1200x675) :
https://www.8muses.com/image/fm/YJibZR0eqoaydJBLHURb6YSN+q7drdRUgeQJYkp34MeP3MFJWPeVqQGazVvPkukXtSKQf4SoFl6CHAzdxy8eEE7d25Es767mZfIapg49KL85D0VCkKwwiV+nKIi8rChw4mlO9COxMfoKmAfWuYUjUg.jpg

**Comment by Derperino** [comment]
That links not working for me. But when I download any of the images and it says 1920x1080 in the details..

**Comment by biladina** [comment]
can you show the detail log that says image resolution 1920x1080?? because I try download from your link with same Ripme version and its working, there is no warning or something like that..

**Comment by Derperino** [comment]
As you can see, when downloaded manually i have a resolution of 1920x1080. 

![Manual download](https://user-images.githubusercontent.com/39758976/45287727-4c94cd00-b4e9-11e8-90a9-6bd5cb41843f.png)
![ripmedownload](https://user-images.githubusercontent.com/39758976/45287728-4d2d6380-b4e9-11e8-9381-0c8e8b924fe7.png)

**Comment by cyian-1756** [comment]
I can confirm this. 8Muses is returning different data based on screen size and I assume that 1200x675 is the default

**Comment by cyian-1756** [comment]
Looks like we can force full sized images by changing the image url to /image/fl/IMAGE instead of  /image/fm/IMAGE

**Comment by Derperino** [comment]
But how do I force that when using the link I used originally to download the whole album?

**Comment by Derperino** [comment]
And how can I change the url when using the link I used originally?

**Comment by cyian-1756** [comment]
> And how can I change the url when using the link I used originally?

You can't, it's something that ripme has to do when it downloads the images. I've already fixed it in a PR and will be pushing an update in the next few minutes
