### ISSUE TITLE
Can download only 12 photos from xhamster gallery

### ISSUE THREAD

**Issue by ruinedJelly** [RipMeApp/ripme#943]
* Ripme version: v1.7.64
* Java version:  1.8.0_181
* Operating system: Version 1709 (OS Build 16299.611)
* Exact URL you were trying to rip when the problem occurred: https://xhamster.com/photos/gallery/beautiful-girls-vol11-3727492

## Expected Behavior
Things were working before I updated RipMe. 
All the photos in an xhamster gallery were getting downloaded.

## Actual Behavior
Now, only 12 photos are downloaded from a gallery.

**Comment by cyian-1756** [comment]
> Exact URL you were trying to rip when the problem occurred: Any xhamster gallery with >12 photos

Please link an album so that I can test this issue

**Comment by ruinedJelly** [comment]
https://xhamster.com/photos/gallery/beautiful-girls-vol11-3727492

**Comment by cyian-1756** [comment]
This is fixed in 1.7.65
