### ISSUE TITLE
Feedback: Needs confirmation screen on Clear and more

### ISSUE THREAD

**Issue by UnforeseenOcean** [RipMeApp/ripme#95]
I accidentally hit Clear on history list and I wiped my history. It really needs some confirmation screen; Just a simple "Are you sure" message will work.

Plus, either add Clear Checkbox function or make it clear the selection once it has successfully downloaded at least 1 image/video.

**Comment by Varinara** [comment]
Hi. I am new here and I want to start working on this issue as my first PR.

**Comment by rephormat** [comment]
@cyian-1756 Fixed with Merge #322.  Recommend closing.
