### ISSUE TITLE
Tumblr ripper missing files

### ISSUE THREAD

**Issue by oldesoul95** [RipMeApp/ripme#954]
* Ripme version: 1.7.65
* Java version: Version 8 update 171 build 1.8.0_171-b11
* Operating system: Win10

* Exact URL you were trying to rip when the problem occurred: http://these-are-my-b-sides.tumblr.com
* Please include any additional information about how to reproduce the problem: see below

## Expected Behavior

Ripme will rip all photos from a full tumblr rip or single post rip

## Actual Behavior

Ripme only downloads 104 files and skips many when attempting a full rip of the tumblr. For example the photo from https://these-are-my-b-sides.tumblr.com/post/178225921524/this-was-fun is not downloaded. Even attempting to directly rip from that link does not download the photo. It just creates an empty directory with the log file. I have attached the log from attempting to rip the link directly, and from attempting to full rip using https://these-are-my-b-sides.tumblr.com.
[log.txt](https://github.com/RipMeApp/ripme/files/2398850/log.txt)
[full rip log.txt](https://github.com/RipMeApp/ripme/files/2398851/full.rip.log.txt)

**Comment by cyian-1756** [comment]
> Even attempting to directly rip from that link does not download the photo. It just creates an empty directory with the log file.

Can you post a link to one of the things that isn't downloaded?

**Comment by cyian-1756** [comment]
Looks like this is happening because this isn't a "real" image post (It doesn't have a photos field), but rather just includes a link to an image.

It should be possible to make ripme support these, at least to an extent

**Comment by Hrxn** [comment]
Yeah, those are posts of the type "text" with embedded/inline images..
