### ISSUE TITLE
Ripme displays null on tumblr 404

### ISSUE THREAD

**Issue by cyian-1756** [RipMeApp/ripme#968]
* Ripme version: 1.7.65
* Java version: 
* Operating system:  Ubuntu 16.04

* Exact URL you were trying to rip when the problem occurred: grimphantom.tumblr.com
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Ripme tells the user the album/user they tried to rip doesn't exist

## Actual Behavior

Ripme just displays a red null

**Comment by dominiksitar** [comment]
Hello, can I work on this?

**Comment by cyian-1756** [comment]
@dominiksitar 

Go ahead

**Comment by dominiksitar** [comment]
Pull request #1048 to a fixed issue.

**Comment by dominiksitar** [comment]
Hope this solution is better
