### ISSUE TITLE
AUR version of ripme is out of date

### ISSUE THREAD

**Issue by cyian-1756** [RipMeApp/ripme#97]
[The version of ripme in the Arch User repository](https://aur.archlinux.org/packages/ripme-git/) is pretty massively out of date (It was last updated 2015-12-23). Someone might want to take over as maintainer (It should be as easy as messaging a mod/admin and asking) and update the wiki/PKGBUILD

**Comment by MrTimscampi** [comment]
I just took ownership of the package and I'm currently building the updated PKGBUILD to test it.

It should be ready in a few minutes.

**Comment by cyian-1756** [comment]
@MrTimscampi The upsteam url still seems to be set to https://github.com/4pr0n/ripme.git, can you set it to this repo instead?

**Comment by MrTimscampi** [comment]
@cyian-1756 Done, it should be good to go now.

**Comment by cyian-1756** [comment]
@MrTimscampi The upstream url is still showing as https://github.com/4pr0n/ripme.git for me

**Comment by MrTimscampi** [comment]
@cyian-1756 It was changed in the PKGBUILD, I don't think the url in the AUR browser can be changed, unfortunately.

**Comment by cyian-1756** [comment]
Ah well
