### ISSUE TITLE
 Instagram and Following

### ISSUE THREAD

**Issue by wankio** [RipMeApp/ripme#970]
Some Instagram required following to see content, how i can login my account to download it ? because i dont see any option to use instagram account

**Comment by cyian-1756** [comment]
> Some Instagram required following to see content, how i can login my account to download it ?

You can't currently

**Comment by wankio** [comment]
> 
> 
 
> 
> You can't currently

oh nvm :) i found another app...

and about this  https://github.com/RipMeApp/ripme/issues/784 , it should not rip @username in tweet media post caption

**Comment by Isaaku** [comment]
same as #200 . @cyian-1756 please close this
