### ISSUE TITLE
Xhamster Video Ripper Broken

### ISSUE THREAD

**Issue by digitalnoise** [RipMeApp/ripme#973]
* Ripme version:
* Java version: 1.8.0_181
* Operating system: Microsoft Windows [Version 10.0.17134.285]
* Exact URL you were trying to rip when the problem occurred: Xhamster
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Should rip video from link.

## Actual Behavior

Ripme reports "no compatible ripper found" - using latest release.

## Notes

I'm going to attempt to fix myself, however if someone can do it faster - have at.

**Comment by cyian-1756** [comment]
> Exact URL you were trying to rip when the problem occurred: Xhamster

What url where you trying to rip?

**Comment by cyian-1756** [comment]
Looks I accidentally removed it when I was updating some video rippers, I've readded it in a PR and it should be in the next version of ripme
