### ISSUE TITLE
"tumblr.get_raw_image =true" doesn't work and still downloads small images

### ISSUE THREAD

**Issue by castor9mm** [RipMeApp/ripme#974]
* Ripme version: 1.7.66
* Java version:  Java 8 151
* Operating system: Version 1607 (win 10)

* Exact URL you were trying to rip when the problem occurred: NSFW  fragmangh.tumblr.com/
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

should download raw or 1280 size images. I don't think raw works anymore, but the application should just translate the "_540.jpg" to 1280 because images will always load with "_1280.jpg" on tumblr even if the size isn't that large.

## Actual Behavior

"tumblr.get_raw_image = true" gets removed from config when you close the app, or change any setting, or put an url in the queue.

If I add and save "tumblr.get_raw_image = true" to the config, and then open the app, pictures with 480 540 640 etc are still downloaded in those formats.  It happens on any tumblr page, not just the one I listed. 

If add "tumblr.get_raw_image = true" to the config while the app is open it has no effect either.

**Comment by cyian-1756** [comment]
Tumblr no longer supports downloading raw images so the feature was removed from ripme

**Comment by castor9mm** [comment]
Can you make it so it appends 1280 instead? It would be really helpful. 1280 always works regardless of size. It will simply take the largest. Some blogs make the size all 540 when the pics are all larger.

**Comment by kevin51jiang** [comment]
@castor9mm

Is 1280 the maximum size tumblr supports?

**Comment by castor9mm** [comment]
> @castor9mm
> Is 1280 the maximum size tumblr supports?

yes, it seems that way. if a pic's url has a smaller number the max you can go is 1280
