### ISSUE TITLE
Cannot re-rip failed rips

### ISSUE THREAD

**Issue by RikuKawai** [RipMeApp/ripme#977]
* Ripme version: 1.7.66
* Java version: "1.8.0_162"
* Operating system: Windows 10 Pro x64 1803 Build 17134.285
* Exact URL you were trying to rip when the problem occurred: Any URL, specifically imagefap in this case
* Please include any additional information about how to reproduce the problem: Attempt to re-rip a previously failed URL with or without overwrite files enabled. This can be easily reproduced by ripping under conditions where disk space will run out then freeing disk space and attempting to re-rip.

## Expected Behavior
URL is ripped normally, overwriting previous incomplete or non-present files.

## Actual Behavior
RipMe throws Already downloaded for every image, then deletes the empty directory, even if there were no such files successfully downloaded. Restarting RipMe does not mitigate the issue.

**Comment by cyian-1756** [comment]
Sounds like you have "Remeber URL History" enabled. That feature causes ripme to skip files it downloaded in previous rips. Uncheck it and try again and see it that fixes it
