### ISSUE TITLE
Re-rip a history item should download new content only

### ISSUE THREAD

**Issue by Redsandro** [RipMeApp/ripme#978]
* Ripme version: 1.7.65
* Java version: 10.0.2 2018-07-17
* Operating system: Ubuntu 18.04
* Exact URL you were trying to rip when the problem occurred: Any (reddit)

[Features](https://github.com/RipMeApp/ripme#features) include:

> Easily re-rip albums to fetch new content

## Expected Behavior

Only download new content (e.g. posts later/newer than the "modified" date mentioned in "history").

## Actual Behavior

It re-downloads everything, including all the images I had carefully weeded out (removed).

**Comment by cyian-1756** [comment]
Check "Remember URL History" in the GUI  (Or add the line "remember.url_history" rip.properties file) and add the line "history.end_rip_after_already_seen = 5" to your rip.properties file

This will cause ripme to skip all urls it has seen in the past and end the current rip after finding 5 or more urls it has seen in the past

Your rip.properties file should be at ~/.config/ripme/rip.properties

**Comment by Redsandro** [comment]
@cyian-1756 thank you. If this was documented, I missed it.

How likely are items to be in chronological order? I.e. why not `history.end_rip_after_already_seen = 1`

**Comment by cyian-1756** [comment]
> How likely are items to be in chronological order?

It's a bit iffy. They'll be in the rate order if you sort by modification date. Honestly now that I think about it I should add an option to add the current date in front of any download files 

> I.e. why not history.end_rip_after_already_seen = 1

No real reason. I just copied and pastes the docs 

[You can find all ripmes config options here](https://github.com/RipMeApp/ripme/wiki/Config-options)

**Comment by Redsandro** [comment]
Thank you. :+1:
