### ISSUE TITLE
useragents are pretty outdated 

### ISSUE THREAD

**Issue by cyian-1756** [RipMeApp/ripme#98]
* Ripme version:
* Java version:  1.5.13
* Operating system:  Ubuntu 16.04
* Exact URL you were trying to rip when the problem occurred: NA
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Ripme should use up to date useragents to avoid things like the "Unsupported browser" page on sites

## Actual Behavior

Ripme uses very old useragents like `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:36.0) Gecko/20100101 Firefox/36.0`. MacOS 10.7 has been out of support for a long time and firefox is above version 50 at this point

**Comment by metaprime** [comment]
Is there a recommended new user agent we should update to? Something new but not "latest possible"?

**Comment by cyian-1756** [comment]
> Is there a recommended new user agent we should update to?

I say just update the current one to the last stable release of MacOS and the last LTS release of firefox.

**Comment by metaprime** [comment]
I think we probably should pick a common user agent matching a consumer browser like Chrome.

**Comment by metaprime** [comment]
https://techblog.willshouse.com/2012/01/03/most-common-user-agents/

**Comment by metaprime** [comment]
Most common is Chrome 61 on Windows 10 x64

8.5% | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
-- | --

http://useragentstring.com/index.php
