### ISSUE TITLE
xhamster picture albums not able to rip 

### ISSUE THREAD

**Issue by chokiechok** [RipMeApp/ripme#983]
today xhamster pictures /album not able to rip at all. pls advise thanks

**Comment by chokiechok** [comment]
it keeps stating non-retriable status code 403 while downloading

**Comment by cyian-1756** [comment]
What OS are you on? What version of Ripme? What exact url did you try to rip when you ran into the error?

**Comment by chokiechok** [comment]
windows 8  cant rip album 
example
2018-10-05 17:06:14,815 ERROR ripper.DownloadFileThread .run() [!] Non-retriable status code 403 while downloading from http://thumb-p8.xhcdn.com/a/1rYiEsKzUMLI0G0_PZHxkw/000/223/120/308_1000.jpg

**Comment by chokiechok** [comment]
version 1.766.

**Comment by cyian-1756** [comment]
> example
2018-10-05 17:06:14,815 ERROR ripper.DownloadFileThread .run() [!] Non-retriable status code 403 while downloading from http://thumb-p8.xhcdn.com/a/1rYiEsKzUMLI0G0_PZHxkw/000/223/120/308_1000.jpg

What link where you trying to rip when you got that error?

**Comment by chokiechok** [comment]
i have checked but funny think is that rip download from this link instead of the orginal https://m.xhamster.com/photos/gallery/japanese-amateur-girl1131-part-2-10576154

it is trying to download from https://m.xhamster.com/photos/gallery/japanese-amateur-girl1131-part-2-10576154
(m.xhamster.com)?

**Comment by optomus-slime** [comment]
> (m.xhamster.com)?

mobile

**Comment by Muther11** [comment]
I get the same "ERROR ripper.DownloadFileThread .run() [!] Non-retriable status code 403" on all albums.. The most recent link was https://xhamster.com/photos/gallery/dominant-teen-temptations-10726803

**Comment by cyian-1756** [comment]
> i have checked but funny think is that rip download from this link instead of the orginal https://m.xhamster.com/photos/gallery/japanese-amateur-girl1131-part-2-10576154

Yea ripme downloads from the mobile instead of the desktop site

**Comment by cyian-1756** [comment]
Looks like xhamster now requires you to open the image page to get the full size image and we can't just change up the thumbnail url to get it
