### ISSUE TITLE
More efficient re-rips an option?

### ISSUE THREAD

**Issue by tehchubchug** [RipMeApp/ripme#995]
* Ripme version:1.7.67

## Expected Behavior

Would love to see an option to rip only new items, such that ripme URLs can be re-run efficiently  over and over (over time). 

If while doing a re-rip, after reaching n number of already downloaded files (or URLs), abort the rip, and mark URL as complete. 

## Actual Behavior

During a re-rip, Ripme pulls new files, and continues to iterate through all remaining found URLs, finding them already downloaded. In some cases, this takes a VERY long time complete. 

Secondary issue - if a target directory has been cleaned up, with any number of files removed, they immediately get re-downloaded on re-rip, even though the URL list shows them as downloaded.

**Comment by rautamiekka** [comment]
The N number of files idea has been here before and it never got implemented; although, it never got actually refused either.

**Comment by tehchubchug** [comment]
Seems like it might be reasonable to implement, especially if comparing against the URL list.

**Comment by cyian-1756** [comment]
@rautamiekka 

> The N number of files idea has been here before and it never got implemented

it got implemented way back

@tehchubchug 

> If while doing a re-rip, after reaching n number of already downloaded files (or URLs), abort the rip, and mark URL as complete.


To do that make sure "Remember URL History" is checked in the GUI (or that remember.url_history is set to true in rip.properties) and add the line "history.end_rip_after_already_seen = X" (where x is how many already items you want ripme to check before ending the current rip) to rip.properties

**Comment by tehchubchug** [comment]
Oh exactly what I was looking for. Just needs to be added to the config UI :)
